### ISSUE TITLE
DeploymentConfig export always contains reference to old Namespace 

### ISSUE THREAD

**Issue by damemi** [openshift/origin#10091]
When exporting a DeploymentConfig to either JSON or YAML, there is a field entry added to the exported template under `Spec.Triggers.ImageChangeParams.From` with the Namespace the DC is currently in.  Is this an intentional feature? There doesn't seem to be any documentation on it. It's possible that, when exporting a DC, a user may not want any references to the Namespace from which it was exported (such as in the case of re-creating that DC in a different Namespace).
##### Steps To Reproduce
1. Create a project with a deploymentconfig
2. `oc export -o yaml dc`
   (note: this also occurs with other `oc` commands such as `oc get` as well as JSON)
##### Current Result

```
- apiVersion: v1
  kind: DeploymentConfig
  ...
  spec:
    ...
    triggers:
    - imageChangeParams:
        ...
        from:
          kind: ImageStreamTag
          name: origin-ruby-sample:latest
          namespace: test
```
##### Expected Result

It would be nice to be able to exclude the `namespace` field when exporting these kind of resources.
