### ISSUE TITLE
Django-example deploy failed. Dial tcp 172.30.0.1:443:  getsockopt: connection refused

### ISSUE THREAD

**Issue by anhnguyenbk** [openshift/origin#10124]
The cluster has 1 master (also be a infra node with `openshift_schedulable=true` ) and 1 primary node. All of them were created by Vagrant with VirtualBox Provider. When I deploy django-example application on the cluster, build phase sucessful, but deployment phase failed with below result

##### Version
openshift v1.2.1
kubernetes v1.2.0-36-g4a3f9c5
etcd 2.2.5

##### Steps To Reproduce
1. Create new project and run django-example app

##### Current Result
F0730 19:09:21.344556 1 deployer.go:70] couldn't get deployment test/django-example-4: Get https://172.30.0.1:443/api/v1/namespaces/test/replicationcontrollers/django-example-4: dial tcp 172.30.0.1:443: getsockopt: connection refused 

##### Expected Result
Deployment successful

##### Additional Information
I have setting up BIND DNS on 192.168.56.1 to resolve master and node hostname to its IP. My `/etc/resolv.conf` file on master and node
```
search mycom.local 
nameserver 192.168.56.1
```
On master and node
```
[root@master ~]# dig master.mycom.local +short
192.168.56.110
[root@master ~]# dig node1.mycom.local +short
192.168.56.120
```
The django-example-build has assigned to node1.mycom.local

**Comment by mfojtik** [comment]
This looks like the deployer can't make an API call back to the API server for some reason. I suspect something is wrong in VirtualBox networking setup. @abhgupta any clues?

**Comment by anhnguyenbk** [comment]
I created a new nodejs-example app for test Kubernetes deployment. Openshift deployment phase failed again. So I created `nodejs.yaml` file and use `kubectl create -f nodejs.yaml` command to deploy. 

nodejs.yaml
```
apiVersion: v1
kind: ReplicationController
metadata:
  name: nodejs-ex
spec:
  replicas: 1
  template:
    metadata:
      name: nodejs-ex
      labels:
        app: nodejs-ex
    spec:
      containers:
        -
          name: nodejs-ex
          image: '172.30.185.184:5000/test/nodejs-example'
          ports:
            -
              containerPort: 8080
              protocol: TCP
```
The nodejs-ex pod was created successful and when I exec to running container
```
bash-4.2$ curl -X GET localhost:8080 | grep "Welcome"   
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 40382  100 40382    0     0  5614k      0 --:--:-- --:--:-- --:--:-- 6  <title>Welcome to OpenShift</title>
572k
            <h1>Welcome to your Node.js application on OpenShift</h1>
```
I think this is origin problem.
