### ISSUE TITLE
Improve high level yaml/json parsing and error handling

### ISSUE THREAD

**Issue by vnugent** [openshift/origin#10171]
Sometimes well-formed yaml/json files don't conform to openshift/kubernetes data structure.  My DeploymentConfig was missing `containers` key and as a result I got a cryptic yaml parsing error: DeploymentConfig: only encoded map or array can be decoded into a struct.  The error is too vague to novice users.
##### Version

openshift v3.3.0.4
kubernetes v1.3.0+57fb9ac
etcd 2.3.0+git
##### Steps To Reproduce

```
    template:
      metadata:
        labels:
          name: ${NAME}
        name: ${NAME}
      spec:
       containers:
       - image: docker.io/hawkularqe/hawkular-services:latest
```

remove `containers:`
##### Current Result

 DeploymentConfig in version "v1" cannot be handled as a DeploymentConfig: only encoded map or array can be decoded into a struct.
##### Expected Result

A friendly message such as "Missing Containers object" would greatly improve the user experience.

**Comment by mfojtik** [comment]
@smarterclayton to make this possible, we will need to validate the input against the swagger schema to see what fields are missing, or what fields are extra, correct? Do you know if there is a plan in kube to integrate something like that to kubectl?

**Comment by smarterclayton** [comment]
You mean like --validate?  We default it to off today in oc, but you
can still specify it.

**Comment by smarterclayton** [comment]
We should probably start turning validate on by default now that all the schema stuff is fixed end to end (if explain works, validate should work).

**Comment by mfojtik** [comment]
@fabianofranz opinions about turning --validate on by default?

**Comment by liggitt** [comment]
no, client-side validate fails for schema-less types and required fields that are typically defaulted server-side

**Comment by smarterclayton** [comment]
Michal, can you find the issue for server side dry run and dupe this on
that?

On Nov 11, 2016, at 1:06 AM, Jordan Liggitt <notifications@github.com>
wrote:

no, client-side validate fails for schema-less types and required fields
that are typically defaulted server-side

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/openshift/origin/issues/10171#issuecomment-259913103>,
or mute the thread

**Comment by rafaeltuelho** [comment]
+1 for this.

My env:
```
Version
OpenShift Master: v3.3.1.7
Kubernetes Master: v1.3.0+52492b4
```

I faced this issue trying to create the following BuildConfig definition:

```yaml
kind: "BuildConfig"
apiVersion: "v1"
metadata:
  labels:
    app: "tomcat6-webapp-docker"
  name: "tomcat6-webapp-docker"
spec:
  output:
    to:
      kind: "ImageStreamTag"
      name: "tomcat6-webapp:latest"
  runPolicy: "Serial"
  source:
    type: "Git"
    git:
      uri: "http://gogs-cicd.cloud.<mydomain>.com/gogs/openshift-tomcat6-sample.git"
      contextDir: "openshift/docker"
  strategy:
    type: "Docker"
    dockerStrategy:
      env:
        name: "BUILD_LOGLEVEL"
        value: "2"
      from:
        kind: "ImageStreamTag"
        name: "tomcat:6.0.48-jre7"
```

from `oc` CLI

```
oc create -f openshift/template/tomcat6-docker-buildconfig.yaml                                                                                                                                                                      1 ↵
Error from server: error when creating "openshift/template/tomcat6-docker-buildconfig.yaml": BuildConfig in version "v1" cannot be handled as a BuildConfig: only encoded map or array can be decoded into a struct
```

after a while trying to figureout what was wrong... The issue was:

```
      env:
        name: "BUILD_LOGLEVEL"
        value: "2"
```

removing the above `env` snippet from my BuildConfig definition worked!

```
oc create -f openshift/template/tomcat6-docker-buildconfig.yaml                                                                                                                                                                      1 ↵
buildconfig "tomcat6-webapp-docker" created
```

The --validate didn't helpd at all

```
oc create --dry-run --validate -f openshift/template/buildconfig.yaml                                                                                                                                                                1 ↵
error: error validating "openshift/template/buildconfig.yaml": error validating data: couldn't find type: v1.BuildConfig; if you choose to ignore these errors, turn validation off with --validate=false
 ```

Well, at least I hope these issue comments save some hours to someone....
