### ISSUE TITLE
Egress Solution

### ISSUE THREAD

**Issue by cw-aleks** [openshift/origin#10323]
We need to provide on some dedicated nodes the egress routes.

With the current solution an the PR https://github.com/openshift/origin/pull/10322 you are able to make this, but only one egress per node, as far as I have understood the implementation right.

https://github.com/openshift/origin/blob/master/images/router/egress/egress-router.sh

For the current solution I miss some Logging options and a PaaS Solution.

It would be nice to have something like

https://docs.openshift.org/latest/install_config/install/deploy_router.html#using-namespace-router-shards

My question is why was not tried to use the current router image with a `haproxy-egress-config.template`?
It would be nice to understand the reason and the idea behind the current solution.

##### Version
oc v3.2.1.9-1-g2265530
kubernetes v1.2.0-36-g4a3f9c5

Yes I know its Enterprise but the egress is not yet there ;-)

**Comment by knobunc** [comment]
@danwinship Can you please comment.

**Comment by danwinship** [comment]
> With the current solution an the PR #10322 you are able to make this, but only one egress per node, as far as I have understood the implementation right.

Each egress-router pod only handles a single IP address, but you can run as many egress-router pods on a node as you want.

> My question is why was not tried to use the current router image

The "ingress router" is an application layer load balancing proxy (which only works with http or TLS-based protocols), while the "egress router" is a TCP/UDP-level traffic redirector (which is totally protocol-agnostic).

**Comment by cw-aleks** [comment]
Hi Dan.

Thanks for explanation.
I hope it works so.

BR Aleks

**Comment by cw-aleks** [comment]
Hi Dan.

I have tried to run https://github.com/cw-aleks/openshift-egress , which is a clone of https://github.com/openshift/origin/tree/master/images/router/egress .

```
oc new-app https://github.com/cw-aleks/openshift-egress.git
oc env dc/openshift-egress EGRESS_SOURCE=<SOURCE-IP> EGRESS_GATEWAY=<GATEWAY> EGRESS_DESTINATION=<DEST-IP>
```
Now the POD fails with this message.

```
oc logs openshift-egress-3-stizn
+ '[' -z EGRESS_SOURCE ']'
+ '[' -z EGRESS_DESTINATION ']'
+ '[' -z EGRESS_GATEWAY ']'
+ ip route get EGRESS_DESTINATION
+ grep -q macvlan0
+ ip addr add EGRESS_SOURCE/32 dev macvlan0
Cannot find device "macvlan0"
```

I run this on `oc version`

```
oc v3.2.1.9-1-g2265530
kubernetes v1.2.0-36-g4a3f9c5
````
Should I open for this a RH Ticket or stay on github?

**Comment by danwinship** [comment]
As per the README.md file, the egress-router pod needs to have

    annotations:
      pod.network.openshift.io/assign-macvlan: true

and

    containers:
    - ...
      securityContext:
        privileged: true

I'm not sure how you'd set that up with "new-app". It's not really set up to be used with "new-app" right now really.

**Comment by cw-aleks** [comment]
Hi.

I have used
```
oc patch dc openshift-egress \
    -p '{"metadata":{"annotations": {"pod.network.openshift.io/assign-macvlan": "true"}}}'
```
to add it to dc.

The dc looks no like this.

```
oc export dc openshift-egress
apiVersion: v1
kind: DeploymentConfig
metadata:
  annotations:
    openshift.io/generated-by: OpenShiftNewApp
    pod.network.openshift.io/assign-macvlan: "true"
  creationTimestamp: null
  labels:
    app: openshift-egress
  name: openshift-egress
spec:
  replicas: 1
  selector:
    app: openshift-egress
    deploymentconfig: openshift-egress
  strategy:
    resources: {}
    rollingParams:
      intervalSeconds: 1
      maxSurge: 25%
      maxUnavailable: 25%
      timeoutSeconds: 600
      updatePeriodSeconds: 1
    type: Rolling
  template:
    metadata:
      annotations:
        openshift.io/container.openshift-egress.image.entrypoint: '["/usr/bin/openshift"]'
        openshift.io/generated-by: OpenShiftNewApp
      creationTimestamp: null
      labels:
        app: openshift-egress
        deploymentconfig: openshift-egress
    spec:
      containers:
      - env:
        - name: EGRESS_SOURCE
          value: <IP>
        - name: EGRESS_GATEWAY
          value: <IP>
        - name: EGRESS_DESTINATION
          value: <IP>
        image: 172.30.94.49:5000/aleks-egress-router/openshift-egress@sha256:ee734864399d841bc1b396da6ce2ae2673c30b13b06234cfa62b56c6cda6ecde
        imagePullPolicy: Always
        name: openshift-egress
        ports:
        - containerPort: 53
          protocol: TCP
        - containerPort: 8443
          protocol: TCP
        resources: {}
        terminationMessagePath: /dev/termination-log
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      securityContext: {}
      terminationGracePeriodSeconds: 30
  test: false
  triggers:
  - type: ConfigChange
  - imageChangeParams:
      automatic: true
      containerNames:
      - openshift-egress
      from:
        kind: ImageStreamTag
        name: openshift-egress:latest
    type: ImageChange
status: {}
```
Yes the **privileged serviceaccount** is the problem due to the fact that we don't like to give some user a **privileged serviceaccount** service account.

I mean when the user have this SA in his project he can use this for every DC, which we don't like ;-)
Maybe there is a possibility to solve this issue?
