### ISSUE TITLE
Use --ports= also for ROUTER_SERVICE_HTTP*_PORT

### ISSUE THREAD

**Issue by ghost** [openshift/origin#10331]
When I use a custom router and want to create it with

```
# oc adm router egress-google \
    --service-account=sa-egress-google \
    --host-network=false \
    --host-ports=false \
    -o yaml \
    --ports='1080:1080,10443:10443' \
  --stats-port=1937
```

The Variables ROUTER_SERVICE_HTTPS_PORT and ROUTER_SERVICE_HTTP_PORT are still setuped to 80 & 443 because it's hardcoded in go.

https://github.com/openshift/origin/blob/master/pkg/cmd/admin/router/router.go#L622-L623
##### Version

Current master
##### Steps To Reproduce
1. `oc create serviceaccount sa-egress-google`

```
# oc adm router egress-google \
    --service-account=sa-egress-google \
    --host-network=false \
    --host-ports=false \
    -o yaml \
    --ports='1080:1080,10443:10443' \
  --stats-port=1937
```
##### Current Result

```
      spec:
        containers:
        - env:
          - name: ROUTER_EXTERNAL_HOST_HOSTNAME
          - name: ROUTER_EXTERNAL_HOST_HTTPS_VSERVER
          - name: ROUTER_EXTERNAL_HOST_HTTP_VSERVER
          - name: ROUTER_EXTERNAL_HOST_INSECURE
            value: "false"
          - name: ROUTER_EXTERNAL_HOST_PARTITION_PATH
          - name: ROUTER_EXTERNAL_HOST_PASSWORD
          - name: ROUTER_EXTERNAL_HOST_PRIVKEY
            value: /etc/secret-volume/router.pem
          - name: ROUTER_EXTERNAL_HOST_USERNAME
          - name: ROUTER_SERVICE_HTTPS_PORT
            value: "443"
          - name: ROUTER_SERVICE_HTTP_PORT
            value: "80"
```
##### Expected Result

```
      spec:
        containers:
        - env:
          - name: ROUTER_EXTERNAL_HOST_HOSTNAME
          - name: ROUTER_EXTERNAL_HOST_HTTPS_VSERVER
          - name: ROUTER_EXTERNAL_HOST_HTTP_VSERVER
          - name: ROUTER_EXTERNAL_HOST_INSECURE
            value: "false"
          - name: ROUTER_EXTERNAL_HOST_PARTITION_PATH
          - name: ROUTER_EXTERNAL_HOST_PASSWORD
          - name: ROUTER_EXTERNAL_HOST_PRIVKEY
            value: /etc/secret-volume/router.pem
          - name: ROUTER_EXTERNAL_HOST_USERNAME
          - name: ROUTER_SERVICE_HTTPS_PORT
            value: "10443"
          - name: ROUTER_SERVICE_HTTP_PORT
            value: "1080"
```
