### ISSUE TITLE
BuildDefaults: add a "gitNO_PROXY"

### ISSUE THREAD

**Issue by sterburg** [openshift/origin#10400]
Currently OpenShift supports setting gitHTTPProxy as a BuildDefaults.
I am missing a "gitNO_PROXY" attribute.
This makes the whole BuildDefaults.gitHTTPProxy useless as i cannot have 1 global default that both enables me to go through proxy for accessing public github.com and not to go through proxy for accessing internal corporate git. (common use-case)

BuildDefaults to specify Proxy are a perfect way to unburden developers with infrastructure related config. I love it. 

##### Version
oc v3.2.1.9-1-g2265530
kubernetes v1.2.0-36-g4a3f9c5

##### Steps To Reproduce
```
kubernetesMasterConfig:
  admissionConfig:
    pluginConfig:
      BuildDefaults:
        configuration:
          apiVersion: v1
          kind: BuildDefaultsConfig
          gitHTTPProxy: http://my.proxy:8080 
          gitHTTPSProxy: https://my.proxy:8443 
```
##### Current Result
All git operations go through the proxy

##### Expected Result
Be able to distinguish git traffic between public & internal git repo's.
