### ISSUE TITLE
DeploymentConfig's don't deploy if the docker images take too long to download

### ISSUE THREAD

**Issue by jstrachan** [openshift/origin#10531]
on an empty [minishift](https://github.com/jimmidyson/minishift/) VM if I [install fabric8 like this](http://fabric8.io/guide/getStarted/minishift.html) we get 5 DeploymentConfig objects. 

What usually happens on my laptop is 2 of them fail to ever deploy any pods. To force them to deploy I have to run this a little after things fail (as hopefully by then the docker images are downloaded):

```
oc deploy --retry jenkins
oc deploy --retry fabric8-forge
```

(depending on which DeploymentConfig objects fail).

The issue seems to be related to the amount of time it takes to download the docker images. My wifi isn't too fast.

Interestingly there's no such issue on Kubernetes using Deployments; the deployment controller just waits until the  Deployment happens.

I noticed there's a timeout on the Deployment strategy:
https://github.com/openshift/origin/blob/ee84df6820df28e15643fa2c5cf716e7d5f1ad22/pkg/deploy/api/types.go#L77

I guess there's just one timeout; so we can't separate the docker image download time from the actual deploy time right? 

I wonder is there a way to set the global timeout for DeploymentConfig timeouts? As that might be a nice thing to do on minishift in general to give laptop users more time to download docker images from the internet?

**Comment by kargakis** [comment]
> I guess there's just one timeout; so we can't separate the docker image download time from the actual deploy time right?

Yes, downloading a new image is part of the deployment so if you want longer times set a bigger TimeoutSeconds value than the default 10 minutes.

**Comment by kargakis** [comment]
> I wonder is there a way to set the global timeout for DeploymentConfig timeouts? As that might be a nice thing to do on minishift in general to give laptop users more time to download docker images from the internet?

No way to set a global timeout currently. Is there a real use case for it?  I think an average cluster will be comprised of various deployments so there isn't a one-size-fits-all deployment timeout.

**Comment by kargakis** [comment]
Also if you want the demo gods by your side, pre-download the images you need:)

**Comment by jstrachan** [comment]
While production installations probably have fast wifi & will often have reasonable docker image caches - when folks are kicking the tyres of openshift via minishift this makes OpenShift look pretty bad compared to kubernetes as most DeploymentConfigs don't work on slow wifi ;). Being able to configure the default timeout would be really handy!

For now I'm just gonna set a massive timeout on all the DeploymentConfig's we create in fabric8 so at least then our DeploymentConfig's behave more like the Deployments on kubernetes - i.e. they actually work without manual intervention, irrespective of how fast the users wifi is ;)

**Comment by jstrachan** [comment]
BTW this is how to configure it right? 
```yaml
---
apiVersion: "v1"
kind: "DeploymentConfig"
metadata:
  name: "foo"
spec:
  replicas: 1
  selector:
    project: "foo"
  strategy:
    recreateParams:
      timeoutSeconds: 10800
  template:
     ...
  triggers:
  - type: "ConfigChange"
```

**Comment by kargakis** [comment]
> BTW this is how to configure it right? 

Yes.

We have https://github.com/openshift/origin/issues/7522 for making the deployment timeout optional ie. you will be able to get the current behavior of Kube deployments.

**Comment by jstrachan** [comment]
ah great thanks!

**Comment by jstrachan** [comment]
at some point it would be nice to differentiate between 'wait forever for the docker image to download' from "keep retrying a failed pod" - but I guess restart counts and whatnot can solve this

**Comment by kargakis** [comment]
> at some point it would be nice to differentiate between 'wait forever for the docker image to download' from "keep retrying a failed pod" - but I guess restart counts and whatnot can solve this

Let's keep this issue open for tracking this request as I have been asked about it before.
cc: @mfojtik @smarterclayton @ironcladlou

**Comment by jstrachan** [comment]
@kargakis so it seems setting the timeout has no effect. 

Here's the timeout setting - I made it 3 hours:
https://gist.github.com/jstrachan/d5f74075c10d0f6818781b5ab7f94915#file-jenkins-dc-yaml-L32-L33

Then the deploy pod still times out after 10 minutes (600 seconds):
https://gist.github.com/jstrachan/d5f74075c10d0f6818781b5ab7f94915#file-deployer-pod-log-L3

Any ideas how I can change the timeout?

FWIW this is the latest minishift; the server version is:
```
Server Version: version.Info{Major:"", Minor:"", GitVersion:"v1.3.0-alpha.1-331-g0522e63", GitCommit:"983578e", GitTreeState:"not a git tree", BuildDate:"1970-01-01T00:00:00Z", GoVersion:"go1.6", Compiler:"gc", Platform:"linux/amd64"}
```

**Comment by kargakis** [comment]
@jstrachan you shouldn't set it in recreateParams but in rollingParams since you use the Rolling strategy.
```yaml
  strategy:
    recreateParams:
      timeoutSeconds: 10800
    resources: {}
    rollingParams:
      intervalSeconds: 1
      maxSurge: 25%
      maxUnavailable: 25%
      timeoutSeconds: 600
      updatePeriodSeconds: 1
type: Rolling
```
should be
```yaml
  strategy:
    rollingParams:
      intervalSeconds: 1
      maxSurge: 25%
      maxUnavailable: 25%
      timeoutSeconds: 10800
      updatePeriodSeconds: 1
type: Rolling
```
