### ISSUE TITLE
oc export should print the nodePort if service type is NodePort

### ISSUE THREAD

**Issue by rawlingsj** [openshift/origin#10530]
`oc export` doesn't display the nodePort if service type is NodePort
##### Versionoc v1.3.0-alpha.3

kubernetes v1.3.0+507d3a7
features: Basic-Auth
##### Steps To Reproduce

edit a service and change its type to NodePort
oc export svc [your service]
##### Current Result

```
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 3000
  selector:
    group: io.fabric8.devops.apps
    project: gogs
    provider: fabric8
  sessionAffinity: None
  type: NodePort
```
##### Expected Result

```
spec:
  clusterIP: 172.30.205.198
  portalIP: 172.30.205.198
  ports:
  - nodePort: 30295
    port: 80
    protocol: TCP
    targetPort: 3000
  selector:
    group: io.fabric8.devops.apps
    project: gogs
    provider: fabric8
  sessionAffinity: None
  type: NodePort
```
