### ISSUE TITLE
Capacity of glusterfs pvc is  zero and Accessmodes is null

### ISSUE THREAD

**Issue by yepengxj** [openshift/origin#10567]
Capacity of glusterfs pvc is  zero and Accessmodes is null
I created a v1.3.0-alpha.3 cluster ,and it's  glusterfs pvc can not work properly
```
$ oc get pvc
NAME                                   STATUS    VOLUME                                 CAPACITY   ACCESSMODES   AGE
vol-4823123e6103f5e47abf78bea28fee1b   Bound     vol-4823123e6103f5e47abf78bea28fee1b   0                        1m
vol-777225d08a17c0274597a29b86a777ea   Bound     vol-777225d08a17c0274597a29b86a777ea   0                        1m
vol-831f1251b153eac7ea585f0bfb53fc0d   Bound     vol-831f1251b153eac7ea585f0bfb53fc0d   0                        1m
vol-95ac1c23cacd4005324b5a59ee454a3f   Bound     vol-95ac1c23cacd4005324b5a59ee454a3f   0                        1m
vol-9bfb0189b40e65d3ae7b2f052e9f9485   Bound     vol-9bfb0189b40e65d3ae7b2f052e9f9485   0                        1m
vol-d5f725bb2394778ed4cfb40613f13eaa   Bound     vol-d5f725bb2394778ed4cfb40613f13eaa   0                        1m
```
```
oc get pv
NAME                                   CAPACITY   ACCESSMODES   STATUS    CLAIM                                       REASON    AGE
vol-4823123e6103f5e47abf78bea28fee1b   10Gi       RWX           Bound     test/vol-4823123e6103f5e47abf78bea28fee1b             1m
vol-777225d08a17c0274597a29b86a777ea   10Gi       RWX           Bound     test/vol-777225d08a17c0274597a29b86a777ea             1m
vol-831f1251b153eac7ea585f0bfb53fc0d   10Gi       RWX           Bound     test/vol-831f1251b153eac7ea585f0bfb53fc0d             1m
vol-95ac1c23cacd4005324b5a59ee454a3f   10Gi       RWX           Bound     test/vol-95ac1c23cacd4005324b5a59ee454a3f             1m
vol-9bfb0189b40e65d3ae7b2f052e9f9485   10Gi       RWX           Bound     test/vol-9bfb0189b40e65d3ae7b2f052e9f9485             1m
vol-d5f725bb2394778ed4cfb40613f13eaa   10Gi       RWX           Bound     test/vol-d5f725bb2394778ed4cfb40613f13eaa             1m
```
those pvc could be mounted in POD but can not access
The glusterfs cluster works fine with v1.1.6 origin cluster 
##### Version
[provide output of the `openshift version` or `oc version` command]
```
$ ./oc version
oc v1.3.0-alpha.3
kubernetes v1.3.0+507d3a7
features: Basic-Auth GSSAPI Kerberos SPNEGO

Server https://192.168.12.95:443
openshift v1.3.0-alpha.3
kubernetes v1.3.0+507d3a7
```
##### Steps To Reproduce
1. create pv
```
apiVersion: v1
kind: PersistentVolume
metadata:
  name: #pv_name#
spec:
  capacity:
    storage: 10Gi
  accessModes:
  - ReadWriteMany
  glusterfs:
    endpoints: glusterfs-cluster
    path: #pv_path#
    readOnly: false
  persistentVolumeReclaimPolicy: Retain
```
2. create pvc
```
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  creationTimestamp: null
  name: "#pv_name#"
spec:
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 10Gi
status: {}
```
##### Additional Information
[try to run `$ oadm diagnostics` command if possible]
[if you are reporting issue related to builds, provide build logs with `BUILD_LOGLEVEL=5`]
[consider attaching output of the `$ oc get all -o json -n <namespace>` command to the issue]
[visit https://docs.openshift.org/latest/welcome/index.html]
