### ISSUE TITLE
env with valueFrom in execNewPod containers doesn't get expanded

### ISSUE THREAD

**Issue by chmouel** [openshift/origin#10831]
env with valueFrom in execNewPod containers doesn't get expanded like for others

##### Version
oc v1.3.0-alpha.3+e3e0f53

##### Steps To Reproduce
1. Create a confgmap : 

```yaml
  - kind: ConfigMap
    apiVersion: v1
    metadata:
      name: configmap
    data:
      hello: moto
```

2. have a template with a container that has a execNewPod in recreateParams  : 

```yaml
      strategy:
        recreateParams:
          post:
            execNewPod:
              command: ["echo $HELLO"]
              env:
                - name: HELLO
                  valueFrom:
                    configMapKeyRef:
                      name: configmap
                      key: hello

```

3. Start the pod

##### Current Result
$HELLO is defined but not set to my value in my configmap

##### Expected Result

$HELLO defined with moto

#### Additional notes

Looks like hook pods only build name/value pairs: 

https://git.io/vicvw
