### ISSUE TITLE
Azure File storage in a PV doesn't seem to work

### ISSUE THREAD

**Issue by jam13** [openshift/origin#10881]
AzureFile storage, when used in a PV doesn't seem to work. The configuration is accepted by OpenShift, but when trying to initialise a pod with a mount it doesn't complete.

This storage driver is not documented in OpenShift, however it is part of Kubernetes v1.3 and it's documentation suggests that it can be used in a PV configuration as well as direct mounting to a pod.

The CIFS tools are installed on all nodes, and the mount has been tested manually on the nodes to ensure it is valid. Was not able to directly mount the share into a Pod due to OpenShift restrictions.

##### Version
oc v1.3.0-rc1
kubernetes v1.3.0+52492b4
features: Basic-Auth GSSAPI Kerberos SPNEGO

##### Steps To Reproduce
1. Create 5Gi File Storage in Azure and record credentials.

2. Create Secret:
```
apiVersion: v1
kind: Secret
metadata:
  name: azure-secret
type: Opaque
data:
  azurestorageaccountname: <base64 encoded storage name>
  azurestorageaccountkey: <base64 encoded storage key>
```

3. Create PV:
```
apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv001
spec:
  capacity:
    storage: 5Gi
  accessModes:
  - ReadWriteOnce
  azureFile:
    secretName: azure-secret
    shareName: test
    readOnly: false
```

4. Create PVC:
```
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: pvc001
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
```

5. Create Pod using PVC:
```
kind: Pod
apiVersion: v1
metadata:
  name: mypod
spec:
  containers:
    - name: mypod
      image: nginx
      volumeMounts:
      - mountPath: "/mnt"
        name: mypd
  volumes:
    - name: mypd
      persistentVolumeClaim:
        claimName: pvc001
```
##### Current Result
Secret and PV register correctly, and PV Claim binds to PV. However when pod tries to start it just hangs retrying the PVC mount and an error is displayed in the node log similar to this (names are different from above):

```
Sep 12 17:20:58 healthforge-platform-staging-node-2 origin-node: I0912 17:20:58.225131   13166 reconciler.go:254] MountVolume operation started for volume "kubernetes.io/azure-file/44ead656-790d-11e6-bdb8-0022480108e8-test2" (spec.Name: "test2") to pod "44ead656-790d-11e6-bdb8-0022480108e8" (UID: "44ead656-790d-11e6-bdb8-0022480108e8").
Sep 12 17:20:58 healthforge-platform-staging-node-2 origin-node: E0912 17:20:58.262408   13166 nestedpendingoperations.go:233] Operation for "\"kubernetes.io/azure-file/44ead656-790d-11e6-bdb8-0022480108e8-test2\" (\"44ead656-790d-11e6-bdb8-0022480108e8\")" failed. No retries permitted until 2016-09-12 17:20:58.762317646 +0000 UTC (durationBeforeRetry 500ms). Error: MountVolume.SetUp failed for volume "kubernetes.io/azure-file/44ead656-790d-11e6-bdb8-0022480108e8-test2" (spec.Name: "test2") pod "44ead656-790d-11e6-bdb8-0022480108e8" (UID: "44ead656-790d-11e6-bdb8-0022480108e8") with: exit status 1
``` 

##### Expected Result
Volume mounts correctly and pod starts.
