### ISSUE TITLE
DeploymentConfig without ConfigChange rollouts deployment on creation

### ISSUE THREAD

**Issue by mfojtik** [openshift/origin#10990]
When create a deployment config like this:

```yaml
apiVersion: v1
kind: DeploymentConfig
metadata:
  name: deployment-simple
spec:
  replicas: 1
  selector:
    name: deployment-simple
  strategy:
    type: Rolling
    rollingParams:
      pre:
        failurePolicy: Abort]
  template:
    metadata:
      labels:
        name: deployment-simple
    spec:
      containers:
      - image: "openshift/origin-base:latest"
        args: [ "sleep 120" ]
        imagePullPolicy: IfNotPresent
        name: myapp
```

the initial deployment is automatically created regardless of the absence of ConfigChange trigger.

Since this is most probably causing couple deployment extended tests flakes, marking this as P0.
