### ISSUE TITLE
wrong context on oc cluster up binded to 127.0.0.1

### ISSUE THREAD

**Issue by jorgemoralespou** [openshift/origin#11033]
I have created a cluster with "oc cluster up" bound to 127.0.0.1 and saving config to local and keeping existing config:

```
oc cluster up --public-hostname 127.0.0.1  --host-data-dir /Users/jmorales/.oc/roadshow/data  --host-config-dir /Users/jmorales/.oc/roadshow/config --use-existing-config
```

I try to use admin.kubeconfig to execute commands as system:admin but it fails with:

```
error: Get https://192.168.65.2:8443/api: dial tcp 192.168.65.2:8443: i/o timeout
```

It's trying to connect to the cluster internal IP as the context is using that instead of 127.0.0.1 which is the one that it should use.

```
$cat /Users/jmorales/.oc/roadshow/config/master/admin.kubeconfig
apiVersion: v1
clusters:
- cluster:
    certificate-authority-data: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUM2akNDQWRLZ0F3SUJBZ0lCQVRBTkJna3Foa2lHOXcwQkFRc0ZBREFtTVNRd0lnWURWUVFEREJ0dmNHVnUKYzJocFpuUXRjMmxuYm1WeVFERTBOelEwTlRNd05ETXdIaGNOTVRZd09USXhNVEF4TnpJeVdoY05NakV3T1RJdwpNVEF4TnpJeldqQW1NU1F3SWdZRFZRUUREQnR2Y0dWdWMyaHBablF0YzJsbmJtVnlRREUwTnpRME5UTXdORE13CmdnRWlNQTBHQ1NxR1NJYjNEUUVCQVFVQUE0SUJEd0F3Z2dFS0FvSUJBUUMyVnl2Wjd6WnRCSjFmTThUMGlwVlkKRi9EdmxNdnFkZnlReU1JY1VoQVhJbS9kN1l2b05iRDIxcTdKK0x0cEtKL1BkdlVzQzVDYU9BZkQxOFZOeFVVWQpUeGZQbTZpMnNIejRXVitqT1VwaC9YbVlQdlAycm1pTGpxeDFTeVJGelRoZk9NbDl4d0tXMFQ3UVJmWlVtQkNWCjF3UUNJajJXMXFRK3ZmN1l0Z0Z2NmR3MTZuNjV0d3U3emw0YXFReEJEdEQ4UTU3K0NEQlF2M3FqR0VtbDZQUnIKYlhBUXpLaHp3RjFYRVhSVHpTN2ZtQVBHK24rSlNGRTN4bmFPREEzRVdCVDRQU1pvU2l1S1NMSFpJclBSZ242bwpHVnFWYUNCU2x1NVoxTkRzYVFHdVk5a0IzUnc4K1d2MnRXdWVYTEwwSGd5NllyeXh6MCt1eHJTZFhxNE8wQmFQCkFnTUJBQUdqSXpBaE1BNEdBMVVkRHdFQi93UUVBd0lDcERBUEJnTlZIUk1CQWY4RUJUQURBUUgvTUEwR0NTcUcKU0liM0RRRUJDd1VBQTRJQkFRQlUrUTBCVytPZFZzRFJwT1N0cXR1VlRFOHlaSEREUS9jNEhkSDJEcWphZUl0KwovMW15WmNhTC83U2lFK3J1cFdYaEZ0bHk0Q3FZT1orYlJyY0puR1Z4eHJzcmJNSGsyYVlYd2FXZWFWbWZRVml1CkMwSjZCSGlncWRNQTlKVEdKOXUxUURPeUZLaHk4cEhIU1NaMFQzVCtHajE1YW51Mmp5Z1AwclhzMmdWWCtMK0IKVWJQNGZKRmFicnBpeDBWUDFGaFAwRnliMU1hWkF6Z0ppVytEVXpydTRXc0ZVY2FCU09NVkpURlhRSHQ5VDNtWgpLNWlLQ2NMQWVwV29lSWdXaVZOb3g2V2NqTFVYb2ZRUWFKTzllWkNyV2NHNmk2YjBXUnZKeXljUDhlS1JRWEI5CmlOZFk2UzNUVUZMaDZxRUNGc1FlSVhsOHk3WDhuY1NQSFYrTkFzRnAKLS0tLS1FTkQgQ0VSVElGSUNBVEUtLS0tLQo=
    server: https://127.0.0.1:8443
  name: 127-0-0-1:8443
- cluster:
    certificate-authority-data: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUM2akNDQWRLZ0F3SUJBZ0lCQVRBTkJna3Foa2lHOXcwQkFRc0ZBREFtTVNRd0lnWURWUVFEREJ0dmNHVnUKYzJocFpuUXRjMmxuYm1WeVFERTBOelEwTlRNd05ETXdIaGNOTVRZd09USXhNVEF4TnpJeVdoY05NakV3T1RJdwpNVEF4TnpJeldqQW1NU1F3SWdZRFZRUUREQnR2Y0dWdWMyaHBablF0YzJsbmJtVnlRREUwTnpRME5UTXdORE13CmdnRWlNQTBHQ1NxR1NJYjNEUUVCQVFVQUE0SUJEd0F3Z2dFS0FvSUJBUUMyVnl2Wjd6WnRCSjFmTThUMGlwVlkKRi9EdmxNdnFkZnlReU1JY1VoQVhJbS9kN1l2b05iRDIxcTdKK0x0cEtKL1BkdlVzQzVDYU9BZkQxOFZOeFVVWQpUeGZQbTZpMnNIejRXVitqT1VwaC9YbVlQdlAycm1pTGpxeDFTeVJGelRoZk9NbDl4d0tXMFQ3UVJmWlVtQkNWCjF3UUNJajJXMXFRK3ZmN1l0Z0Z2NmR3MTZuNjV0d3U3emw0YXFReEJEdEQ4UTU3K0NEQlF2M3FqR0VtbDZQUnIKYlhBUXpLaHp3RjFYRVhSVHpTN2ZtQVBHK24rSlNGRTN4bmFPREEzRVdCVDRQU1pvU2l1S1NMSFpJclBSZ242bwpHVnFWYUNCU2x1NVoxTkRzYVFHdVk5a0IzUnc4K1d2MnRXdWVYTEwwSGd5NllyeXh6MCt1eHJTZFhxNE8wQmFQCkFnTUJBQUdqSXpBaE1BNEdBMVVkRHdFQi93UUVBd0lDcERBUEJnTlZIUk1CQWY4RUJUQURBUUgvTUEwR0NTcUcKU0liM0RRRUJDd1VBQTRJQkFRQlUrUTBCVytPZFZzRFJwT1N0cXR1VlRFOHlaSEREUS9jNEhkSDJEcWphZUl0KwovMW15WmNhTC83U2lFK3J1cFdYaEZ0bHk0Q3FZT1orYlJyY0puR1Z4eHJzcmJNSGsyYVlYd2FXZWFWbWZRVml1CkMwSjZCSGlncWRNQTlKVEdKOXUxUURPeUZLaHk4cEhIU1NaMFQzVCtHajE1YW51Mmp5Z1AwclhzMmdWWCtMK0IKVWJQNGZKRmFicnBpeDBWUDFGaFAwRnliMU1hWkF6Z0ppVytEVXpydTRXc0ZVY2FCU09NVkpURlhRSHQ5VDNtWgpLNWlLQ2NMQWVwV29lSWdXaVZOb3g2V2NqTFVYb2ZRUWFKTzllWkNyV2NHNmk2YjBXUnZKeXljUDhlS1JRWEI5CmlOZFk2UzNUVUZMaDZxRUNGc1FlSVhsOHk3WDhuY1NQSFYrTkFzRnAKLS0tLS1FTkQgQ0VSVElGSUNBVEUtLS0tLQo=
    server: https://192.168.65.2:8443
  name: 192-168-65-2:8443
contexts:
- context:
    cluster: 127-0-0-1:8443
    namespace: default
    user: system:admin/192-168-65-2:8443
  name: default/127-0-0-1:8443/system:admin
- context:
    cluster: 192-168-65-2:8443
    namespace: default
    user: system:admin/192-168-65-2:8443
  name: default/192-168-65-2:8443/system:admin
current-context: default/192-168-65-2:8443/system:admin
kind: Config
preferences: {}
users:
- name: system:admin/192-168-65-2:8443
  user:
    client-certificate-data: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUREVENDQWZXZ0F3SUJBZ0lCQnpBTkJna3Foa2lHOXcwQkFRc0ZBREFtTVNRd0lnWURWUVFEREJ0dmNHVnUKYzJocFpuUXRjMmxuYm1WeVFERTBOelEwTlRNd05ETXdIaGNOTVRZd09USXhNVEF4TnpJeldoY05NVGd3T1RJeApNVEF4TnpJMFdqQTNNUjR3SEFZRFZRUUtFeFZ6ZVhOMFpXMDZZMngxYzNSbGNpMWhaRzFwYm5NeEZUQVRCZ05WCkJBTVRESE41YzNSbGJUcGhaRzFwYmpDQ0FTSXdEUVlKS29aSWh2Y05BUUVCQlFBRGdnRVBBRENDQVFvQ2dnRUIKQUt5TDlOMXlRMDMzN2NvUjE2cm00VGQrZ09FbFpybDRIR2lSbEN0eEJOcHYzZGdMeEE3RXpETXNxeFlVQXowWQo1UjdHbDd3MWRGWENZaHhsOHFyaWFobUhZTzRCd0svSFZHcHBnNGxvMTNOQ01XaUN2SFd5dlBOMUE3VDFkUDR5ClhYcFlLZHJ5aEVlMVk5VlRIN2pXMUNIekFoN1ZvdHdEdlRDUmUySExibkQvaGhIUndUOFQ1UG9NcWhyUUVyNjEKK3ZEQU5LdmdFWkRpOXhSTDdyY3gyQnd2amQyUWhTS3FUU0hzNktZa1RWNWJERVF1clFNV09tV0tGTTlsanRKagpQaGhpa1Jmc1dzYXh4VHU1bER4LzFMYzdCSE1HZWhuT0QxVmZMNXZXMmw1ekpkSlNSekU3SHlVeG1paGd2aGx2CmlpS0VMS2lRRUwxOTVlaStMUm5URFZzQ0F3RUFBYU0xTURNd0RnWURWUjBQQVFIL0JBUURBZ1dnTUJNR0ExVWQKSlFRTU1Bb0dDQ3NHQVFVRkJ3TUNNQXdHQTFVZEV3RUIvd1FDTUFBd0RRWUpLb1pJaHZjTkFRRUxCUUFEZ2dFQgpBTFk1SWpQRUVlTkNYYVVTVi9ObDF4R1IzbUp4ZVNzOEoxOURPcHlIbm1meVVUdktoRXp6dVUveTNvRTY5OUc2CnA5UVJlUlBPOEVkNVFYWG9jQThoOGdpVWVTRmxWY3llUHJHQlFVRjFwVHdkVjcyWi92THFUUS9Id09KQm1wVWwKTmt4NGhzUUtscnBTbTRjWUg4WlZqdXlLdXl0SUhOYkhCMElML1hjUWxVNWVvOGFvT2tSZ0NRYnlWcWlicnp6dwpsYVcrc1c2anBZZHFCa1R4YmN6bTdrcDhTVGVDTGdqRnh6V1hNZ1hlSTZUSHJEdVJZOERRbFR5RVBCK2FUc2dPCjdFNHlPdWswcWR1eTlqa2xGajRrT2dVY2c1UUIyRDkxaHk2bC9ibU5YL0R6UzdpaU9ZYWE3a2VCMlpicG5YVVgKZ0R5M2daQmdzUm1FWlVPWXRtczBBeW89Ci0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0K
    client-key-data: LS0tLS1CRUdJTiBSU0EgUFJJVkFURSBLRVktLS0tLQpNSUlFb2dJQkFBS0NBUUVBckl2MDNYSkRUZmZ0eWhIWHF1YmhOMzZBNFNWbXVYZ2NhSkdVSzNFRTJtL2QyQXZFCkRzVE1NeXlyRmhRRFBSamxIc2FYdkRWMFZjSmlIR1h5cXVKcUdZZGc3Z0hBcjhkVWFtbURpV2pYYzBJeGFJSzgKZGJLODgzVUR0UFYwL2pKZGVsZ3AydktFUjdWajFWTWZ1TmJVSWZNQ0h0V2kzQU85TUpGN1ljdHVjUCtHRWRIQgpQeFBrK2d5cUd0QVN2clg2OE1BMHErQVJrT0wzRkV2dXR6SFlIQytOM1pDRklxcE5JZXpvcGlSTlhsc01SQzZ0CkF4WTZaWW9VejJXTzBtTStHR0tSRit4YXhySEZPN21VUEgvVXR6c0Vjd1o2R2M0UFZWOHZtOWJhWG5NbDBsSkgKTVRzZkpUR2FLR0MrR1crS0lvUXNxSkFRdlgzbDZMNHRHZE1OV3dJREFRQUJBb0lCQURkMTBPSHczVE5OY3BBVgp4aFYzbW9KazFmWUlPSWw2MHQ3RmxET1dZekgyN1A2SllaNUJvVVQ5b1l3NktJUlY0U2RRTyt0UjN5L0ZpQldLCnEwSkQva2h3WERhRU43UUlSTmpqUzFVNmJxM3NZOGNzNW5pS1YvT0U5QWtSTUdhWU43V2dhdXVtTWVCK3JEVWcKUDcwQXlEU1ZVR1FxMU9zVkJKVjgzWVNraDc0bnpGK1ZIZ21GSGIrMFpDVHB0T1ZzVit2bCtsZWZUeXVJaFQwdgowdk9aRHVucm93VURYamt3U09JNGprUEZxSitObDlQMVZ3RWc3eFptT0xNQnlKaER6amhWZEhXSXBIdy9zeTRzCk5DN0NPa3Z4UU42N1QxeWxhL0lrWHVJbUF1YTA2bDhMdWRIdDFkZFZnSnJodkl5bWYyZkpOc2xhaUNldElRK3UKN0daZmJEa0NnWUVBM1A1U0M5emRkRVFiZG92alptK3FDaXlqQmM0akd5S21Eclpsd2JPT21rQjZQanRIaVdoTgpodEMvbjJxQ0hPeW1ucEFRMXpxczRKU0VTSWdXOStEaVNxQkR2WnhPZCtPZVhRSHh4bjlsMkZKcHFZbmV3M1Q3CnNLMGRCckl6OFkxNDJ2SHhzSUZwNG0zeHFKUndHQzU5bmt5bzh1aUZtejhzTnp4eVBlUVM3WVVDZ1lFQXgrRUkKd3M0SDdaSkZsN3NLakJEUEZrRTBZVVRZNUhWYy9uYlpJbGJBUG9uL2ROYU13Y2JBakh6V041SWpkM0JId01ZWgp5ZVJFUWZmeHl3eGZOUm1ncWdRQStCTkZZNUFVNkt1N3NmSVBCZnI0eXg1SkJmZFJhSmRwSlZoMXBzNHZUV1NBCmhBeHFCcFc5ZThOdDQrZWdiNFV6MHp2ZjU5WlFnYld3NHlCZEZWOENnWUJBQTh0d2RFSVI4OGlneGxUUXozZksKQ3JRT2NtL281RmlGMm9BUFpCdml3dHFtUERXMHIrb0ZLMkxXb3R1ZDFVOU9qeHpSdThWb0tKMUpCV0xoMnRxeQpFMHFNR2tNQXA0YXdHbWdXdjhDWXNRYTZmWjF4c09sWGZFMzBLcHF4VmZHME9uRndWNHg4Y3F5VjBLbkgxMis3Cjh5amRkRTEvY3dVejJ1YWMxdnhFb1FLQmdEem40NFdJeG4ycjdxelhmOVZDWWZnRUVuUDVTS1lFNVR0Yzk3a3cKK2crVWVWVWU4M0V3b1FldUdwQ0FaWEpGc25lWlpjNVJVa05QekV2MUR5WGRFMG43UWxoVmR2VnB1QlZXRHpHZgo4dGY5cThZcENsTlpFMk50ajhxamMrWktPYnU1ZmplK21LZzlCS29yMk5aemhEMjNOeDJNeHlPYitKZ3R4eUxPCmY4NjlBb0dBV04zNGNZc21UZTU5enBIdWx6aUZWdWxXb0VSSjEyNGlvN1NwekpYVGxqejFlTDl6TlBGTGVwL04KOENWU1QrdWhNZ2NpWlVORmgxRjZ2T040dFZ1dVdpTHJrbENiZ3RtcEVtNXZIdUJXVFJBb2JFdHhQSitRd05KYQpaRTlSM0pzdGVZNmxRREdtUGFFLzJnRHo5V3Zabm5MNU1BYzByT09jd1RvaGphekU1NkU9Ci0tLS0tRU5EIFJTQSBQUklWQVRFIEtFWS0tLS0tCg==
```
##### Version

oc v1.3.0
kubernetes v1.3.0+52492b4
features: Basic-Auth
