### ISSUE TITLE
ClusterResourceOverrideConfig not honored in admissionConfig

### ISSUE THREAD

**Issue by andrewklau** [openshift/origin#11128]
As stated here https://docs.openshift.org/latest/architecture/additional_concepts/admission_controllers.html#admission-controllers-general-admission-rules we should merge kuberentes admission config. However when ClusterResourceOverrideConfig is merged eg.

```
admissionConfig:
  pluginConfig:
    ClusterResourceOverride:   
      configuration:
        apiVersion: v1
        kind: ClusterResourceOverrideConfig
        memoryRequestToLimitPercent: 25  
        cpuRequestToLimitPercent: 25     
        limitCPUToMemoryPercent: 200  
```

The overrides don't seem to be applied. Perhaps it could be another reason for this issue https://github.com/openshift/origin-web-console/issues/554
##### Version

v1.3.0
