### ISSUE TITLE
How to build pipeline in openshift origin 1.3

### ISSUE THREAD

**Issue by wenskys** [openshift/origin#11166]
##### Version
openshift origin v1.3.0(build by openshift-ansible)

##### Current Result
Hi,
I have build a jenkins,and configure master-config(maybe is wrong),But haven't pipeline button.
![jenkins-1](https://cloud.githubusercontent.com/assets/12937669/18980276/4ee7bc0c-8705-11e6-949a-041dc6448caf.png)
```
#/etc/origin/master/master-config.yaml
jenkinsPipelineConfig:
  autoProvisionEnabled: true 
  templateNamespace: openshift 
  templateName: jenkins-persistent
  serviceName: jenkins
  parameters: null
```
##### Expected Result
how can i do for make it in openshift origin 1.3,such as official[1]? thanks.
![jenkins-2](https://cloud.githubusercontent.com/assets/12937669/18980308/9218d3bc-8705-11e6-88a9-fea81c162510.png)

[1] https://blog.openshift.com/whats-new-openshift-3-3-web-console/
