### ISSUE TITLE
How to add a line on /etc/hosts?

### ISSUE THREAD

**Issue by luiscoms** [openshift/origin#11191]
Hi, I could not find a way to add a line on /etc/hosts via configuration like docker documentation:

https://docs.docker.com/engine/reference/run/
##### Version

``` bash
$ oc version
oc v1.3.0
kubernetes v1.3.0+52492b4
features: Basic-Auth

Server https://openshift.localhost.com.br:8443
kubernetes v1.2.0-36-g4a3f9c5
```

**Comment by detiber** [comment]
@ncdc The request is for adding entries to /etc/hosts on the managed containers.

**Comment by ncdc** [comment]
Not supported today. Although you get this for free with Services, since they're available via DNS.

**Comment by ncdc** [comment]
@luiscoms what kind of host entry are you trying to add?

**Comment by luiscoms** [comment]
@ncdc In a `docker-compose` application we have the configuration like this:


```yml
version: '2'
services:
  service_name:
    ...
    extra_hosts:
        api.example.com.br: 192.168.5.10

```

That just add the parameter `--add-host  "api.example.com.br:192.168.5.10"` in the `docker run` command.

My question is if exists an equivalence in openshift
