### ISSUE TITLE
"Host ports are not allowed to be used"

### ISSUE THREAD

**Issue by meagon** [openshift/origin#11271]
```
pods "javaweb" is forbidden: unable to validate against any security context constraint: [spec.containers[0].securityContext.containers[0].hostPort: Invalid value: 8001: Host ports are not allowed to be used]
```

**I got "Host ports are not allowed to be used" this error while i use web console to load bellow yaml,
what should i do, if i want use the host port?**

##### Version
```
# openshift version
openshift 4
kubernetes v1.3.0+52492b4
etcd 2.3.0+git

#oc version
oc 4
kubernetes v1.3.0+52492b4
features: Basic-Auth

Server https://192.168.0.100:8443
openshift 4
kubernetes v1.3.0+52492b4

```

##### Steps To Reproduce

```
apiVersion: v1
kind: Pod
metadata:
  name: javaweb
spec:
  containers:
  - image: resouer/sample:v1
    name: war
    volumeMounts:
    - mountPath: /app
      name: app-volume
  - image: resouer/mytomcat:7.0
    name: tomcat
    command: ["sh","-c","/root/apache-tomcat-7.0.42-v2/bin/start.sh"]
    volumeMounts:
    - mountPath: /root/apache-tomcat-7.0.42-v2/webapps
      name: app-volume
    ports:
    - containerPort: 8080
      hostPort: 8001
  volumes:
  - name: app-volume
    emptyDir: {}
```
