### ISSUE TITLE
pipeline deployment keeps re-deploying over and over again

### ISSUE THREAD

**Issue by mbalazs** [openshift/origin#11519]
I am trying to set up a build pipeline by following the tutorial on the OpenShift blog site  (https://blog.openshift.com/create-build-pipelines-openshift-3-3/), but I couldn't manage to set it up properly, not even the simple pipeline from Part 1.

When I start the pipeline, the build phase succeeds, and then at the deployment phase it keeps on deploying the application over and over again. 10 minutes and about 30 deployments later the deployment phase of the pipeline times out, and the build pipeline stops with an error. At this point, the continous re-deployment stops and I end up with a working deployment of my app.

##### Version
openshift v1.3.0
kubernetes v1.3.0+52492b4

##### Steps To Reproduce
1. Set up a pipeline build with the following config:
```yaml
apiVersion: v1
kind: BuildConfig
metadata:
  annotations:
    pipeline.alpha.openshift.io/uses: '[{"name": "myapp", "namespace": "", "kind":
      "DeploymentConfig"}]'
  creationTimestamp: null
  labels:
    name: myfirstpipeline
  name: myfirstpipeline
spec:
  output: {}
  postCommit: {}
  resources: {}
  runPolicy: Serial
  source:
    type: None
  strategy:
    jenkinsPipelineStrategy:
      jenkinsfile: |-
        node('maven') {
        stage 'build'
        openshiftBuild(buildConfig: 'myapp', showBuildLogs: 'true')
        stage 'deploy'
        openshiftDeploy(deploymentConfig: 'myapp')
        openshiftScale(deploymentConfig: 'myapp',replicaCount: '2')
        }
    type: JenkinsPipeline
  triggers: []
```
2. Deploy an S2I application ("myapp") from the web console (I used Wildfly 10 with the sample repository).
Uncheck the "Config Change" and "Image Change" triggers at the advanced options during the application creation.

3. Edit the "myapp" DC, and add the proper image spec (172.30.232.245:5000/pipeline-build/myapp:latest) on the pod template. The resulting DC looks like this:
```yaml
apiVersion: v1
kind: DeploymentConfig
metadata:
  annotations:
    openshift.io/generated-by: OpenShiftWebConsole
  creationTimestamp: null
  generation: 129
  labels:
    app: myapp
  name: myapp
spec:
  replicas: 1
  selector:
    deploymentconfig: myapp
  strategy:
    resources: {}
    rollingParams:
      intervalSeconds: 1
      maxSurge: 25%
      maxUnavailable: 25%
      timeoutSeconds: 600
      updatePeriodSeconds: 1
    type: Rolling
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: myapp
        deploymentconfig: myapp
    spec:
      containers:
      - image: 172.30.232.245:5000/pipeline-build/myapp:latest
        imagePullPolicy: Always
        name: myapp
        ports:
        - containerPort: 8080
          protocol: TCP
        resources: {}
        terminationMessagePath: /dev/termination-log
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      securityContext: {}
      terminationGracePeriodSeconds: 30
  test: false
  triggers: []
```
4. Start the pipeline

##### Current Result

The "Build" phase of the pipeline succeeds, but at the deployment phase the myapp DC keeps deploying over and over again until the pipeline times out. The deployments of the myapp DC always succeed. The pipeline build ends up failing after the timeout.

##### Expected Result

The deployment phase of the pipeline succeeds after a single deployment of "myapp" is completed.
