### ISSUE TITLE
Using env for OAuth config clientSecret doesn't work?

### ISSUE THREAD

**Issue by alikhajeh1** [openshift/origin#11652]
[The docs](https://docs.openshift.org/latest/install_config/master_node_configuration.html#master-node-configuration-passwords-and-other-data) mention that [the OAuth configs](https://docs.openshift.org/latest/install_config/configuring_authentication.html) can use env variables instead of hard coding the clientSecret into master-config.yaml. However, an error complaining that the clientSecret is missing is thrown when this is done.

##### Version
```
# oc version
oc v1.3.0
kubernetes v1.3.0+52492b4
features: Basic-Auth GSSAPI Kerberos SPNEGO

Server https://[...]:8443
openshift v1.3.0
kubernetes v1.3.0+52492b4
```

##### Steps To Reproduce
1. On the master node terminal, run `export GITLAB_OAUTH_CLIENT_SECRET=MY_SECRET_HERE`
2. Edit master-config.yaml as follows:
```
oauthConfig:
  ...
  identityProviders:
  - name: GitLab
    challenge: true
    login: true
    mappingMethod: generate
    provider:
      apiVersion: v1
      kind: GitLabIdentityProvider
      url: https://gitlab.com/
      clientID: MY_CLIENT_ID_HERE
      clientSecret:
        env: GITLAB_OAUTH_CLIENT_SECRET
```
Restart origin master

##### Current Result
```
$ systemctl restart origin-master
Job for origin-master.service failed because the control process exited with error code. See "systemctl status origin-master.service" and "journalctl -xe" for details.

$ journalctl -xe
Oct 30 02:35:02 ... origin-master[93224]: Invalid MasterConfig /etc/origin/master/master-config.yaml
Oct 30 02:35:02 ... origin-master[93224]: oauthConfig.identityProvider[0].provider.clientSecret: Required value
```
I also tried using the following variations but no luck:
```
clientSecret:
        env: $GITLAB_OAUTH_CLIENT_SECRET
```

```
clientSecret:
        env: ${GITLAB_OAUTH_CLIENT_SECRET}
```

```
clientSecret:
        file: /etc/origin/master/gitlab_client_secret.txt
```

##### Expected Result
Origin master should restart without errors, and users should be able to login using the configured identity provider.

Any idea what I'm doing wrong?
