### ISSUE TITLE
during mass simultaneous build creations, Docker timeouts occur

### ISSUE THREAD

**Issue by thoraxe** [openshift/origin#11761]
In my particular case, I am scheduling 100 builds simultaneously using a loop. In build logs I will see the following:

error: build error: timeout after waiting 1m0s for Docker to create container

It also seems to take builds quite a long time to move from Pending -> Running.

Out of 100 builds, 26 failed in this way (timeout after waiting). I have 6 m4.4xlarge nodes on EC2.

##### Version
oc v3.3.1.3
kubernetes v1.3.0+52492b4
features: Basic-Auth GSSAPI Kerberos SPNEGO
openshift v3.3.1.3
kubernetes v1.3.0+52492b4

##### Steps To Reproduce
1. Create 100 builds "simultaneously" across multiple projects

##### Current Result
A large number will fail unexpectedly with Docker timeouts.

##### Expected Result
All builds start and run to completion.

**Comment by bparees** [comment]
@jeremyeder I think we need some help from the performance team to understand why the docker daemon seems to become unresponsive(takes over a minute to response to a create container api call) in these conditions and whether there's anything we can do better.

**Comment by jeremyeder** [comment]
Ack -- @thoraxe can you share how you're triggering this please?  The exact reproducer including any images used.

**Comment by thoraxe** [comment]
Assuming you already have the projects created:

```bash
for num in $(seq -f %02d 0 100)
do
  oc new-app simple-java-s2i~https://github.com/openshift-roadshow/nationalparks -n project$num
done
```

simple-java-s2i is a builder imagestream definition as follows:

```yaml
---
kind: ImageStream
apiVersion: v1
metadata:
  name: simple-java-s2i
spec:
  dockerImageRepository: jorgemoralespou/s2i-java
  tags:
  - name: 'latest'
    annotations:
      description: Simple Java 1.8 S2I builder
      iconClass: icon-jboss
      tags: builder,java
      supports: java:8
      version: '1.0'
```

The builder image is already cached on every node in the environment.

There are already several pods running on each node -- probably about 10 -- that are all the same image: docker.io/openshiftdemos/parksmap:0.4
