### ISSUE TITLE
Custom Deployment Strategy Examples

### ISSUE THREAD

**Issue by MarkRx** [openshift/origin#11963]
The OpenShift origin documentation mentions a way to create custom deployment strategies at https://docs.openshift.org/latest/dev_guide/deployments/deployment_strategies.html#custom-strategy. I cannot find any examples doing this. Are there any?

In particular I am wondering how it would be able to perform REST calls as that would require some way to pass around user credentials or an authentication token.

**Comment by kargakis** [comment]
@mfojtik passing this to you since you work on custom deployments lately

**Comment by mfojtik** [comment]
@MarkRx an example deployment configuration can be found here: https://github.com/openshift/origin/blob/master/test/extended/testdata/deployments/custom-deployment.yaml

For authentication you can pass the service account token and give the service account access your deployment strategy require. The service account token is a mounted secret (`/var/run/secrets/...`).

**Comment by kargakis** [comment]
@mfojtik this is a test fixture. We should have an example in docs.

**Comment by mfojtik** [comment]
@kargakis agree, I will update docs

**Comment by mfojtik** [comment]
PR: https://github.com/openshift/openshift-docs/pull/3260

**Comment by mfojtik** [comment]
docs PR landed, closing this issue.

**Comment by nhenderson** [comment]
I thought I would include a deployment strategy of `type: Custom`. I could not find any concrete examples online or in the OpenShift documentation about this. So, I came up with the following method that works in my Minishift environment:
```yaml
spec:
  replicas: 1
  selector:
    cbbridges.service: bridges-web
  strategy:
    resources: {}
    type: Custom
    customParams:
      image: openshift/origin-deployer
      command:
      - /bin/sh
      - -c
      - >
        # Pre-deployment code goes here

        oc scale replicationcontrollers/${OPENSHIFT_DEPLOYMENT_NAME}
        --replicas=1
        -n ${OPENSHIFT_DEPLOYMENT_NAMESPACE}
        --token=${LOGIN_TOKEN}
        --server=${MASTER_SERVER}
        --insecure-skip-tls-verify;

        # Post-deployment code goes here.

        # TODO: Figure out to make sure the deployment is complete 
        #       and the pod is running before executing any post-deployment code
      environment:
      - name: LOGIN_TOKEN
        value: (* see below)
      - name: MASTER_SERVER
        # Minishift login URL
        value: https://192.168.42.229:8443
...
```
 *  Fill in the value of the `LOGIN_TOKEN` env var above with a token of a service account that has permission to `scale` your replication controllers. For example, in minishift, the `pvinstaller` service account has permission by default to scale replication controllers. You can get `pvinstaller` token by running `oc sa get-token pvinstaller -n default`. 
**TIP**: To see all service accounts that have permission to scale your replicationcontrollers on your current project, run the following: `oc policy who-can deploy rc`.
* **NOTE**: The `openshift/origin-deployer` pod comes with many useful environment variables that are helpful for interacting with your cluster (including the `OPENSHIFT_DEPLOYMENT_NAMESPACE` and `OPENSHIFT_DEPLOYMENT_NAME` variables).
