### ISSUE TITLE
deploymentconfigs when run iteratively [Conformance] [It] should only deploy the last deployment 

### ISSUE THREAD

**Issue by kargakis** [openshift/origin#12060]
Finally a new one:
```
• Failure [142.736 seconds]
deploymentconfigs
/data/src/github.com/openshift/origin/test/extended/deployments/deployments.go:840
  when run iteratively [Conformance]
  /data/src/github.com/openshift/origin/test/extended/deployments/deployments.go:196
    should only deploy the last deployment [It]
    /data/src/github.com/openshift/origin/test/extended/deployments/deployments.go:135

    Expected error:
        <*errors.errorString | 0xc820e5f3c0>: {
            s: "found multiple running deployments: [deployment-simple-3 deployment-simple-4]",
        }
        found multiple running deployments: [deployment-simple-3 deployment-simple-4]
    not to have occurred

    /data/src/github.com/openshift/origin/test/extended/deployments/deployments.go:124
------------------------------
```
Third deployment thinks its deployer pod is gone, 4th deployer gets created.
```
apiVersion: v1
kind: ReplicationController
metadata:
  annotations:
    kubectl.kubernetes.io/desired-replicas: "2"
    openshift.io/deployer-pod.name: deployment-simple-3-deploy
    openshift.io/deployment-config.latest-version: "3"
    openshift.io/deployment-config.name: deployment-simple
    openshift.io/deployment.phase: Failed
    openshift.io/deployment.replicas: "0"
    openshift.io/deployment.status-reason: deployer pod no longer exists
```
https://ci.openshift.redhat.com/jenkins/job/test_pull_requests_origin_conformance/8960/consoleFull#-169259343956c60d7be4b02b88ae8c268b
