### ISSUE TITLE
Not possible to run PetSets whitout "add-scc-to-user anyuid..."

### ISSUE THREAD

**Issue by eni23** [openshift/origin#12063]
Openshift makes the PetSet feature from Kubernetes nearly unusable, since it's not possible to run them out-of-the-box.

##### Version
openshift v1.3.0
kubernetes v1.3.0+52492b4

##### Steps To Reproduce
- Create a PetSet with an NFS Volume
- Try to access this volume

##### Current Result
- Permission denied on all Pet Volumes when trying to access them inside the pod.

##### Expected Result
- I can access the volume which have the same mount permissions as the user my stuff runs in the container. 

##### Additional Information
- The solution you mention in a few issues basically disables ALL security features in OpenShift. I would expect that the volumes got mounted as user who runs my stuff in the pod and not something completely unrelated uid.

What is your vision here? Will there be improvements for this problems? Like this PetSets are not useable in OpenShift.

**Comment by ncdc** [comment]
@smarterclayton @ingvagabund

**Comment by smarterclayton** [comment]
What kind of NFS volume?  @pmorie

**Comment by vigneshmpn** [comment]
@pweil- @pmorie 
I ran into a permission issue while adding persistent volume to a Petset. I am running Openshift Origin all-in-one setup using Vagrant. I have setup petset for my couchbase image using pre-provisioned volumes in all-in-one setup. While I bring the couchbase pod, I get the following permission issue during the bootup.
`chown: changing ownership of 'var/lib/couchbase/stats': Operation not permitted`
I wonder if it is related to this issue. Here is my Petset config:
```
apiVersion: apps/v1alpha1
kind: PetSet
metadata:
  name: couchbase
spec:
  serviceName: "couchbase"
  replicas: 2
  template:
    metadata:
      labels:
        app: couchbase
      annotations:
        pod.alpha.kubernetes.io/initialized: "true"
    spec:
      terminationGracePeriodSeconds: 0
      serviceAccount: infra
      containers:
      - name: couchbase
        image: couchbase/server:latest
        ports:
        - containerPort: 8091
        volumeMounts:
        - name: couchbase-data
          mountPath: /opt/couchbase/var
      securityContext:
        supplementalGroups: [65534]
  volumeClaimTemplates:
  - metadata:
      name: couchbase-data
    spec:
      accessModes: [ "ReadWriteOnce" ]
      resources:
        requests:
          storage: 1Gi
```

File permission of the mounted volume: /opt/couchbase/var 
```
# ls -al /opt/couchbase/var -d
drwxrwxrwx. 3 nobody nogroup 4096 Mar   8 14:45 /opt/couchbase/var
```

After investigating more on SCC, I understood that openshift runs containers with specific user ID which part of the root group. As the pre-provisioned volumes in all-in-one setup is NFS, I tried adding group ID of "nogroup" as supplementalGroups, so that openshift's user ID will be part of nogroup and hence will have required file permissions to operate on /opt/couchbase/var.

# id nobody
uid=65534(nobody) gid=65534(nogroup) groups=65534(nogroup)

Following is the securityContext config for my petset:
      securityContext:
        supplementalGroups: [65534]

As mentioned in this issue, I also executed "oc adm policy add-scc-to-user anyuid -z default"

Based on my understanding of SCC, I have tried two solutions: 1. Add nogroup group ID in the supplementalGroups and 2. executing add-scc-to-user anyuid, but still I am unable to resolve the file permission issue.

Any help is appreciated
