### ISSUE TITLE
DeploymentConfig is not able to resolve all images if it has more than one container

### ISSUE THREAD

**Issue by AlbertoPeon** [openshift/origin#12109]
`DeploymentConfig` with a pod template containing more than one container fail to resolve the image from the `ImageChange` trigger. This happens only if the two containers are specified in the `containerNames` attribute of the same trigger. 
This issue appeared in 1.3.1 as on 1.2.1 worked as expected

##### Version
```
$ oc version 
oc v1.3.1
kubernetes v1.3.0+52492b4
features: Basic-Auth GSSAPI Kerberos SPNEGO
```
Server is also running 1.3.1. 

##### Steps To Reproduce
1. Creating a `DeploymentConfig` with more than one container, e.g.
```yaml
kind: "DeploymentConfig"
apiVersion: "v1"
metadata:
  name: "example"
spec:
  triggers:
  - type: "ConfigChange"
  - type: "ImageChange"
    imageChangeParams:
      automatic: true
      containerNames:
      - 'container-a'
      - 'container-b'
      from:
        kind: "ImageStreamTag"
        name: "wildfly:latest"
        namespace: openshift
  replicas: 1
  selector:
    name: 'example'
  template:
    metadata:
      labels:
        name: 'example'
    spec:
      containers:
        -
          name: "container-a"
          image: "wildfly:latest"
        -
          name: "container-b"
          image: "wildfly:latest"

```
##### Current Result
Only `container-a` resolves the image from the `ImageStreamTag`, while `container-b` tries to pull `library/wildfly:latest`:

```
ReplicationController             Normal    SuccessfulCreate   {replication-controller }   Created pod: example-1-rr8jj
Pod                 Normal    Scheduled   {default-scheduler }   Successfully assigned example-1-rr8jj to node1
Pod       spec.containers{container-a}   Normal    Pulling   {kubelet node1}   pulling image "openshift/wildfly-100-centos7@sha256:6a059132fa41743b6aa536b7b19bc152fdf7954e4574fcbdeb60afb5edf2e44b"
Pod       spec.containers{container-a}   Normal    Pulled    {kubelet node1}   Successfully pulled image "openshift/wildfly-100-centos7@sha256:6a059132fa41743b6aa536b7b19bc152fdf7954e4574fcbdeb60afb5edf2e44b"
Pod       spec.containers{container-a}   Normal    Created   {kubelet node1}   Created container with docker id 13a216323732
Pod       spec.containers{container-a}   Normal    Started   {kubelet node1}   Started container with docker id 13a216323732
Pod       spec.containers{container-b}   Normal    Pulling   {kubelet node1}   pulling image "wildfly:latest"
Pod       spec.containers{container-b}   Warning   Failed    {kubelet node1}   Failed to pull image "wildfly:latest": Error: image library/wildfly not found
Pod                 Warning   FailedSync   {kubelet oonode109}   Error syncing pod, skipping: failed to "StartContainer" for "container-b" with ErrImagePull: "Error: image library/wildfly not found"

```

##### Expected Result
Both `container-a` and `container-b` start using the image in `"openshift/wildfly-100-centos7@sha256:...` instead of interpreting the ImageStream name as the final image name

##### Additional Information
The problem seems to be in setting more than one container in the `ImageChange` trigger. Using two different triggers make both container to successfully resolve the images, e.g.
```yaml
      - type: "ImageChange"
        imageChangeParams:
          automatic: true
          containerNames:
          - "container-a"
          from:
            kind: "ImageStreamTag"
            name: "wildfly:latest"
            namespace: openshift
      - type: "ImageChange"
        imageChangeParams:
          automatic: true
          containerNames:
          - "container-b"
          from:
            kind: "ImageStreamTag"
            name: "wildfly:latest
            namespace: openshift
```

This issue appeared after the upgrade to Origin 1.3.1.
