### ISSUE TITLE
build error: No submodule mapping found in .gitmodules

### ISSUE THREAD

**Issue by surajssd** [openshift/origin#12139]
Build pod errors out as above error while normal git clone normally done works.
The repo on which this is done is https://github.com/container-workbook/docker-workshop.git which has pyconapp folder with Dockerfile.

##### Version
```bash
$ oc version
oc v1.4.0-rc1+b4e0954
kubernetes v1.4.0+776c994
features: Basic-Auth GSSAPI Kerberos SPNEGO

Server https://192.168.121.103:8443
openshift v1.4.0-rc1+b4e0954
kubernetes v1.4.0+776c994
```

##### Steps To Reproduce

Imagestream used:

```yaml
$ cat app-imagestream.yaml 
apiVersion: v1
kind: ImageStream
metadata:
  creationTimestamp: null
  name: app
spec: {}
status:
  dockerImageRepository: ""
```

buildconfig used:

```yaml
$ cat app-buildconfig.yaml 
apiVersion: v1
kind: BuildConfig
metadata:
  creationTimestamp: null
  name: app
spec:
  output:
    to:
      kind: ImageStreamTag
      name: app:latest
  postCommit: {}
  resources: {}
  runPolicy: Serial
  source:
    contextDir: pyconapp
    git:
      ref: master
      uri: https://github.com/container-workbook/docker-workshop.git
    type: Git
  strategy:
    dockerStrategy: {}
    type: Docker
  triggers:
  - type: ConfigChange
  - type: ImageChange
status:
  lastVersion: 0
```

creating project and deploying above artifacts:

```bash
$ oc new-project gitclone

$ oc create -f app-imagestream.yaml 
imagestream "app" created

$ oc create -f app-buildconfig.yaml 
buildconfig "app" created
```

##### Current Result

check running pods:
```bash
$ oc get pods
NAME          READY     STATUS    RESTARTS   AGE
app-1-build   0/1       Error     0          26s
```

which errors out as:

```bash
$ oc logs app-1-build
Cloning "https://github.com/container-workbook/docker-workshop.git" ...
error: build error: No submodule mapping found in .gitmodules for path 'asciidoctor-reveal.js'
```

##### Expected Result

while I can do normal git clone

```bash
$ git clone https://github.com/container-workbook/docker-workshop.git
Cloning into 'docker-workshop'...
remote: Counting objects: 98, done.
remote: Total 98 (delta 0), reused 0 (delta 0), pack-reused 98
Unpacking objects: 100% (98/98), done.
Checking connectivity... done.

$ ll docker-workshop/
total 40
lrwxrwxrwx. 1 vagrant vagrant    26 Dec  5 12:27 README.adoc -> docker_basic_workshop.adoc
drwxrwxr-x. 2 vagrant vagrant  4096 Dec  5 12:27 asciidoc
drwxrwxr-x. 2 vagrant vagrant  4096 Dec  5 12:27 asciidoctor-reveal.js
-rw-rw-r--. 1 vagrant vagrant  5026 Dec  5 12:27 docker_basic_workshop.adoc
-rw-rw-r--. 1 vagrant vagrant 14529 Dec  5 12:27 docker_basic_workshop_handson.adoc
drwxrwxr-x. 2 vagrant vagrant  4096 Dec  5 12:27 pyconapp
drwxrwxr-x. 2 vagrant vagrant  4096 Dec  5 12:27 reveal.js
```
