### ISSUE TITLE
Is it possible to scope LimitRanges?

### ISSUE THREAD

**Issue by alikhajeh1** [openshift/origin#12130]
We're using a project template with LimitRange to bound pod cpu/memory usage. However, this is also limiting build pods so builds are pretty slow. We'd like to give users a fast build experience so is it possible to set per-pod LimitRanges that are only scoped to user pods? i.e. not builder or deployer pods. ResourceQuotas have support for NotTerminating scopes, but it doesn't seem like a similar option is available for LimitRanges.

Or perhaps there's another way to achieve this? We'd like to let users launch as many pods as they like, but limit each pod's cpu/memory usage, ResourceQuotas don't seem to cover this use-case.

```
Extracts from our project template:
- apiVersion: v1
  kind: ResourceQuota
  metadata:
    creationTimestamp: null
    name: project-pod-limits
    namespace: ${PROJECT_NAME}
  spec:
    hard:
      pods: 1000
    scopes:
    - NotTerminating

- apiVersion: v1
  kind: LimitRange
  metadata:
    creationTimestamp: null
    name: project-compute-resource-limits
    namespace: ${PROJECT_NAME}
  spec:
    limits:
    - max:
        cpu: 100m
        memory: 500Mi
      type: Pod
      scopes:                                 <<<<<<< Something like this
      - NotTerminating                        <<<<<<<
``` 

##### Version
```
oc v1.4.0-alpha.1+5f9a5ec-217
kubernetes v1.4.0+776c994
features: Basic-Auth GSSAPI Kerberos SPNEGO

openshift v1.4.0-alpha.1+5f9a5ec-217
kubernetes v1.4.0+776c994
```

P.S. Loving 1.4's Memberships and Secrets UI, simplifies demos a lot.
