### ISSUE TITLE
Build failure reasons aren't being reported

### ISSUE THREAD

**Issue by jwforres** [openshift/origin#12146]
For builds that end up in the Failed status phase, the build failure reason and message aren't showing up

Example of a build status that failed because I deleted the build pod

```
status:
  phase: Failed
  startTimestamp: '2016-12-05T20:18:19Z'
  completionTimestamp: '2016-12-05T20:18:27Z'
  duration: 8000000000
  config:
    kind: BuildConfig
    namespace: myproject
    name: node-ex
```

Also reproduced this by putting in a bogus source url

Cancelled builds do seem to get their reason/message added.
