### ISSUE TITLE
Design proposal for "Use build source secret based on annotation on Secret"

### ISSUE THREAD

**Issue by jim-minter** [openshift/origin#12298]
@api-review, please consider the following design proposal to implement [Use build source secret based on annotation on Secret](https://trello.com/c/NoVpS2OS/1059-5-use-build-source-secret-based-on-annotation-on-secret-builds) in this sprint cycle.

(The card goal is for oc new-app/new-build to discover a relevant pre-existing Secret and attempt to use it when a source repo requires authentication.  The intention is to do this without adding yet more CLI arguments to new-app/new-build.)

Design proposal:
----------------

- A Secret may include an annotation with a well-known name.  The name *io.openshift.match-urls* is proposed.

- A valid annotation value consists of zero or more comma-separated "optionally-wildcarded URL patterns" (defined below).

- If a source repository requires authentication, and a Secret exists where any of its "optionally-wildcarded URL patterns" matches the source repository URL, oc new-app/new-build will use that Secret to authenticate against the repository.  If the new-app/new-build process succeeds and a BuildConfig is created, the BC sourceSecret will be set to refer to the same Secret.

- The optionally-wildcarded URL patterns are proposed to be very similar to Chrome's [Match Patterns](https://developer.chrome.com/extensions/match_patterns).  I believe these provide the appropriate level of flexibility, are as intuitive as these things can be, cover relevant security considerations in their design, and can be implemented reasonably straightforwardly.  Proposed differences from the referenced spec would include:
  - the '<all_urls>' pattern would not be implemented.
  - permitted schemes would be 'http', 'https' and 'ssh'.
  - a scheme wildcard would match all above schemes.
  - comma characters in patterns would not be permitted.

  Also note for clarity that the empty pattern is invalid and as such matches no URL.

- In the valid case that a given source repository URL matches optionally-wildcarded URL patterns from multiple Secrets, the Secret chosen would be the one whose individual matching URL pattern is longest.  This allows for overrides, e.g. in scenarios such as the following:

```
- kind: Secret
  metadata:
    name: matches-all-corporate-servers-https-only
    annotations:
      io.openshift.match-urls: https://*.mycorp.com/*
  ...

- kind: Secret
  metadata:
    name: override-for-my-dev-servers
    annotations:
      io.openshift.match-urls: https://mydev1.mycorp.com/*, https://mydev2.mycorp.com/*
  ...
```

@bparees
