### ISSUE TITLE
Illegal HTTP 1.1 behavior in instantiatebinary operation

### ISSUE THREAD

**Issue by nicolaferraro** [openshift/origin#12300]
When doing a binary build by posting a `tar` file to the endpoint `https://$HOST:$PORT/oapi/v1/namespaces/myproject/buildconfigs/my-build-config/instantiatebinary`, if there are problems with the builder image (in my case, I used a docker image that **does not exist**), the build container is terminated and the data stream coming from the client is interrupted brutally by Openshift (the client gets a "Connection Reset") but Openshift also creates a JSON response giving all the details about the build (response code 201).

This combination of "Created" (201) and connection closed while the client is still sending data prevents the user sending unuseful bytes when the build is going to fail, but seems not to be compliant with HTTP 1.1 specifications.

In fact many (if not all) Java HTTP client ignore the 201 message and the JSON response and throw back an exception to the user (Connection Reset). I've tested it with Java URLConnection, Apache HTTP Client, OkHTTP.

This does not allow us to send details of the error to the client, to investigate the cause.

The only client that supports such behavior seems to be CURL (I've not checked the Go client).

##### Version
```
oc v1.4.0-rc1+b4e0954
kubernetes v1.4.0+776c994
features: Basic-Auth GSSAPI Kerberos SPNEGO

Server https://192.168.2.148:8443
openshift v1.4.0-rc1+b4e0954
kubernetes v1.4.0+776c994
```

##### Steps To Reproduce
1. Start the cluster with `oc cluster up`
2. Create a image stream `oc create is my-is-nok`
3. Create a build config with an invalid docker image: `oc create -f bc_not_ok.yaml`
The content of the file can be:
```yaml
apiVersion: v1
kind: BuildConfig
metadata:
  name: bc-nok-s2i
  namespace: myproject
spec:
  triggers: []
  runPolicy: Serial
  source:
    type: Binary
    binary: {}
  strategy:
    type: Source
    sourceStrategy:
      from:
        kind: DockerImage
        name: 'this-image/does-not-exist:1.0'
  output:
    to:
      kind: ImageStreamTag
      name: 'my-is-nok:latest'
  resources: {}
  postCommit: {}
  nodeSelector: null
```

4. The following script should return a normal JSON:
```
curl --insecure -X POST --data-binary @any-tar.tar \
    --header "Content-Type: application/octet-stream" \
    --header "Accept: application/json" \
    --header "Authorization: Bearer $TOKEN" \
    "$PROTOCOL://$HOST:$PORT/oapi/v1/namespaces/myproject/buildconfigs/bc-nok-s2i/instantiatebinary?commit="
```

5. An equivalent post using any Java client will result in a "Connection Reset" exception.

##### Current Result

A connection reset.

##### Expected Result
```json
{
  "kind": "Build",
  "apiVersion": "v1",
  "metadata": {
    "name": "bc-nok-s2i-2",
    "namespace": "myproject",
    "selfLink": "/oapi/v1/namespaces/myproject/builds/bc-nok-s2i-2",
    "uid": "3a788182-c3ac-11e6-aa38-507b9dcf1324",
    "resourceVersion": "767",
    "creationTimestamp": "2016-12-16T16:25:16Z",
    "labels": {
      "buildconfig": "bc-nok-s2i-",
      "openshift.io/build-config.name": "bc-nok-s2i",
      "openshift.io/build.start-policy": "Serial"
    },
    "annotations": {
      "openshift.io/build-config.name": "bc-nok-s2i",
      "openshift.io/build.number": "2",
      "openshift.io/build.pod-name": "bc-nok-s2i-2-build"
    }
  },
  "spec": {
    "serviceAccount": "builder",
    "source": {
      "type": "Binary",
      "binary": {}
    },
    "strategy": {
      "type": "Source",
      "sourceStrategy": {
        "from": {
          "kind": "DockerImage",
          "name": "this-image/does-not-exist:1.0"
        }
      }
    },
    "output": {
      "to": {
        "kind": "ImageStreamTag",
        "name": "my-is-nok:latest"
      },
      "pushSecret": {
        "name": "builder-dockercfg-9hivl"
      }
    },
    "resources": {},
    "postCommit": {},
    "nodeSelector": null,
    "triggeredBy": null
  },
  "status": {
    "phase": "Running",
    "startTimestamp": "2016-12-16T16:25:19Z",
    "config": {
      "kind": "BuildConfig",
      "namespace": "myproject",
      "name": "bc-nok-s2i"
    }
  }
}
```
