### ISSUE TITLE
can't specify resources from template

### ISSUE THREAD

**Issue by leejansq** [openshift/origin#12334]
##### Version
1.3.1+2748423

##### Steps To Reproduce
1. create a template with resource
```yaml
   ...
    containers:
            -
              image: ""
              name: '${APP_NAME}'
              ports: [{containerPort: '${APP_PORT}', protocol: TCP}]
              resource: {limits: {cpu: '${CPU_LIMIT}', memory: '${MEMORY_LIMIT}'}, requests: {cpu: '${CPU_LIMIT}'
  ...
  parameters:
  -
    name: MEMORY_LIMIT
    description: 'memory limit'
    value: 512mi
  -
    name: CPU_LIMIT
    description: 'cpu limit'
    value: 1000m
```
2. create a dc from the template

##### Current Result
```yaml
containers:
        -
          name: app1
          image: 'xxx'
          ports:
            -
              containerPort: 8000
              protocol: TCP
          resources:
```
##### Expected Result
the resources of container should not be null
