### ISSUE TITLE
Unicode escape sequence visible in router status message

### ISSUE THREAD

**Issue by spadgett** [openshift/origin#12405]
A unicode escape sequence is visible in the router ingress status message. This shows up in the web console tooltip warning for the route.

![screen_shot_2017-01-06_at_8_18_43_am](https://cloud.githubusercontent.com/assets/1167259/21719106/e3243496-d3e9-11e6-8e2a-08be9dd25a0b.png)

Here is the route status YAML:

```yaml
status:
  ingress:
    - host: origin-web-console-origin-web-console.localhost.dev
      routerName: router
      conditions:
        - type: Admitted
          status: 'False'
          reason: ExtendedValidationFailed
          message: |-

              - spec.tls.destinationCACertificate: Invalid value: "\u003cdestination ca certificate data\u003e": failed to parse destination CA certificate: Could not read any certificates
          lastTransitionTime: '2017-01-06T13:14:46Z'
      wildcardPolicy: None
```

cc @knobunc

##### Version
v1.5.0-alpha.1+67e632c-41

##### Steps To Reproduce
1. Create a reencrypt route with no destination CA cert
2. View the route warning in the web console (or view YAML to see the raw message)
