### ISSUE TITLE
Azure disk as a PV 

### ISSUE THREAD

**Issue by blasrodriguez** [openshift/origin#12498]
Trying to configure azure disk as a Persistent Volume in openshift. 
We are following the official guide: https://docs.openshift.org/latest/install_config/configuring_azure.html
Documentation seems to be bad indented. It says:
```
kubernetesMasterConfig:
  ...
  apiServerArguments:
    cloud-provider:
      - "azure"
      cloud-config:
        - "/etc/azure/azure.conf"
```
but it has to be:
```
kubernetesMasterConfig:
  apiServerArguments:
    cloud-provider:
      - "azure"
    cloud-config:
      - "/etc/azure.conf"
```

With the configuration corrected, when trying to start the service we get this error:
```
origin-master[122055]: F0116 07:57:42.934582  122055 start_master.go:102] unknown cloud provider "azure"
```

##### Version
oc v1.3.1
kubernetes v1.3.0+52492b4
features: Basic-Auth GSSAPI Kerberos SPNEGO

##### Steps To Reproduce
1. Modify /etc/origin/master/master-config.yaml to include azure configuration as explained in https://docs.openshift.org/latest/install_config/configuring_azure.html
2. service origin-master restart

##### Current Result
Failed to start Origin Master Service

##### Expected Result
Origin Master Service is started with azure as a cloud provider
