### ISSUE TITLE
Incremental build much slower than non-incremental build

### ISSUE THREAD

**Issue by omallo** [openshift/origin#12703]
I would like to use incremental builds together with the Wildfly s2i image but it turns out that incremental builds are much slower than non-incremental ones. The functionality of the incremental build itself seems to work fine which means that Maven artifacts are not downloaded anymore but what takes lots of time is pulling the previous image which is necessary to get the saved artifacts. I'm testing with a local cluster (using `oc cluster up`) so pulling an existing image should be fast.

##### Version
```
$ oc version
oc v1.4.1+3f9807a
kubernetes v1.4.0+776c994
features: Basic-Auth

Server https://127.0.0.1:8443
openshift v1.4.1+3f9807a
kubernetes v1.4.0+776c994
```

##### Steps To Reproduce
1. Store the build config in a file `build.yaml`:
```yaml
---
apiVersion: v1
kind: ImageStream
metadata:
  name: jee-ex
---
apiVersion: v1
kind: BuildConfig
metadata:
  name: jee-ex
spec:
  output:
    to:
      kind: ImageStreamTag
      name: jee-ex:latest
  source:
    git:
      uri: https://github.com/openshift/jee-ex.git
    type: Git
  strategy:
    type: Source
    sourceStrategy:
      incremental: ${INCREMENTAL}
      from:
        kind: ImageStreamTag
        name: wildfly:10.0
        namespace: openshift
```
2. Write the following to a shell file in the same folder as the `build.yaml` and execute it:
```bash
#!/bin/sh

set -e

# configure a non-incremental build
sed 's/${INCREMENTAL}/false/g' build.yaml | oc apply -f -

# do a warm up build and then a timed non-incremental build
oc start-build jee-ex --wait --follow
(time oc start-build jee-ex --wait --follow) 2>&1 | tee non-incremental.txt

# configure an incremental build
sed 's/${INCREMENTAL}/true/g' build.yaml | oc apply -f -

# do a warm up build and then a timed incremental build
oc start-build jee-ex --wait --follow
(time oc start-build jee-ex --wait --follow) 2>&1 | tee incremental.txt
```

##### Current Result
If you execute the shell script, two files `non-incremental.txt` and `incremental.txt` will be written with the output of the non-incremental and incremental builds, respectively. The output shows that the incremental build works correctly but on my machine, the non-incremental build takes around 40s while the incremental build takes 2min 20s (I have the same effect when testing on a DigitalOcean server). Almost all the time of the incremental build is spent pulling the previous image to get the saved artifacts. Here are the results as executed on my machine.

[non-incremental.txt](https://github.com/openshift/origin/files/736879/non-incremental.txt)
[incremental.txt](https://github.com/openshift/origin/files/736878/incremental.txt)

##### Expected Result
The incremental build should be faster than the non-incremental build.
