### ISSUE TITLE
Lifecycle Hook pods do not inherit ENV vars from secrets

### ISSUE THREAD

**Issue by mhutter** [openshift/origin#12893]
When using lifecycle hook pods for the "Recreate" strategy, the hook pods do not have access to ENV vars from secrets.

##### Version
```
oc v1.3.3
kubernetes v1.3.0+52492b4
features: Basic-Auth

Server https://????:443
openshift v1.3.1
kubernetes v1.3.0+52492b4
```

##### Steps To Reproduce

DC used (uses the `nginx:alpine` docker image):

```yml
apiVersion: v1
kind: DeploymentConfig
metadata:
  labels:
    app: nginx
  name: nginx
spec:
  replicas: 1
  selector:
    app: nginx
    deploymentconfig: nginx
  strategy:
    rollingParams:
      pre:
        execNewPod:
          command:
          - env
          containerName: nginx
          env:
          - name: FROM_PRE_ENV
            value: set
          - name: FROM_PRE_SECRET
            valueFrom:
              secretKeyRef:
                key: password
                name: poc-secret
        failurePolicy: Abort
    type: Rolling
  template:
    metadata:
      labels:
        app: nginx
        deploymentconfig: nginx
    spec:
      containers:
      - env:
        - name: FROM_DC_ENV
          value: set
        - name: FROM_DC_SECRET
          valueFrom:
            secretKeyRef:
              key: password
              name: poc-secret
        image: 172.30.1.1:5000/mhu-test/nginx
        imagePullPolicy: Always
        name: nginx
      restartPolicy: Always
  test: false
  triggers:
  - type: ConfigChange
```
Secret example:
```yaml
apiVersion: v1
data:
  password: c3dvcmRmaXNo # swordfish :)
kind: Secret
metadata:
  name: poc-secret
type: Opaque
```

Deploy, and then do `oc logs nginx-1-hook-pre | grep '^FROM'`

##### Current Result
```
FROM_DC_ENV=Hase
FROM_DC_SECRET=
FROM_PRE_ENV=set
FROM_PRE_SECRET=
```

##### Expected Result
```
FROM_DC_ENV=Hase
FROM_DC_SECRET=swordfish
FROM_PRE_ENV=set
FROM_PRE_SECRET=swordfish
```

##### Additional Information

According to #3739 and related PRs this _should_ have been resolved.

In the running container, everything works out as expected:
```
FROM_DC_SECRET=swordfish
FROM_DC_ENV=Hase
```
