### ISSUE TITLE
Routers liveness and readiness probes fails

### ISSUE THREAD

**Issue by mignev** [openshift/origin#13008]
Hello guys,
I'm watching serious readiness and liveness fails with our routers. There are around `900` routes and the reload time for the routes is `5s`

I found that bug which has similar symptoms
- https://bugzilla.redhat.com/show_bug.cgi?id=1329399

I workaround it with the following liveness settings to prevent the restarts because I saw that the routers become ready fast and it's a cheaper that way preventing restarts.

My current probes settings are:

```
livenessProbe:
  httpGet:
    path: /healthz
    port: 1936
    host: localhost
    scheme: HTTP
  initialDelaySeconds: 10
  timeoutSeconds: 10
  periodSeconds: 10
  successThreshold: 1
  failureThreshold: 10
readinessProbe:
  httpGet:
    path: /healthz
    port: 1936
    host: localhost
    scheme: HTTP
  initialDelaySeconds: 10
  timeoutSeconds: 3
  periodSeconds: 10
  successThreshold: 1
  failureThreshold: 3
```

##### Version
oc v1.4.1
openshift v1.4.1
kubernetes v1.4.0+776c994
etcd 3.1.0-rc.0
Docker version 1.12.5, build 047e51b/1.12.5
Dnsmasq version 2.66

##### Current Result

![](http://i.imgur.com/DEIYsxQ.png)

Another thing I watched was with 1.4.1 routers the number of sockets (a lot ofTIME_WAIT, CLOSE_WAIT, FIN_WAIT2 ... etc) was about 20000+ I tried to change the router version with 1.3.3 and the number decrese to 5-7k.

Without any traffic is working fine, but when I route from the production traffic to this deployment the stuff from above was happen.
