### ISSUE TITLE
SDN are not created when AWS configured as CloudProvider

### ISSUE THREAD

**Issue by nusnewob** [openshift/origin#13116]
Node network SDN is not created when AWS is configured as CloudProvider

##### Version
```
openshift v1.4.1+3f9807a
kubernetes v1.4.0+776c994
etcd 3.1.0-rc.0
```

##### Steps To Reproduce
1. update master-config.yaml with
```
kubernetesMasterConfig:
  apiServerArguments:
    cloud-config:
    - /etc/origin/cloudprovider/aws.conf
    cloud-provider:
    - aws
  controllerArguments:
    cloud-config:
    - /etc/origin/cloudprovider/aws.conf
    cloud-provider:
    - aws
```
2. restart master
3. register node

##### Current Result
Node network not configured and node fails to startup.

##### Expected Result
SDN configured as normal install.

##### Additional Information
It's a containerized install with `OPTIONS="--loglevel=6"`
Configs and logs are [here](https://gist.github.com/nusnewob/34de54b26b0ff4350394e775b26fd280)
