### ISSUE TITLE
DeploymentConfig pulls the wrong image and incorrectly reports the error

### ISSUE THREAD

**Issue by kvaidas** [openshift/origin#13302]
DeploymentConfig tries to pull the image in spec.triggers.imageChangeParams instead of spec.template.image when doing a manual deploy.
And the error shows the name of 

##### Version
oc v1.4.1+3f9807a
kubernetes v1.4.0+776c994
features: Basic-Auth GSSAPI Kerberos SPNEGO

Server https://192.168.7.3:8443
openshift v1.4.1+3f9807a
kubernetes v1.4.0+776c994

##### Steps To Reproduce
oc create -f template_builder.yml ; oc new-app --template=project-engine -p REPLICA_COUNT=1 -p NAME=someapp -p CONTENT_GIT_REPO=https://github.com/kvaidas/multicast_mpeg_scan
Invoke deployment of the dc, check the log of the created pod.

##### Current Result
Errors out while pulling the image from spec.triggers.imageChangeParams. And states that it tried to pull the one in spec.template.image.

##### Expected Result
Probably should pull the spec.template.image and definitely should correctly report the image that it's trying to pull.

##### Additional Information
Attaching my template that I used:
```
kind: Template
apiVersion: v1
objects:

  - kind: ImageStream
    apiVersion: v1
    metadata:
      name: ${NAME}-nginx

  - kind: ImageStream
    apiVersion: v1
    metadata:
      name: ${NAME}-app

  - kind: BuildConfig
    apiVersion: v1
    metadata:
      name: ${NAME}-nginx
    spec:
      source:
        type: Git
        git:
          uri: https://github.com/kvaidas/nginx-openshift
      strategy:
        type: Docker
        dockerStrategy:
          from:
            kind: DockerImage
            name: 'nginx:mainline'
          env:
            - name: NGINX_PORT
              value: "8080"
      output:
        to:
          kind: ImageStreamTag
          name: ${NAME}-nginx:latest
      triggers:
        - type: ConfigChange
        - type: ImageChange

  - kind: BuildConfig
    apiVersion: v1
    metadata:
      name: ${NAME}-app
    spec:
      source:
        type: Git
        git:
          uri: ${{CONTENT_GIT_REPO}}
      strategy:
        type: Source
        sourceStrategy:
          from:
            kind: ImageStreamTag
            name: ${NAME}-nginx:latest
      output:
        to:
          kind: ImageStreamTag
          name: ${NAME}-app:latest
      triggers:
        - type: ConfigChange
        - type: ImageChange

  - kind: DeploymentConfig
    apiVersion: v1
    metadata:
      name: ${NAME}-app
    spec:
      strategy:
        type: Rolling
      replicas: "${{REPLICA_COUNT}}"
      template:
        spec:
          containers:
          - name: ${NAME}-app
            readinessProbe:
              timeoutSeconds: 1
              initialDelaySeconds: 5
              httpGet:
                path: /
                port: 8080
            image: ${NAME}-app
        metadata:
          labels:
            name: ${NAME}-app
      selector:
        name: ${NAME}-app
      triggers:
        - type: ConfigChange
        - type: ImageChange
          imageChangeParams:
            automatic: true
            from:
              kind: ImageStreamTag
              name: randomimage:latest
            containerNames:
              - ${NAME}-app

  - kind: Service
    apiVersion: v1
    metadata:
      name: ${NAME}
    spec:
      ports:
        - port: 80
          targetPort: 8080
      selector:
        name: ${NAME}-app

  - kind: Route
    apiVersion: v1
    metadata:
      name: ${NAME}
    spec:
      to:
        kind: Service
        name: ${NAME}
        weight: 100

metadata:
  name: project-engine

parameters:
  - name: NAME
    required: true
    generate: expression
    from: "engine-[a-z0-9]{16}"
    description: The name assigned to all objects
  - name: CONTENT_GIT_REPO
    required: true
    description: Git repo where the website content will be pulled from
  - name: REPLICA_COUNT
    description: Number of replicas to run
    value: "2"
    required: true
```
