### ISSUE TITLE
Triggered panic during regular update

### ISSUE THREAD

**Issue by smarterclayton** [openshift/origin#1351]
When updating this object:

```
apiVersion: v1beta1
creationTimestamp: null
desiredState:
  manifest:
    containers:
    - capabilities: {}
      image: centos:centos7
      command: ["/usr/bin/sleep"]
      imagePullPolicy: ""
      name: test
      resources: {}
    id: ""
    restartPolicy: {}
    version: v1beta2
    volumes: null
id: test
kind: Pod
labels:
  run-container: test
```
to
```
apiVersion: v1beta1
creationTimestamp: null
desiredState:
  manifest:
    containers:
    - capabilities: {}
      image: centos:centos7
      command: ["/usr/bin/sleep", "1"]
      imagePullPolicy: ""
      name: test
      resources: {}
    id: ""
    restartPolicy: {}
    version: v1beta2
    volumes: null
id: test
kind: Pod
labels:
  run-container: test
```

```
goroutine 6371 [running]:
runtime.panic(0xfcbe80, 0xc209f2d3f0)
	/usr/lib/golang/src/pkg/runtime/panic.c:279 +0xf5
reflect.Value.Index(0xf91140, 0xc2088d5220, 0x0, 0x176, 0x1, 0x0, 0x0, 0x0, 0x0)
	/usr/lib/golang/src/pkg/reflect/value.go:1008 +0x316
github.com/GoogleCloudPlatform/kubernetes/pkg/conversion.Equalities.deepValueEqual(0xc2080a0db0, 0xf91140, 0xc209c12140, 0x0, 0x176, 0xf91140, 0xc2088d5220, 0x0, 0x176, 0xc20a0bd9b0, ...)
	/data/src/github.com/openshift/origin/Godeps/_workspace/src/github.com/GoogleCloudPlatform/kubernetes/pkg/conversion/deep_equal.go:167 +0x1882
github.com/GoogleCloudPlatform/kubernetes/pkg/conversion.Equalities.deepValueEqual(0xc2080a0db0, 0x13c8ec0, 0xc209c12120, 0x0, 0x196, 0x13c8ec0, 0xc2088d5200, 0x0, 0x196, 0xc20a0bd9b0, ...)
	/data/src/github.com/openshift/origin/Godeps/_workspace/src/github.com/GoogleCloudPlatform/kubernetes/pkg/conversion/deep_equal.go:181 +0x1b36
github.com/GoogleCloudPlatform/kubernetes/pkg/conversion.Equalities.deepValueEqual(0xc2080a0db0, 0xf870c0, 0xc209be10b8, 0x0, 0x172, 0xf870c0, 0xc209be1128, 0x0, 0x172, 0xc20a0bd9b0, ...)
	/data/src/github.com/openshift/origin/Godeps/_workspace/src/github.com/GoogleCloudPlatform/kubernetes/pkg/conversion/deep_equal.go:167 +0x192c
github.com/GoogleCloudPlatform/kubernetes/pkg/conversion.Equalities.deepValueEqual(0xc2080a0db0, 0x1358f80, 0xc209be10a0, 0x0, 0x192, 0x1358f80, 0xc209be1110, 0x0, 0x192, 0xc20a0bd9b0, ...)
	/data/src/github.com/openshift/origin/Godeps/_workspace/src/github.com/GoogleCloudPlatform/kubernetes/pkg/conversion/deep_equal.go:181 +0x1b36
github.com/GoogleCloudPlatform/kubernetes/pkg/conversion.Equalities.DeepEqual(0xc2080a0db0, 0x1358f80, 0xc209be10a0, 0x1358f80, 0xc209be1110, 0xc209c12120)
	/data/src/github.com/openshift/origin/Godeps/_workspace/src/github.com/GoogleCloudPlatform/kubernetes/pkg/conversion/deep_equal.go:234 +0x255
github.com/GoogleCloudPlatform/kubernetes/pkg/api/validation.ValidatePodUpdate(0xc20a146340, 0xc20a146680, 0x0, 0x0, 0x0)
	/data/src/github.com/openshift/origin/Godeps/_workspace/src/github.com/GoogleCloudPlatform/kubernetes/pkg/api/validation/validation.go:650 +0x79f
github.com/GoogleCloudPlatform/kubernetes/pkg/registry/pod.podStrategy.ValidateUpdate(0x7fc09be2e240, 0xc20804a0e0, 0x7fc09be2b9d0, 0x0, 0x7fc09be2b9f8, 0xc20a146340, 0x7fc09be2b9f8, 0xc20a146680, 0x0, 0x0, ...)
	/data/src/github.com/openshift/origin/Godeps/_workspace/src/github.com/GoogleCloudPlatform/kubernetes/pkg/registry/pod/rest.go:71 +0xa3
github.com/GoogleCloudPlatform/kubernetes/pkg/registry/pod.(*podStrategy).ValidateUpdate(0xc208223da0, 0x7fc09be2b9f8, 0xc20a146340, 0x7fc09be2b9f8, 0xc20a146680, 0x0, 0x0, 0x0)
	<autogenerated>:38 +0xe5
github.com/GoogleCloudPlatform/kubernetes/pkg/api/rest.BeforeUpdate(0x7fc09be4b548, 0xc208223da0, 0x7fc09be4ae50, 0xc20a5a6210, 0x7fc09be2b9f8, 0xc20a146340, 0x7fc09be2b9f8, 0xc20a146680, 0x0, 0x0)
	/data/src/github.com/openshift/origin/Godeps/_workspace/src/github.com/GoogleCloudPlatform/kubernetes/pkg/api/rest/update.go:55 +0x28d
github.com/GoogleCloudPlatform/kubernetes/pkg/registry/generic/etcd.func·001(0x7fc09be2b9f8, 0xc20a146680, 0x0, 0x0, 0x0, 0x0)
	/data/src/github.com/openshift/origin/Godeps/_workspace/src/github.com/GoogleCloudPlatform/kubernetes/pkg/registry/generic/etcd/etcd.go:249 +0x313
github.com/GoogleCloudPlatform/kubernetes/pkg/tools.(*EtcdHelper).AtomicUpdate(0xc2083e4148, 0xc20a11f000, 0x1b, 0x7fc09be2b9f8, 0xc20a1464e0, 0x1, 0xc20a097e28, 0x0, 0x0)
	/data/src/github.com/openshift/origin/Godeps/_workspace/src/github.com/GoogleCloudPlatform/kubernetes/pkg/tools/etcd_tools.go:389 +0x2d9
github.com/GoogleCloudPlatform/kubernetes/pkg/registry/generic/etcd.(*Etcd).Update(0xc2083e40c0, 0x7fc09be4ae50, 0xc20a5a6210, 0x7fc09be2b9f8, 0xc20a146340, 0x0, 0x0, 0x7fc081a6ef80, 0x0, 0x0)
	/data/src/github.com/openshift/origin/Godeps/_workspace/src/github.com/GoogleCloudPlatform/kubernetes/pkg/registry/generic/etcd/etcd.go:254 +0x284
github.com/GoogleCloudPlatform/kubernetes/pkg/registry/pod/etcd.(*REST).Update(0xc20804ac90, 0x7fc09be4ae50, 0xc20a5a6210, 0x7fc09be2b9f8, 0xc20a146340, 0x0, 0x0, 0x41df2c, 0x0, 0x0)
	/data/src/github.com/openshift/origin/Godeps/_workspace/src/github.com/GoogleCloudPlatform/kubernetes/pkg/registry/pod/etcd/etcd.go:113 +0x87
github.com/GoogleCloudPlatform/kubernetes/pkg/apiserver.func·021(0x0, 0x0, 0x0, 0x0)
	/data/src/github.com/openshift/origin/Godeps/_workspace/src/github.com/GoogleCloudPlatform/kubernetes/pkg/apiserver/resthandler.go:224 +0x91
github.com/GoogleCloudPlatform/kubernetes/pkg/apiserver.func·025()
	/data/src/github.com/openshift/origin/Godeps/_workspace/src/github.com/GoogleCloudPlatform/kubernetes/pkg/apiserver/resthandler.go:311 +0x37
created by github.com/GoogleCloudPlatform/kubernetes/pkg/apiserver.finishRequest
	/data/src/github.com/openshift/origin/Godeps/_workspace/src/github.com/GoogleCloudPlatform/kubernetes/pkg/apiserver/resthandler.go:316 +0x156
```

Also, the panic should have been recovered.
