### ISSUE TITLE
2 pods from different namespaces had the same ip

### ISSUE THREAD

**Issue by ssendev** [openshift/origin#13543]
2 pods from different namespaces had the same ip. which caused the service and thus route of one to point to the other.

Restarting them gave them different ips but how do i ensure that dosn't happen again?

This is on 3 fedora atomic hosts with ansible http://www.projectatomic.io/blog/2016/12/part1-install-origin-on-f25-atomic-host/ 

##### Version
openshift v1.4.1+3f9807a
kubernetes v1.4.0+776c994

**Comment by pweil-** [comment]
@knobunc assigning to p1 for triage.  If this is a reproducible bug I'd expect it to be a p0. cc @derekwaynecarr 

@ssendev - we're going to need more info here.  Master logs at a minimum.  Thanks!

**Comment by knobunc** [comment]
@ssendev I'd like the master config too (at least what network plugin are you using, and what is the ClusterNetworkCIDR).  Also, what does `oc get hostsubnet` show?  Thanks!

**Comment by ssendev** [comment]
I am using ovs-multitenant but [switched](https://docs.openshift.com/container-platform/3.4/install_config/configuring_sdn.html#migrating-between-sdn-plugins) it manually. during install it was ovs-subnet.

`journalctl -u origin-master > master.log` is 160M any way i can shrink it. or how should i get it to you?

the doubled ip was 10.129.0.153

```console
# oc get hostsubnet
NAME        HOST        HOST IP     SUBNET
10.14.0.4   10.14.0.4   10.14.0.4   10.128.0.0/23
10.14.0.5   10.14.0.5   10.14.0.5   10.130.0.0/23
10.14.0.6   10.14.0.6   10.14.0.6   10.129.0.0/23
```

```yaml
# /etc/origin/master/master-config.yaml
admissionConfig:
  pluginConfig:
    BuildDefaults:
      configuration:
        apiVersion: v1
        env: []
        kind: BuildDefaultsConfig
    BuildOverrides:
      configuration:
        apiVersion: v1
        kind: BuildOverridesConfig
        nodeSelector:
          build: "true"
  pluginOrderOverride:
apiLevels:
- v1
apiVersion: v1
assetConfig:
  logoutURL: ""
  masterPublicURL: https://10.14.0.4:8443
  metricsPublicURL: https://hawkular.10.14.0.5.nip.io/hawkular/metrics
  publicURL: https://10.14.0.4:8443/console/
  servingInfo:
    bindAddress: 0.0.0.0:8443
    bindNetwork: tcp4
    certFile: master.server.crt
    clientCA: ""
    keyFile: master.server.key
    maxRequestsInFlight: 0
    requestTimeoutSeconds: 0
controllerConfig:
  serviceServingCert:
    signer:
      certFile: service-signer.crt
      keyFile: service-signer.key
controllers: '*'
corsAllowedOrigins:
- 127.0.0.1
- localhost
- 10.14.0.4
- openshift
- kubernetes
- kubernetes.default
- kubernetes.default.svc.cluster.local
- openshift.default.svc
- kubernetes.default.svc
- 172.30.0.1
- openshift.default
- openshift.default.svc.cluster.local
dnsConfig:
  bindAddress: 0.0.0.0:8053
  bindNetwork: tcp4
etcdClientInfo:
  ca: master.etcd-ca.crt
  certFile: master.etcd-client.crt
  keyFile: master.etcd-client.key
  urls:
  - https://10.14.0.4:2379
etcdStorageConfig:
  kubernetesStoragePrefix: kubernetes.io
  kubernetesStorageVersion: v1
  openShiftStoragePrefix: openshift.io
  openShiftStorageVersion: v1
imageConfig:
  format: openshift/origin-${component}:${version}
  latest: false
kind: MasterConfig
kubeletClientInfo:
  ca: ca.crt
  certFile: master.kubelet-client.crt
  keyFile: master.kubelet-client.key
  port: 10250
kubernetesMasterConfig:
  admissionConfig:
  apiServerArguments:
  controllerArguments:
  masterCount: 1
  masterIP: 10.14.0.4
  podEvictionTimeout:
  proxyClientInfo:
    certFile: master.proxy-client.crt
    keyFile: master.proxy-client.key
  schedulerArguments:
  schedulerConfigFile: /etc/origin/master/scheduler.json
  servicesNodePortRange: ""
  servicesSubnet: 172.30.0.0/16
  staticNodeNames: []
masterClients:
  externalKubernetesClientConnectionOverrides:
    acceptContentTypes: application/vnd.kubernetes.protobuf,application/json
    burst: 400
    contentType: application/vnd.kubernetes.protobuf
    qps: 200
  externalKubernetesKubeConfig: ""
  openshiftLoopbackClientConnectionOverrides:
    acceptContentTypes: application/vnd.kubernetes.protobuf,application/json
    burst: 600
    contentType: application/vnd.kubernetes.protobuf
    qps: 300
  openshiftLoopbackKubeConfig: openshift-master.kubeconfig
masterPublicURL: https://10.14.0.4:8443
networkConfig:
  clusterNetworkCIDR: 10.128.0.0/14
  externalIPNetworkCIDRs:
  - 0.0.0.0/0
  hostSubnetLength: 9
  networkPluginName: redhat/openshift-ovs-multitenant
  serviceNetworkCIDR: 172.30.0.0/16
oauthConfig:
  assetPublicURL: https://10.14.0.4:8443/console/
  grantConfig:
    method: auto
  identityProviders:
  - challenge: true
    login: true
    mappingMethod: claim
    name: htpasswd_auth
    provider:
      apiVersion: v1
      file: /etc/origin/master/htpasswd
      kind: HTPasswdPasswordIdentityProvider
  masterCA: ca-bundle.crt
  masterPublicURL: https://10.14.0.4:8443
  masterURL: https://10.14.0.4:8443
  sessionConfig:
    sessionMaxAgeSeconds: 3600
    sessionName: ssn
    sessionSecretsFile: /etc/origin/master/session-secrets.yaml
  tokenConfig:
    accessTokenMaxAgeSeconds: 86400
    authorizeTokenMaxAgeSeconds: 500
pauseControllers: false
policyConfig:
  bootstrapPolicyFile: /etc/origin/master/policy.json
  openshiftInfrastructureNamespace: openshift-infra
  openshiftSharedResourcesNamespace: openshift
projectConfig:
  defaultNodeSelector: ""
  projectRequestMessage: ""
  projectRequestTemplate: ""
  securityAllocator:
    mcsAllocatorRange: s0:/2
    mcsLabelsPerProject: 5
    uidAllocatorRange: 1000000000-1999999999/10000
routingConfig:
  subdomain: 10.14.0.5.nip.io
serviceAccountConfig:
  limitSecretReferences: false
  managedNames:
  - default
  - builder
  - deployer
  masterCA: ca-bundle.crt
  privateKeyFile: serviceaccounts.private.key
  publicKeyFiles:
  - serviceaccounts.public.key
servingInfo:
  bindAddress: 0.0.0.0:8443
  bindNetwork: tcp4
  certFile: master.server.crt
  clientCA: ca.crt
  keyFile: master.server.key
  maxRequestsInFlight: 500
  requestTimeoutSeconds: 3600
volumeConfig:
  dynamicProvisioningEnabled: true
```
