### ISSUE TITLE
CPU usage on node stalls at certain point

### ISSUE THREAD

**Issue by bahho** [openshift/origin#13566]
I have a HA cluster with 3 masters 2 infra and some app nodes. I am running an image that uses stress  in order to produce cpu load. When I increase the number of pods to some high number,  new pods are being created but  the cpu load stop at around 60%. When I check with top I can see that half of the cpus is under %100 load but the other half is idle.

Ther is no resource quota defined for the project. Subnet length is set to 9 and kubelet argumetns as follows:

```yml
kubeletArguments:
  image-gc-high-threshold:
  - '90'
  image-gc-low-threshold:
  - '80'
  max-pods:
  - '400'
  node-labels:
  - region=primary
  pods-per-core:
  - '0'
  kube-reserved:
  - "cpu=300m,memory=1G"
  system-reserved:
  - "cpu=300m,memory=1G"
```

Any I deas I how can get the idle cpus to work?

##### Version
OpenShift CP 3.4
kubernetes v1.4.0+776c994
##### Steps To Reproduce
1. Spin up a pod that executes:
stress --cpu 8 --io 4 
2. Increse pod number to 1000

##### Current Result
Only 60% of the 
##### Expected Result
more tha 90% load
