### ISSUE TITLE
deploymentconfig status only reports 0

### ISSUE THREAD

**Issue by andrewklau** [openshift/origin#13602]
oc export dc reports status incorrectly compared to the API ?

oc export dc/test

```
[...]
status:
  availableReplicas: 0
  latestVersion: 0
  observedGeneration: 0
  replicas: 0
  unavailableReplicas: 0
  updatedReplicas: 0
```

GET https://localhost:8443/oapi/v1/namespaces/test/deploymentconfigs/test

```
[...]
"status": {
"latestVersion": 2,
"observedGeneration": 3,
"replicas": 1,
"updatedReplicas": 1,
"availableReplicas": 1,
"unavailableReplicas": 0,
"details": {
"message": "manual change",
"causes": [
  {
"type": "Manual"
}
],
},
```

oc version

```
oc v1.5.0-rc.0+49a4a7a
kubernetes v1.5.2+43a9be4
features: Basic-Auth GSSAPI Kerberos SPNEGO

openshift v1.5.0-rc.0+49a4a7a
kubernetes v1.5.2+43a9be4
```
