### ISSUE TITLE
error: object does not implement the Object interfaces

### ISSUE THREAD

**Issue by Tiboris** [openshift/origin#13615]
Creating [mongodb example](https://github.com/sclorg/mongodb-container/tree/12a0b41100d9a555c4b5674550467aaea01c527a/examples/petset) fails with **error: object does not implement the Object interfaces** when providing volumes.

##### Version
```
# openshift version
openshift v1.4.1
kubernetes v1.4.0+776c994
etcd 3.1.0-rc.0
```

##### Steps To Reproduce
1.create volumes like:
```yaml
kind: PersistentVolume
apiVersion: v1
metadata:
  name: pv-datadir-0 
  labels:
    type: local
spec:
  capacity:
    storage: 20Gi
  accessModes:
    - ReadWriteOnce
  nfs:
    path: /tmp/dir0
    server: 127.0.0.1
```
and
```yaml

kind: PersistentVolume
apiVersion: v1
metadata:
  name: pv-datadir-3 
  labels:
    type: local
spec:
  capacity:
    storage: 20Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/tmp/dir3"
```
```
# oc get pv
NAME               CAPACITY   ACCESSMODES   RECLAIMPOLICY   STATUS      CLAIM     REASON    AGE
pv-datadir-0   20Gi       RWO           Retain          Available                       1m
pv-datadir-1   20Gi       RWO           Retain          Available                       1m
pv-datadir-2   20Gi       RWO           Retain          Available                       1m
pv-datadir-3   20Gi       RWO           Retain          Available                       1m
```
2. oc create new-project  mongodb
3. oc new-app ...
```
#  oc new-app https://raw.githubusercontent.com/sclorg/mongodb-container/master/examples/petset/mongodb-petset-persistent.yaml
--> Deploying template "mongodb/mongodb-petset-replication" for "https://raw.githubusercontent.com/sclorg/mongodb-container/master/examples/petset/mongodb-petset-persistent.yaml" to project mongodb

     mongodb-petset-replication
     ---------
     MongoDB Replication Example (based on StatefulSet). You must have persistent volumes available in your cluster to use this template.

     * With parameters:
        * MongoDB Connection Username=kPE # generated
        * MongoDB Connection Password=ORty1DPq6vEUcGVb # generated
        * MongoDB Database Name=sampledb
        * MongoDB Admin Password=g8qDeQOKBVC6fNuk # generated
        * Replica Set Name=rs0
        * Keyfile Content=6QAogrEVu25bXXeHlkSrawbCwAnJVPdbfTBpqIePoWVhlugBGnPwj6fmeiX7EHhm3Yf861Qc0IccUTdnA4hXDURvtik73ob2q8gH5nWCI0EdMqVFgAXDq0DaDVH8CbnUNUiAVnu5FPKsxVo8c8hf4l7jBngpMVOOTKA0wXc0lYai7ERH53UQjVIT8556WuyS4tNGH5Pm2sxYewvAfqsKc53xM1blEKQI7BHEPgaYFfFHXhgufFrqhtOiqd4FlB2 # generated
        * MongoDB Docker Image=centos/mongodb-32-centos7
        * OpenShift Service Name=mongodb
        * Volume Capacity=1Gi
        * Memory Limit=512Mi

error: object does not implement the Object interfaces
```
Why it will not take these volumes?

##### Current Result
error: object does not implement the Object interfaces
##### Expected Result
```
$ oc get pods -l name=mongodb
NAME        READY     STATUS    RESTARTS   AGE
mongodb-0   1/1       Running   0          50m
mongodb-1   1/1       Running   0          50m
mongodb-2   1/1       Running   0          49m
```
