### ISSUE TITLE
oadm new-project behaviour is different from oc new-project. Is it expected?

### ISSUE THREAD

**Issue by Jooho** [openshift/origin#13760]
When I create new project with oadm to assign node-selector, the default request template is not applied. it looks the behavior is different from oc project.

**Example**
~~~

$ oadm new-project test-oadm --node-selector=region=infra
$ oc describe project tes-oadm
..
Node Selector:		region=infra
Quota:			<none>
Resource limits:	<none>

$ oc new-project test-oc 
$ oc describe project test-oc
...
Node Selector:	<none>
Quota:		<none>
Resource limits:
	Name:		core-resource-limits
	Type		Resource	Min	Max	Default
	----		--------	---	---	---
	Pod		memory		6Mi	1Gi	-
	Pod		cpu		200m	2	-
	Container	cpu		100m	2	300m
	Container	memory		4Mi	1Gi	200M
...
~~~
##### Version
[root@master1 quota]# oc version
oc v3.3.0.32
kubernetes v1.3.0+52492b4
features: Basic-Auth GSSAPI Kerberos SPNEGO

Server https://master1.example.com:8443
openshift v3.3.0.32
kubernetes v1.3.0+52492b4

##### Steps To Reproduce
1. Config projectRequestTemplate[1] and before the template is created, please add LimitRange object[2] to the default template.
2. Create new-project with oadm command

[1]https://docs.openshift.org/latest/admin_guide/managing_projects.html#modifying-the-template-for-new-projects
[2] 
```yaml
- apiVersion: "v1"
  kind: "LimitRange"
  metadata:
    name: "core-resource-limits" 
  spec:
    limits:
      - type: "Pod"
        max:
          cpu: "2" 
          memory: "1Gi" 
        min:
          cpu: "200m" 
          memory: "6Mi" 
      - type: "Container"
        max:
          cpu: "2" 
          memory: "1Gi" 
        min:
          cpu: "100m" 
          memory: "4Mi" 
        default:
          cpu: "300m" 
          memory: "200Mi" 
        defaultRequest:
          cpu: "200m" 
          memory: "100Mi" 
        maxLimitRequestRatio:
          cpu: "10"
```

[3]https://docs.openshift.org/latest/admin_guide/managing_projects.html#setting-the-project-wide-node-selector
##### Current Result
```console
$ oadm new-project test-oadm --node-selector=region=infra
$ oc describe project tes-oadm
..
Node Selector:		region=infra
Quota:			<none>
Resource limits:	<none>
```

##### Expected Result
```console
$ oadm new-project test-oadm --node-selector=region=infra
$ oc describe project test-oadm
...
Node Selector:	<none>
Quota:		<none>
Resource limits:
	Name:		core-resource-limits
	Type		Resource	Min	Max	Default
	----		--------	---	---	---
	Pod		memory		6Mi	1Gi	-
	Pod		cpu		200m	2	-
	Container	cpu		100m	2	300m
	Container	memory		4Mi	1Gi	200M
...
```
##### Additional Information
I attach loglevel=8 log for both case (oadm and oc)
1. oadm 
[test-oadm.txt](https://github.com/openshift/origin/files/920229/test-oadm.txt)

2. oc 
[test-oc.txt](https://github.com/openshift/origin/files/920231/test-oc.txt)
