### ISSUE TITLE
Build does not trigger automatically when image already exists:

### ISSUE THREAD

**Issue by smarterclayton** [openshift/origin#13773]
The following build config should be triggered immediately if `prometheus:binaries` exists, but it does not.

```
  apiVersion: v1
  kind: BuildConfig
  metadata:
    name: prometheus
  spec:
    output:
      to:
        kind: ImageStreamTag
        name: prometheus:latest
    source:
      images:
      - from:
          kind: ImageStreamTag
          name: prometheus:binaries
        paths:
        - destinationDir: .
          sourcePath: /go/src/github.com/prometheus/prometheus
    strategy:
      dockerStrategy:
        from:
          kind: DockerImage
          name: busybox:latest
    triggers:
    - imageChange:
        from:
          kind: ImageStreamTag
          name: prometheus:binaries
      type: ImageChange
```
