### ISSUE TITLE
Image source path has no way to place a directory in the root

### ISSUE THREAD

**Issue by smarterclayton** [openshift/origin#13775]
Using an image as a source, there is no way to copy a directory into the root.

```
      - from:
          kind: ImageStreamTag
          name: prometheus:binaries
        paths:
        - destinationDir: .
          sourcePath: /go/src/github.com/prometheus/prometheus
```

creates a root level directory called `prometheus` inside of the source dir.  That's a bug - it should be possible to use the source path as the complete contents.  Suggest that we make `.../prometheus/` as the sourcePath mean "contents of this directory".  Might be backward compatible implications, in which case we could special case that on destination dir == ., or add an attribute "asDirectory".
