### ISSUE TITLE
role of the serviceaccount jenkins of the jenkins template don't allow to create roleBinding

### ISSUE THREAD

**Issue by cmoulliard** [openshift/origin#13801]
The "edit" role of the serviceaccount defined within the [jenkins template](https://github.com/openshift/origin/blob/master/examples/jenkins/jenkins-ephemeral-template.json#L187) don't allow to assign a role to a user/group or to create a roleBinding resource for an application

If the jenkins groovy file contains this command "oc policy add-role-to-user view -n $(oc project -q) -z default" to assign the role "view" to the default serviceaccount of the pod created,

```
node("launchpad-maven") {
  checkout scm
  stage("Prepare") {
    sh "oc policy add-role-to-user view -z default"
  }
  stage("Build") {
    sh "mvn fabric8:deploy -Popenshift -DskipTests"
  }
  stage("Deploy")
}
```
then jenkins pipeline (s2i build) will report this error during the execution of the step `Prepare`

```
[ERROR] Failure executing: GET at: https://kubernetes.default.svc/oapi/v1/namespaces/demo2/rolebindings/springboot-configmap. Message: Forbidden!Configured service account doesn't have access. Service account may have been revoked.. -> [Help 1] 
```

To get rid of this issue, We could change the role from "edit" to "admin" [1]
[1]: Line to be changed : https://github.com/openshift/origin/blob/master/examples/jenkins/jenkins-ephemeral-template.json#L187

or that we add a new roleBinding for the jenkins serviceaccount

```
apiVersion: v1
kind: RoleBinding
metadata:
  name: rolebindings_creator  
roleRef:
  name: rolebindings_creator
subjects:
- kind: SystemGroup
  name: system:serviceaccounts
groupNames:
- system:serviceaccounts  
```
Such problem is really blocking on OpenShift online as we can't change the templates deployed and we could resolve the problem easily if we change the values within the templates published within OSO or OSD
