### ISSUE TITLE
Make outputs of oc policy scc-review/scc-subject-review consistent

### ISSUE THREAD

**Issue by php-coder** [openshift/origin#13858]
`oc policy scc-review` should show `<none>` in case resource is not allowed, to be consistent with `oc policy scc-review` output:
```console
$ oc policy scc-review -f es-master.yaml 
RESOURCE   SERVICE ACCOUNT   ALLOWED BY
$ oc policy scc-subject-review -f es-master.yaml 
RESOURCE               ALLOWED BY   
Deployment/es-master   <none>
```
Also with the current behavior user could think that there were no resources in provided file.

CC @sdminonne @soltysh

**Comment by sdminonne** [comment]
@php-coder to reproduce should I follow this: https://pastebin.com/rUXH4fnx ?

**Comment by php-coder** [comment]
@sdminonne Yes, exactly.

**Comment by php-coder** [comment]
Here is the content of `es-master.yaml` file:
```yaml
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: es-master
  labels:
    component: elasticsearch
    role: master
spec:
  replicas: 3
  template:
    metadata:
      labels:
        component: elasticsearch
        role: master
      annotations:
        pod.beta.kubernetes.io/init-containers: '[
          {
          "name": "sysctl",
            "image": "busybox",
            "imagePullPolicy": "IfNotPresent",
            "command": ["sysctl", "-w", "vm.max_map_count=262144"],
            "securityContext": {
              "privileged": true
            }
          }
        ]'
    spec:
      containers:
      - name: es-master
        securityContext:
          privileged: false
          capabilities:
            add:
              - IPC_LOCK
              - SYS_RESOURCE
        image: quay.io/pires/docker-elasticsearch-kubernetes:5.3.0
        imagePullPolicy: Always
        env:
        - name: NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: NODE_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: "CLUSTER_NAME"
          value: "myesdb"
        - name: "NUMBER_OF_MASTERS"
          value: "2"
        - name: NODE_MASTER
          value: "true"
        - name: NODE_INGEST
          value: "false"
        - name: NODE_DATA
          value: "false"
        - name: HTTP_ENABLE
          value: "false"
        - name: "ES_JAVA_OPTS"
          value: "-Xms256m -Xmx256m"
        ports:
        - containerPort: 9300
          name: transport
          protocol: TCP
        volumeMounts:
        - name: storage
          mountPath: /data
      volumes:
          - emptyDir:
              medium: ""
            name: "storage"
```
