### ISSUE TITLE
admin.kubeconfig only includes config for hostname, not IP as well

### ISSUE THREAD

**Issue by jduncan-rva** [openshift/origin#13869]
While this isn't a put bug, it is a confusing experience we may want to improve. When admin.kubeconfig is created, it sets up credentials to work with the master's hostname. But it doesn't create a stanza to work by the same IP address.

I am sure this is largely by design, but for Ops teams out there everywhere, IP addresses are still used, even in environments with proper hostnames. 

If this failed in a predictable way that could be fine, too. 

However you CAN connect using an auth mechanism to the master's IP address. 

logging in by IP for an auth user (this is using AllowAll)

```
 $ oc login -u dev -p dev https://192.168.122.100:8443
Login successful.

```

logging in with system:admin doesn't work and the error isn't greatly helpful
```
$ oc login -u system:admin  --config=admin.kubeconfig https://192.168.122.100:8443
The server uses a certificate signed by an unknown authority.
You can bypass the certificate check, but any data you send to the server could be intercepted by others.
Use insecure connections? (y/n): y

Authentication required for https://192.168.122.100:8443 (openshift)
Username: system:admin
Password: 
error: username system:admin is invalid for basic auth
```

but it works fine by hostname:
```
$ oc login -u system:admin  --config=admin.kubeconfig https://ocp-1.192.168.122.100.nip.io:8443
Logged into "https://ocp-1.192.168.122.100.nip.io:8443" as "system:admin" using existing credentials.

You have access to the following projects and can switch between them with 'oc project <projectname>':

  * default
    kube-system
    logging
    management-infra
    openshift
    openshift-infra

Using project "default".
```

##### Version
[provide output of the `openshift version` or `oc version` command]

openshift v1.4.1
kubernetes v1.4.0+776c994
etcd 3.1.0-rc.0

##### Steps To Reproduce
1. attempt to connect to OCP Origin using system:admin and the master's IP address

##### Current Result
it fails to the auth mechanism, causing much confusion

##### Expected Result

It should kick an error for the system:admin user or better yet an IP stanza should be created in admin.kubeconfig to allow it to work.

##### Additional Information

installer.cfg.yml
```
[root@ocp-1 ~]# cat .config/openshift/installer.cfg.yml 
ansible_callback_facts_yaml: /root/.config/openshift/.ansible/callback_facts.yaml
ansible_inventory_path: /root/.config/openshift/hosts
ansible_log_path: /tmp/ansible.log
deployment:
  ansible_ssh_user: root
  hosts:
  - connect_to: 192.168.122.100
    hostname: ocp-1.192.168.122.100.nip.io
    ip: 192.168.122.100
    public_hostname: ocp-1.192.168.122.100.nip.io
    public_ip: 192.168.122.100
    roles:
    - master
    - etcd
    - node
    - storage
  - connect_to: 192.168.122.101
    hostname: ocp-2.192.168.122.101.nip.io
    ip: 192.168.122.101
    node_labels: '{''region'': ''infra''}'
    public_hostname: ocp-2.192.168.122.101.nip.io
    public_ip: 192.168.122.101
    roles:
    - node
  master_routingconfig_subdomain: apps.192.168.122.101.nip.io
  openshift_master_cluster_hostname: None
  openshift_master_cluster_public_hostname: None
  roles:
    etcd: {}
    master: {}
    node: {}
    storage: {}
variant: origin
variant_version: '1.4'
version: v2
```

admin.kubeconfig:
```
$ cat admin.kubeconfig 
apiVersion: v1
clusters:
- cluster:
    certificate-authority-data: ...
    server: https://ocp-1.192.168.122.100.nip.io:8443
  name: ocp-1-192-168-122-100-nip-io:8443
contexts:
- context:
    cluster: ocp-1-192-168-122-100-nip-io:8443
    namespace: default
    user: system:admin/ocp-1-192-168-122-100-nip-io:8443
  name: default/ocp-1-192-168-122-100-nip-io:8443/system:admin
current-context: default/ocp-1-192-168-122-100-nip-io:8443/system:admin
kind: Config
preferences: {}
users:
- name: system:admin/ocp-1-192-168-122-100-nip-io:8443
  user:
    client-certificate-data: ...
    client-key-data: ...
```

examples from ~/.kube/config with it working with IP and hostname:
```
clusters:
- cluster:
    insecure-skip-tls-verify: true
    server: https://192.168.122.100:8443
  name: 192-168-122-100:8443
- cluster:
    insecure-skip-tls-verify: true
    server: https://ocp-1.192.168.122.100.nip.io:8443
  name: ocp-1-192-168-122-100-nip-io:8443
contexts:
- context:
    cluster: 192-168-122-100:8443
    user: dev/192-168-122-100:8443
  name: /192-168-122-100:8443/dev
- context:
    cluster: ocp-1-192-168-122-100-nip-io:8443
    user: dev/ocp-1-192-168-122-100-nip-io:8443
  name: /ocp-1-192-168-122-100-nip-io:8443/dev
```
