### ISSUE TITLE
GSSAPI extended test failure on deployment config change after 1.6.1 rebase

### ISSUE THREAD

**Issue by enj** [openshift/origin#13927]
First seen after 1.6.1 rebase merge https://ci.openshift.redhat.com/jenkins/job/test_branch_origin_extended_gssapi/48/

```
=== BEGIN TEST CASE ===
test/extended/gssapi.sh:116: executing 'oc get pods -l deploymentconfig=gssapiproxy-server -o jsonpath='{.items[0].spec.containers[0].env[?(@.name=="SERVER")].value}_{.items[0].status.conditions[?(@.type=="Ready")].status}'' expecting any result and text '^SERVER_GSSAPI_BASIC_FALLBACK_True$'; re-trying every 0.2s until completion or 60.000s
FAILURE after 59.077s: test/extended/gssapi.sh:116: executing 'oc get pods -l deploymentconfig=gssapiproxy-server -o jsonpath='{.items[0].spec.containers[0].env[?(@.name=="SERVER")].value}_{.items[0].status.conditions[?(@.type=="Ready")].status}'' expecting any result and text '^SERVER_GSSAPI_BASIC_FALLBACK_True$'; re-trying every 0.2s until completion or 60.000s: the command timed out
Standard output from the command:
SERVER_GSSAPI_ONLY_True
... repeated 75 times
SERVER_GSSAPI_ONLY_False
... repeated 17 times
SERVER_GSSAPI_BASIC_FALLBACK_False
... repeated 41 times
Standard error from the command:
=== END TEST CASE ===
```

Re-ran https://ci.openshift.redhat.com/jenkins/job/test_branch_origin_extended_gssapi/49/ and it failed again on the same line but slightly differently.

```
=== BEGIN TEST CASE ===
test/extended/gssapi.sh:116: executing 'oc get pods -l deploymentconfig=gssapiproxy-server -o jsonpath='{.items[0].spec.containers[0].env[?(@.name=="SERVER")].value}_{.items[0].status.conditions[?(@.type=="Ready")].status}'' expecting any result and text '^SERVER_GSSAPI_ONLY_True$'; re-trying every 0.2s until completion or 60.000s
FAILURE after 60.231s: test/extended/gssapi.sh:116: executing 'oc get pods -l deploymentconfig=gssapiproxy-server -o jsonpath='{.items[0].spec.containers[0].env[?(@.name=="SERVER")].value}_{.items[0].status.conditions[?(@.type=="Ready")].status}'' expecting any result and text '^SERVER_GSSAPI_ONLY_True$'; re-trying every 0.2s until completion or 60.000s: the command timed out
Standard output from the command:
_True
... repeated 74 times
_False
... repeated 26 times
Error executing template: array index out of bounds: index 0, length 0. Printing more information for debugging the template:
	template was:
		{.items[0].spec.containers[0].env[?(@.name=="SERVER")].value}_{.items[0].status.conditions[?(@.type=="Ready")].status}
	object given to jsonpath engine was:
		map[string]interface {}{"items":[]interface {}{}, "kind":"List", "apiVersion":"v1", "metadata":map[string]interface {}{}, "selfLink":"", "resourceVersion":""}
SERVER_GSSAPI_ONLY_False
... repeated 31 times
Standard error from the command:
error: error executing jsonpath "{.items[0].spec.containers[0].env[?(@.name==\"SERVER\")].value}_{.items[0].status.conditions[?(@.type==\"Ready\")].status}": array index out of bounds: index 0, length 0
=== END TEST CASE ===
```

The `update_auth_proxy_config` does a `set env`

```bash
function update_auth_proxy_config() {
    local server_config="${1}"
    local spec='{.items[0].spec.containers[0].env[?(@.name=="SERVER")].value}'
    spec+='_'
    spec+='{.items[0].status.conditions[?(@.type=="Ready")].status}'

    os::cmd::expect_success "oc set env dc/gssapiproxy-server SERVER='${server_config}'"
    os::cmd::try_until_text "oc get pods -l deploymentconfig=gssapiproxy-server -o jsonpath='${spec}'" "^${server_config}_True$"
}
```

which triggers the deployment config:

```yaml
kind: "DeploymentConfig"
apiVersion: "v1"
metadata:
  name: "gssapiproxy-server"
spec:
  strategy:
    type: "Recreate"
    resources: {}
  triggers:
    -
      type: "ImageChange"
      imageChangeParams:
        automatic: true
        containerNames:
          - "gssapiproxy-server"
        from:
          kind: "ImageStreamTag"
          name: "gssapiproxy:latest"
        lastTriggeredImage: ""
    -
      type: "ConfigChange"
...
```

It seems like pod does not come back up with the new configuration.

cc @stevekuznetsov @liggitt @smarterclayton @deads2k
