### ISSUE TITLE
Getting the current namespace to use inside a template

### ISSUE THREAD

**Issue by alikhajeh1** [openshift/origin#13934]
Has anyone found a way to get the current namespace to use inside a template so we don't have to ask the user to provide it? 

This is useful when creating the required resources to create a new app, and for example, the deploymentconfig needs the current namespace, where the imagestream is:
```
    triggers:
    - type: ImageChange
      imageChangeParams:
        automatic: true
        containerNames:
        - ${SERVICE_NAME}
        from:
          kind: ImageStreamTag
          name: ${SERVICE_NAME}:latest
          namespace: ${CURRENT_NAMESPACE}    <<<<<< User needs to define this
```

##### Version
```
oc v1.4.0-rc1+b4e0954
kubernetes v1.4.0+776c994
features: Basic-Auth

Server https://dashboard.abarcloud.com:443
openshift v1.4.1
kubernetes v1.4.0+776c994
```

##### Current Result
A variable has to be defined for the user to fill in while using the template.

##### Expected Result
It would be nice if there was a $CURRENT_NAMESPACE variable that could be pre-populated by the system so we wouldn't have to ask users to enter the current namespace.
