### ISSUE TITLE
Auto generated node kubeconfigs have null server value

### ISSUE THREAD

**Issue by sdodson** [openshift/origin#1393]
When a master automatically creates kubeconfig for nodes specified via --nodes it does not set the server address.

```
/usr/bin/openshift start master --images=registry.access.redhat.com/openshift3_beta/ose-${component}:${version} --master=ose3-master.example.com --public-master=ose3-master.example.com --nodes=ose3-master.example.com,ose3-node1.example.com,ose3-node2.example.com,ose3-node3.example.com --loglevel=2
```

```
[root@ose3 ~]# head -n 6 /var/lib/openshift/openshift.local.certificates/node-ose3-master.example.com/.kubeconfig 
apiVersion: v1
clusters:
- cluster:
    certificate-authority-data: L--GIANT-BLOB-OF-CERT-DATA--g==
    server: ""
  name: master
```
