### ISSUE TITLE
BuildConfig's mounted secrets are not fully truncated

### ISSUE THREAD

**Issue by PiotrKlimczak** [openshift/origin#14017]
In Openshift Origin 1.4.1 running on CentOS 7.3 I have a build like: 
```yaml
apiVersion: v1
  kind: BuildConfig
  metadata:
    labels:
      app: ${APP_NAME}
    name: ${APP_NAME}
  spec:
    completionDeadlineSeconds: 300
    output:
      to:
        kind: ImageStreamTag
        name: ${APP_NAME}:latest
    postCommit: {}
    resources: {}
    runPolicy: Serial
    source:
      git:
        ref: ${ASSEMBLY_REPO_BRANCH}
        uri: ${ASSEMBLY_REPO_ULR}
      secrets:
      - destinationDir: /tmp/X1
        secret:
          name: y
      sourceSecret:
        name: x
      type: Git
```

My Images are using cantos:7 as parent image.

According to docs for s2i builds:
https://docs.openshift.com/container-platform/3.4/dev_guide/builds/build_inputs.html:
"
Currently, any files with these secrets are world-writable (have 0666 permissions) and will be truncated to size zero after executing the assemble script. This means that the secret files will exist in the resulting image, but they will be empty for security reasons.
"

However after successful s2i builds in a runtime pod with my app, secret is indeed truncated for:
/tmp/y/username
/tmp/y/password
/tmp/y/..5985_03_05_08_34_42.008853181/username
/tmp/y/..5985_03_05_08_34_42.008853181/password

BUT there are still some strange directories inside, which have same values and are not truncated:
/tmp/y/..data/username
/tmp/y/..data/password

Also I am finding bit strange the fact that there are subdirs like "..data" and "..5985_03_05_08_34_42.008853181" as I am not finding it reasonable.
I haven't found any information about that anywhere.

##### Version
oc v1.4.1+3f9807a
kubernetes v1.4.0+776c994
features: Basic-Auth

Server https://X:443
openshift v1.4.1
kubernetes v1.4.0+776c994

##### Steps To Reproduce
1. Create s2i docker image
2. Mount buildconfig secrets to disk
2. Once build succeed, runtime pod will have only some passwords truncated

##### Current Result
After successful s2i build, pod with my app still have passwords mounted for BuildConfig purpose only

##### Expected Result
Either:
1. Mounted secret should not have those strange subdirs with same secret mounted again
OR
2. All mounted secrets should be truncated
