### ISSUE TITLE
build defaulter admission controller config loading is broken

### ISSUE THREAD

**Issue by bparees** [openshift/origin#14039]
with what should be a valid master-config for the build default admission controller:

```
admissionConfig:
  pluginConfig:
    BuildDefaults:
      configuration:
        apiVersion: v1
        env:
          - name: test2
            value: value2
        kind: BuildDefaultsConfig
        resources:
          limits:
            cpu: "400m"
            memory: "600Mi"
          requests:
            cpu: "300m"
            memory: "400Mi"
```

the master fails to start with:

```
F0504 00:37:55.308957    7210 start_master.go:743] Could not start build controller: env[0].name: Required value
```

because the validation of the bulid defaulter env section fails.

setting the env "name" field to "Name" works around this issue, but that should not be necessary.
