### ISSUE TITLE
have a command like `oc delete pod --garbage` to delete all pods which are completed/failed

### ISSUE THREAD

**Issue by jstrachan** [openshift/origin#14327]
having lots of failed deploy pods or completed build pods is kinda messy when viewing pods with `oc get pod` or via the Pods tab in UIs - it can be hard to see the wood for the trees when you've, say, 6 different pods and lots of failed deploys or completed builds.

I'd like a quick one liner to clean up dead/terminate/failed pods in a namespace. 

I've seen the garbage collection settings which are cool https://docs.openshift.com/enterprise/3.1/admin_guide/garbage_collection.html#container-garbage-collection

but I can imagine folks wanting to keep around a few dead pods and then have a clean button or something. 

having a quick way to filter them out via `oc get pod` or in the openshift console would be handy too!

**Comment by fabianofranz** [comment]
We have something like that already but it's more targeted at cluster-administration tasks:

```
oadm prune builds -h
oadm prune deployments -h
```

@jstrachan something like that but per namespace? cc @csrwng @mfojtik @kargakis

**Comment by mjudeikis** [comment]
we have same problem for succ jobs. We have bunch of `successful` pods 
Do we have anything like `oc adm prube pods` in our pipeline?
Now we solving this with init container:
```
 initContainers:
          - command: ["oc", "delete", "jobs", "-l", "parent=ldapsync"]
            image: openshift3/ose
            imagePullPolicy: IfNotPresent
            name: ldapsync-cleanup
          containers:
          - name: ldapsync
            image: openshift3/ose
            #sudo oc adm groups sync --sync-config=/usr/local/ldap/ldapsync.yaml --whitelist=/usr/local/ldap/ldapsync.whitelist
            command: ["oc", "adm", "groups", "sync", "--sync-config=/usr/local/ldap/ldapsync.yml", "--whitelist=/usr/local/ldap/ldapsync.whitelist","--confirm"]
            volumeMounts:
              - name: ldapconfig-volume
                mountPath: /usr/local/ldap
```

But we where looking for something wider for administrator as some users will not be able to think this kind of stuff :)
