### ISSUE TITLE
Pipelines does not accept parametrised build 

### ISSUE THREAD

**Issue by mangirdaz** [openshift/origin#14369]
If I create Pipeline from Build config and try execute This build Using Jenkins API and pass parameteres it will fail:
```yaml
apiVersion: v1
kind: BuildConfig
metadata:
  annotations:
    pipeline.alpha.openshift.io/uses: '[{"name": "${NAME}", "namespace": "", "kind":
      "DeploymentConfig"}]'
  creationTimestamp: null
  labels:
    name: test2
  name: test2
spec:
  nodeSelector: {}
  output: {}
  postCommit: {}
  resources: {}
  runPolicy: Parallel
  source:
    type: None
  strategy:
    jenkinsPipelineStrategy:
      jenkinsfile: |-
        // Add fancy build parameter.
        properties([
          parameters([
            string(
              defaultValue: "asd",
              description: 'Some description',
              name: 'foo'
            ),
          ])
        ])

        print foo
        if (foo == "true") {
          print "true"
        }
        else {
          print "false"
        }
    type: JenkinsPipeline
  triggers:
  - github:
      secret: OHaFSFdG3E3n6TM7lkxE7hS0QQfBAQYVMH5TI1bJ
    type: GitHub
  - generic:
      secret: naBnLGoPYh2dYgmMwAyXtrRgW4VPiMxVVn7dyLY8
    type: Generic
status:
  lastVersion: 
```
output:
```
OpenShift Build pipelines/test2-3
[Pipeline] properties
WARNING: The properties step will remove all JobPropertys currently configured in this job, either from the UI or from an earlier properties step.
This includes configuration for discarding old builds, parameters, concurrent builds and build triggers.
WARNING: Removing existing job property 'This project is parameterized'
WARNING: Removing existing job property 'BuildConfigProjectProperty'
[Pipeline] echo

asd
[Pipeline] echo
false
[Pipeline] End of Pipeline
Finished: SUCCESS
```

If I create same pipeline from Jenkins UI it works just fine and accepts parameters from API and UI.

UseCase is we want to trigger Jenkins Build/Pipeline from external CI tool and pass Commit ID or Tag to be used. 

https://issues.jenkins-ci.org/browse/JENKINS-44509 

To trigger job:
curl -k -X POST https://admin-admin:asadasdsad@jenkins-pipelines.ocp.example.com/job/project/job/pipelines-openshift-jee-sample/buildWithParameters?foo=true

native pipeline code:
```groovy
 // Add fancy build parameter.
        properties([
          parameters([
            string(
              defaultValue: "asd",
              description: 'Some description',
              name: 'foo'
            ),
          ])
        ])

        print foo
        if (foo == "true") {
          print "true"
        }
        else {
          print "false"
        }
```
