### ISSUE TITLE
system:unauthenticated group should imply system:authenticated

### ISSUE THREAD

**Issue by aweiteka** [openshift/origin#14381]
See https://github.com/cockpit-project/cockpit/issues/6711

When a project has registry-viewer role assigned to system:unauthenticated group, an authenticated user cannot view the project.

##### Version

```
$ oc version
oc v3.3.1.3
kubernetes v1.3.0+52492b4
features: Basic-Auth

Server https://xxxxxxxx:8443
openshift v1.5.0
kubernetes v1.5.2+43a9be4
```

##### Steps To Reproduce

*see https://github.com/cockpit-project/cockpit/issues/6711*

1. Using registry console, create new project with "Anonymous" access
2. As another user, login to registry console

##### Current Result

Cannot see project because `system:authenticated` group is not explicitly granted. Reproducible with cockpit console version 140.

##### Expected Result

Any authenticated user should be able to see objects that unauthenticated users cannot

cc @petervo

**Comment by stevekuznetsov** [comment]
I think you mean the other way around? That `system:authenticated` should have bound to it a super-set of roles bound to `system:unauthenticated`? 

/cc @enj

**Comment by aweiteka** [comment]
> system:authenticated should have bound to it a super-set of roles bound to system:unauthenticated?

Yes, that's what I mean.

**Comment by enj** [comment]
This is working as expected.  Bind to both groups if you want everyone to see it.

For example, this is how we handle discovery:

```yaml
apiVersion: v1
kind: ClusterRoleBinding
metadata:
  name: system:discovery-binding
roleRef:
  name: system:discovery
subjects:
- kind: SystemGroup
  name: system:authenticated
- kind: SystemGroup
  name: system:unauthenticated
```

> `system:unauthenticated` group should imply `system:authenticated`

No it should not.  There is nothing magical about those groups, they just happen to be added at the end of the authenticator request chain based on whichever bucket you fall in, assuming you meet one at all.
