### ISSUE TITLE
secretKeyRef in env does not validate during deployment on 3.5

### ISSUE THREAD

**Issue by sohrab-** [openshift/origin#14503]
I am not sure if I am doing something silly but on OpenShift 3.5, I am trying to use a `secretKeyRef` or `configMapKeyRef` in the deployment config but it fails validation in the rc. Similar syntax was working fine in 3.4.

Am I doing something wrong here?

##### Version
```
oc v1.5.1+7b451fc
kubernetes v1.5.2+43a9be4
features: Basic-Auth

Server https://10.102.100.177:8443
openshift v3.5.5.15
kubernetes v1.5.2+43a9be4
```

##### Steps To Reproduce

Here is an example of the bc:

```yaml
apiVersion: v1
kind: DeploymentConfig
spec:
  template:
    spec:
      containers:
      - env:
        - name: JAVA_OPTS
          valueFrom:
            secretKeyRef:
              key: java.opts
              name: client-credentials
        name: api-somethings-v1
```

Here is the secret, it is referencing:

```
Name:		client-credentials
Namespace:	dev
Labels:		<none>
Annotations:	<none>

Type:	Opaque

Data
====
java.opts:	129 bytes
```

##### Current Result

The deployment fails with the following validation exception:

```
I0607 08:28:18.351469       1 deployer.go:195] Deploying from dev/api-somethings-v1-13 to dev/api-somethings-v1-14 (replicas: 1)
I0607 08:28:19.366075       1 rolling.go:175] couldn't assign source annotation to deployment dev/api-somethings-v1-14: ReplicationController "api-somethings-v1-14" is invalid: spec.template.spec.containers[0].env[0].valueFrom: Invalid value: "": may not have more than one field specified at a time
```

##### Expected Result

The deployment works.

##### Additional Information

This is the line that throws that validation exception from Kube: https://github.com/kubernetes/kubernetes/blob/v1.5.2/pkg/api/validation/validation.go#L1382

Looking at logic, it is either not reading the `secretKeyRef` or  it's reading that and something else. It's doing my head in.
