### ISSUE TITLE
Lifecycle POD doesn't work with imageStreams

### ISSUE THREAD

**Issue by jmprusi** [openshift/origin#14553]
Lifecycle POD doesn't resolve the image from a imagestreams, and tries to pull an incorrect image.

##### Version
```
oc v1.5.1+7b451fc
kubernetes v1.5.2+43a9be4
features: Basic-Auth

Server https://127.0.0.1:8443
openshift v1.4.1+3f9807a
kubernetes v1.4.0+776c994
```

##### Steps To Reproduce
1. Create an ImageStream: 
```
- kind: ImageStream
  apiVersion: v1
  metadata:
    name: myimage
    annotations:
      openshift.io/display-name: myimage
  spec:
    tags:
    - name: latest
      annotations:
        openshift.io/display-name: myimage (Latest)
      from:
        kind: DockerImage
        name: company/image:0.1-tag
```

2. Point a DeploymentConfig with a lifecycle to this imagestream

```
- apiVersion: v1
  kind: DeploymentConfig
  metadata:
    name: myapp
  spec:
    replicas: 1
    selector:
      name: myapp
    strategy:
      rollingParams:
       (..)
        pre:
          failurePolicy: Retry
          execNewPod:
            containerName:  mycontainer
            command:
            - bash
            - -c
            -something
            env: (..)
        post:
          failurePolicy: Abort
          execNewPod:
            containerName: mycontainer
            command:
            - bash
            - -c
            - do something
      type: Rolling
    template:
      metadata:
        labels:
          name: myapp
      spec:
        containers:
        - args:
          env: (..) 
          image: myimage:latest
          imagePullPolicy: Always
          command: [ ... ]
          name: name
         (..)
    triggers:
      - type: ConfigChange
```

##### Current Result

The deploymentConfig doesn't work due to the "pods/myapp-1-hook-pre" failing to run because: "Image pull back off"

It's not able to find the image "myimage:latest" instead of resolving to the internal imagestream (image:0.1-tag)

##### Expected Result

The lifecycle POD runs after pulling the image based on the imageStream (image:0.1-tag) and executes the command.
