### ISSUE TITLE
openshift online forces large (memory + CPU) containers to be created - can we reduce them?

### ISSUE THREAD

**Issue by jstrachan** [openshift/origin#14583]
I'd like to be able to create small containers in terms of memory + CPU so that I can make more use of the 2 CPU and 1Gb memory limits on OpenShift Online.

However if I ever try to use low limits like:
```yaml
        resources:
          limits:
            memory: '200Mi'
            cpu: '200m'
```

I get errors like this:
```
minimum cpu usage per Pod is 29m, but request is 23m., minimum memory usage per Pod is 150Mi, but request is 125829120., minimum memory usage per Container is 150Mi, but request is 120Mi., minimum cpu usage per Container is 29m, but request is 23m
```

Right now (rounding up a little) these are about the smallest I've been able to get:
```yaml
        resources:
          limits:
            memory: '250Mi'
            cpu: '250m'
```

But I'd like to run more small containers. e.g. to demo FaaS I'd like to have lots of little containers running. I'd be happy to use about 50Mb for each really. e.g. here's the view from the OpenShift Online console of their resource usage:

![openshift_web_console](https://user-images.githubusercontent.com/30140/27028665-5e599888-4f5d-11e7-9a5d-c98edf4348d5.png)

so its using 260Mb of memory, barely any CPU but already my quota has gone. 

Is there a chance we could specify smaller memory & CPU limits?
![openshift_web_console](https://user-images.githubusercontent.com/30140/27028722-94bd1f30-4f5d-11e7-96e5-25719499d089.png)
