### ISSUE TITLE
Secret volumes content is not available in containers

### ISSUE THREAD

**Issue by jimmidyson** [openshift/origin#1469]
Working through with @pmorie.

Secrets/RC created via following manifest:

```
---
  id: "fabric8-config"
  kind: "Config"
  apiVersion: "v1beta1"
  name: "fabric8-config"
  description: "Creates a hawtio console"
  items:
    - apiVersion: "v1beta2"
      kind: "Secret"
      id: "openshift-cert-secrets"
      data:
        my-file: amltbWkK
    - apiVersion: "v1beta1"
      desiredState:
        podTemplate:
          desiredState:
            manifest:
              containers:
                - image: "busybox:latest"
                  name: "test-container"
                  imagePullPolicy: "PullIfNotPresent"
                  volumeMounts:
                    - name: openshift-cert-secrets
                      mountPath: /etc/secret-volume
                      readOnly: true
                  command:
                    - sleep
                    - 5000000
              id: "busyboxPod"
              version: "v1beta1"
              volumes:
                - name: openshift-cert-secrets
                  source:
                    secret:
                      target:
                        kind: Secret
                        namespace: default
                        name: openshift-cert-secrets
          labels:
            component: "test"
        replicaSelector:
          component: "test"
        replicas: 1
      id: "busybox-controller"
      kind: "ReplicationController"
```

Volume is mounted in container but contains no files, either visible in container or on host. Logs from a customized origin image provided by @pmorie with extra logging are available at https://gist.github.com/jimmidyson/d378d4a0e7c6f0fdfe0a, specifically see https://gist.github.com/jimmidyson/d378d4a0e7c6f0fdfe0a#file-openshift-log-L407-L421. Initial guess is that it's the Cleaner that's cleaning files too eagerly.
