### ISSUE TITLE
oc process can give an obscure error when it receives an incorrect input

### ISSUE THREAD

**Issue by benjaminapetersen** [openshift/origin#14755]
Given the following `yaml` file: 

```yaml 
apiVersion: servicecatalog.k8s.io/v1alpha1
kind: Broker
metadata:
  name: ups-broker
spec:
  url: http://ups-broker.ups-broker.svc.cluster.local
```
The command:
`$ oc process -f ups-broker.yaml | oc create -f -`
will result in:
```bash
error: unable to decode "ups-broker.yaml": no kind "Broker" is registered for version "servicecatalog.k8s.io/v1alpha1"
error: no objects passed to create
```
When passed straight to `oc create` it works fine:
`$ oc create -f ups-broker.yaml`
results in 
`broker "ups-broker" created`

Ideally if process doesn't receive a template file it would indicate that the contents of the file are unexpected (not a template). 

@jwforres @bparees
