### ISSUE TITLE
Confusion about setting up build nodes

### ISSUE THREAD

**Issue by twforeman** [openshift/origin#14786]
We are trying to setup build nodes as described in the 1.4 documentation here: https://docs.openshift.org/latest/install_config/build_defaults_overrides.html

We are having some conflict issues with the fact that we have set osm_default_node_selector='region=primary'. If we set a label of "region: primary" on the build nodes along with a nodeSelector specific to the build nodes then the builds target the build nodes correctly, however, since the "region: primary" label exists, regular pods are also getting scheduled on the build nodes.

If we do not set the "region:" label on the build nodes, or set it to some other value, then the builds will fail to find a target and will not build.

What is the suggested way to create build nodes that normal pods will not get scheduled on?

##### Version
oc v1.4.1+3f9807a
kubernetes v1.4.0+776c994
openshift v1.4.1
kubernetes v1.4.0+776c994

##### Steps To Reproduce
Create a cluster with osm_default_node_selector='region=primary' set. Set the build build config options to:
``` 
admissionConfig:
  pluginConfig:
    BuildDefaults:
      configuration:
        apiVersion: v1
        kind: BuildDefaultsConfig
        nodeSelector: 
          BuildNode: foobar
    BuildOverrides:
      configuration:
        apiVersion: v1
        kind: BuildOverridesConfig
        nodeSelector: 
          BuildNode: foobar
```
Create a build node with labels "region: build, BuildNode: foobar"

Builds will fail to schedule. Change the region to primary and builds will work, but other pods will schedule too.

Adding "region: build" to the nodeSelector in the plugin config doesn't work either since then the region label gets set twice and it's an AND operation.
