### ISSUE TITLE
Template broker can't provision a template that contains a Deployment resource

### ISSUE THREAD

**Issue by jwforres** [openshift/origin#14780]
Using a template like this:

```
apiVersion: v1
kind: Template
metadata:
  name: deployment-simple-test
objects:
- apiVersion: apps/v1beta1
  kind: Deployment
  metadata:
    name: hello-openshift
  spec:
    replicas: 1
    template:
      metadata:
        labels:
          app: nginx
      spec:
        containers:
        - name: hello-openshift
          image: openshift/hello-openshift
          ports:
          - containerPort: 80
```

The error being returned by the service catalog on the service instance is:

```
Provision call failed: Error deprovisioning Instance "temptest6/deployment-simple-test-gnld6" of ServiceClass "deployment-simple-test" at Broker "template-broker": ""
```
