### ISSUE TITLE
Disable settings.k8s.io/v1alpha1 for 3.6

### ISSUE THREAD

**Issue by mfojtik** [openshift/origin#14935]
Possible solutions:

* Use RuntimeConfig and parse the strings (nobody wants this ;-)
* Keep the API enabled and restrict access with policy
* Other options?

**Comment by mfojtik** [comment]
@deads2k lets kick the discussions... i'm fine with 2)

**Comment by mfojtik** [comment]
@soltysh we have to figure out what to do with `"/apis/batch/v2alpha1"` and @DirectXMan12 what to do with `"/apis/autoscaling/v2alpha1"` :-)

**Comment by deads2k** [comment]
@mfojtik I think I may have found a clever-ish spot to wire this in.  Mind including a snippet of your extended args?

**Comment by mfojtik** [comment]
```yaml
kubernetesMasterConfig:
  admissionConfig:
    pluginConfig: null
  apiLevels: null
  apiServerArguments:
    runtime-config:
    - apis/settings.k8s.io/v1alpha1=true
```
