### ISSUE TITLE
The `oc` cli fails to apply HorizontalPodAutoscalers from v3.6 -> v3.4

### ISSUE THREAD

**Issue by tavogel** [openshift/origin#14965]
For the past week we've been experiencing issues when applying a HorizontalPodAutoscaler via YAML to the cluster, but only on our newly built Jenkins servers:
```
error: autoscaling.HorizontalPodAutoscaler is not suitable for converting to ""
```

I noticed that the `oc` command line has been updated to v3.6 around when this issue started to occur: https://github.com/openshift/jenkins/commit/c3bc69a0945e878644e006ca9b74c1231070a45d

This has been hard to tackle, because we are reapplying the same YAML to the cluster for every deployment in our CI pipelines. The only workaround has been to comment out the YAML and instead use `oc autoscale` in our Jenkinsfile (which also requires we run `oc delete hpa` first).

In fact, as a workaround for deleting the HPA we tried the `-o yaml | oc apply -f -` trick:
```
oc autoscale dc/<my-deployment> --min 1 --max 5 --cpu-percent=80 --dry-run -o yaml | oc apply -f -
```
This also fails with the same "not suitable for converting" error as applying handwritten YAML.

Locally using `brew install openshift-cli` (oc v1.5.1) I can apply this YAML no problem. There appears to be a validation issue with the 3.6 client. We've also tried different HPA formats, e.g. autoscaling/v1, extensions/v1beta1, etc. Checking the 3.6 docs, it should support all of these.

We've also confirmed we are using the same formatting as in the latest origin docs:
```
  - apiVersion: extensions/v1beta1
    kind: HorizontalPodAutoscaler
    metadata:
      name: <my-app>
    spec:
      scaleRef:
        kind: DeploymentConfig
        name: <my-app>
        apiVersion: v1
        subresource: scale
      minReplicas: 1
      maxReplicas: 5
      cpuUtilization:
        targetPercentage: 80
```

##### Version
oc v3.6.0-alpha.2+3c221d5                                                                                                                                              
kubernetes v1.6.1+5115d708d7                                                                                                                                           
features: Basic-Auth GSSAPI Kerberos SPNEGO                                                                                                                            
                                                                                                                                                                       
Server https://172.30.0.1:443                                                                                                                                          
openshift v3.4.1.18                                                                                                                                                    
kubernetes v1.4.0+776c994 

##### Steps To Reproduce
Apply HPA as YAML with `oc` v3.6 to v3.4 (dedicated) cluster.

##### Current Result
```
error: autoscaling.HorizontalPodAutoscaler is not suitable for converting to ""
```

##### Expected Result
HPA gets updated

**Comment by bparees** [comment]
@deads2k possibly related to(and fixed by?) the other mapper work you're doing?

**Comment by tavogel** [comment]
Before this we were also having issues with https://github.com/kubernetes/kubernetes/issues/34413

The fix for this was to also running `oc delete hpa` before `oc apply -f hpa.yml` in our Jenkinsfile. It was fixed in Kuber 1.5.2, and we still have 1.4.0 on our dedicated cluster. Would be nice if we could fix this as well... i'm not sure when OpenShift is planning to upgrade to 1.5.2+.

**Comment by deads2k** [comment]
> @deads2k possibly related to(and fixed by?) the other mapper work you're doing?

I don't think so, but I'm not sure what `kubectl apply` looks like these days.

@openshift/cli-review

**Comment by deads2k** [comment]
@fabianofranz The message seems to imply an attempt at conversion, perhaps to internal, which I would not expect inside of the apply command.

**Comment by derekwaynecarr** [comment]
@DirectXMan12 -- anything you can help out with here?

**Comment by DirectXMan12** [comment]
I have a suspicion that this is related to the fact that you're using `extensions/v1beta1` for the HPA, which got remove in upstream Kubernetes -- you should be using `autoscaling/v1`.  I'll need to confirm, though.

**Comment by DirectXMan12** [comment]
Sorry about this -- my update got lost in the shuffle.  I was never able to reproduce this using a 3.6 oc and a 3.4 ose.  I tried building from the exact versions listed in the issue, but no dice.  If you're still having this issue, can you provide more details about your setup?

**Comment by tavogel** [comment]
Strangely, I am currently able to apply a YAML file and run `oc autoscale -o yaml | oc apply` now. Looks like something has been fixed!

The issue seems to be only happening when processing a template with `new-app`, while `oc process` works:
```yaml
apiVersion: v1
kind: Template
metadata:
  name: test
parameters:
- name: DEPLOYMENT_NAME
  description: What to name this application
  value: production
- name: NUM_REPLICAS
  description: How many replicas of the pod to deploy?
  value: '1'
- name: MAX_REPLICAS
  description: Limit on number of replicas to create
  value: '5'
objects:
- apiVersion: extensions/v1beta1
  kind: HorizontalPodAutoscaler
  metadata:
    name: ${DEPLOYMENT_NAME}
  spec:
    scaleRef:
      kind: DeploymentConfig
      name: ${DEPLOYMENT_NAME}
      apiVersion: v1
      subresource: scale
    minReplicas: ${NUM_REPLICAS}
    maxReplicas: ${MAX_REPLICAS}
    cpuUtilization:
      targetPercentage: 80
```

```sh
sh-4.2$ oc process test -o yaml | oc apply -f -                                                                                                                                                
horizontalpodautoscaler "production" configured                                                                                                                                
sh-4.2$ oc new-app --template=test -o yaml | oc apply -f -                                                                                                          
error: autoscaling.HorizontalPodAutoscaler is not suitable for converting to ""                                                                                                                
error: no objects passed to apply
sh-4.2$ oc new-app --template=test -o yaml                                                                                                                
error: autoscaling.HorizontalPodAutoscaler is not suitable for converting to ""```

So... easy fix for us, stop using `new-app` with templates.
