### ISSUE TITLE
Openshift Resource Limits Freeze New Pod Deployments Completely

### ISSUE THREAD

**Issue by chenchik** [openshift/origin#15051]
I'm running Openshift as the "All in One" VM on Vagrant using Virtual Box.

A link to the "All in One" VM can be found here:

https://atlas.hashicorp.com/openshift/boxes/origin-all-in-one

My VM is using 2 cores.

I'm using the image confluentinc/cp-kafka-connect, using an hdfs connector, and connecting to a kafka topic filled with values from 1 to 1,000,000.

I want to set a really low resource limit for my pods to create a bottleneck in order to simulate a production environment while using a really simple topic.

When I try to set limits, I am unable to create new apps or restart the deployments of existing apps. They are stuck in the "Rolling deployment in progress..." phase, and they are unable to load any logs. When I try to run:

`oc logs -f dc/konnekta-3`

the response is:

`Error from server: failed to run deployer pod konnekta-3-1-deploy: timed out waiting for the condition`

I am also unable to view the logs from the web console, and the pod never actually gets built.

##### Version
oc v1.1.1
kubernetes v1.1.0-origin-1107-g4c8e6f4

##### Steps To Reproduce
1. Create a resource limit .yaml file. Mine is called pod-limits.yaml and looks like this:

```
apiVersion: "v1"
kind: "LimitRange"
metadata:
  name: "core-resource-limits-4" 
spec:
  limits:
    - type: "Pod"
      max:
        cpu: "100m" 
        memory: "1Gi" 
      min:
        cpu: "10m" 
        memory: "6Mi" 
```

**(I have tried to increase the amount of CPU but received the same results)**

2.` oc create -f pod-limits.yaml`

3. `oc new-app confluentinc/cp-kafka-connect -e CONNECT_BOOTSTRAP_SERVERS=***.***.***.*** -e CONNECT_GROUP_ID="connect_group_multi_worker_7" -e CONNECT_CONFIG_STORAGE_TOPIC="whatever-a" -e CONNECT_OFFSET_STORAGE_TOPIC="whatever-b" -e CONNECT_STATUS_STORAGE_TOPIC="whatever-c" -e CONNECT_KEY_CONVERTER="org.apache.kafka.connect.storage.StringConverter" -e CONNECT_VALUE_CONVERTER="org.apache.kafka.connect.storage.StringConverter" -e CONNECT_INTERNAL_KEY_CONVERTER="org.apache.kafka.connect.json.JsonConverter" -e CONNECT_INTERNAL_VALUE_CONVERTER="org.apache.kafka.connect.json.JsonConverter" -e CONNECT_REST_ADVERTISED_HOST_NAME="connect" -e HADOOP_USER_NAME="hdfs" -e CONNECT_KEY_CONVERTER_SCHEMAS_ENABLE="false" -e CONNECT_VALUES_CONVERTER_SCHEMAS_ENABLE="false" -e CONNECT_INTERNAL_KEY_CONVERTER_SCHEMAS_ENABLE="false" -e CONNECT_INTERNAL_VALUE_CONVERTER_SCHEMAS_ENABLE="false" -e TERM=xterm --name=konnekta`

(this huge command creates a kafka connect app running an hdfs connector and operates as expected if no resource limits are added).

4. I have tried creating the app before setting the limit but then the pod doesn't pick up on the limits. It seems like the pod needs to be restarted in order to apply the new limits to it, but if I try to restart it, it gets stuck in the new deployment phase.

##### Current Result

Deployment of any pod freezes regardless of limits set.

##### Expected Result

Ability to deploy pods and be able to use the services/apps that the pods enable. I would like for the deployments to completely deploy and then have the pods be limited to 50 millicores ideally.

##### Additional Information

```
$ oadm diagnostics
-bash: oadm: command not found
$ oc adm diagnostics
Error: unknown command "adm" for "oc"
Run 'oc --help' for usage.
$ oc get builds
**returns nothing so I can't find any build logs***
$  oc get all -o json -n konnekta-3
{
    "kind": "List",
    "apiVersion": "v1",
    "metadata": {},
    "items": []
}
```

**Comment by smarterclayton** [comment]
A limit range limit *prevents* pods from running outside of that range.  You want to set the defaults that provide those for any pod in the namespace (or just add it to the deployment)

**Comment by derekwaynecarr** [comment]
you can apply a default resource request limit on your pods using following limit range:

```
apiVersion: v1
kind: LimitRange
metadata:
  name: defaults
spec:
  limits:
  - default:
      cpu: 300m
      memory: 200Mi
    defaultRequest:
      cpu: 200m
      memory: 100Mi
    type: Container
```

would set a default cpu limit of 300m and cpu request of 200m for example.

closing issue, and feel free to re-open if you have more problems.
