### ISSUE TITLE
Running pre-hook only as ANYUID SCC

### ISSUE THREAD

**Issue by mikk150** [openshift/origin#15111]
Hello, I need to run container pre-hook as root but would like to run container itselt as non-root

Is there any way to run pre-hook as other serviceaccount?

**Comment by php-coder** [comment]
Could you provide a more information? What are you trying to accomplish? How your DeploymentConfig/BuildConfig/Pod specification is look like?

If you're asking about [pre-hook for deployments](https://docs.openshift.com/enterprise/3.1/dev_guide/deployments.html#pod-based-lifecycle-hook) that's impossible at this moment because [hooks use the same SecurityContext as a pod](https://github.com/openshift/origin/blob/18c573053b30b567bc0b58153f3fc3e11f552a8b/pkg/deploy/strategy/support/lifecycle.go#L426).

If you're asking not about deployments then it should be possible to do this with [init-containers](https://kubernetes.io/docs/tasks/configure-pod-container/configure-pod-initialization/). In this case, you can have different `SecurityContext`s for init and normal containers.

**Comment by mikk150** [comment]
I think I could do it so that I build multiple containers
Build base image
Build production image based on base image(that will initialize all I need)
Build staging image based on base image(that will initialize all I need)

I only need to think how can I version it

initcontainers do not work, because it is not the same container but rather shares a directory with it through voume claims

**Comment by php-coder** [comment]
So, looks like you're talking about hooks during image building. It's still not clear what problem do you have and why do you need to run containers with different UIDs. Without this information I can''t help.

**Comment by mikk150** [comment]
So, I am trying to make Yii2 run in container

[Build stage]
* first step is to compile a container with all the code(happens in root, and because of that all files and directories belong to root)

[Pre-hook stage]
* second step is to initialize, this will copy environment configuration into config folders that belong to root, in addition to that it will make all directories that need to be world-writable as world-writable(so it needs to be run as root, otherwise you get bunch of permission denied errors)
* third step is to migrate database up

[Deployment]
* Run it

**Comment by php-coder** [comment]
> second step is to initialize, this will copy environment configuration into config folders that belong to root,

After build stage, a container has been committed. If you want to modify it's content you should do it during the build OR during the runtime from the script that serves as entry point. Which one you need?

> in addition to that it will make all directories that need to be world-writable as world-writable(so it needs to be run as root, otherwise you get bunch of permission denied errors)

See point above and also I'm wondering why you can't make directories world-writable during the build phase? (And I should warn you that having world-writable files/directories could lead to security issues. So, this should be avoided in most cases.)

> third step is to migrate database up

Is it impossible to do from init container? One of the advantages of init containers is that they block the execution. Other hooks AFAIR don't provide such a guarantee.

**Comment by mikk150** [comment]
ok, so now I am trying to do this:
[Build stage]

* build base image
* build environment specific image

[Pre-hook stage / init container]
* migrate db

[Deployment]
* Run it

But how can I pull base image from buildconfig?

**Comment by php-coder** [comment]
> But how can I pull base image from buildconfig?

As far I understand you can copy artifacts from one image to another: https://docs.openshift.org/latest/dev_guide/builds/advanced_build_operations.html#dev-guide-chaining-builds In other words, you will have 2 build configs where the last one will copy some artifacts from the first one.

**Comment by mikk150** [comment]
```yaml
- kind: BuildConfig
  apiVersion: v1
  metadata:
    name: "${NAME}-production"
    annotations:
      description: Defines how to build the application
  spec:
    source:
      dockerfile: |-
        FROM ${NAME}-base:latest
        RUN ./init --env=Production --overwrite=All
    strategy:
      type: Docker
      dockerStrategy:
        from: 
          kind: ImageStreamTag
          name: ${NAME}-base:latest
    output:
      to:
        kind: ImageStreamTag
        name: "${NAME}-production:latest"
    triggers:
    - type: ImageChange
    - type: ConfigChange
```

does the business
