### ISSUE TITLE
decide what to do about new admission plugins

### ISSUE THREAD

**Issue by deads2k** [openshift/origin#15290]
we have new plugins in `pkg/cmd/server/origin/admission/register.go` and we need to decide which are enabled and which aren't.

**Comment by deads2k** [comment]
1. initializers - off
2. webhook - off
3. NodeRestriction - @liggitt preference?
4. PodTolerationRestriction - @aveshagarwal @sjenning default on or off in our admission chain?

**Comment by sjenning** [comment]
PodTolerationRestriction seems like it would be ok to have by default but I'll let @aveshagarwal make the call as he authored it

**Comment by aveshagarwal** [comment]
Having PodTolerationRestriction on by default seems like a waste of cpu cycles. I think the same is true with other similar (that require some configurations to really make some impact) plugins.  The default on behavior can be achieved easily by configuring the following in master config file. 

```
  pluginConfig:
    PodTolerationRestriction:
      configuration:
        apiVersion: podtolerationrestriction.admission.k8s.io/v1alpha1
        kind: Configuration
```

So my preference would be to keep it off by default. Let me know if you have other thoughts.
