### ISSUE TITLE
Keepalived spontaneously starts flapping

### ISSUE THREAD

**Issue by carlpett** [openshift/origin#15394]
We have an issue where our keepalived containers apparently spontaneously starts flapping back and forth between master/backup. The only resolution we have found so far is to restart all the keepalived:s. At the longest, it has been working for a few months before getting into this state. After the latest problem, it just worked for a few hours before requiring a new restart. 

##### Version
```shell
$ openshift version
openshift v1.4.1
kubernetes v1.4.0+776c994
etcd 3.1.0-rc.0
```

##### Steps To Reproduce
1. ???

##### Configuration
We have three virtual master nodes, and two physical application+infra nodes. The spec part of the deployment configuration for ipfailover looks like this:
```yaml
spec:
  replicas: 2
  selector:
    ipfailover: ipfailover
  strategy:
    recreateParams:
      timeoutSeconds: 600
    resources: {}
    type: Recreate
  template:
    metadata:
      annotations:
        scheduler.alpha.kubernetes.io/affinity: |
          {
            "podAntiAffinity": {
              "requiredDuringSchedulingIgnoredDuringExecution": [{
                "labelSelector": {
                  "matchExpressions": [{
                    "key": "ipfailover",
                    "operator": "In",
                    "values":["ipfailover"]
                  }]
                },
                "topologyKey": "kubernetes.io/hostname"
              }]
            }
          }
      creationTimestamp: null
      labels:
        ipfailover: ipfailover
    spec:
      containers:
      - env:
        - name: OPENSHIFT_HA_CONFIG_NAME
          value: ipfailover
        - name: OPENSHIFT_HA_IPTABLES_CHAIN
          value: INPUT
        - name: OPENSHIFT_HA_MONITOR_PORT
          value: "80"
        - name: OPENSHIFT_HA_NETWORK_INTERFACE
        - name: OPENSHIFT_HA_REPLICA_COUNT
          value: "2"
        - name: OPENSHIFT_HA_USE_UNICAST
          value: "true"
        - name: OPENSHIFT_HA_VIRTUAL_IPS
          value: 10.50.193.100-101,10.50.193.128-191
        - name: OPENSHIFT_HA_VRRP_ID_OFFSET
          value: "0"
        image: openshift/origin-keepalived-ipfailover:v1.4.1
```
Changes from the default: 
- We are using unicast due to multicast not being supported at our hosting provider. 
- We also had to add pod anti-affinity after having both keepalived containers scheduled on the same node, which keepalived did not like at all.

Let me know what other information would be helpful in figuring this out.
