### ISSUE TITLE
Extended.deploymentconfigs when changing image change trigger [Conformance] should successfully trigger from an updated image

### ISSUE THREAD

**Issue by bparees** [openshift/origin#15418]
```
/go/src/github.com/openshift/origin/_output/local/go/src/github.com/openshift/origin/test/extended/deployments/deployments.go:367
Expected error:
    <*errors.errorString | 0xc420432720>: {
        s: "timed out waiting for the condition",
    }
    timed out waiting for the condition
not to have occurred
/go/src/github.com/openshift/origin/_output/local/go/src/github.com/openshift/origin/test/extended/deployments/deployments.go:348
```

https://ci.openshift.redhat.com/jenkins/job/merge_pull_request_origin/1355

**Comment by tnozicka** [comment]
Deployer pod #2

```
  containerStatuses:
  - containerID: docker://215859419e127c5f3c0c87a0bbdaf06d779ae23721f70f5faada0b84a040bf69
    image: docker.io/openshift/origin-deployer:v3.6.0-rc.0
    imageID: docker-pullable://docker.io/openshift/origin-deployer@sha256:6b99d86c96949a6717fbcdbe4a8fe6b65b5bee08e179e947f9993c7ae597bf83
    lastState: {}
    name: deployment
    ready: false
    restartCount: 0
    state:
      terminated:
        containerID: docker://215859419e127c5f3c0c87a0bbdaf06d779ae23721f70f5faada0b84a040bf69
        exitCode: 128
        finishedAt: 2017-07-23T07:04:51Z
        message: 'cannot join network of a non running container: 4381ca229d53e76cc39d0a0dc99fe7281caf1e1b86c08a4ff080d4bb7b127347'
        reason: ContainerCannotRun
        startedAt: 2017-07-23T07:04:51Z
  hostIP: 10.128.0.5
  phase: Failed
  qosClass: BestEffort
  startTime: 2017-07-23T07:04:40Z
```

@mfojtik  infra?
