### ISSUE TITLE
`osc login` can generate invalid config file

### ISSUE THREAD

**Issue by liggitt** [openshift/origin#1562]
Run `osc login  --certificate-authority=openshift.local.certificates/ca/cert.crt`

This file gets generated in `~/.config/openshift/.config`:
```
apiVersion: v1
clusters:
- cluster:
    certificate-authority: openshift.local.certificates/ca/cert.crt
    server: https://localhost:8443
  name: localhost-8443
contexts:
- context:
    cluster: localhost-8443
    user: a
  name: a
current-context: a
kind: Config
preferences: {}
users:
- name: a
  user:
    token: ...
```

Note that the certificate-authority path is still relative.

Now run `osc get ...`. The certificate authority file cannot be loaded, because it is resolved relative to the config file. When writing the config file, paths need to be absolutized, then relativized to the location of the config file. See `RelativizePathWithNoBacksteps` and `RelativizeMasterConfigPaths` for examples
