### ISSUE TITLE
Forbidden from mounting hostPath to CronJob

### ISSUE THREAD

**Issue by abdelhegazi** [openshift/origin#15720]
I am basically creating a CronJob that does one specific job taking a snapshot of Consul cluster metadata that is set up within statefulSet, this metadata to be saved by this cronjob somewhere (which i thought I will be able to mount a hostPath)
##### Version
```
oc v1.5.1+7b451fc
kubernetes v1.5.2+43a9be4
features: Basic-Auth

Server https://server-host:8443
openshift v3.5.5.31
kubernetes v1.5.2+43a9be4
```
##### Steps To Reproduce
1. Stateful set cluster is already up an running
2. ` oc create -f cronjob.yml`
```
$ cat cronjob.yml
apiVersion: batch/v2alpha1
kind: CronJob
metadata:
  name: consul-cronjob
spec:
  schedule: "*/5 * * * *"
  jobTemplate:            
    spec:
      template:
        metadata:
          name: consul-cronjob
          labels:
            app: consul          
        spec:
          nodeSelector:
            name: 879132-stg-openshift-mstr-03
          serviceaccount: consul-account
          dnsPolicy: ClusterFirst          
          containers:
          - name: consul
            image: 172.30.80.255:5000/aqua-security/consul:0.9.0
            # securityContext:
            #   privileged: true
            volumeMounts:
            - mountPath: /consul/data/
              name: "cronjob"
            command:
            - "/bin/sh"
            - "-c"
            - "curl http://consul-0.consul:8500/v1/snapshot -o /consul/data/backup.tgz; sleep 20 "
          restartPolicy: OnFailure
          volumes:
          - name: "cronjob"
            hostPath:
              path: /var/lib/docker/volumes/cc-cronjob/

```

##### Current Result
cronjob is created successfully but it generate loads of failed jobs that never die until I delete them manually which is very very slow process 
```
$ oc create -f cronjob.yml 
cronjob "consul-cronjob" created
$ oc get cronjob
NAME             SCHEDULE      SUSPEND   ACTIVE    LAST-SCHEDULE
consul-cronjob   */1 * * * *   False     0         <none>

# oc get job
consul-cronjob-1502322540   1         0            17m
consul-cronjob-1502322600   1         0            16m
consul-cronjob-1502322660   1         0            15m
consul-cronjob-1502322720   1         0            14m
consul-cronjob-1502322780   1         0            13m
consul-cronjob-1502322840   1         0            12m
consul-cronjob-1502322900   1         0            11m
consul-cronjob-1502322960   1         0            10m
consul-cronjob-1502323020   1         0            9m
consul-cronjob-1502323080   1         0            8m
consul-cronjob-1502323140   1         0            7m
consul-cronjob-1502323200   1         0            6m
...

$ oc describe job consul-cronjob-1502323200
Name:		consul-cronjob-1502323200
Namespace:	aqua-security
...
Pods Statuses:	0 Running / 0 Succeeded / 0 Failed
Volumes:
  cronjob:
    Type:	HostPath (bare host directory volume)
    Path:	/var/lib/docker/volumes/cc-cronjob/
Events:
  FirstSeen	LastSeen	Count	From			SubObjectPath	Type		Reason		Message
  ---------	--------	-----	----			-------------	--------	------		-------
  8m		3m		2	{job-controller }			Warning		FailedCreate	Error creating: pods "consul-cronjob-1502323200-" is forbidden: unable to validate against any security context constraint: [spec.containers[0].securityContext.privileged: Invalid value: true: Privileged containers are not allowed spec.containers[0].securityContext.volumes[0]: Invalid value: "hostPath": hostPath volumes are not allowed to be used spec.containers[0].securityContext.privileged: Invalid value: true: Privileged containers are not allowed spec.containers[0].securityContext.volumes[0]: Invalid value: "hostPath": hostPath volumes are not allowed to be used]
```

I would have to run something like this to cleanup all the failing job even if I have deleted the cronjob I would need to manually clean the failing jobs  
```
# oc delete job $(oc get job | grep consul-cronjob  | awk '{print $1}')
job "consul-cronjob-1502288340" deleted
job "consul-cronjob-1502288400" deleted
job "consul-cronjob-1502288580" deleted
job "consul-cronjob-1502288640" deleted
job "consul-cronjob-1502288700" deleted
``` 

##### Expected Result
Expected to have the hostPath to be mounted normally as I always do.

**Comment by pweil-** [comment]
@php-coder

**Comment by php-coder** [comment]
This looks like that the service account `consul-account` needs permissions to create privileged pods and mount hostPath volumes. Try to execute `oc adm policy add-scc-to-user privileged -z consul-account` command within the project.

See https://docs.openshift.org/latest/admin_guide/manage_scc.html#grant-access-to-the-privileged-scc and https://docs.openshift.org/latest/admin_guide/manage_scc.html#add-scc-to-user-group-project

**Comment by abdelhegazi** [comment]
Thanks @php-coder 
I actually have looked at this, and I did use a super super super privileged service account that is enjoying cluster-admin

to complete my issue, it only happens with any thing acts as scheduler, looking at this job it executes very well but its only Job not cronJob neither scheduledJob which is what exactly I need 

This is succeeding to mount it, 
```
apiVersion: batch/v1
kind: Job
metadata:
  name: consul-cronjob
spec:
  parallelism: 1    
  completions: 1    
  template:         
    metadata:
      name: consul-cronjob
      labels:
        app: consul
    spec:
      volumes:
      - name: "consul"
        hostPath:
          path: /var/lib/docker/volumes/cc-cronjob/
      nodeSelector:
        name: 879132-stg-openshift-mstr-03
        region: infra
      serviceAccount: aqua-account
      containers:
      - name: consul
        image: 172.30.80.255:5000/aqua-security/consul:0.9.0 
        securityContext:
          privileged: true
        command:
        - "/bin/sh"
        - "-c"
        - "curl http://consul-1.consul:8500/v1/snapshot -o /consul/data/`date '+%Y.%m.%d-%H.%M.%S'`.tgz"
        volumeMounts:
        - mountPath: /consul/data
          name: "consul"
      restartPolicy: Never
```

and this is my cronjob/scheduledJob and it totally FAILS to mount it with the error shown in my original ticket
```
apiVersion: batch/v2alpha1
kind: CronJob   #ScheduledJob
metadata:
  name: consul-cronjob
spec:
  schedule: "*/2 * * * *"
  jobTemplate:            
    spec:
      template:
        metadata:
          name: consul-cronjob
          labels:
            app: consul          
        spec:
          volumes:
          - name: "cronjob"
            hostPath:
              path: /var/lib/docker/volumes/cc-cronjob/
          nodeSelector:
            name: 879132-stg-openshift-mstr-03
            region: infra
          serviceaccount: aqua-account
          containers:
          - name: consul
            image: 172.30.80.255:5000/aqua-security/consul:0.9.0
            securityContext:
              privileged: true
#               runAsUser: 0
            volumeMounts:
            - mountPath: /consul/data/
              name: "cronjob"
            command:
            - "/bin/sh"
            - "-c"
            - "touch /consul/data/testme"
#            - "curl http://consul-1.consul:8500/v1/snapshot -o /consul/data/`date '+%Y.%m.%d-%H.%M.%S'`.tgz"
          restartPolicy: OnFailure

```

**Comment by abdelhegazi** [comment]
At any point, being a `batch/v2alpha1` would that be an issue?

**Comment by php-coder** [comment]
> At any point, being a batch/v2alpha1 would that be an issue?

@soltysh Could you take a look?

**Comment by abdelhegazi** [comment]
To show you the weird happenings here, this is what exactly I have done
```
$ oc adm policy add-scc-to-user privileged -z aqua-account

oc get job -w
NAME      DESIRED   SUCCESSFUL   AGE
NAME                      DESIRED   SUCCESSFUL   AGE
aqua-cronjob-1502451120   1         0            0s

$ oc describe job aqua-cronjob-1502451120 
Name:		aqua-cronjob-1502451120
Namespace:	aqua-security
Image(s):	172.30.80.255:5000/aqua-security/consul:0.9.0
Selector:	controller-uid=b1914746-7e88-11e7-ad6d-005056a25c7d
Parallelism:	1
Completions:	1
Labels:		app=consul
		controller-uid=b1914746-7e88-11e7-ad6d-005056a25c7d
		job-name=aqua-cronjob-1502451120
Pods Statuses:	0 Running / 0 Succeeded / 0 Failed
Volumes:
  cronjob:
    Type:	HostPath (bare host directory volume)
    Path:	/var/lib/docker/volumes/cc-cronjob/
Events:
  FirstSeen	LastSeen	Count	From			SubObjectPath	Type		Reason		Message
  ---------	--------	-----	----			-------------	--------	------		-------
  18s		18s		1	{job-controller }			Warning		FailedCreate	Error creating: pods "aqua-cronjob-1502451120-" is forbidden: unable to validate against any security context constraint: [spec.containers[0].securityContext.privileged: Invalid value: true: Privileged containers are not allowed spec.containers[0].securityContext.volumes[0]: Invalid value: "hostPath": hostPath volumes are not allowed to be used spec.containers[0].securityContext.privileged: Invalid value: true: Privileged containers are not allowed spec.containers[0].securityContext.volumes[0]: Invalid value: "hostPath": hostPath volumes are not allowed to be used]
```

This is never a problem with the Job, as I am literally able to snapshot consul metadata but I don't really want to have a cronjob running on the cluster, instead would rather have it run  by a cronjob object.

**Comment by abdelhegazi** [comment]
@php-coder I guess I may have found a bug
One thing just spotted when exporting the job created by my job.yaml i can see it has the `serviceaccount`exported as you can see here 
```
$ oc export job consul-cronjob
apiVersion: batch/v1
kind: Job
metadata:
  creationTimestamp: null
  labels:
    app: consul
    controller-uid: 617ffa40-7e8e-11e7-a91a-005056a22585
    job-name: consul-cronjob
  name: consul-cronjob
spec:
  completions: 1
  parallelism: 1
  selector:
    matchLabels:
      controller-uid: 617ffa40-7e8e-11e7-a91a-005056a22585
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: consul
        controller-uid: 617ffa40-7e8e-11e7-a91a-005056a22585
        job-name: consul-cronjob
      name: consul-cronjob
    spec:
      containers:
      - command:
        - /bin/sh
        - -c
        - curl http://consul-1.consul:8500/v1/snapshot -o /consul/data/`date '+%Y.%m.%d-%H.%M.%S'`.tgz
        image: 172.30.80.255:5000/aqua-security/consul:0.9.0
        imagePullPolicy: IfNotPresent
        name: consul
        resources: {}
        securityContext:
          privileged: true
        terminationMessagePath: /dev/termination-log
        volumeMounts:
        - mountPath: /consul/data
          name: consul
      dnsPolicy: ClusterFirst
      nodeSelector:
        name: 879132-stg-openshift-mstr-03
        region: infra
      restartPolicy: Never
      securityContext: {}
      serviceAccount: aqua-account
      serviceAccountName: aqua-account
      terminationGracePeriodSeconds: 30
      volumes:
      - hostPath:
          path: /var/lib/docker/volumes/cc-cronjob/
        name: consul
status:
  completionTime: 2017-08-11T12:12:51Z
  conditions:
  - lastProbeTime: 2017-08-11T12:12:51Z
    lastTransitionTime: 2017-08-11T12:12:51Z
    status: "True"
    type: Complete
  startTime: 2017-08-11T12:12:49Z
  succeeded: 1
```

but when exporting one of the failed jobs created by my cronjob i can't see that information there
```
$ oc export job consul-cronjob-1502453520
apiVersion: batch/v1
kind: Job
metadata:
  annotations:
    kubernetes.io/created-by: |
      {"kind":"SerializedReference","apiVersion":"v1","reference":{"kind":"CronJob","namespace":"aqua-security","name":"consul-cronjob","uid":"0eb583ab-7e8e-11e7-a91a-005056a22585","apiVersion":"batch","resourceVersion":"2037307"}}
  creationTimestamp: null
  labels:
    app: consul
    controller-uid: 4abb0610-7e8e-11e7-ad6d-005056a25c7d
    job-name: consul-cronjob-1502453520
  name: consul-cronjob-1502453520
spec:
  completions: 1
  parallelism: 1
  selector:
    matchLabels:
      controller-uid: 4abb0610-7e8e-11e7-ad6d-005056a25c7d
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: consul
        controller-uid: 4abb0610-7e8e-11e7-ad6d-005056a25c7d
        job-name: consul-cronjob-1502453520
      name: consul-cronjob
    spec:
      containers:
      - command:
        - /bin/sh
        - -c
        - touch /consul/data/testme
        image: 172.30.80.255:5000/aqua-security/consul:0.9.0
        imagePullPolicy: IfNotPresent
        name: consul
        resources: {}
        terminationMessagePath: /dev/termination-log
        volumeMounts:
        - mountPath: /consul/data/
          name: cronjob
      dnsPolicy: ClusterFirst
      nodeSelector:
        name: 879132-stg-openshift-mstr-03
        region: infra
      restartPolicy: OnFailure
      securityContext: {}
      terminationGracePeriodSeconds: 30
      volumes:
      - hostPath:
          path: /var/lib/docker/volumes/cc-cronjob/
        name: cronjob
status: {}
```
and exporting the real cronjob itself doesn't have it too
```
$ oc export cronjob consul-cronjob 
apiVersion: batch/v2alpha1
kind: CronJob
metadata:
  creationTimestamp: null
  name: consul-cronjob
spec:
  concurrencyPolicy: Allow
  jobTemplate:
    metadata:
      creationTimestamp: null
    spec:
      template:
        metadata:
          creationTimestamp: null
          labels:
            app: consul
          name: consul-cronjob
        spec:
          containers:
          - command:
            - /bin/sh
            - -c
            - touch /consul/data/testme
            image: 172.30.80.255:5000/aqua-security/consul:0.9.0
            imagePullPolicy: IfNotPresent
            name: consul
            resources: {}
            terminationMessagePath: /dev/termination-log
            volumeMounts:
            - mountPath: /consul/data/
              name: cronjob
          dnsPolicy: ClusterFirst
          nodeSelector:
            name: 879132-stg-openshift-mstr-03
            region: infra
          restartPolicy: OnFailure
          securityContext: {}
          terminationGracePeriodSeconds: 30
          volumes:
          - hostPath:
              path: /var/lib/docker/volumes/cc-cronjob/
            name: cronjob
  schedule: '*/2 * * * *'
  suspend: false
status: {}
```

**Comment by soltysh** [comment]
@abdelhegazi can you double check where you're setting the SA in a cronjob?. I've been using SA for cronjobs since 1.5 in my [workshop materials](https://github.com/soltysh/blast/blob/master/scraper/template.yaml#L34) and it's working as expected. Please double check if your SA is the SA of a `jobTemplate'`s pod template.

**Comment by abdelhegazi** [comment]
```
  template:
    metadata:
      name: consul-snapshot
      labels:
        app: consul
    spec:
      volumes:
      - name: "consul"
        hostPath:
          path: /var/lib/docker/volumes/cc-cronjob/
      nodeSelector:
        name: 879132-stg-openshift-mstr-03
        region: infra
      serviceAccount: aqua-account
      containers:
      - name: consul
```
