### ISSUE TITLE
Cronjobs stop working, need advice

### ISSUE THREAD

**Issue by ksemaev** [openshift/origin#15759]
After some time (less then one day) cronjob stops creating jobs.

##### Version
oc v1.5.1
kubernetes v1.5.2+43a9be4
features: Basic-Auth GSSAPI Kerberos SPNEGO

##### Steps To Reproduce
1. create cronjob:
```
apiVersion: batch/v2alpha1
kind: CronJob
metadata:
  name: cancelorder
spec:
  schedule: "*/1 * * * *"  
  jobTemplate:             
    spec:
      template:
        metadata:
          labels:          
            parent: "cancelordercron"
        spec:
          containers:
          - name: cancelorderpod
            image: dockerhub.prod:5000/project/image:release
            command: ["php", "/intercity-backend/bin/console", "app:orders:cancel"]
            env:
            - name: SYMFONY_ENV
              value: prod
          restartPolicy: OnFailure
  concurrencyPolicy: Forbid
```
2. Several minutes later: oc get jobs (shows them)
3. Several hours later: oc get jobs (nothing)

##### Current Result
No resources found.

##### Expected Result
NAME                     DESIRED   SUCCESSFUL   AGE
cancelorder-1502699400   1         1            3m
cancelorder-1502699460   1         1            2m
cancelorder-1502699520   1         1            1m
cancelorder-1502699580   1         1            42s

##### Additional Information
I have no idea where to look for the reason of th failure. I do have this cron task for removing  old jobs:
*/15 * * * *  oc delete job -l parent=cancelordercron -n elpass > /dev/null
#Remove unnneded dc
* */3 * * * oadm prune deployments --orphans --keep-complete=3 --keep-failed=0 --keep-younger-than=60m --confirm

I suspect that when I deploy new version of "image: dockerhub.prod:5000/project/image:release" the cronjob stop working. But shouldnt't just create at the specified time the pod from image:tag (and not care if it was updated)?

I have no idea where to look for logs of cronjob, because:
oc logs cronjob/cancelorder
error: cannot get the logs from batch/__internal, Kind=CronJob

Ahy help is very appreciated
