### ISSUE TITLE
s2i image build pull too many/wrong source images

### ISSUE THREAD

**Issue by vaudk** [openshift/origin#15954]
when building images via buildconfigs using dockerstrategy not only the specified source image[:tag] gets pulled but also (unnecessarily) other tags that are available for a specific docker image.

##### Version
```
[root@3 ~]# oc version
oc v3.6.0+c4dd4cf
kubernetes v1.6.1+5115d708d7
features: Basic-Auth GSSAPI Kerberos SPNEGO

Server https://127.0.0.1:8443
openshift v3.6.0+c4dd4cf
kubernetes v1.6.1+5115d708d7
```
```
[root@3 ~]# docker version
Client:
 Version:         1.12.6
 API version:     1.24
 Package version: docker-1.12.6-32.git88a4867.el7.centos.x86_64
 Go version:      go1.7.4
 Git commit:      88a4867/1.12.6
 Built:           Mon Jul  3 16:02:02 2017
 OS/Arch:         linux/amd64

Server:
 Version:         1.12.6
 API version:     1.24
 Package version: docker-1.12.6-32.git88a4867.el7.centos.x86_64
 Go version:      go1.7.4
 Git commit:      88a4867/1.12.6
 Built:           Mon Jul  3 16:02:02 2017
 OS/Arch:         linux/amd64
```

##### Steps To Reproduce
1. build image with this buildconfig:
```
apiVersion: v1
kind: BuildConfig
metadata:
  labels:
    name: s2i-frontend
  name: s2i-frontend
  namespace: s2i
spec:
  output:
    to:
      kind: ImageStreamTag
      name: s2i-frontend:latest
      namespace: s2i
  postCommit: {}
  resources: {}
  source:
    dockerfile: "FROM node:latest\nRUN echo test"
  strategy:
    dockerStrategy:
      forcePull: true
      from:
        kind: DockerImage
        name: node:latest
    type: Docker
  triggers:
  - type: ConfigChange
```
##### Current Result
```
[root@3 ~]# docker images
REPOSITORY                                   TAG                 IMAGE ID            CREATED             SIZE
docker.io/openshift/origin-docker-builder    v3.6.0              a9f1eedc2cb3        3 weeks ago         974.2 MB
docker.io/openshift/origin-deployer          v3.6.0              ad03ec44312c        3 weeks ago         974.2 MB
docker.io/openshift/origin-docker-registry   v3.6.0              ec456625b2a0        3 weeks ago         1.062 GB
docker.io/openshift/origin-haproxy-router    v3.6.0              75e805233369        3 weeks ago         995.3 MB
docker.io/openshift/origin                   v3.6.0              25e1f260f8ae        3 weeks ago         974.2 MB
docker.io/openshift/origin-pod               v3.6.0              fb52c4c8f037        3 weeks ago         213.4 MB
docker.io/node                               0-wheezy            f4f4709eb79b        8 months ago        496 MB
docker.io/node                               0-slim              c39f11e4bcbb        8 months ago        199.6 MB
docker.io/node                               0-onbuild           eb72ee9de204        8 months ago        644.4 MB
.
.
.
```

##### Expected Result
```
[root@3 ~]# docker images
REPOSITORY                                   TAG                 IMAGE ID            CREATED             SIZE
docker.io/openshift/origin-docker-builder    v3.6.0              a9f1eedc2cb3        3 weeks ago         974.2 MB
docker.io/openshift/origin-deployer          v3.6.0              ad03ec44312c        3 weeks ago         974.2 MB
docker.io/openshift/origin-docker-registry   v3.6.0              ec456625b2a0        3 weeks ago         1.062 GB
docker.io/openshift/origin-haproxy-router    v3.6.0              75e805233369        3 weeks ago         995.3 MB
docker.io/openshift/origin                   v3.6.0              25e1f260f8ae        3 weeks ago         974.2 MB
docker.io/openshift/origin-pod               v3.6.0              fb52c4c8f037        3 weeks ago         213.4 MB
docker.io/node                               latest              6f6ffe2a1302        5 days ago          668.6 MB
```
