### ISSUE TITLE
Failed to provision volume with StorageClass "cinder-1": No suitable endpoint could be found in the service catalog.

### ISSUE THREAD

**Issue by pennpeng** [openshift/origin#15979]
[provide a description of the issue]

##### Version
[provide output of the `openshift version` or `oc version` command]
```
[root@master ~]# oc version
oc v3.6.0+c4dd4cf
kubernetes v1.6.1+5115d708d7
features: Basic-Auth GSSAPI Kerberos SPNEGO

Server https://master:8443
openshift v3.6.0+c4dd4cf
kubernetes v1.6.1+5115d708d7
```
##### Steps To Reproduce
use openstack cinder storageclass,i have test pv use cinder and is ok,but storageclass is failed.
```
kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: cinder-1
  annotations:
    storageclass.kubernetes.io/is-default-class: "true" 
provisioner: kubernetes.io/cinder
parameters:
  availability: nova 
```
```
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
 name: pvc-registry
spec:
 accessModes:
  - ReadWriteOnce
 resources:
   requests:
     storage: 20Gi
```

##### Current Result
Failed to provision volume with StorageClass "cinder-1": No suitable endpoint could be found in the service catalog.
```
[root@penn-1 home]# oc describe pvc pvc-registry 
Name:		pvc-registry
Namespace:	default
StorageClass:	cinder-1
Status:		Pending
Volume:		
Labels:		<none>
Annotations:	volume.beta.kubernetes.io/storage-provisioner=kubernetes.io/cinder
Capacity:	
Access Modes:	
Events:
  FirstSeen	LastSeen	Count	From				SubObjectPath	Type		Reason			Message
  ---------	--------	-----	----				-------------	--------	------			-------
  16s		9s		2	persistentvolume-controller			Warning		ProvisioningFailed	Failed to provision volume with StorageClass "cinder-1": No suitable endpoint could be found in the service catalog.

```
##### Additional Information
[try to run `$ oc adm diagnostics` (or `oadm diagnostics`) command if possible]
[if you are reporting issue related to builds, provide build logs with `BUILD_LOGLEVEL=5`]
[consider attaching output of the `$ oc get all -o json -n <namespace>` command to the issue]
[visit https://docs.openshift.org/latest/welcome/index.html]
