### ISSUE TITLE
oc new-app does not support annotations on 'servicecatalog.k8s.io/v1alpha1, Kind=Broker'

### ISSUE THREAD

**Issue by gordillo-ramon-redhat** [openshift/origin#15996]
When adding a broker object to a template, it can be used an oc process, but not oc new-app.

##### Version
oc v3.6.0+c4dd4cf
kubernetes v1.6.1+5115d708d7
features: Basic-Auth GSSAPI Kerberos SPNEGO

##### Steps To Reproduce
1. Example (broker.yaml):

```
apiVersion: v1
kind: Template
metadata:
  name: broker
objects:
- apiVersion: servicecatalog.k8s.io/v1alpha1
  kind: Broker
  metadata:
    name: ansible-service-broker
  spec:
    url: ${BROKER_URL}
    authInfo:
      basicAuthSecret:
        namespace: ${NAMESPACE}
        name: asb-auth-secret
parameters:
- description: Namespace
  displayname: namespace
  name: NAMESPACE
  required: true
- description: Broker URL
  displayname: Broker URL
  name: BROKER_URL
  required: true
```

2. works: 

`oc process -f broker.yaml -p BROKER_URL=http://asb-1338.example.com -p NAMESPACE=sample | oc create -f -
`

3. Not works: 

`oc new-app --file=broker.yaml -p BROKER_URL=http://asb-1338.example.com -p NAMESPACE=sample
`

##### Current Result

failed to add annotation to object of type "servicecatalog.k8s.io/v1alpha1, Kind=Broker", this resource type is probably unsupported by your client version.

##### Expected Result

Same as 2.
