### ISSUE TITLE
Extended.deploymentconfigs with custom deployments [Conformance] should run the custom deployment steps

### ISSUE THREAD

**Issue by bparees** [openshift/origin#16023]
```
/go/src/github.com/openshift/origin/test/extended/deployments/deployments.go:518
Expected error:
    <*errors.errorString | 0xc420ec3710>: {
        s: "deployment failed: config change",
    }
    deployment failed: config change
not to have occurred
/go/src/github.com/openshift/origin/test/extended/deployments/deployments.go:499
```
https://ci.openshift.redhat.com/jenkins/job/test_pull_request_origin_extended_conformance_install_update/4987/

**Comment by tnozicka** [comment]
Deployer pod failed because of infra:
```
containerStatuses:
  - containerID: docker://14c467bf179ec92bbb8294b364b9c516ca13f9a263cd5941af900878d7c6bf22
    image: openshift/origin-deployer:8453380
    imageID: docker://sha256:7abe0813c18a9d874d13d00201eb5c51e09f2ef23a72c249cbe3ad1fa8e18188
    lastState: {}
    name: deployment
    ready: false
    restartCount: 0
    state:
      terminated:
        containerID: docker://14c467bf179ec92bbb8294b364b9c516ca13f9a263cd5941af900878d7c6bf22
        exitCode: 128
        finishedAt: 2017-08-28T21:33:38Z
        message: 'invalid header field value "oci runtime error: container_linux.go:247:
          starting container process caused \"process_linux.go:258: applying cgroup
          configuration for process caused \\\"write /sys/fs/cgroup/pids/kubepods.slice/kubepods-besteffort.slice/kubepods-besteffort-pod8cd1564c_8c38_11e7_8d0a_0e359e0baf04.slice/docker-14c467bf179ec92bbb8294b364b9c516ca13f9a263cd5941af900878d7c6bf22.scope/cgroup.procs:
          no such device\\\"\"\n"'
        reason: ContainerCannotRun
        startedAt: 2017-08-28T21:33:38Z
```
