### ISSUE TITLE
Build status should not record a PostCommit step if none was specified

### ISSUE THREAD

**Issue by smarterclayton** [openshift/origin#16119]
Had a build report a stage and step for PostCommit, which was not actually specified.  Build shouldn't include steps that aren't run.

```
  - name: PostCommit
    startTime: 2017-09-03T20:42:07Z
    steps:
    - name: RunPostCommitHook
      startTime: 2017-09-03T20:42:07Z
```
