### ISSUE TITLE
Weird display after creating PVC in web UI

### ISSUE THREAD

**Issue by dsfranzi** [openshift/origin#16300]
Because I don't even know how to google this kind of issue, I'm going to post it here. 

##### Version
```
oc version
oc v3.6.0+c4dd4cf
kubernetes v1.6.1+5115d708d7
features: Basic-Auth

Server http://************
openshift v1.5.1
kubernetes v1.5.2+43a9be4
```

##### Steps To Reproduce
1. Create a **persistent volume** using the command line and a yaml file.
    I decided to use a dynamically provisioned storage offered by Kubernetes 1.4.
```yaml
kind: StorageClass
apiVersion: storage.k8s.io/v1beta1
metadata:
  name: fast
provisioner: kubernetes.io/gce-pd
parameters:
  type: pd-ssd
```

2. Create a **persistent volume claim** using the previously created **pv** in openshifts web UI.

##### Current Result

If I create a **pvc** with `1GiB` of storage, the UI stays in "pending" state forever.
If I create a **pvc** with `0,95GiB` of storage, this weird result happens:

![grafik](https://user-images.githubusercontent.com/7378020/30332116-d9d38644-97d9-11e7-95cf-3eb2e697be7c.png)

The UI stays in "pending" state here, too.

##### Expected Result

A created **pvc** to be used by pods. Or at least a meaningful error message what has gone wrong.
