### ISSUE TITLE
admin kubeconfig public-master context doesn't point at public-master cluster

### ISSUE THREAD

**Issue by sosiouxme** [openshift/origin#1641]
The kubeconfig openshift-master automatically generates for admin includes these contexts:

```
- context:
    cluster: master
    user: system:admin
  name: master
- context:
    cluster: master
    user: system:admin
  name: public-master
```

Note the second one is still pointing at the internal master. The public-master cluster is defined, just needs to be used here.
