### ISSUE TITLE
What's the User Workflow for Profiling Ephemeral Workflows?

### ISSUE THREAD

**Issue by stevekuznetsov** [openshift/origin#16498]
Recently @csrwng and I were trying to determine how to size the containers we were using for running ephemeral workloads on the cluster. Some of these take ten minutes, some five, some forty. We were not happy with the availability of Prometheus metrics for the pods as often they give us a glimpse into the vCPU and RAM use at one or two points in time during the entire execution. Do we have a better way to measure vCPU-hours or MB-hours for a pod once it's finished executing? Or a way to set up more frequent profiling for short-lived workloads? Or is there a different approach entirely?

/cc @smarterclayton @bparees @gabemontero

**Comment by smarterclayton** [comment]
Heapster used to have some of that, but maybe not anymore?

@DirectXMan12

**Comment by DirectXMan12** [comment]
oh dear, sorry for the delay in seeing this.  I think we just want the ability to control Prometheus collection rates based on workload types, etc, perhaps.  Heapster has a fixed collection interval (we run at 30s), but with Heapster being deprecated, I think we need a Prometheus-based solution.  I'll add it to my card on Prometheus collection: https://trello.com/c/aF2o4XYK/786-13-autoscaling-ability-to-ingest-custom-metrics-from-a-pod-at-scale

**Comment by stevekuznetsov** [comment]
Currently our workaround for not having some of these metrics is running pods like:

```yaml
      command:
      - /bin/bash
      args:
      - -c
      - 'function o() { e="$?"; cat /sys/fs/cgroup/memory/memory.max_usage_in_bytes; exit "$e"; }; trap o EXIT; <<actual pod work>>'
```
