### ISSUE TITLE
error: build error: Failed to push image: unauthorized: authentication required

### ISSUE THREAD

**Issue by magick93** [openshift/origin#16528]
We are unable to push images to the internal docker registry after doing a build.

The error in the build log is:
```
error: build error: Failed to push image: unauthorized: authentication required
```

##### Version

- openshift version
- openshift v3.6.0+c4dd4cf
- kubernetes v1.6.1+5115d708d7
- etcd 3.2.1

##### Steps To Reproduce
Not exactly sure how to reproduce this as it used to work!
Today we are trying to do a build but its not able to push to the internal docker registry.

##### Current Result

```
error: build error: Failed to push image: unauthorized: authentication required
```

##### Expected Result
Expect build to complete successfully and push to registry.

##### Additional Information
See this gist (https://gist.github.com/magick93/f6f838aa9b30bb2c0b60cb781e036770 )for diagnostics and build logs.

**Comment by bbrfkr** [comment]
+1

**Comment by bparees** [comment]
level 5 build logs would be useful (I do not see any build logs in your gist) however based on the registry output it appears that the build did not detect any secret in your project which matched to the registry, thus it attempted to push the image w/o providing any credentials.

if you create a new project and perform a build in that project, does the push succeed?

Did you change anything about the secrets in your project recently?

**Comment by magick93** [comment]
Thanks @bparees - I will try creating a new project.

> Did you change anything about the secrets in your project recently?

No I didnt.

**Comment by magick93** [comment]
> if you create a new project and perform a build in that project, does the push succeed?

Unfortunately no. 

I created a new project, and created a new build using the following build config:

```
kind: "BuildConfig"
apiVersion: "v1"
metadata:
  name: "s2i-cpp" 
  annotations:
    openshift.io/build-config.name: s2i-cpp
  labels:
    build: s2i-cpp
    buildconfig: s2i-cpp
    openshift.io/build-config.name: s2i-cpp
    openshift.io/build.start-policy: Serial
spec:
  source:
    contextDir: "dockerfiles/builder"
    git:
      ref: master
      uri: 'https://gitlab.com/myrepo/s2i-cpp.git'
    sourceSecret:
      name: gitlab-priceinsight
    type: Git
  strategy:
   type: Docker
   dockerStrategy:
    dockerfilePath: dockerfiles/builder/
  output: 
    to:
      kind: "ImageStreamTag"
      name: "s2i-cpp:latest"
```

When I try to run this new build, it doesnt even start - the message I get is `Invalid output reference`.
