### ISSUE TITLE
oc export does not respect imagestreams original source

### ISSUE THREAD

**Issue by ThomasSteinbach** [openshift/origin#16531]
The YAML export of an image stream replaces the source URL of the external registry by the URL of the internal registry. Thus images won't be pulled correctly after importing the export on another OpenShift cluster.

##### Version

```
oc v3.6.0+c4dd4cf
kubernetes v1.6.1+5115d708d7
features: Basic-Auth GSSAPI Kerberos SPNEGO

Server https://ip-10-52-101-57.eu-central-1.compute.internal:8443
openshift v1.5.1
kubernetes v1.5.2+43a9be4
```

##### Steps To Reproduce
1. create imgestream from external repository
2. `oc export is -o yaml > export.yaml`

##### Current Result

The exported imagestream points to the internal registry:

```
- kind: ImageStream
  spec:
    tags:
    - annotations:
        openshift.io/imported-from: <external-registry>/my/image:17.08
      from:
        kind: DockerImage
        name: <internal-registry>:5000/my/image:17.08
```

##### Expected Result

The exported imagestreams should point to the original external registry:

```
- kind: ImageStream
  spec:
    tags:
    - annotations:
        openshift.io/imported-from: <external-registry>/my/image:17.08
      from:
        kind: DockerImage
        name: <external-registry>/my/image:17.08
```
