### ISSUE TITLE
Sometimes get 409 error provisioning template with no other details

### ISSUE THREAD

**Issue by spadgett** [openshift/origin#16734]
This error doesn't happen every time, but I see it occasionally.

> Error provisioning ServiceInstance "test/mysql-persistent-jvz7r" of ServiceClass "mysql-persistent" at ServiceBroker "template-service-broker": Status: 409; ErrorMessage: <nil>; Description: <nil>; ResponseError: <nil>

The template was instantiated, however.

Here is the YAML from the service instance:

```yaml
  conditions:
    - lastTransitionTime: '2017-10-06T19:32:33Z'
      message: >-
        ServiceBroker returned a failure for provision call; operation will not
        be retried: Error provisioning ServiceInstance
        "test/mysql-persistent-jvz7r" of ServiceClass "mysql-persistent" at
        ServiceBroker "template-service-broker": Status: 409; ErrorMessage:
        <nil>; Description: <nil>; ResponseError: <nil>
      reason: ProvisionCallFailed
      status: 'False'
      type: Ready
    - lastTransitionTime: '2017-10-06T19:32:34Z'
      message: >-
        Error provisioning ServiceInstance "test/mysql-persistent-jvz7r" of
        ServiceClass "mysql-persistent" at ServiceBroker
        "template-service-broker": Status: 409; ErrorMessage: <nil>;
        Description: <nil>; ResponseError: <nil>
      reason: ServiceBrokerReturnedFailure
      status: 'True'
      type: Failed
```

Here is the status on the template instance:

```yaml
status:
  conditions:
    - lastTransitionTime: '2017-10-06T19:32:48Z'
      message: ''
      reason: Created
      status: 'True'
      type: Ready
```
![openshift web console 2017-10-06 15-39-48](https://user-images.githubusercontent.com/1167259/31295531-e0bdada0-aaac-11e7-9618-73ef22376fa9.png)

cc @jim-minter @ncameronbritt @pmorie 

##### Version

oc v3.7.0-alpha.1+62d9640-936
kubernetes v1.7.6+a08f5eeb62
features: Basic-Auth

Server https://127.0.0.1:8443
openshift v3.7.0-alpha.1+62d9640-936
kubernetes v1.7.6+a08f5eeb62
