### ISSUE TITLE
Add Downward API feature to JenkinsPipeline

### ISSUE THREAD

**Issue by git001** [openshift/origin#16770]
I have tried to use the downward api in the **type: JenkinsPipeline**.  
https://docs.openshift.org/3.6/dev_guide/downward_api.html

```
  strategy:
    jenkinsPipelineStrategy:
      env:
        - name: PROJECT_NAME
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: metadata.namespace
        - name: APP_NAME
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: metadata.name
        - name: GIT_SSL_NO_VERIFY
          value: 'true'
      jenkinsfilePath: Jenkinsfile
    type: JenkinsPipeline
```

##### Version
**oc version**

```
oc v3.6.0+c4dd4cf
kubernetes v1.6.1+5115d708d7
features: Basic-Auth GSSAPI Kerberos SPNEGO

Server https://master.....local:8443
openshift v3.6.0+c4dd4cf
kubernetes v1.6.1+5115d708d7
```
##### Steps To Reproduce

Just use the snipplet above in your jenkins pipeline 

##### Current Result

The environment variables are empty.

##### Expected Result

The environment variables should have the values from the Downward API.
