### ISSUE TITLE
[Question] How to apply config + pull remote images in one step, atomically

### ISSUE THREAD

**Issue by dkarlovi** [openshift/origin#16805]
_(this is a question about using the platform, if it's not appropriate here, apologies in advance, please point me elsewhere)_

If I have a config like this (excerpt, generated with Kompose):

```yaml
# app.yaml
apiVersion: v1
kind: ImageStream
metadata:
    name: app
spec:
    tags:
        -
            from:
                kind: DockerImage
                name: registry.example.com/my/example.com/app:latest
            name: latest
---
apiVersion: v1
kind: DeploymentConfig
metadata:
    name: app
spec:
    replicas: 1
    selector:
        io.kompose.service: app
    strategy:
        type: Recreate
    template:
        metadata:
            labels:
                io.kompose.service: app
        spec:
            containers:
                -
                    imagePullPolicy: Always
                    name: app
            restartPolicy: Always
    triggers:
        -
            type: ConfigChange
        -
            imageChangeParams:
                automatic: true
                containerNames:
                    - app
                from:
                    kind: ImageStreamTag
                    name: app:latest
            type: ImageChange

```

Is there a way for me to make use of both `ImageStream` triggers atomically?

Ie. if I run `oc apply -f app.yaml`, it will recognize the changes in config, but will not pull new images from remote repo (at least for me).

If I run `oc import-image app`, it will pull the image and restart the pods, but obviously no configuration changes can be discovered as I haven't applied the config in the first place.

I can do both sequentially, but if I have both new config and new images, that will cause two consecutive deploys, but what I'd like to do is have one step which will apply config changes (if any), pull images (if new available) and only then trigger the deploy, if required. Is this even possible currently?

TIA.
