### ISSUE TITLE
Extended.[Feature:Builds][Slow] s2i build with environment file in sources Building from a template should create a image from "/tmp/fixture-testdata-dir498136365/test/extended/testdata/test-env-build.json" template and run it in a pod

### ISSUE THREAD

**Issue by bparees** [openshift/origin#16826]
In this failure:
https://ci.openshift.redhat.com/jenkins/job/test_branch_origin_extended_builds/237/testReport/junit/(root)/Extended/_Feature_Builds__Slow__s2i_build_with_environment_file_in_sources__Building_from_a_template_should_create_a_image_from___tmp_fixture_testdata_dir498136365_test_extended_testdata_test_env_build_json__template_and_run_it_in_a_pod__Suite_openshift_/

We created a pod and we can see the pod(build-test-pod) is running+ready:
```
containerStatuses:
    - containerID: docker://a354ab77742fe02e89e3ec055fd58a439c2698995890a7312b3ca975a4696559
      image: docker-registry.default.svc:5000/extended-test-build-sti-env-z6dn8-lt93k/test:latest
      imageID: docker-pullable://docker-registry.default.svc:5000/extended-test-build-sti-env-z6dn8-lt93k/test@sha256:813afa1b836979451450a8fb0919251b5e3968cf885b811524e45dfc1af3456b
      lastState: {}
      name: test
      ready: true
      restartCount: 0
      state:
        running:
          startedAt: 2017-10-12T12:28:04Z
    hostIP: 172.18.10.52
    phase: Running
```

yet we timed out getting an endpoint for the service associated w/ the pod:

```
err = e2e.WaitForEndpoint(oc.KubeFramework().ClientSet, oc.Namespace(), buildTestService)
```

here's the full pod definition:

```
    {
      "kind":"Pod",
      "apiVersion":"v1",
      "metadata":{
        "name":"build-test-pod",
        "labels":{
          "name":"build-test-pod"
        }
      },
      "spec":{
        "containers":[
          {
            "name":"test",
            "image":"${IMAGE_NAME}",
            "readinessProbe": {
              "httpGet": {
                "port": 8080
              }
            }
          }
        ],
        "dnsPolicy":"ClusterFirst"
      }
    }
```

and the service definition:

```
    {
      "kind": "Service",
      "apiVersion":"v1",
      "metadata": {
        "name":"build-test-svc"
      },
      "spec": {
        "ports": [
          {
            "name": "8080-tcp",
            "protocol": "TCP",
            "port": 8080,
            "targetPort": 8080
          }
        ],
        "selector": {
          "name": "build-test-pod"
        }
      }
    }
```

The log from the pod also shows it is running as expected (which is confirmed by the ready+running state of the pod):
```
Oct 12 12:28:58.694: INFO: Running 'oc logs --config=/tmp/extended-test-build-sti-env-z6dn8-lt93k-user.kubeconfig --namespace=extended-test-build-sti-env-z6dn8-lt93k pod/build-test-pod'
Oct 12 12:28:58.966: INFO: Log for pod "build-test-pod"
---->
You might consider adding 'puma' into your Gemfile.
[2017-10-12 12:28:05] INFO  WEBrick 1.3.1
[2017-10-12 12:28:05] INFO  ruby 2.2.2 (2015-04-13) [x86_64-linux]
[2017-10-12 12:28:05] INFO  WEBrick::HTTPServer#start: pid=1 port=8080
<----end of log for "build-test-pod"
```
