### ISSUE TITLE
Templates don't keep 'image:latest' in the statefulset config

### ISSUE THREAD

**Issue by spicysomtam** [openshift/origin#16948]
Templates don't keep 'image:latest' in the statefulset config. Also some oddities on redeploy.

##### Version
3.7.0-alpha.1

##### Steps To Reproduce
1. `oc cluster up`
2. `oc login -u system:admin`
3. `oc new-project app-origin`
4. `oc import-image app-zookeeper:latest --from=docker-registry.local:5000/app-zookeeper:latest --confirm`
5. `oc set image-lookup app-zookeeper`
6. `oc new-app  -p IMAGE=app-zookeeper -p TAG=latest -p RUID=1000060000 -f zoo-no-pvcs.yml`
7. `oc export statefulset/zoo|grep image
image: docker-registry.local:5000/app-zookeeper@sha256:bd5dd80253171e4dffccbea7c639c90a63d5424aa2d7fe655aea766405c83036`
8. Then I have to do a `oc edit statefulset/zoo` to set the image to `app-zookeeper:latest`. Soon after this I see the image change happening, even though the hash on the image has not changed!

-Snippet from the template:

```
- apiVersion: apps/v1beta1 
  kind: StatefulSet 
  metadata:
    name: zoo
  spec:
    updateStrategy:
      type: RollingUpdate
    serviceName: "zk"
    replicas: ${REPLICAS}
    template:
      metadata:
        labels:
          app: zk
        annotations:
          pod.alpha.kubernetes.io/initialized: "true"
          service.alpha.kubernetes.io/tolerate-unready-endpoints: "true"
      spec:
        securityContext:
#         specify a user, to ensure it does not get run as root.
          runAsUser: ${RUID}
        containers:
        - name: zk
          image: ${IMAGE}:${TAG}

parameters:
- description: Number of zookeeper pods (max 5; only 5 pvcs in the template)
  name: REPLICAS
  value: '3'
- description: Zookeeper container image
  name: IMAGE
  value: app-zookeeper
- description: Container run user uid.
  name: RUID
  value: '1000110000'
- description: Image and imagestream tags
  name: TAG
  value: latest
```

##### Current Result
`docker-registry.local:5000/app-zookeeper@sha256:bd5dd80253171e4dffccbea7c639c90a63d5424aa2d7fe655aea766405c83036`

##### Expected Result
`app-zookeeper:latest`

##### Additional Information

If I then retag, it does not redeploy:

```
$ oc tag docker-registry.local:5000/app-zookeeper@sha256:3af7d9edb252108e9b7dc2f1e2f1fc4b999a2445b7415cd7c24c95ccc606837f app-zookeeper:latest
Tag app-zookeeper:latest set to docker-registry.local:5000/app-zookeeper@sha256:3af7d9edb252108e9b7dc2f1e2f1fc4b999a2445b7415cd7c24c95ccc606837f.
```

When I edit the statefulset, I see it has a hash tag again; I edit it back to 'image:latest' and I get a redeploy on the new image.

Maybe I am missing something, or is this a safety feature? It seems on the retag, the hash is added to the statefulset config to prevent a redeploy? If I retag back to the original image hash nothing happens (no redeploy; no update of the statefulset config)?

I understand dc image triggers, but hopefully there will be some good examples of how this works with k8s objects when 3.7 is released? On a dc, on a oc retag there is a new deployment.

Thanks.
