### ISSUE TITLE
Unable to create APB service instance since last service-catalog update

### ISSUE THREAD

**Issue by jmontleon** [openshift/origin#17040]
[provide a description of the issue]

When I walk through the UI to deploy a Postgresql (APB) service instance the UI acts as though the request went through fine, but in the apiserver logs I see:

```
I1026 03:40:03.807745      11 admission.go:166] Fetching serviceclass by class k8s name ""
I1026 03:40:03.807794      11 request.go:606] Error in request: resource name may not be empty
```

Similarly a resource file that previously worked no longer does:

```
apiVersion: servicecatalog.k8s.io/v1beta1
kind: ServiceInstance
metadata:
  name: postgresql
  namespace: default
spec:
  externalClusterServiceClassName: dh-rhscl-postgresql-apb
  externalClusterServicePlanName: prod
  parameters:
    postgresql_database: "admin"
    postgresql_password: "admin"
    postgresql_user: "admin"
    postgresql_version: "9.5"
```

```
$ oc create -f scripts/broker-ci/postgresql.yaml 
Error from server (Forbidden): error when creating "scripts/broker-ci/postgresql.yaml": serviceinstances.servicecatalog.k8s.io "postgresql" is forbidden: resource name may not be empty
```

##### Version
$ docker exec -it origin bash
[root@jmontleo origin]# oc version
oc v3.7.0-alpha.1+598a4ac-1328
kubernetes v1.7.6+a08f5eeb62
features: Basic-Auth GSSAPI Kerberos SPNEGO

Server https://127.0.0.1:8443
openshift v3.7.0-alpha.1+598a4ac-1328
kubernetes v1.7.6+a08f5eeb62

##### Steps To Reproduce
1. oc cluster up --service-catalog=true
2. configure ansible-service-broker
3. attempt to deploy an apb

##### Current Result
errors described above

##### Expected Result
successfully deploys an apb instance
