### ISSUE TITLE
How to enable Initializers?

### ISSUE THREAD

**Issue by karmab** [openshift/origin#17118]
##### Version
oc v3.7.0-alpha.1+fdbd3dc
kubernetes v1.7.0+695f48a16f
features: Basic-Auth GSSAPI Kerberos SPNEGO

Server https://127.0.0.1:8443
openshift v3.7.0-alpha.1+fdbd3dc
kubernetes v1.7.0+695f48a16f

##### Steps To Reproduce
1. deploy openshift
2. try to make use of the initializers functionality

##### Current Result
should work

##### Expected Result
doesnt work

##### Additional Information
understand that i should edit admissionConfig/pluginConfig section in  /var/lib/origin/openshift.local.config/master/master-config.yml
but dont know which data to put there

**Comment by karmab** [comment]
tried with the following snippet but with no luck ( server did start though)

```
kubernetesMasterConfig:
  apiLevels: null
  apiServerArguments:
    storage-backend:
    - etcd3
    storage-media-type:
    - application/vnd.kubernetes.protobuf
    admission-control:
    - Initializers
    - NamespaceLifecycle
    - LimitRanger
    - SecurityContextDeny
    - ServiceAccount
    - ResourceQuota
    runtime-config:
    - admissionregistration.k8s.io/v1alpha1
```
