### ISSUE TITLE
StatefulSet pulls image from docker hub instead of internal registry

### ISSUE THREAD

**Issue by dsfranzi** [openshift/origin#17157]
I'm using Kubernetes 1.5 in OpenShift.
I pushed all my customized docker images to OpenShift's internal registry. When using a DeploymentConfig, everything works fine, kubernetes pulls the right image.

When using a StatefulSet, Kubernetes won't find my docker image in the internal registry and instead pulls an image from docker hub.

My StatefulSet:

```
        spec:
          containers:
            - image: zookeeper:latest
              args:
                - bin/zkServer.sh
                - 'start-foreground'
```

It would work when i put the internal registry URL in front of the image name like this:

`image: 172.30.158.156:5000/<projectname>/zookeeper:latest`

But when I'm working with multiple clusters, this isn't practical (and again, it works with DeploymentConfigs)

##### Version
```
$ oc version
oc v3.6.0+c4dd4cf
kubernetes v1.6.1+5115d708d7
features: Basic-Auth

Server https://master.*********:443
openshift v1.5.0
kubernetes v1.5.2+43a9be4
```

##### Steps To Reproduce
Change a `DeploymentConfig` using an internal image to a `StatefulSet`.

##### Current Result
See description above.
##### Expected Result
I expected the same behavior as with DeploymentConfigs: That kubernetes would pull the image from the internal registry.

**Comment by dsfranzi** [comment]
FYI, i posted this issue at kubernetes first and they think it's an OpenShift issue:
https://github.com/kubernetes/kubernetes/issues/55003

**Comment by smarterclayton** [comment]
`oc set image-lookup` on an image stream called `zookeeper` will make it so that an image stream tag for `zookeeper:latest` will be loaded from the registry when accessed directly in a stateful set, daemonset, deployment, replica set, job, or cronjob.

**Comment by mfojtik** [comment]
@dsfranzi what Clayton suggested, lemme know if that fixes your problem. 

@smarterclayton do we have docs about `oc set image-lookup` ?

**Comment by dsfranzi** [comment]
`oc set image-lookup zookeeper` didn't work, the result of `oc set image-lookup` always stays the same:

```
$ oc set image-lookup
NAME              LOCAL
solr              false
spark             false
spark-ui-proxy    false
zeppelin          false
zookeeper         false
zoonavigator-api  false
zoonavigator-web  false
```

I also tried to delete the ImageStream and redeploy my template with this config (lookupPolicy: local), but still no luck:

```
  # ImageStream
  - apiVersion: v1
    kind: ImageStream
    metadata:
      name: solr
    spec:
      lookupPolicy:
        local: true
      tags:
        - annotations: null
          from:
            kind: DockerImage
            name: 'solr:latest'
          generation: null
          importPolicy: {}
          name: latest
          referencePolicy:
            type: ''
```

P.S.: @mfojtik I think you mentioned this piece of documentation: https://docs.openshift.com/container-platform/3.6/dev_guide/managing_images.html#using-is-with-k8s ?
