### ISSUE TITLE
Error when I whant run a build with as source an "images" input with a "git" input and as strategy, a dockerStrategy : "An error occurred while starting the build.an error on the server ("") has prevented the request from succeeding"

### ISSUE THREAD

**Issue by dylanBehetre** [openshift/origin#17169]
[provide a description of the issue]
Hello, I come here because i don't find any solution to my problem.

I try to retrieve a .war build by a gradle docker image in a precedently build to build an other docker image.
Therefore, after reading your documentation, I tried to use the "images" source in a build config with a docker strategy.

But I cannot run the build because an error occured : "An error occurred while starting the build.an error on the server ("") has prevented the request from succeeding".

This error come only with the "images" source, the "git" source alone work and build.

To build, I import two templates, the first to build the war : 

```
kind: "Template"
apiVersion: "v1"
metadata: 
    name: back-end-docker-build1
objects: 
    # Creation d'une ImageStream pour la sortie du build contenant le .war  
    - 
        kind: "ImageStream"
        apiVersion: "v1"
        metadata: 
            name: "vsphere-view-back-build"
    # Creation du BuildConfig qui va créer l'image Docker contenant le .war à partir du Git
    -
        kind: "BuildConfig"
        apiVersion: "v1"
        metadata:
            name: "vsphere-view-back-build-buildconfig" 
        spec:
            runPolicy: "Serial" 
            triggers: 
                - 
                    type: "ConfigChange"
                - 
                    type: "Generic"
                    generic:
                        secret: "aSecret"
                        allowEnv: true
            source: 
                type: "Git"
                git:
                    uri: "http://my-git/vsphere-view.git"
                sourceSecret:
                    name: "dhe-gitlab-exploitation-basicauth"
                contextDir: "middle-tier/"
            strategy:
                type: "Docker"
                dockerStrategy:
                    pullSecret:
                        name: "userbxxy05"
                    dockerfilePath: "DockerfileToOpenShift1"
                    forcePull: true
                    noCache: true
            output: 
                to:
                    kind: "ImageStreamTag"
                    name: "vsphere-view-back-build:latest"
```

The DockerfileToOpenShift1 if you want : 
```
### STAGE 0: Build ###
# Use an official gradle image as a parent image
FROM userbxxy05:9192/gradle:4.2.1-jdk8-alpine

# Copy all files to build
COPY . . 

# We switch to the 'root' user to build (needed to fix an issue)
USER root

# Let's build the project with gradle
RUN gradle build

```

The second with the don't working build : 
```
kind: "Template"
apiVersion: "v1"
metadata: 
    name: back-end-docker-build2
objects:           
    # Creation d'une ImageStream pour la sortie du build qui contiendra l'image finale du back-end
    - 
        kind: "ImageStream"
        apiVersion: "v1"
        metadata: 
            name: "vsphere-view-back"
    # Creation du BuildConfig qui va créer l'image Docker à partir du Git
    -
        kind: "BuildConfig"
        apiVersion: "v1"
        metadata:
            name: "vsphere-view-back-buildconfig" 
        spec:
            runPolicy: "Serial" 
            triggers: 
                - 
                    type: "imageChange"
                    imageChange:
                        from:
                            kind: "ImageStreamTag"
                            name: "vsphere-view-back-build:latest"
                - 
                    type: "ConfigChange"
            source:
                git:
                    uri: "http://my-git/vsphere-view.git"
                images:
                -
                    from:
                        kind: "ImageStreamTag"
                        name: "vsphere-view-back-build:latest"
                        namespace: management-infra
                    paths:
                    -
                        destinationDir: "middle-tier/build/libs/"
                        sourcePath: "/home/gradle/build/libs/MiddleTier-VSphere.war"
                sourceSecret:
                    name: "dhe-gitlab-exploitation-basicauth"
                contextDir: "middle-tier/"
            strategy:
                type: "Docker"
                dockerStrategy:
                    pullSecret:
                        name: "userbxxy05"
                    dockerfilePath: "DockerfileToOpenShift2"
                    forcePull: true
                    noCache: true
            output: 
                to:
                    kind: "ImageStreamTag"
                    name: "vsphere-view-back:latest"
```

The DockerfileToOpenShift2 if you want : 

```
### STAGE 1: SETUP ###
# Use an official jetty image as a parent image
FROM userbxxy05:9192/jetty:9.4.7-jre8-alpine

# Copy the WAR in the webapps directory
COPY build/libs/MiddleTier-VSphere.war /var/lib/jetty/webapps
```

##### Version
![image](https://user-images.githubusercontent.com/10670549/32379633-5471064a-c0ae-11e7-9272-bc302e8eec7b.png)
