### ISSUE TITLE
[KeystoneIdentityProvider] Obtain Keystone fernet token.

### ISSUE THREAD

**Issue by fisache** [openshift/origin#17254]
[provide a description of the issue]

##### Version
[provide output of the `openshift version` or `oc version` command]
3.6

##### Steps To Reproduce
1. connect to KeystonePasswordIdp on master-config.yml
```yaml
  identityProviders:
  - name: my_keystone_provider
    challenge: true
    login: true
    mappingMethod: claim
    provider:
      apiVersion: v1
      kind: KeystonePasswordIdentityProvider
      url: http://{keystone_ip}:5000/v3
      domainName: default
```
2. Authenticate user in default domain (oc cmd or origin-web-console)
3. cmd 'oc whoami -t', then obtain token (probably kubernetes issued)

##### Current Result
I want to obtain token issued from keystone,
because other services not in openshift but in keystone would use same token with openshift.
Can I receive keystone token on openshift like cmd 'oc whoami -t' ?

##### Expected Result
When login on openshift web console or oc, received token can be used in keystone directly.

Thx :)
