### ISSUE TITLE
Route is not admitted because it conflicts with itself

### ISSUE THREAD

**Issue by smarterclayton** [openshift/origin#17419]
The routers on us-east-1 (3.7) are delayed significantly due to size of routing set.  When I deleted a route and recreated, my routes were marked as already claimed by themselves.  This is wrong.  Possible causes:

1. we have a rogue router that is lagging and competing?
2. we have bad synchronization in one router and it has the old copy of the prometheus route in the map but didn't remove it when it was deleted
3. we have bad logic in the host admitter - we should never block a route from registering itself

It's likely multiple causes are here - all need to be investigated.

Outcome is that the app is completely down because the routers aren't self correcting.

```
  status:
    ingress:
    - conditions:
      - lastTransitionTime: 2017-11-22T01:36:11Z
        message: route prometheus already exposes prometheus-openshift-devops-monitor.1d35.starter-us-east-1.openshiftapps.com
          and is older
        reason: HostAlreadyClaimed
        status: "False"
        type: Admitted
      host: prometheus-openshift-devops-monitor.1d35.starter-us-east-1.openshiftapps.com
      routerName: router
      wildcardPolicy: None
```
