### ISSUE TITLE
`oc get all` shows some resources twice

### ISSUE THREAD

**Issue by tnozicka** [openshift/origin#17446]
```
$ oc version
oc v3.8.0-alpha.0+ff1e190-253
kubernetes v1.8.1+0d5291c
features: Basic-Auth GSSAPI Kerberos SPNEGO

Server https://172.16.20.11:8443
openshift v3.8.0-alpha.0+ff1e190-253-dirty
kubernetes v1.8.1+0d5291c
```

```
oc get all
NAME                DOCKER REPO                     TAGS      UPDATED
imagestreams/test   172.30.228.163:5000/test/test             

NAME                     REVISION   DESIRED   CURRENT   TRIGGERED BY
deploymentconfigs/test   0          1         0         config,image(test:latest)
deploymentconfigs/test   0          1         0         config,image(test:latest)

NAME                DOCKER REPO                     TAGS      UPDATED
imagestreams/test   172.30.228.163:5000/test/test    
```

dc.yaml:
```yaml
kind: "DeploymentConfig"
apiVersion: "apps.openshift.io/v1"
metadata:
  name: "test"
spec:
  replicas: 1
  strategy: 
    type: "Rolling"
#  revisionHistoryLimit: 5 
#  minReadySeconds: 0
  triggers:
  - type: ConfigChange
  - type: ImageChange
    imageChangeParams:
      automatic: true
      containerNames: ["test"]
      from:
        kind: ImageStreamTag
        name: test:latest
  template: 
    metadata:
      labels:
        name: "test"
    spec:
      containers:
        - name: "test"
          image: "test"
          command:
           - sleep
           - "9999999"
      terminationGracePeriodSeconds: 0
```
oc create -f <dc.yaml>

likely related to `apiVersion: "apps.openshift.io/v1"`

the object should be seen in all the groups but we should list from only one of the groups
