### ISSUE TITLE
origin login with openid (keycloak) error

### ISSUE THREAD

**Issue by fisache** [openshift/origin#17505]
origin login with openid (keycloak) error

##### Version
oc v3.6.0+c4dd4cf
kubernetes v1.6.1+5115d708d7

##### Steps To Reproduce
1. Set oauth openid in master-config.yaml

```
  identityProviders:
  - name: keycloak
    challenge: true
    login: true
    mappingMethod: claim
    provider:
      apiVersion: v1
      kind: OpenIDIdentityProvider
      clientID: {clientId}
      clientSecret: {clientSecret}
      claims:
        id:
        - sub
        preferredUsername:
        - preferred_username
        name:
        - name
        email:
        - email
       urls:
          authorize: https://{keycloak}:8443/auth/realms/openshift/protocol/openid-connect/auth
          token: https://{keycloak}:8443/auth/realms/openshift/protocol/openid-connect/token

```

2. oc cluster up
3. access https://{openshift}:8443
4. redirect to keycloak login page
5. login with keycloak user
6. return into openshift portal
7. show _An authentication error occurred._

##### Current Result

when openid login, authentication error ocurred.

##### Expected Result

success login, then show service catalog or project view.

##### Additional Information

openshift and keycloak are installed on aws ec2 in different instance.
clientId and clientSecret copy from keycloak admin console.
using curl, can obtain jwt token from keycloak.

**Comment by wanghaoran1988** [comment]
Could you please paste the error logs here?

**Comment by fisache** [comment]
@wanghaoran1988 
I don't know where I watch origin error.
if tell me how to get error log, I will paste here.
I run openshift on docker.

I did some test oauth github and openid(keycloak).

in case of github,
after github login, redirect to 
_{openshift}/oauth2callback._
then, with result status 302, redirect to 
_/oauth/authorize?client_id=openshift-web-console.._
then, result status 302, redirect to
_/console/oauth.._ with status 200

however, in case of openid(keycloak),
after keycloak login, redirect to 
_{openshift}/oauth2callback._
then, just return status 200 with _An authentication error occurred._ screen.

In this case, is there a possibility that is wrong?

thx.

**Comment by simo5** [comment]
@abstractj could you give us a hand here ?

**Comment by abstractj** [comment]
@simo5 sure thing.

@fisache I'm afraid we need more details to help you. Otherwise it's really hard to tell what's going on. If possible, please provide the following information:

1. Keycloak version
2. The JSON file of your realm. See: http://www.keycloak.org/docs/latest/server_admin/index.html#_export_import
3. Keycloak log files.
4. OC log files like @wanghaoran1988 mentioned. Maybe you can look at https://github.com/openshift/origin/blob/master/docs/debugging-openshift.md

**Comment by fisache** [comment]
@abstractj 
Thanks for your help.

I'm testing on my pc (keycloak port : 8543, origin port : 8443)

the oc log seems to be refused by firewall, but firewall is stopped or using another port?

- Keycloak version
**3.4.0.Final**

- Keycloak log files
Look like nothing relative to this problem(server.log, audit.log).

- OC log files
```
$ docker logs {origin container id}
E1202 05:18:05.863612     513 errorpage.go:30] AuthenticationError: Post https://localhost:8543/auth/realms/openshift/protocol/openid-connect/token: dial tcp [::1]:8543: getsockopt: connection refused
```

- oc mater-config.yaml
```
  identityProviders:
  - name: keycloak
    challenge: false
    login: true
    provider:
      apiVersion: v1
      kind: OpenIDIdentityProvider
      clientID: {client_id}
      clientSecret: {client_secret}
      ca: ca-keycloak.crt
      claims:
        id:
        - sub
        preferredUsername:
        - preferred_username
        name:
        - name
      urls:
        authorize: https://localhost:8543/auth/realms/openshift/protocol/openid-connect/auth
        token: https://localhost:8543/auth/realms/openshift/protocol/openid-connect/token
```

- realm JSON file
https://gist.github.com/fisache/a074b181c9eaf287fae69c1b5bc77883
