### ISSUE TITLE
ingress resources arent' displayed or deleted using oc get/delete all --all

### ISSUE THREAD

**Issue by cmoulliard** [openshift/origin#17632]
When we use the oc client of openshift 3.7, create an Ingress yaml resource such as this one

and push it to the platform, 

```
oc create -f >>
apiVersion: v1
items:
- apiVersion: extensions/v1beta1
  kind: Ingress
  metadata:
    annotations:
      kubernetes.io/ingress.class: istio
    labels:
      app: say-service
    name: say-service
  spec:
    rules:
    - http:
        paths:
        - backend:
            serviceName: say-service
            servicePort: 8080
          path: /say
```

then it is not displayed or deleted using these commands

```
oc get ingress
NAME          HOSTS     ADDRESS        PORTS     AGE
say-service   *         172.29.6.118   80        5h

oc get all
NAME                      TYPE      FROM      LATEST
bc/greeting-service-s2i   Source    Binary    1
bc/say-service-s2i        Source    Binary    10

NAME                            TYPE      FROM      STATUS                       STARTED       DURATION
builds/greeting-service-s2i-1   Source    Binary    Complete                     6 hours ago   2m25s
builds/say-service-s2i-10       Source    Binary    Complete                     4 hours ago   19s

NAME                  DOCKER REPO                                   TAGS            UPDATED
is/alpine             172.30.1.1:5000/demo-istio/alpine             3.5,latest      4 hours ago
is/greeting-service   172.30.1.1:5000/demo-istio/greeting-service   latest          6 hours ago
is/proxy_debug        172.30.1.1:5000/demo-istio/proxy_debug        0.2.12,latest   4 hours ago
is/proxy_init         172.30.1.1:5000/demo-istio/proxy_init         0.2.12,latest   4 hours ago
is/say-service        172.30.1.1:5000/demo-istio/say-service        latest          4 hours ago

NAME                  REVISION   DESIRED   CURRENT   TRIGGERED BY
dc/greeting-service   1          1         1         config,image(greeting-service:latest)
dc/say-service        1          1         1         config,image(enable-core-dump:alpine:3.5),image(istio-init:proxy_init:0.2.12),image(proxy_debug:0.2.12),image(say-service:latest)

NAME                    DESIRED   CURRENT   READY     AGE
rc/greeting-service-1   1         1         1         5h
rc/say-service-1        1         1         1         3h

NAME                      HOST/PORT                                          PATH      SERVICES           PORT      TERMINATION   WILDCARD
routes/greeting-service   greeting-service-demo-istio.192.168.64.26.nip.io             greeting-service   8080                    None

NAME                   CLUSTER-IP       EXTERNAL-IP   PORT(S)    AGE
svc/greeting-service   172.30.152.177   <none>        8080/TCP   5h
svc/say-service        172.30.199.202   <none>        8080/TCP   5h

NAME                              READY     STATUS       RESTARTS   AGE
po/greeting-service-1-plrbn       1/1       Running      1          5h
po/greeting-service-s2i-1-build   0/1       Completed    0          5h
po/say-service-1-gx9db            2/2       Running      2          3h
po/say-service-s2i-10-build       0/1       Completed    0          3h

oc delete all --all
>> Ingress resource is still there
```
