### ISSUE TITLE
LDAPPasswordIdentityProvider  TLS connection failed while OpenLDAP server uses ssf=256.

### ISSUE THREAD

**Issue by mangokingTW** [openshift/origin#17644]
Openshift origin uses ssf=128 for TLS connection and can not be changed to ssf=256.

##### Version
oc v3.6.1+008f2d5
kubernetes v1.6.1+5115d708d7
features: Basic-Auth GSSAPI Kerberos SPNEGO

##### Steps To Reproduce
1. OpenLDAP server and set Security Strength Factors(ssf) to 256 (AES-256). `security ssf=256`
2. Using LDAPPasswordIdentityProvider for identity.
3. `oc login`

##### Current Result
oc response : `error: The server was unable to respond - verify you have provided the correct host and port and that the server is currently running.`
journald : `Error authenticating login "user" with provider "ldap": LDAP Result Code 13 "Confidentiality Required": stronger confidentiality required`

##### Expected Result
Successfully connect to OpenLDAP server over TLS and identify the user.

**Comment by enj** [comment]
Please provide your master config and a minimum reproducer (something like a docker container with the LDAP bits set up).

**Comment by simo5** [comment]
@mangokingTW before providing a reproducer, may I ask why don't you just configure your server to offer only TLS ciphers of your chosing so the client/server negotiation ends up selecting only ciphers you want, rather than letting TLS negotiate any random cpher and then fail to pass the minimum SSF requirement ?

**Comment by mangokingTW** [comment]
@enj My problem is about origin its own identity provider, not about the docker.
And this is the configuration of my LDAPPasswordIdentityProvider:
```
- challenge: true
    login: true
    mappingMethod: claim
    name: myldap
    provider:
      apiVersion: v1
      attributes:
        email:
        - mail
        id:
        - dn
        name:
        - cn
        preferredUsername:
        - uid
      insecure: false
      kind: LDAPPasswordIdentityProvider
      ca: myrootca.crt
      url: ldaps://mydomain.com:636/ou=People,dc=mydomain,dc=com?uid?sub?
```
As much as I know, there is no coloumn for the TLS encryption algorithm.
====
@simo5 
I am trying to make origin negotiate with OpenLDAP server by using AES256, but it's failed.
If I downgrade ssf to 128, it works.
However, I wonder why can't origin use AES256 cipher in this case.
