### ISSUE TITLE
ContainerCannotRun: devmapper: Error activating devmapper device for ''46d82310de547f7f9e3e87d95f6a5af6420fe4b69ea3e1142bfc86486999e0f0'':           devicemapper: Error running deviceCreate (ActivateDevice) dm_task_run failed

### ISSUE THREAD

**Issue by tnozicka** [openshift/origin#17787]
https://openshift-gce-devel.appspot.com/build/origin-ci-test/pr-logs/pull/17751/test_pull_request_origin_extended_conformance_install/4109/

```
  containerStatuses:
  - containerID: docker://b7f14c8009aee731cd5199c9cce74b5b46912ffd0175c26b3ff73f2139a8212b
    image: openshift/origin-deployer:551f02f
    imageID: docker://sha256:ed03e11e54a7b36812b1a76d0f821357f727b59f3fa56fd290efa5a94fd745a6
    lastState: {}
    name: deployment
    ready: false
    restartCount: 0
    state:
      terminated:
        containerID: docker://b7f14c8009aee731cd5199c9cce74b5b46912ffd0175c26b3ff73f2139a8212b
        exitCode: 128
        finishedAt: 2017-12-14T13:59:13Z
        message: 'devmapper: Error activating devmapper device for ''46d82310de547f7f9e3e87d95f6a5af6420fe4b69ea3e1142bfc86486999e0f0'':
          devicemapper: Error running deviceCreate (ActivateDevice) dm_task_run failed'
        reason: ContainerCannotRun
        startedAt: 2017-12-14T13:59:13Z
```
