### ISSUE TITLE
openshift bootstrapPolicyFile is not applied when cluster up

### ISSUE THREAD

**Issue by fisache** [openshift/origin#17823]
[provide a description of the issue]
Create `policy.json` and `bootstrapPolicyFile` in `master-config.yaml`,
however don't create new role when `cluster up`.

##### Version
openshift v3.7.0+7ed6862
kubernetes v1.7.6+a08f5eeb62

##### Steps To Reproduce
1. Create `openshift.local.config/master/policy.json`
2. Add `Cluster Role` in `policy.json`
```

    "kind": "Template",
    "apiVersion": "v1",
    "metadata": {
        "creationTimestamp": null
    },
    "objects": [
        {
            "kind": "ClusterRole",
            "apiVersion": "v1",
            "metadata": {
                "name": "test",
                "creationTimestamp": null
            },
            "rules": [
            ]
        },
    ]
}
```
3. `oc cluster up` and `oc login -u system:admin`
4. `oc get clusterrole`

##### Current Result
Not update my policy.json

##### Expected Result
When get clusterrole, show `test` cluster role.

##### Additional Information
I tried `oadm policy reconcile-cluster-roles`, but not changed.

policyConfig in `master-config.yaml`
```
policyConfig:
  bootstrapPolicyFile: policy.json
  openshiftInfrastructureNamespace: openshift-infra
  openshiftSharedResourcesNamespace: openshift
  userAgentMatchingConfig:
    defaultRejectionMessage: ""
    deniedClients: null
    requiredClients: null

```

I think `bootstrapPolicyFile` means default cluster role and rolebinding.
but although add new cluster role, it's not applied to origin.
