### ISSUE TITLE
BuildConfig `secrets` not available during build

### ISSUE THREAD

**Issue by matthewvalimaki** [openshift/origin#17892]
`secrets` in `BuildConfig` work on build `A` but do not work with build `B` which is a copy of `A` with minor changes. The minor change is merely in the `dockerStrategy` pointing back to `A` in `kind: "ImageStreamTag"`. No matter which secrets I want to expose in build `B` they do not become available. The builder pod does show them as mounts.

I am wondering if build `A` using secrets somehow blocks secrets in the `B`, which again is using `A` as `kind: "ImageStreamTag"`. I have tried changing `destinationDir` but it does not seem to make a difference.

##### Version
```
oc v3.6.1+008f2d5
kubernetes v1.6.1+5115d708d7
```

##### Steps To Reproduce
1. Create two builds with second builds `ImageStreamTag` pointing to the first
2. Expose secrets in both builds
3. Observe that none of the secrets are in the second build

##### Current Result
Secrets are not available during build.

##### Expected Result
Any and all secrets should be accessible during build. In the example yamls below I am expecting to see `ssh-key` secret in `var/www/html/`.

##### Additional Information
Build `A`
```
apiVersion: v1
kind: BuildConfig
metadata:
  name: a
  namespace: development
spec:
  triggers:
    - imageChange:
      from:
        kind: "ImageStreamTag"
        name: "base:latest"
      type: ImageChange
  output:
    to:
      kind: "ImageStreamTag"
      name: "a:latest"
  strategy:
    dockerStrategy:
      noCache: true
      from:
        kind: "ImageStreamTag"
        name: "base:latest"
      dockerfilePath: Dockerfile
  source:
    secrets:
      - secret:
          name: ssh-key
          destinationDir: var/www/html
    sourceSecret:
      name: ssh-key
    git:
      uri: "git@git-server:development/project.git" 
```

Build `B`
```
apiVersion: v1
kind: BuildConfig
metadata:
  name: b
  namespace: development
spec:
  triggers:
    - imageChange:
      from:
        kind: "ImageStreamTag"
        name: "a:latest"
      type: ImageChange
  output:
    to:
      kind: "ImageStreamTag"
      name: "b:latest"
  strategy:
    dockerStrategy:
      noCache: true
      from:
        kind: "ImageStreamTag"
        name: "a:latest"
      dockerfilePath: Dockerfile
  source:
    secrets:
      - secret:
          name: ssh-key
          destinationDir: var/www/html
    sourceSecret:
      name: ssh-key
    git:
      uri: "git@git-server:development/additional-things.git" 
```
