### ISSUE TITLE
Processes unavailable by service: port

### ISSUE THREAD

**Issue by eivantsov** [openshift/origin#17981]
### Description
Can not access to container port via service on local OCP. 

### Reproduction Steps

1. Run a local OCP (oc cluster up) or MiniShift
2. Create the following objects via OCP console:
  - Create a project;
  - Click `Add to Project`
  - Click `Import YAML/JSON`
  - Paste the following YAML and click `Create`

<details>
<summary>Objects to import</summary>

```yaml
---
kind: List
items:
-
  apiVersion: v1
  kind: Pod
  metadata:
    name: tomcat-pod
    labels:
      app: tomcat
  spec:
    containers:
      -
        image: sleshchenko/webapp
        name: tomcat-container
        ports:
          -
            containerPort: 8080
            protocol: TCP
      -
        image: eclipse/ubuntu_jdk8
        name: requester
-
  apiVersion: v1
  kind: Service
  metadata:
    name: tomcat
  spec:
    ports:
      - name: tomcat
        port: 8080
        protocol: TCP
        targetPort: 8080
    selector:
      app: tomcat
```
</details>

3. Open terminal in the newly created pod in `requester` container.
4. Try to access tomcat via service. Execute `curl tomcat:8080`
Expected: Response `HELLO`
Actual: Request hung up.

Note that it works fine on our OSD and OSO too.

Note that it works fine if containers are in separated pods.
<details>
<summary>Containers in separate pods</summary>

```yaml
---
kind: List
items:
-
  apiVersion: v1
  kind: Pod
  metadata:
    name: tomcat-pod
    labels:
      app: tomcat
  spec:
    containers:
      -
        image: sleshchenko/webapp
        name: tomcat-container
        ports:
          -
            containerPort: 8080
            protocol: TCP
-
  apiVersion: v1
  kind: Pod
  metadata:
    name: requester
  spec:
    containers:
      -
        image: eclipse/ubuntu_jdk8
        name: requester
-
  apiVersion: v1
  kind: Service
  metadata:
    name: tomcat
  spec:
    ports:
      - name: tomcat
        port: 8080
        protocol: TCP
        targetPort: 8080
    selector:
      app: tomcat
```
</details>

**OCP version:**    
3.7.0

Fedora 27. Firewalld is off.

The process is unavailable even when there's just one pod. Say I run tomcat on port 8080, and can curl it from inside a container as `localhost:8080` but not `tomcat:8080`
