### ISSUE TITLE
How to configure storage capability unit

### ISSUE THREAD

**Issue by lanliu99** [openshift/origin#18041]
##### Version
ocp 3.7

##### Steps To Reproduce
1. configure pv like this:
```yaml
apiVersion: v1
kind: PersistentVolume
metadata:
  name: mysqldb-volume3
spec:
  capacity:
    storage: 1Gi
  accessModes:
  - ReadWriteOnce
  hostPath:
    path: /root/mypv3
```

##### Current Result
pv can be created.

##### Expected Result
I need to change 1Gi to 500m, or 1.1Gi, does it work? and if different unit is used(Gi vs. m) in pv and pvc, does openshift know how to match them?

##### Additional Information
Just did some simple tests, seems didn't work, but I want to make sure openshift support this feature, then I will test again further.
