### ISSUE TITLE
Lots of etcd errors in origin-master-api logs after upgrading to 3.7

### ISSUE THREAD

**Issue by jfchevrette** [openshift/origin#18123]
After upgrading from 3.5->3.6->3.7 I am getting a lot of etcd errors/warnings in the apiserver log.

etcd data was ugpraded from v2 to v3 as instructed by the documentation.

The cluster itself appear to be working fine but it looks like the api server is having trouble setting up watches.

This is a 5-nodes cluster, 3 masters, standalone 3-nodes etcd cluster (on the master nodes)

154 projects
303 pods

```
etcd-3.2.9-3.el7.x86_64
origin-3.7.0-1.0.7ed6862.x86_64
origin-clients-3.7.0-1.0.7ed6862.x86_64
origin-docker-excluder-3.7.0-1.0.7ed6862.noarch
origin-excluder-3.7.0-1.0.7ed6862.noarch
origin-master-3.7.0-1.0.7ed6862.x86_64
origin-node-3.7.0-1.0.7ed6862.x86_64
origin-sdn-ovs-3.7.0-1.0.7ed6862.x86_64
```

```
atomic-openshift-master-api[66261]: E0116 09:25:14.197820   66261 watcher.go:210] watch chan error: etcdserver: mvcc: required revision has been compacted
atomic-openshift-master-api[66261]: E0116 09:25:34.330559   66261 watcher.go:210] watch chan error: etcdserver: mvcc: required revision has been compacted
atomic-openshift-master-api[66261]: E0116 09:25:54.463933   66261 watcher.go:210] watch chan error: etcdserver: mvcc: required revision has been compacted
atomic-openshift-master-api[66261]: E0116 09:26:13.559825   66261 watcher.go:210] watch chan error: etcdserver: mvcc: required revision has been compacted
atomic-openshift-master-api[66261]: W0116 09:26:13.560116   66261 reflector.go:343] github.com/openshift/origin/pkg/security/generated/informers/internalversion/factory.go:45: watch of *security.SecurityContextConstraints ended with: etcdserver: mvcc: required revision has been compacted
atomic-openshift-master-api[66261]: E0116 09:26:14.495962   66261 watcher.go:210] watch chan error: etcdserver: mvcc: required revision has been compacted
atomic-openshift-master-api[66261]: E0116 09:26:34.626900   66261 watcher.go:210] watch chan error: etcdserver: mvcc: required revision has been compacted
atomic-openshift-master-api[66261]: E0116 09:26:37.565374   66261 watcher.go:210] watch chan error: etcdserver: mvcc: required revision has been compacted
atomic-openshift-master-api[66261]: W0116 09:26:37.565692   66261 reflector.go:343] github.com/openshift/origin/vendor/k8s.io/kubernetes/pkg/client/informers/informers_generated/internalversion/factory.go:72: watch of *rbac.ClusterRoleBinding ended with: etcdserver: mvcc: required revision has been compacted
atomic-openshift-master-api[66261]: E0116 09:26:54.757139   66261 watcher.go:210] watch chan error: etcdserver: mvcc: required revision has been compacted
atomic-openshift-master-api[66261]: E0116 09:27:09.534030   66261 watcher.go:210] watch chan error: etcdserver: mvcc: required revision has been compacted
atomic-openshift-master-api[66261]: W0116 09:27:09.534363   66261 reflector.go:343] github.com/openshift/origin/vendor/k8s.io/apiextensions-apiserver/pkg/client/informers/internalversion/factory.go:61: watch of *apiextensions.CustomResourceDefinition ended with: etcdserver: mvcc: required revision has been compacted
atomic-openshift-master-api[66261]: E0116 09:27:10.563035   66261 watcher.go:210] watch chan error: etcdserver: mvcc: required revision has been compacted
atomic-openshift-master-api[66261]: W0116 09:27:10.563363   66261 reflector.go:343] github.com/openshift/origin/vendor/k8s.io/kubernetes/pkg/client/informers/informers_generated/internalversion/factory.go:72: watch of *api.LimitRange ended with: etcdserver: mvcc: required revision has been compacted
atomic-openshift-master-api[66261]: E0116 09:27:14.887981   66261 watcher.go:210] watch chan error: etcdserver: mvcc: required revision has been compacted
atomic-openshift-master-api[66261]: E0116 09:27:27.495149   66261 watcher.go:210] watch chan error: etcdserver: mvcc: required revision has been compacted
atomic-openshift-master-api[66261]: W0116 09:27:27.495375   66261 reflector.go:343] github.com/openshift/origin/vendor/k8s.io/kubernetes/pkg/client/informers/informers_generated/internalversion/factory.go:72: watch of *rbac.Role ended with: etcdserver: mvcc: required revision has been compacted
atomic-openshift-master-api[66261]: E0116 09:27:35.023735   66261 watcher.go:210] watch chan error: etcdserver: mvcc: required revision has been compacted
atomic-openshift-master-api[66261]: E0116 09:27:39.616202   66261 watcher.go:210] watch chan error: etcdserver: mvcc: required revision has been compacted
atomic-openshift-master-api[66261]: W0116 09:27:39.616600   66261 reflector.go:343] github.com/openshift/origin/vendor/k8s.io/kubernetes/pkg/client/informers/informers_generated/internalversion/factory.go:72: watch of *rbac.RoleBinding ended with: etcdserver: mvcc: required revision has been compacted
atomic-openshift-master-api[66261]: E0116 09:27:42.520463   66261 watcher.go:210] watch chan error: etcdserver: mvcc: required revision has been compacted
atomic-openshift-master-api[66261]: W0116 09:27:42.520750   66261 reflector.go:343] github.com/openshift/origin/vendor/k8s.io/client-go/informers/factory.go:72: watch of *v1.Namespace ended with: etcdserver: mvcc: required revision has been compacted
atomic-openshift-master-api[66261]: E0116 09:27:55.158288   66261 watcher.go:210] watch chan error: etcdserver: mvcc: required revision has been compacted
atomic-openshift-master-api[66261]: E0116 09:28:15.190568   66261 watcher.go:210] watch chan error: etcdserver: mvcc: required revision has been compacted
atomic-openshift-master-api[66261]: E0116 09:28:29.776341   66261 watcher.go:210] watch chan error: etcdserver: mvcc: required revision has been compacted
atomic-openshift-master-api[66261]: W0116 09:28:29.776675   66261 reflector.go:343] github.com/openshift/origin/vendor/k8s.io/kubernetes/pkg/client/informers/informers_generated/internalversion/factory.go:72: watch of *api.Secret ended with: etcdserver: mvcc: required revision has been compacted
atomic-openshift-master-api[66261]: E0116 09:28:31.579169   66261 watcher.go:210] watch chan error: etcdserver: mvcc: required revision has been compacted
atomic-openshift-master-api[66261]: W0116 09:28:31.579556   66261 reflector.go:343] github.com/openshift/origin/pkg/image/generated/informers/internalversion/factory.go:45: watch of *image.ImageStream ended with: etcdserver: mvcc: required revision has been compacted
atomic-openshift-master-api[66261]: E0116 09:28:35.324080   66261 watcher.go:210] watch chan error: etcdserver: mvcc: required revision has been compacted
atomic-openshift-master-api[66261]: E0116 09:28:36.493798   66261 watcher.go:210] watch chan error: etcdserver: mvcc: required revision has been compacted
atomic-openshift-master-api[66261]: W0116 09:28:36.494200   66261 reflector.go:343] github.com/openshift/origin/vendor/k8s.io/kubernetes/pkg/client/informers/informers_generated/internalversion/factory.go:72: watch of *extensions.ThirdPartyResource ended with: etcdserver: mvcc: required revision has been compacted
atomic-openshift-master-api[66261]: E0116 09:28:44.506455   66261 watcher.go:210] watch chan error: etcdserver: mvcc: required revision has been compacted
atomic-openshift-master-api[66261]: W0116 09:28:44.506789   66261 reflector.go:343] github.com/openshift/origin/pkg/quota/generated/informers/internalversion/factory.go:45: watch of *quota.ClusterResourceQuota ended with: etcdserver: mvcc: required revision has been compacted
atomic-openshift-master-api[66261]: E0116 09:28:49.546091   66261 watcher.go:210] watch chan error: etcdserver: mvcc: required revision has been compacted
atomic-openshift-master-api[66261]: W0116 09:28:49.546387   66261 reflector.go:343] github.com/openshift/origin/pkg/user/generated/informers/internalversion/factory.go:45: watch of *user.Group ended with: etcdserver: mvcc: required revision has been compacted
atomic-openshift-master-api[66261]: E0116 09:28:53.536046   66261 watcher.go:210] watch chan error: etcdserver: mvcc: required revision has been compacted
atomic-openshift-master-api[66261]: W0116 09:28:53.536324   66261 reflector.go:343] github.com/openshift/origin/vendor/k8s.io/kubernetes/pkg/client/informers/informers_generated/internalversion/factory.go:72: watch of *api.PersistentVolume ended with: etcdserver: mvcc: required revision has been compacted
atomic-openshift-master-api[66261]: E0116 09:28:55.455226   66261 watcher.go:210] watch chan error: etcdserver: mvcc: required revision has been compacted
atomic-openshift-master-api[66261]: E0116 09:29:15.492205   66261 watcher.go:210] watch chan error: etcdserver: mvcc: required revision has been compacted
atomic-openshift-master-api[66261]: E0116 09:29:26.290268   66261 watcher.go:210] watch chan error: etcdserver: mvcc: required revision has been compacted
atomic-openshift-master-api[66261]: E0116 09:29:27.392186   66261 watcher.go:210] watch chan error: etcdserver: mvcc: required revision has been compacted
atomic-openshift-master-api[66261]: E0116 09:29:28.512307   66261 watcher.go:210] watch chan error: etcdserver: mvcc: required revision has been compacted
atomic-openshift-master-api[66261]: E0116 09:29:35.523397   66261 watcher.go:210] watch chan error: etcdserver: mvcc: required revision has been compacted
atomic-openshift-master-api[66261]: E0116 09:29:55.561162   66261 watcher.go:210] watch chan error: etcdserver: mvcc: required revision has been compacted
atomic-openshift-master-api[66261]: E0116 09:30:02.561564   66261 watcher.go:210] watch chan error: etcdserver: mvcc: required revision has been compacted
atomic-openshift-master-api[66261]: W0116 09:30:02.561834   66261 reflector.go:343] github.com/openshift/origin/vendor/k8s.io/kubernetes/pkg/client/informers/informers_generated/internalversion/factory.go:72: watch of *rbac.ClusterRole ended with: etcdserver: mvcc: required revision has been compacted
```

And seeing hundreds of these per minute
```
atomic-openshift-master-api[66261]: W0116 09:31:25.736235   66261 watcher.go:358] Fast watcher, slow processing. Number of buffered events: 100.Probably caused by slow decoding, user not receiving fast, or other processing logic

atomic-openshift-master-api[66261]: W0116 09:31:25.737485   66261 watcher.go:238] Fast watcher, slow processing. Number of buffered events: 100.Probably caused by slow dispatching events to watchers
```

/etc/origin/master/master-config.yaml
```
ggsadmissionConfig:
  pluginConfig:
    BuildDefaults:
      configuration:
        apiVersion: v1
        env: []
        kind: BuildDefaultsConfig
        resources:
          limits: {}
          requests: {}
    BuildOverrides:
      configuration:
        apiVersion: v1
        kind: BuildOverridesConfig
    openshift.io/ImagePolicy:
      configuration:
        apiVersion: v1
        executionRules:
        - matchImageAnnotations:
          - key: images.openshift.io/deny-execution
            value: 'true'
          name: execution-denied
          onResources:
          - resource: pods
          - resource: builds
          reject: true
          skipOnResolutionFailure: true
        kind: ImagePolicyConfig
  pluginOrderOverride:
apiLevels:
- v1
apiVersion: v1
assetConfig:
  logoutURL: ""
  masterPublicURL: https://dev.REDACTED.com:8443
  publicURL: https://dev.REDACTED.com:8443/console/
  servingInfo:
    bindAddress: 0.0.0.0:8443
    bindNetwork: tcp4
    certFile: master.server.crt
    clientCA: ""
    keyFile: master.server.key
    maxRequestsInFlight: 0
    requestTimeoutSeconds: 0
controllerConfig:
  election:
    lockName: openshift-master-controllers
  serviceServingCert:
    signer:
      certFile: service-signer.crt
      keyFile: service-signer.key
controllerLeaseTTL: 30
controllers: '*'
corsAllowedOrigins:
- 127.0.0.1
- localhost
- kubernetes.default
- kubernetes.default.svc.cluster.local
- kubernetes
- openshift.default
- openshift.default.svc
- openshift.default.svc.cluster.local
- kubernetes.default.svc
- openshift
- dev.REDACTED.com
- 192.168.173.22
- n22.c1.REDACTED.com
- 192.168.173.23
- n23.c1.REDACTED.com
- 192.168.173.24
- n24.c1.REDACTED.com
dnsConfig:
  bindAddress: 0.0.0.0:8053
  bindNetwork: tcp4
etcdClientInfo:
  ca: master.etcd-ca.crt
  certFile: master.etcd-client.crt
  keyFile: master.etcd-client.key
  urls:
  - https://n22.c1.REDACTED.com:2379
  - https://n23.c1.REDACTED.com:2379
  - https://n24.c1.REDACTED.com:2379
etcdStorageConfig:
  kubernetesStoragePrefix: kubernetes.io
  kubernetesStorageVersion: v1
  openShiftStoragePrefix: openshift.io
  openShiftStorageVersion: v1
imageConfig:
  format: openshift/origin-${component}:${version}
  latest: false
kind: MasterConfig
kubeletClientInfo:
  ca: ca-bundle.crt
  certFile: master.kubelet-client.crt
  keyFile: master.kubelet-client.key
  port: 10250
kubernetesMasterConfig:
  admissionConfig:
  apiServerArguments:
    storage-backend:
    - etcd3
    storage-media-type:
    - application/vnd.kubernetes.protobuf
  controllerArguments:
  masterCount: 3
  masterIP: 192.168.173.24
  podEvictionTimeout:
  proxyClientInfo:
    certFile: master.proxy-client.crt
    keyFile: master.proxy-client.key
  schedulerArguments:
  schedulerConfigFile: /etc/origin/master/scheduler.json
  servicesNodePortRange: ""
  servicesSubnet: 172.30.0.0/16
  staticNodeNames: []
masterClients:
  externalKubernetesClientConnectionOverrides:
    acceptContentTypes: application/vnd.kubernetes.protobuf,application/json
    burst: 400
    contentType: application/vnd.kubernetes.protobuf
    qps: 200
  externalKubernetesKubeConfig: ""
  openshiftLoopbackClientConnectionOverrides:
    acceptContentTypes: application/vnd.kubernetes.protobuf,application/json
    burst: 600
    contentType: application/vnd.kubernetes.protobuf
    qps: 300
  openshiftLoopbackKubeConfig: openshift-master.kubeconfig
masterPublicURL: https://dev.REDACTED.com:8443
networkConfig:
  clusterNetworkCIDR: 10.1.0.0/16
  externalIPNetworkCIDRs:
  - 0.0.0.0/0
  hostSubnetLength: 8
  networkPluginName: redhat/openshift-ovs-subnet
  serviceNetworkCIDR: 172.30.0.0/16
oauthConfig:
  assetPublicURL: https://dev.REDACTED.com:8443/console/
  grantConfig:
    method: auto
  identityProviders:
  - challenge: true
    login: true
    mappingMethod: claim
    name: htpasswd
    provider:
      apiVersion: v1
      file: /etc/origin/master/users.htpasswd
      kind: HTPasswdPasswordIdentityProvider
  masterCA: ca-bundle.crt
  masterPublicURL: https://dev.REDACTED.com:8443
  masterURL: https://n24.c1.REDACTED.com:8443
  sessionConfig:
    sessionMaxAgeSeconds: 3600
    sessionName: ssn
    sessionSecretsFile: /etc/origin/master/session-secrets.yaml
  tokenConfig:
    accessTokenMaxAgeSeconds: 86400
    authorizeTokenMaxAgeSeconds: 500
pauseControllers: false
policyConfig:
  bootstrapPolicyFile: /etc/origin/master/policy.json
  openshiftInfrastructureNamespace: openshift-infra
  openshiftSharedResourcesNamespace: openshift
projectConfig:
  defaultNodeSelector: ""
  projectRequestMessage: ""
  projectRequestTemplate: ""
  securityAllocator:
    mcsAllocatorRange: s0:/2
    mcsLabelsPerProject: 5
    uidAllocatorRange: 1000000000-1999999999/10000
routingConfig:
  subdomain: dev.REDACTED.com
serviceAccountConfig:
  limitSecretReferences: false
  managedNames:
  - default
  - builder
  - deployer
  masterCA: ca-bundle.crt
  privateKeyFile: serviceaccounts.private.key
  publicKeyFiles:
  - serviceaccounts.public.key
servingInfo:
  bindAddress: 0.0.0.0:8443
  bindNetwork: tcp4
  certFile: master.server.crt
  clientCA: ca.crt
  keyFile: master.server.key
  maxRequestsInFlight: 500
  requestTimeoutSeconds: 3600
volumeConfig:
  dynamicProvisioningEnabled: true
```

/etc/etcd/etcd.conf
```
ETCD_NAME=n24.c1.REDACTED.com
ETCD_LISTEN_PEER_URLS=https://192.168.173.24:2380
ETCD_DATA_DIR=/var/lib/etcd/
#ETCD_WAL_DIR=""
#ETCD_SNAPSHOT_COUNT=10000
ETCD_HEARTBEAT_INTERVAL=500
ETCD_ELECTION_TIMEOUT=2500
ETCD_LISTEN_CLIENT_URLS=https://192.168.173.24:2379
#ETCD_MAX_SNAPSHOTS=5
#ETCD_MAX_WALS=5
#ETCD_CORS=


#[cluster]
ETCD_INITIAL_ADVERTISE_PEER_URLS=https://192.168.173.24:2380
ETCD_INITIAL_CLUSTER=n22.c1.REDACTED.com=https://192.168.173.22:2380,n23.c1.REDACTED.com=https://192.168.173.23:2380,n24.c1.REDACTED.com=https://192.168.173.24:2380
ETCD_INITIAL_CLUSTER_STATE=existing
ETCD_INITIAL_CLUSTER_TOKEN=etcd-cluster-1
#ETCD_DISCOVERY=
#ETCD_DISCOVERY_SRV=
#ETCD_DISCOVERY_FALLBACK=proxy
#ETCD_DISCOVERY_PROXY=
ETCD_ADVERTISE_CLIENT_URLS=https://192.168.173.24:2379
#ETCD_STRICT_RECONFIG_CHECK="false"
#ETCD_AUTO_COMPACTION_RETENTION="0"
#ETCD_ENABLE_V2="true"
ETCD_QUOTA_BACKEND_BYTES=4294967296

#[proxy]
#ETCD_PROXY=off
#ETCD_PROXY_FAILURE_WAIT="5000"
#ETCD_PROXY_REFRESH_INTERVAL="30000"
#ETCD_PROXY_DIAL_TIMEOUT="1000"
#ETCD_PROXY_WRITE_TIMEOUT="5000"
#ETCD_PROXY_READ_TIMEOUT="0"

#[security]
ETCD_TRUSTED_CA_FILE=/etc/etcd/ca.crt
ETCD_CLIENT_CERT_AUTH="true"
ETCD_CERT_FILE=/etc/etcd/server.crt
ETCD_KEY_FILE=/etc/etcd/server.key
#ETCD_AUTO_TLS="false"
ETCD_PEER_TRUSTED_CA_FILE=/etc/etcd/ca.crt
ETCD_PEER_CLIENT_CERT_AUTH="true"
ETCD_PEER_CERT_FILE=/etc/etcd/peer.crt
ETCD_PEER_KEY_FILE=/etc/etcd/peer.key
#ETCD_PEER_AUTO_TLS="false"

#[logging]
ETCD_DEBUG="False"

#[profiling]
#ETCD_ENABLE_PPROF="false"
#ETCD_METRICS="basic"
#
#[auth]
#ETCD_AUTH_TOKEN="simple"
```
