### ISSUE TITLE
DeploymentConfig behaviour change from 3.6 to 3.7

### ISSUE THREAD

**Issue by mojsha** [openshift/origin#18406]
In 3.6, using F-M-P which updates the both the container image reference and the image trigger reference, there was no automatic re-deployment when trigger is set to automatic false.

In 3.7, it seems like an update to the container image reference automatically re-deploys. 

This breaks our workflow. 

##### Version
oc v3.7.0+7ed6862
kubernetes v1.7.6+a08f5eeb62
features: Basic-Auth

openshift v3.7.0+7ed6862
kubernetes v1.7.6+a08f5eeb62

##### Steps To Reproduce
3.7:
1. Create a DC and deploy it using the rollout command.
2. Update the image container reference and redeploy.  

3.6:
1. Create a DC and deploy it using the rollout command.
2. Update the image container reference and redeploy.

##### Current Result
3.7:
It will trigger a deployment.
3.6:
Nothing will happen. 

##### Expected Result
3.7:
Nothing should happen (as in 3.6) until a manual rollout command has been executed. 

@soltysh @mfojtik @bparees

**Comment by bparees** [comment]
starting as a p1 because it's a regression/change in behavior (possibly intentional and justifiable)

**Comment by bparees** [comment]
(if anything it sounds like the 3.6 behavior was broken, so perhaps this was a bug fix in 3.7)

**Comment by mojsha** [comment]
@bparees From my perspective, a change in the DC - any change - should _only_ be triggered if there is a ConfigChange trigger. That is, after all, why we have the ConfigChange trigger. 

If anything else in the DC is changed, it does not re-deploy. So if this is intentional behaviour, it would effectively amount to an implicit/hidden trigger on the container image reference being introduced. 

@LarsMilland

**Comment by mojsha** [comment]
Ok, after further analysis I can see that F-M-P is doing a PUT which triggers the re-deploy. 

If I do a PATCH with the same content and change the container image reference, it does not seem to trigger a re-deploy.

**Comment by kargakis** [comment]
What is FMP?

**Comment by mojsha** [comment]
@kargakis Sorry, I thought it was a known abbreviation/acronym... it stands for Fabric8 Maven Plugin.

**Comment by kargakis** [comment]
Can you post the DC before and after doing a PUT and before and after doing a PATCH?

cc @tnozicka

**Comment by tnozicka** [comment]
That what I was going to ask, please always provide the DC's YAML and exact steps to reproduce (ideally commands) - it will save us time when trying to understand and resolve the issue.

**Comment by mojsha** [comment]
Ok, I think I was wrong about the PUT vs PATCH thing.  The behaviour is the same regardless. 

But I will try to provide all the steps with a higher level of detail:
I use a disabled (automatic = false) ImageTrigger in order to be able to refer to images using the ImageStream tags, so the "before" is going to be the state after which it has been rolled out and the container image resolved. 

**Before PUT / PATCH:**
```
apiVersion: v1
kind: DeploymentConfig
metadata:
  annotations:
    fabric8.io/git-branch: master
    fabric8.io/git-commit: 321aca8e89fa7c173def57e078e24c433b413c3a
    fabric8.io/scm-tag: HEAD
    fabric8.io/scm-url: https://github.com/spring-projects/spring-boot/spring-boot-starter-parent/demo
  creationTimestamp: null
  generation: 1
  name: demo
spec:
  replicas: 1
  revisionHistoryLimit: 2
  selector:
    group: test.eu
    project: demo
    provider: fabric8
  strategy:
    activeDeadlineSeconds: 21600
    resources: {}
    rollingParams:
      intervalSeconds: 1
      maxSurge: 25%
      maxUnavailable: 25%
      timeoutSeconds: 3600
      updatePeriodSeconds: 1
    type: Rolling
  template:
    metadata:
      annotations:
        fabric8.io/git-branch: master
        fabric8.io/git-commit: 321aca8e89fa7c173def57e078e24c433b413c3a
        fabric8.io/scm-tag: HEAD
        fabric8.io/scm-url: https://github.com/spring-projects/spring-boot/spring-boot-starter-parent/demo
      creationTimestamp: null
      labels:
        group: test.eu
        project: demo
        provider: fabric8
    spec:
      containers:
      - args:
        - /usr/local/s2i/run
        image: 172.30.251.31:5000/fabric8test/demo@sha256:b49793e3c286cbd491a4790bca06c4ea8a805568df1e75b8bd075cd3e298fe5c
        imagePullPolicy: Always
        livenessProbe:
          failureThreshold: 3
          httpGet:
            path: /health
            port: 8081
            scheme: HTTP
          initialDelaySeconds: 180
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 1
        name: demo
        ports:
        - containerPort: 8443
          name: https
          protocol: TCP
        readinessProbe:
          failureThreshold: 3
          httpGet:
            path: /health
            port: 8081
            scheme: HTTP
          initialDelaySeconds: 10
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 1
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /sample
          name: sample
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
      volumes:
      - emptyDir: {}
        name: sample
  test: false
  triggers:
  - imageChangeParams:
      containerNames:
      - demo
      from:
        kind: ImageStreamTag
        name: demo:1.0.37-Stable-Release
        namespace: fabric8test
    type: ImageChange
status:
  availableReplicas: 0
  latestVersion: 0
  observedGeneration: 0
  replicas: 0
  unavailableReplicas: 0
  updatedReplicas: 0
```

**After PUT (using F-M-P)**
```
apiVersion: v1
kind: DeploymentConfig
metadata:
  annotations:
    fabric8.io/git-branch: master
    fabric8.io/git-commit: 321aca8e89fa7c173def57e078e24c433b413c3a
    fabric8.io/scm-tag: HEAD
    fabric8.io/scm-url: https://github.com/spring-projects/spring-boot/spring-boot-starter-parent/demo
  creationTimestamp: null
  generation: 1
  name: demo
spec:
  replicas: 1
  revisionHistoryLimit: 2
  selector:
    group: test.eu
    project: demo
    provider: fabric8
  strategy:
    activeDeadlineSeconds: 21600
    resources: {}
    rollingParams:
      intervalSeconds: 1
      maxSurge: 25%
      maxUnavailable: 25%
      timeoutSeconds: 3600
      updatePeriodSeconds: 1
    type: Rolling
  template:
    metadata:
      annotations:
        fabric8.io/git-branch: master
        fabric8.io/git-commit: 321aca8e89fa7c173def57e078e24c433b413c3a
        fabric8.io/scm-tag: HEAD
        fabric8.io/scm-url: https://github.com/spring-projects/spring-boot/spring-boot-starter-parent/demo
      creationTimestamp: null
      labels:
        group: test.eu
        project: demo
        provider: fabric8
    spec:
      containers:
      - args:
        - /usr/local/s2i/run
        image: fabric8test/demo:1.0.38-Stable-Release
        imagePullPolicy: Always
        livenessProbe:
          failureThreshold: 3
          httpGet:
            path: /health
            port: 8081
            scheme: HTTP
          initialDelaySeconds: 180
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 1
        name: demo
        ports:
        - containerPort: 8443
          name: https
          protocol: TCP
        readinessProbe:
          failureThreshold: 3
          httpGet:
            path: /health
            port: 8081
            scheme: HTTP
          initialDelaySeconds: 10
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 1
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /sample
          name: sample
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
      volumes:
      - emptyDir: {}
        name: sample
  test: false
  triggers:
  - imageChangeParams:
      containerNames:
      - demo
      from:
        kind: ImageStreamTag
        name: demo:1.0.38-Stable-Release
        namespace: fabric8test
    type: ImageChange
status:
  availableReplicas: 0
  latestVersion: 0
  observedGeneration: 0
  replicas: 0
  unavailableReplicas: 0
  updatedReplicas: 0
```

**After PATCH**
```
apiVersion: v1
kind: DeploymentConfig
metadata:
  annotations:
    fabric8.io/git-branch: master
    fabric8.io/git-commit: 321aca8e89fa7c173def57e078e24c433b413c3a
    fabric8.io/scm-tag: HEAD
    fabric8.io/scm-url: https://github.com/spring-projects/spring-boot/spring-boot-starter-parent/demo
  creationTimestamp: null
  generation: 1
  name: demo
spec:
  replicas: 1
  revisionHistoryLimit: 2
  selector:
    group: test.eu
    project: demo
    provider: fabric8
  strategy:
    activeDeadlineSeconds: 21600
    resources: {}
    rollingParams:
      intervalSeconds: 1
      maxSurge: 25%
      maxUnavailable: 25%
      timeoutSeconds: 3600
      updatePeriodSeconds: 1
    type: Rolling
  template:
    metadata:
      annotations:
        fabric8.io/git-branch: master
        fabric8.io/git-commit: 321aca8e89fa7c173def57e078e24c433b413c3a
        fabric8.io/scm-tag: HEAD
        fabric8.io/scm-url: https://github.com/spring-projects/spring-boot/spring-boot-starter-parent/demo
      creationTimestamp: null
      labels:
        group: test.eu
        project: demo
        provider: fabric8
    spec:
      containers:
      - args:
        - /usr/local/s2i/run
        image: fabric8test/demo:1.0.38-Stable-Release
        imagePullPolicy: Always
        livenessProbe:
          failureThreshold: 3
          httpGet:
            path: /health
            port: 8081
            scheme: HTTP
          initialDelaySeconds: 180
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 1
        name: demo
        ports:
        - containerPort: 8443
          name: https
          protocol: TCP
        readinessProbe:
          failureThreshold: 3
          httpGet:
            path: /health
            port: 8081
            scheme: HTTP
          initialDelaySeconds: 10
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 1
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /sample
          name: sample
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
      volumes:
      - emptyDir: {}
        name: sample
  test: false
  triggers:
  - imageChangeParams:
      containerNames:
      - demo
      from:
        kind: ImageStreamTag
        name: demo:1.0.38-Stable-Release
        namespace: fabric8test
    type: ImageChange
status:
  availableReplicas: 0
  latestVersion: 0
  observedGeneration: 0
  replicas: 0
  unavailableReplicas: 0
  updatedReplicas: 0
```

**Comment by mojsha** [comment]
And finally, the reason I was wrong about the difference between PUT / PATCH:

When you PUT / PATCH an _undeployed_ (i.e. not yet had 'oc rollout' executed against it) application, it seems to work fine, i.e. it does not trigger a deployment. I had executed the PATCH against an undeployed application. 

Here is the DC before and after an undeployed app has been patched:

**Before**
```
apiVersion: v1
kind: DeploymentConfig
metadata:
  annotations:
    fabric8.io/git-branch: master
    fabric8.io/git-commit: 321aca8e89fa7c173def57e078e24c433b413c3a
    fabric8.io/scm-tag: HEAD
    fabric8.io/scm-url: https://github.com/spring-projects/spring-boot/spring-boot-starter-parent/demo
  creationTimestamp: null
  generation: 1
  name: demo
spec:
  replicas: 1
  revisionHistoryLimit: 2
  selector:
    group: test.eu
    project: demo
    provider: fabric8
  strategy:
    activeDeadlineSeconds: 21600
    resources: {}
    rollingParams:
      intervalSeconds: 1
      maxSurge: 25%
      maxUnavailable: 25%
      timeoutSeconds: 3600
      updatePeriodSeconds: 1
    type: Rolling
  template:
    metadata:
      annotations:
        fabric8.io/git-branch: master
        fabric8.io/git-commit: 321aca8e89fa7c173def57e078e24c433b413c3a
        fabric8.io/scm-tag: HEAD
        fabric8.io/scm-url: https://github.com/spring-projects/spring-boot/spring-boot-starter-parent/demo
      creationTimestamp: null
      labels:
        group: test.eu
        project: demo
        provider: fabric8
    spec:
      containers:
      - args:
        - /usr/local/s2i/run
        image: fabric8test/demo:1.0.38-Stable-Release
        imagePullPolicy: Always
        livenessProbe:
          failureThreshold: 3
          httpGet:
            path: /health
            port: 8081
            scheme: HTTP
          initialDelaySeconds: 180
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 1
        name: demo
        ports:
        - containerPort: 8443
          name: https
          protocol: TCP
        readinessProbe:
          failureThreshold: 3
          httpGet:
            path: /health
            port: 8081
            scheme: HTTP
          initialDelaySeconds: 10
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 1
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /sample
          name: sample
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
      volumes:
      - emptyDir: {}
        name: sample
  test: false
  triggers:
  - imageChangeParams:
      containerNames:
      - demo
      from:
        kind: ImageStreamTag
        name: demo:1.0.38-Stable-Release
        namespace: fabric8test
    type: ImageChange
status:
  availableReplicas: 0
  latestVersion: 0
  observedGeneration: 0
  replicas: 0
  unavailableReplicas: 0
  updatedReplicas: 0
```

**After**
```
apiVersion: v1
kind: DeploymentConfig
metadata:
  annotations:
    fabric8.io/git-branch: master
    fabric8.io/git-commit: 321aca8e89fa7c173def57e078e24c433b413c3a
    fabric8.io/scm-tag: HEAD
    fabric8.io/scm-url: https://github.com/spring-projects/spring-boot/spring-boot-starter-parent/demo
  creationTimestamp: null
  generation: 1
  name: demo
spec:
  replicas: 1
  revisionHistoryLimit: 2
  selector:
    group: test.eu
    project: demo
    provider: fabric8
  strategy:
    activeDeadlineSeconds: 21600
    resources: {}
    rollingParams:
      intervalSeconds: 1
      maxSurge: 25%
      maxUnavailable: 25%
      timeoutSeconds: 3600
      updatePeriodSeconds: 1
    type: Rolling
  template:
    metadata:
      annotations:
        fabric8.io/git-branch: master
        fabric8.io/git-commit: 321aca8e89fa7c173def57e078e24c433b413c3a
        fabric8.io/scm-tag: HEAD
        fabric8.io/scm-url: https://github.com/spring-projects/spring-boot/spring-boot-starter-parent/demo
      creationTimestamp: null
      labels:
        group: test.eu
        project: demo
        provider: fabric8
    spec:
      containers:
      - args:
        - /usr/local/s2i/run
        image: fabric8test/demo:1.0.40-Stable-Release
        imagePullPolicy: Always
        livenessProbe:
          failureThreshold: 3
          httpGet:
            path: /health
            port: 8081
            scheme: HTTP
          initialDelaySeconds: 180
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 1
        name: demo
        ports:
        - containerPort: 8443
          name: https
          protocol: TCP
        readinessProbe:
          failureThreshold: 3
          httpGet:
            path: /health
            port: 8081
            scheme: HTTP
          initialDelaySeconds: 10
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 1
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /sample
          name: sample
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
      volumes:
      - emptyDir: {}
        name: sample
  test: false
  triggers:
  - imageChangeParams:
      containerNames:
      - demo
      from:
        kind: ImageStreamTag
        name: demo:1.0.38-Stable-Release
        namespace: fabric8test
    type: ImageChange
status:
  availableReplicas: 0
  latestVersion: 0
  observedGeneration: 0
  replicas: 0
  unavailableReplicas: 0
  updatedReplicas: 0
```
