### ISSUE TITLE
When set 0.2Gi to memory of limit range, it would be changed to other value

### ISSUE THREAD

**Issue by YueHuali** [openshift/origin#18433]
```yaml
apiVersion: "v1"
kind: "LimitRange"
metadata:
  name: "core-resource-limits"
spec:
  limits:
    - type: "Pod"
      max:
        cpu: "0.5"
        memory: "0.5Gi"
      min:
        cpu: "200m"
        memory: "0.2Gi"
    - type: "Container"
      max:
        cpu: "0.5"
        memory: "0.5Gi"
      min:
        cpu: "100m"
        memory: "4Mi"
      default:
        cpu: "300m"
        memory: "200Mi"
      defaultRequest:
        cpu: "200m"
        memory: "100Mi"
      maxLimitRequestRatio:
        cpu: "5"
```
