### ISSUE TITLE
Cannot find own template 

### ISSUE THREAD

**Issue by mvlach** [openshift/origin#18523]
I created simple template and tested it in private oc cluster up. After importing to private openshift cluster (instaled by ansible) can't find the template in service catalog.

```
kind: Template
apiVersion: v1
metadata:
  annotations:
    iconClass: icon-mysql-database
    description: Testing database
    tags: rohlik, database, network
    version: 1.0.0
    openshift.io/display-name: Testing database (external service)
    openshift.io/provider-display-name: 'VelkaPecka s.r.o.'
  name: rohlik-testing-database-pipe
labels:
  template: rohlik-testing-database-pipe
parameters:
objects:
- kind: Service
  apiVersion: v1
  spec:
    ports:
      - name: "database"
        port: 3306
  selector:
  metadata:
    name: "database"
- kind: Endpoints
  apiVersion: "v1"
  metadata:
    name: "database"
  subsets:
    -
      addresses:
        -
          ip: "*****"
      ports:
        -
          port: 3306
          name: "database"
```
##### Version
openshift v3.7.0+7ed6862
kubernetes v1.7.6+a08f5eeb62

##### Steps To Reproduce
oc create -f teplate -n openshift

##### Current Result
![image](https://user-images.githubusercontent.com/6176546/35968982-adc50012-0cc5-11e8-9cfd-ff423a64b4b7.png)

##### Expected Result
![image](https://user-images.githubusercontent.com/6176546/35968998-bdeeefca-0cc5-11e8-9220-d5fa8ce7fafc.png)
