### ISSUE TITLE
Build Input Secret fails when destinationDir has trailing "/"

### ISSUE THREAD

**Issue by marob** [openshift/origin#18690]
Build Input Secret fails when destinationDir has trailing "/"

##### Version
oc v3.6.1+008f2d5
kubernetes v1.6.1+5115d708d7
features: Basic-Auth

Server https://daaclx11.dns21-3.socgen:8443
openshift v3.6.173.0.21
kubernetes v1.6.1+5115d708d7

##### Steps To Reproduce
1. provide a build configuration with a secret having a destinationDir with a trailing "/"

```yaml
kind: BuildConfig
spec:
  source:
    secrets:
      - destinationDir: /tmp/
        secret:
          name: whatever
```

2. run the build. The file can't be found and it ends with the following log:

```
truncate: cannot open '/tmp/..2982_21_02_11_00_52.651545078/whatever.ext' for writing: No such file or directory
```

3. fix the config with `/tmp` instead of `/tmp/`

4. no error in logs, the build is successful

##### Current Result

The secret doesn't seam to be available in the destinationDir if it ends with a "/".

##### Expected Result

Configuration should not be sensitive to trailing "/".
