### ISSUE TITLE
Feature request: Template composition

### ISSUE THREAD

**Issue by phemmer** [openshift/origin#18814]
This is a feature request for the ability to create templates which are composed of a number of smaller templates.

In one of our use cases, we have numerous projects that are constructed using templates. The templates of each of these projects are very similar, but different enough to where we can't just use parameters. The ideal solution would instead be to split these common objects out into their own templates which we can then include as necessary into each of the project templates.

The way I might imagine the syntax looks is such as:
```yaml
# This is the template to be included
apiVersion: v1
metadata:
  name: tmpl1
parameters:
- name: PROJECT_NAME
- name: GIT_REPO_URI
objects:
- apiVersion: v1
  kind: Project
  metadata:
    name: ${PROJECT_NAME}
- apiVersion: v1
  kind: BuildConfig
  spec:
    source:
      type: Git
      git:
        uri: ${GIT_REPO_URI}
---
# This is the template performing the inclusion
apiVersion: v1
kind: Template
objects:
- apiVersion: v1
  kind: TemplateReference
  spec:
    namespace: default
    name: tmpl1
    labels:
      foo: bar
    parameters:
      PROJECT_NAME: myproject
- apiVersion: v1
  kind: Service
  ...
```

Since the `TemplateReference` is a single element of the `objects` array, but multiple objects might be provided by the referenced template, `oc process` will have to substitute that one reference object with N number of objects.

Any parameters in the included template which are not provided in the TemplateReference object would automatically become parameters of the top-level template. In the event of a name collision, the default value, description, etc of the top template wins. It might also be a good idea to allow a configurable prefix be added to each of the included template's parameter names.

The process for evaluating the template would be 2 steps. First would be to gather all the templates, and to flatten them all into a valid single template. Then process this as a normal template. The `oc process` command would have a flag to allow emitting this intermediary flattened template, but by default it would perform both steps and emit a normal list of objects.

Obviously cyclical references would have to be detected and return an error, but I don't imagine that would be hard. Implementation of this detection could also be used to provide a relationship graph between the template and all the included ones (akin to `oc adm build-chain`).

&nbsp;

As the above assumes that the referenced templates are already present within OpenShift, a further enhancement would be to allow using local files only. One way I think this could work is to have `oc process` accept a list of files (and possibly a single multi-document file as well), and then a flag which specifies the name of the template to be used as the top-level template. Alternatively, the first template in the list could be the top-level one.
