### ISSUE TITLE
Cannot get manifest for ImageStream referencing external image

### ISSUE THREAD

**Issue by nacef-labidi** [openshift/origin#18831]
After adding an ImageStream referencing a docker.io image, I cannot get manifest through registry REST API

##### Version
```
oc v3.7.1+ab0f056
kubernetes v1.7.6+a08f5eeb62
features: Basic-Auth GSSAPI Kerberos SPNEGO

Server https://openshift.op.acp.adeo.com:443
openshift v3.7.1+ab0f056
kubernetes v1.7.6+a08f5eeb62
```

##### Steps To Reproduce
1. Create ImageStream in project referencing a docker.io image
```
apiVersion: image.openshift.io/v1
kind: ImageStream
metadata:
  name: centos
  namespace: mytestproject
spec:
  dockerImageRepository: docker.io/library/centos
  lookupPolicy:
    local: false
```

2. `curl -kv -X GET -H "Authorization: Bearer xxxxxxxxxxx" http://myregistry.mydomain.com/v2/mytestproject/centos/manifests/latest`

##### Current Result
```
<---- HTTP RESPONSE:
HTTP/1.1 404 Not Found
Content-Length: 142
Content-Type: application/json; charset=utf-8
Date: Mon, 05 Mar 2018 13:08:41 GMT
Docker-Distribution-Api-Version: registry/2.0
Set-Cookie: 41a9fbc321c0026414bbe3c2eb00f854=75bc7fa4b2bee1973867b9b8840a4160; path=/; HttpOnly; Secure
X-Registry-Supports-Signatures: 1

{"errors":[{"code":"MANIFEST_UNKNOWN","message":"manifest unknown","detail":{"Op":"Get","URL":"https://registry-1.docker.io/v2/","Err":{}}}]}
```

##### Expected Result
Obtain manifest of ImageStream
