### ISSUE TITLE
ImageChange trigger won't work when ConfigChange trigger the deploymentconfig

### ISSUE THREAD

**Issue by jeffrey4l** [openshift/origin#18934]
[provide a description of the issue]

##### Version

```
$ rpm -qa | egrep "openshift|origin"
origin-3.7.0-1.0.7ed6862.x86_64
tuned-profiles-origin-node-3.7.0-1.0.7ed6862.x86_64
openshift-ansible-docs-3.7.13-1.el7.noarch
openshift-ansible-roles-3.7.13-1.el7.noarch
centos-release-openshift-origin37-1-1.el7.centos.noarch
origin-clients-3.7.0-1.0.7ed6862.x86_64
origin-docker-excluder-3.7.0-1.0.7ed6862.noarch
origin-master-3.7.0-1.0.7ed6862.x86_64
origin-node-3.7.0-1.0.7ed6862.x86_64
origin-sdn-ovs-3.7.0-1.0.7ed6862.x86_64
openshift-ansible-lookup-plugins-3.7.13-1.el7.noarch
openshift-ansible-filter-plugins-3.7.13-1.el7.noarch
openshift-ansible-playbooks-3.7.13-1.el7.noarch
openshift-ansible-3.7.13-1.el7.noarch
origin-excluder-3.7.0-1.0.7ed6862.noarch
openshift-ansible-callback-plugins-3.7.13-1.el7.noarch
```

##### Steps To Reproduce
1. Create a ImageStream and DeploymentConfig through 

```
---
kind: ImageStream
apiVersion: v1
metadata:
  name: echo
  labels:
    app: echo
spec:
  tags:
    - name: "1.0"
      from:
        kind: DockerImage
        name: googlecontainer/echoserver:1.5
---
kind: DeploymentConfig
apiVersion: v1
metadata:
  name: echo
  labels:
    app: echo
spec:
  strategy:
    type: Recreate
  triggers:
    - type: ConfigChange
    - type: ImageChange
      imageChangeParams:
        automatic: true
        containerNames:
          - echo
        from:
          kind: ImageStreamTag
          name: "echo:1.0"
  replicas: 1
  selector:
    app: echo
  template:
    metadata:
      labels:
        app: echo
    spec:
      containers:
        - name: echo
          image: "echo"
          ports:
            - containerPort: 8080
```

2.  re-apply the above deploymentconfig

```
oc apply -f deploymentconfig.yml
```

##### Current Result

In step 2, the **image** will become "echo", the pod tries to pull this image from hub.docker.com with following logs

```
Failed to pull image "echo": rpc error: code = 2 desc = Error: image library/echo:latest not found
```

##### Expected Result

In step2, the **image** should be parsed to ImageStream like step 1, to pull the image from local registry.
