### ISSUE TITLE
template: use all keys of configmap by defining configmap name

### ISSUE THREAD

**Issue by robdaems** [openshift/origin#18991]
##### Version
```
[rob@openshift ~]$ openshift version
openshift v3.7.1+a8deba5-34
kubernetes v1.7.6+a08f5eeb62
etcd 3.2.8
[rob@openshift ~]$ oc version
oc v3.7.1+a8deba5-34
kubernetes v1.7.6+a08f5eeb62
features: Basic-Auth GSSAPI Kerberos SPNEGO
[rob@openshift ~]$
```
In the 'DeploymentConfig' part of a template you can set your environment variables directly via name/value or via a configmap.

```
  kind: DeploymentConfig
  spec:
    template:
      spec:
        containers:
          - env:
          - name: MY_ENV_NAME_IN_THE_CONTAINER
            valueFrom:
              configMapKeyRef:
                key: MY_ENV_NAME_IN_THE_CONFIGMAP
                name: MY_CONFIGMAP_NAME
```
This is useful when I need keys from different config maps.
But when I want to use all keys from a config map, I need to write a lot of lines.
Is there a way to just point to a config map. (preferable via a parameterized config map name)
The names used in the container are equal to the key names in the configmap.
Perhaps via an optional exclude flag you can exclude some keys to taken into account.

I don't find anything in the configmap explanations, which cover similar possibility.
