### ISSUE TITLE
Gradual traffic splitting between services using alternateBackends not working as expected

### ISSUE THREAD

**Issue by valdestrijus** [openshift/origin#19118]
Trying to perform gradual traffic splitting on the route which has alternateBackends configured with two identical blue and green services.

##### Version
oc v3.6.0+c4dd4cf
kubernetes v1.6.1+5115d708d7
features: Basic-Auth

Server https://192.168.99.101:8443
openshift v3.6.0+c4dd4cf
kubernetes v1.6.1+5115d708d7

##### Steps To Reproduce
1. Add  two deployment configs dc-blue, dc-green, deploy them
2. Expose two services dc-blue, dc-green on tcp 80 -> 8080 name web
3. Create bluegreen route with dc-blue main service and dc-green alternate service
```
apiVersion: v1
kind: Route
metadata:
  name: bluegreen
spec:
  alternateBackends:
    - kind: Service
      name: dc-green
      weight: 0
  port:
    targetPort: web
  to:
    kind: Service
    name: dc-blue
    weight: 100
  wildcardPolicy: None
```

4. Split traffic 50/50
```
Name:                   bluegreen
Namespace:              project
Created:                2 weeks ago
Labels:                 <none>
Annotations:            haproxy.router.openshift.io/balance=roundrobin
Requested Host:         bluegreen-project.192.168.99.101.nip.io
                          exposed on router router 2 weeks ago
Path:                   <none>
TLS Termination:        <none>
Insecure Policy:        <none>
Endpoint Port:          web

Service:        dc-blue
Weight:         50 (50%)
Endpoints:      172.17.0.3:8080

Service:        dc-green
Weight:         50 (50%)
Endpoints:      172.17.0.13:8080
```
5. Service descriptions
```
Name:                   dc-blue
Namespace:              project
Labels:                 app=bluegreen
Annotations:            description=app
Selector:               name=dc-blue
Type:                   ClusterIP
IP:                     172.30.235.67
Port:                   web     80/TCP
Endpoints:              172.17.0.3:8080
Session Affinity:       None
Events:                 <none>
``` 
```
Name:                   dc-green
Namespace:              project
Labels:                 app=dc-green
Annotations:            description=app
Selector:               name=dc-green
Type:                   ClusterIP
IP:                     172.30.17.243
Port:                   web     80/TCP
Endpoints:              172.17.0.13:8080
Session Affinity:       None
Events:                 <none>
```
##### Current Result
All traffic goes to dc-blue.
##### Expected Result
Traffic should be splitted between dc-blue and dc-green evenly.
##### Additional Information
- Tried on minishift locally and work environment with openshift 3.7 result is the same
- If I do split 100% traffic to one or another service, it works as expected

**Comment by jwforres** [comment]
@openshift/sig-networking

**Comment by patrickeasters** [comment]
Did you ever figure this out? I'm hitting this on one of my clusters.

**Comment by valdestrijus** [comment]
@patrickeasters I didint try new version v3.9 of openshift, but no i didint figure this out.

**Comment by patrickeasters** [comment]
@valdestrijus I ended up figuring this out. The routers were setting a cookie and causing session stickiness. I ended up disabling that via an annotation on the route and could no longer reproduce it afterwards.

```
apiVersion: v1
kind: Route
metadata:
  annotations:
    haproxy.router.openshift.io/disable_cookies: true
```

It's also worth noting that you should clear browser cookies after updating the route. Even after setting the annotation, session stickiness still occurred for any browsers that already had that cookie set.
