### ISSUE TITLE
New-build and new-app ignore build env var arguments for pipeline

### ISSUE THREAD

**Issue by siamaksade** [openshift/origin#19142]
The command line arguments to set environment variables on a pipeline buildconfig are ignored with both `new-app` and `new-build`:

```
oc new-app . --strategy=pipeline --build-env=PROJECT_NAME=dev
oc new=build . --strategy=pipeline -e PROJECT_NAME=dev
```

##### Version
oc v3.9.14
kubernetes v1.9.1+a0ce1bc657
features: Basic-Auth GSSAPI Kerberos SPNEGO

Server https://52.215.39.4:8443
openshift v3.9.14
kubernetes v1.9.1+a0ce1bc657

**Comment by jwforres** [comment]
@openshift/sig-developer-experience

**Comment by wozniakjan** [comment]
@siamaksade could you please share relevant parts of your buildconfig with jenkinsfile?

I have tried with both 3.9 and 3.10
```bash
$ oc new-app -f samplepipeline-withenvs.yaml --build-env=FOO4=BAR4
$ oc start-build sample-pipeline-withenvs -e FOO3=BAR3
```

and in both cases the console output was what I would have expected

<details>
<summary>BuildConfig - samplepipeline-withenvs.yaml</summary>

```yaml
apiVersion: v1
kind: Template
labels:
  template: application-template-sample-pipeline
metadata:
  annotations:
    iconClass: icon-jenkins
    tags: instant-app,jenkins
  name: jenkins-pipeline-example
parameters:
objects:
- apiVersion: v1
  kind: BuildConfig 
  metadata:
    labels:
      name: sample-pipeline-withenvs
    name: sample-pipeline-withenvs
  spec:
    strategy:
      jenkinsPipelineStrategy:
        env:
          - name: FOO1
            value: BAR1 
        jenkinsfile: |-
          node() {
            echo "FOO1 is ${env.FOO1}"
            echo "FOO2 is ${env.FOO2}"
            echo "FOO3 is ${env.FOO3}"
            echo "FOO4 is ${env.FOO4}"
          }
      type: JenkinsPipeline
```
</details>

<details>
<summary>console output</summary>

```
OpenShift Build jenkins-ephemeral/sample-pipeline-withenvs-1
[Pipeline] node
Running on Jenkins in /var/lib/jenkins/jobs/jenkins-ephemeral/jobs/jenkins-ephemeral-sample-pipeline-withenvs/workspace
[Pipeline] {
[Pipeline] echo
FOO1 is BAR1
[Pipeline] echo
FOO2 is null
[Pipeline] echo
FOO3 is BAR3
[Pipeline] echo
FOO4 is BAR4
[Pipeline] }
[Pipeline] // node
[Pipeline] End of Pipeline
Finished: SUCCESS
```
</details>
