### ISSUE TITLE
Deployment is fails to create Pods

### ISSUE THREAD

**Issue by gkarthiks** [openshift/origin#19264]
Deployment is failing to create Containers / Pods.

I am trying to deploy the `kafka` and `kubeless` into our cluster. All other objects posted to k8s are created successfully, but `Deployment` config alone is not completing successfully. Instead it is creating an empty `deployment` and no `containers` or `pods` are created via `Deployment`.

In the `Web Console` I could see the following. 
![image](https://user-images.githubusercontent.com/30545166/38463303-74632320-3aac-11e8-8113-c551d784c050.png)

But under the deployments, 
![image](https://user-images.githubusercontent.com/30545166/38463307-9625dafc-3aac-11e8-95fc-eed17838b683.png)

If I execute the `oc get deploy` command,

| NAME  | DESIRED | CURRENT | UP-TO-DATE | AVAILABLE | AGE |
| ------- | --------- | ---------- | ------------- | ----------- | ----- |
| kafka-trigger-controller | 1 | 0 | 0 | 0 | 25m |
| kubeless-controller-manager | 1 | 0 | 0 | 0 | 28m |

##### Version
`oc version` command result,
```
oc v1.5.1+7b451fc
 kubernetes v1.5.2+43a9be4
 features: Basic-Auth

 Server <Internal-Cluster>
 openshift v3.7.9
 kubernetes v1.7.6
```

##### Steps To Reproduce
1. Deploy `kubeless v0.5.0` via `oc create -f https://github.com/kubeless/kubeless/releases/download/v0.5.0/kubeless-openshift-v0.5.0.yaml`
or 
Deploy `kafka` via `oc create -f https://github.com/kubeless/kubeless/releases/download/v0.5.0/kafka-zookeeper-v0.5.0.yaml`

##### Current Result
No `containers` are created from the `deployment` object.

##### Expected Result
Deployment should create the containers/pods defined in the `Deployment` config.

##### Additional Information
Result of `oc describe deploy kafka-trigger-controller` command
```
Name:			kafka-trigger-controller
Namespace:		kubeless
CreationTimestamp:	Sat, 07 Apr 2018 21:15:25 -0700
Labels:			kubeless=kafka-trigger-controller
Selector:		kubeless=kafka-trigger-controller
Replicas:		0 updated | 1 total | 0 available | 0 unavailable
StrategyType:		RollingUpdate
MinReadySeconds:	0
RollingUpdateStrategy:	25% max unavailable, 25% max surge
OldReplicaSets:		<none>
NewReplicaSet:		<none>
No events.
```

**Comment by tnozicka** [comment]
@gkarthiks please provide also the output of `oc get deploy,rs,po -o yaml` and `oc get events -o yaml`

**Comment by tnozicka** [comment]
In the dump you have sent all seems fine:
```yaml
- apiVersion: extensions/v1beta1
  kind: Deployment
  metadata:
    name: kubeless-controller-manager
    namespace: kubeless
  spec:
    replicas: 1
  status:
    availableReplicas: 1
    readyReplicas: 1
    replicas: 1
    updatedReplicas: 1
```
```yaml
apiVersion: v1
items:
- apiVersion: extensions/v1beta1
  kind: Deployment
  metadata:
    name: kafka-trigger-controller
    namespace: kubeless
  spec:
    replicas: 1
  status:
    availableReplicas: 1
    observedGeneration: 1
    readyReplicas: 1
    replicas: 1
    updatedReplicas: 1
```
I even see the RS and Pods running for those Deployments. The old events are already gone.
