### ISSUE TITLE
Custom strategy to be triggered when scale of a deployment is increased/decreased

### ISSUE THREAD

**Issue by jasjeetkaur2211** [openshift/origin#19363]
I have been trying to add a custom strategy that is triggered when a new deployment is deployed successfully

```
oc version
oc v3.6.0+c4dd4cf
kubernetes v1.6.1+5115d708d7
features: Basic-Auth GSSAPI Kerberos SPNEGO

Server https://192.168.42.28:8443
openshift v3.6.0+c4dd4cf
kubernetes v1.6.1+5115d708d7

```
1. Added a rolling strategy via command line - 
```
oc set deployment-hook dc/service-name --pre -c container --failure-policy=abort -- /usr/bin/curl -X POST -d {} url
```
Now when I deploy a new container for service-name, I am able to receive the message in my POST method handler in another container. Also, the strategy is visible in openshift events for the container in which it was added.

2. Now when I try to add the same strategy via yaml file as follows, 
```
spec:
  replicas: 1
  strategy:
    type: Rolling
    rollingParams:
      pre:
        failurePolicy: Abort
        execNewPod:
          containerName: vertx
          command: ["/usr/bin/curl", "-X", "POST", "-d", "{}", "url"]

```
**PROBLEM 1:** I do not see the same in any container events neither is it getting triggered when a new image is successfully deployed. 

**PROBELM 2:** Ideally, I want the strategy to be triggered whenever the scale of the current deployment is changed. Can anybody help me in both the issues?
