### ISSUE TITLE
3.9 don't fetch new image revision

### ISSUE THREAD

**Issue by dungdm93** [openshift/origin#19362]
### `oc version`
```
openshift v3.9.0-alpha.4+881f1dd-440
kubernetes v1.9.1+a0ce1bc657
```

### Steps To Reproduce
1. Deploy application from image
```bash
$ oc new-app docker.io/dungdm93/blog --name blog
```
2. Rebuild image at local & push to Docker registry
```bash
$ docker build -t dungdm93/blog .
$ docker push dungdm93/blog
```
3. Redeploy blog app
Go to OpenShift web console: `Applications > Deployments > 'blog'`
Click deploy button.

### Current Result
OpenShift still deploy old image, although `imagePullPolicy: Always`

### Expected Result
New image revision will be deployed.

**Comment by jwforres** [comment]
@openshift/sig-master

**Comment by jwforres** [comment]
might overlap with @openshift/sig-developer-experience

**Comment by gabemontero** [comment]
just tried it, and it confirms my understanding ...

1) pushing the image to docker hub is not sufficient for updating the deployment ... 
2) either an `oc import-image` needs to be run, to take the update from dockerhub and update the imagestream / internal registry
3) or `oc tag --schedule` on the latest needs to be run so that it periodically checks the source for updates

Once 2) or 3) is in place, the ICT, which is created

```
    - imageChangeParams:
        automatic: true
        containerNames:
        - blog
        from:
          kind: ImageStreamTag
          name: blog:latest
          namespace: myproject
        lastTriggeredImage: docker.io/dungdm93/blog@sha256:8ab376b8ac5bcf5af6009aaf3990e208f19c9327910e12cb47d69fad2da72248
      type: ImageChange

```
 should trigger the redeploy for you

In looking at the yaml for the imagestreamtag that resulted from `oc new-app docker.io/dungdm93/blog --name blog`, scheduled tag import is not set up:

```
    importPolicy: {}
```

Setting scheduled during `oc new-app` seems tricky since the image stream needs to complete to the point that an image has been imported so a tag exists ...

@bparees thoughts?
