### ISSUE TITLE
Can use range limits for user like cluster quota?

### ISSUE THREAD

**Issue by fisache** [openshift/origin#19402]
[provide a description of the issue]

##### Version
[provide output of the `openshift version` or `oc version` command]
openshift 3.7
oc 3.7

##### Current Result
I know cluster quota for user like this

```
apiVersion: v1
kind: ClusterResourceQuota
metadata:
  name: limit-bob
spec:
  quota:
    hard:
      pods: "3"
  selector:
    annotations:
      openshift.io/requester: <user-name>
    labels: null
status:
  namespaces: null
  total: {}
```

this can apply quotas for user in multi projects.
and I also want to apply limit range(CPU, Memory..) for user in multi projects.
Is it available?
Thx
