### ISSUE TITLE
how to use a kubernetes Role for OpenShift resources like routes?

### ISSUE THREAD

**Issue by jstrachan** [openshift/origin#19425]
I'm trying to create a kubernetes role for `Routes` on OpenShift on MiniShift (openshift 3.9.0). I figured I could refer to them now via their apiGroup - but all my attempts at different `apiGroup` strings have failed me ;)

Is this possible?

```yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: access-routes
rules:
- apiGroups:
  - route.openshift.io
  - route.openshift.io/v1
  - routes
  - routes.openshift.io
  - routes.openshift.io/v1
  resources:
  - routes
  verbs:
  - get
  - list
  - watch
```

Whatever value I try for the `apiGroups` seems to be ignored by the pod using this role/rolebinding/serviceaccount

**Comment by enj** [comment]
@jstrachan you are probably missing the legacy group `""`.

```yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: access-routes
rules:
- apiGroups:
  - ""
  - route.openshift.io
  resources:
  - routes
  verbs:
  - get
  - list
  - watch
```

Feel free to reopen if that does not work for you.
