### ISSUE TITLE
Template Service Broker fails to provision api server extensions

### ISSUE THREAD

**Issue by rthallisey** [openshift/origin#19431]
Similar issue to https://github.com/openshift/origin/issues/19368, but I'd like to be able to provision templates through the TSB using an api server extension.  Specifically, the ```kubevirt.io/v1alpha1``` api.

@bparees looking at https://github.com/openshift/origin/pull/19396, the change ```rbac.NewRule("create").Groups(rbac.APIGroupAll).Resources(rbac.ResourceAll).RuleOrDie()``` I think would cover the api server extension?

Questions:
  - Is https://github.com/openshift/origin/pull/19396 the right solution for this?
  - Should any api server extension be allowed?
  - Should we add only ```kubevirt.io/v1alpha1```
  - What happens if you add the permission and the api hasn't been created?

```yaml
apiVersion: v1
kind: Template
metadata:
  name: {{ VMNAME }}-template
  annotations:
    description: "OCP KubeVirt Red Hat Enterprise Linux 7.4 VM template"
    tags: "kubevirt,ocp,template,linux"
  labels:
    kubevirt.io/os: rhel7.4
    miq.github.io/kubevirt-is-vm-template: "true"
objects:
- apiVersion: kubevirt.io/v1alpha1
  kind: OfflineVirtualMachine
  metadata:
    name: ${NAME}
  spec:
    template:
      spec:
        domain:
          cpu:
            cores: ${CPU_CORES}
          resources:
            requests:
              memory: ${MEMORY}
          machine:
            type: q35
          devices:
            disks:
              - name: disk0
                disk:
                  bus: {{ BUS }}
                volumeName: volume-1
        volumes:
          - name: volume-1
            persistentVolumeClaim:
              claimName: {{ PVCNAME }}
parameters:
- name: NAME
  description: Name for the new VM
- name: MEMORY
  description: Amount of memory
  value: {{ MEMORY}}{{ UNIT }}
- name: CPU_CORES
  description: Amount of cores
  value: "{{ CORES }}"
```
