### ISSUE TITLE
oc start-build and pass ImageStreamTag version

### ISSUE THREAD

**Issue by rakk** [openshift/origin#19483]
##### Version
oc v3.6.173.0.96
kubernetes v.16.1+5115d708d7
features: Basic-Auth

#####  Question

Problem to solve:
Create pipeline, which will create docker image in specific version (including Jenkins build number, eg. 1.0.1-117). Then it will deploy it to integration environment and then push docker image to external registry (as version 1.0.1-117).

How to pass current version (eg. 1.0.1-117) to my buildconfig:
```
(...)
spec:
  output:
     to:
       name: external-registry/aaa/my-project:$VERSION
(...)
  strategy:
    dockerStrategy:
      from:
        kind: ImageStreamTag
        name: 'my-project:$VERSION'
(...)
```

I checked the help for 'oc start-build' and there are: 
* build-arg - but that seems to used inside docker file only
* env - this is used on pods
For both I have: 
```
The ImageStreamTag "my-project:$VERSION' is invalid: from: Error resolving ImageStreamTag my-project:$VERSION' in namespace aaaa: unable to find latest tagged image
```
Please advise how to update buildconfig on the fly.
