### ISSUE TITLE
Can't mount flexdriver in origin 3.9

### ISSUE THREAD

**Issue by mlbiam** [openshift/origin#19519]
I'm trying to deploy a cifs flex volume (https://github.com/andyzhangx/kubernetes-drivers/blob/master/flexvolume/cifs/cifs) into Origin 3.9 on CentOS 7.  Once deployed the node didn't recognize it with the following error (on level 8):

```
Apr 25 21:33:55 node origin-node: W0425 21:33:55.420302    1460 driver-call.go:145] FlexVolume: driver call failed: executable: /usr/libexec/kubernetes/kubelet-plugins/volume/exec/azure-cifs/azure-cifs, args: [init], error: fork/exec /usr/libexec/kubernetes/kubelet-plugins/volume/exec/azure-cifs/azure-cifs: no such file or directory, output: ""
Apr 25 21:33:55 node origin-node: E0425 21:33:55.420351    1460 plugins.go:548] Error dynamically probing plugins: Error creating Flexvolume plugin from directory azure-cifs, skipping. Error: unexpected end of JSON input
```

 until it was copied from ```/usr/libexec/kubernetes/kubelet-plugins/volume/exec/azure-cifs/cifs``` to ```/usr/libexec/kubernetes/kubelet-plugins/volume/exec/azure-cifs/azure-cifs```.  The node still refused to mount the volume however

##### Version

```
oc v3.9.0+ba7faec-1
kubernetes v1.9.1+a0ce1bc657
features: Basic-Auth GSSAPI Kerberos SPNEGO
```

##### Steps To Reproduce
On the worker node
```
$ mkdir /usr/libexec/kubernetes/kubelet-plugins/volume/exec/azure-cifs
$ cd /usr/libexec/kubernetes/kubelet-plugins/volume/exec/azure-cifs
$ wget -O cifs https://raw.githubusercontent.com/andyzhangx/kubernetes-drivers/master/flexvolume/cifs/cifs
$ chmod a+x cifs
```

Create a persistent volume referencing the flex volume:
```yaml
apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-cifs-flexvol
spec:
  capacity:
    storage: 100Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  flexVolume:
    driver: "azure/cifs"
    secretRef:
      name: cifscreds
    options:
      source: "//adfs.ent2k12.domain.com/mmosley-share"
      mountOptions: "vers=3.0,dir_mode=0777,file_mode=0777"
```

Create the required secret

Create the PVC in the project
```yaml
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: pvc-cifs-flexvol
spec:
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 10Gi
  volumeName: pv-cifs-flexvol
  storageClassName: ""
```

Create pod referencing persistent volume claim

##### Current Result

See opening description

##### Expected Result

flexvolume to be recognized and loaded
