### ISSUE TITLE
Service accounts with local roles are not behaving the same in 3.9 as before

### ISSUE THREAD

**Issue by dmlond** [openshift/origin#19579]
role bindings changed in 3.9

##### Version
oc version
oc v3.9.0+191fece
kubernetes v1.9.1+a0ce1bc657
features: Basic-Auth

Server https://192.168.99.100:8443
openshift v3.9.0+d0f9aed-12
kubernetes v1.9.1+a0ce1bc657

##### Steps To Reproduce
1. oc new-project foo
2. oc create serviceaccount cbuilder
3. oc create role cbuilder-role --verb=list --resource=builds
4. oc policy add-role-to-user cbuilder-role -z cbuilder --role-namespace=foo
5. auth_token=$(oc serviceaccounts get-token cbuilder)
6. curl -k -H "Authorization: Bearer ${auth_token}" ${k8s_url}oapi/v1/namespaces/foo/builds
{
  "kind": "Status",
  "apiVersion": "v1",
  "metadata": {},
  "status": "Failure",
  "message": "builds is forbidden: User \"system:serviceaccount:foo:cbuilder\" cannot list builds in the namespace \"foo\": User \"system:serviceaccount:foo:cbuilder\" cannot list builds in project \"foo\"",
  "reason": "Forbidden",
  "details": {
    "kind": "builds"
  },
  "code": 403
}

##### Current Result
{
  "kind": "Status",
  "apiVersion": "v1",
  "metadata": {},
  "status": "Failure",
  "message": "builds is forbidden: User \"system:serviceaccount:foo:cbuilder\" cannot list builds in the namespace \"foo\": User \"system:serviceaccount:foo:cbuilder\" cannot list builds in project \"foo\"",
  "reason": "Forbidden",
  "details": {
    "kind": "builds"
  },
  "code": 403
}

##### Expected Result
{
  "kind": "BuildList",
  "apiVersion": "v1",
  "metadata": {
    "selfLink": "/oapi/v1/namespaces/foo/builds",
    "resourceVersion": "7780"
  },
  "items": []
}

##### Additional Information
This worked in 3.7 and before. If I add the edit role to the serviceaccount, it can list the builds. I liked being able to create more specific roles than 'edit'.

**Comment by jwforres** [comment]
@openshift/sig-security

**Comment by liggitt** [comment]
`oc create role` finds resources the server has that match your specified resources.

As part of switching to use API-group-qualified OpenShift APIs (available since 3.6), "builds" now prefers the group-qualified API: `/apis/build.openshift.io/v1/namespaces/foo/builds`

You can see the output with `oc create role cbuilder-role --verb=list --resource=builds --dry-run -o yaml`:

in 3.7:
```yaml
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: Role
metadata:
  name: cbuilder-role
rules:
- apiGroups:
  - ""
  resources:
  - builds
  verbs:
  - list
```

in 3.9:
```
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: cbuilder-role
rules:
- apiGroups:
  - build.openshift.io
  resources:
  - builds
  verbs:
  - list
```

that role would let you do `oc get builds` which would use this API: `/apis/build.openshift.io/v1/namespaces/foo/builds`

If you want to create a role that references the legacy ungroupified resources, you can do that explicitly with your own manifest:
```yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: cbuilder-role
rules:
- apiGroups:
  - ""
  - build.openshift.io
  resources:
  - builds
  verbs:
  - list
```

you should also switch to use the groupified API in your calling code, as the /oapi endpoints have been deprecated since 3.6
