### ISSUE TITLE
destionationDir does not respect contextDir in Openshift Builds 

### ISSUE THREAD

**Issue by HackToHell** [openshift/origin#19585]
##### Version
oc v3.9.0+191fece
kubernetes v1.9.1+a0ce1bc657
features: Basic-Auth GSSAPI Kerberos SPNEGO

Server https://cluster:443
openshift v3.9.0+ba7faec-1
kubernetes v1.9.1+a0ce1bc657

##### Steps To Reproduce
When you create a build of type S2I and add in binary files to be pulled in from images, as an separate input source, the paths of the image, specifically the `destinationDir` does not respect the conextDir setting of source to image.

##### Current Config
```
     source:
    contextDir: directorywithdockerfile
    git:
      ref: feature/fixes_and_3.9
      uri: git@bitbucket.org:xxx.git
    images:
    - from:
        kind: ImageStreamTag
        name: image:latest
      paths:
      - destinationDir: directorywithdockerfile/mypath/files
        sourcePath: /path/of/artifactory/out/
```
##### Expected Config

Expected Config: 
```
     source:
    contextDir: directorywithdockerfile
    git:
      ref: feature/fixes_and_3.9
      uri: git@bitbucket.org:xxxx.git
    images:
    - from:
        kind: ImageStreamTag
        name: image:latest
      paths:
      - destinationDir: mypath/files
        sourcePath: /path/of/artifactory/out/
```

with implicit contextDir prefixing.
