### ISSUE TITLE
ImageStream lookupPolicy is ignored in 3.9.0

### ISSUE THREAD

**Issue by nicolaferraro** [openshift/origin#19663]
On Openshift 3.7.x we used to set "lookupPolicy" -> "local" to true on ImageStreams in order to use them in StatefulSets or other Kubernetes-only objects (for all builds with the fabric8-maven plugin).

But Openshift 3.9.0 seems not to lookup image streams with local lookup policy from the same project.
In the following example, the `spring-boot-camel-xa:latest` image is ignored and Openshift tries to look it up only from docker hub.

In the monitoring console I see:
```
Failed to pull image "spring-boot-camel-xa:latest": rpc error: code = Unknown desc = Error: image library/spring-boot-camel-xa:latest not found
```

I've also executed:
```
oc set image-lookup statefulset/spring-boot-camel-xa
```

That adds the `alpha.image.policy.openshift.io/resolve-names: '*'` annotation, but it does not have any effect.

This is the imagestream I'm using and the statefulset. It works on Openshift 3.7.1.

*is.yml*
```
apiVersion: v1
kind: ImageStream
metadata:
  creationTimestamp: 2018-05-09T15:02:29Z
  generation: 1
  labels:
    app: spring-boot-camel-xa
    group: com.redhat.fuse.quickstarts
    provider: fabric8
    version: 1.0-SNAPSHOT
  name: spring-boot-camel-xa
  namespace: xa
  resourceVersion: "11321"
  selfLink: /oapi/v1/namespaces/xa/imagestreams/spring-boot-camel-xa
  uid: fe71ce8d-5399-11e8-b4f5-96510617fcad
spec:
  lookupPolicy:
    local: true
status:
  dockerImageRepository: 172.30.1.1:5000/xa/spring-boot-camel-xa
  tags:
  - items:
    - created: 2018-05-09T15:03:23Z
      dockerImageReference: 172.30.1.1:5000/xa/spring-boot-camel-xa@sha256:5ebc244e7d6c5ea5d4088aad2f90ad5469fb8ee1ee55dbd7e8caf8cbf0147f08
      generation: 1
      image: sha256:5ebc244e7d6c5ea5d4088aad2f90ad5469fb8ee1ee55dbd7e8caf8cbf0147f08
    tag: latest
```
(pushed by binary build)

*statefulset.yml*
```
---
apiVersion: apps/v1beta1
kind: StatefulSet
metadata:
  annotations:
    fabric8.io/git-commit: c12921b1d12e0403134eb28cc49cb39afa95ad53
    fabric8.io/iconUrl: img/icons/camel.svg
    fabric8.io/git-branch: master
    fabric8.io/metrics-path: dashboard/file/camel-routes.json/?var-project=spring-boot-camel-xa&var-version=1.0-SNAPSHOT
  labels:
    app: spring-boot-camel-xa
    provider: fabric8
    version: 1.0-SNAPSHOT
    group: com.redhat.fuse.quickstarts
  name: spring-boot-camel-xa
spec:
  podManagementPolicy: Parallel
  replicas: 1
  selector:
    matchLabels:
      app: spring-boot-camel-xa
      provider: fabric8
      group: com.redhat.fuse.quickstarts
  serviceName: spring-boot-camel-xa-headless
  template:
    metadata:
      labels:
        app: spring-boot-camel-xa
        provider: fabric8
        version: 1.0-SNAPSHOT
        group: com.redhat.fuse.quickstarts
    spec:
      containers:
      - env:
        - name: CLUSTER_RECOVERY_ENABLED
          value: "false"
        - name: KUBERNETES_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        image: spring-boot-camel-xa:latest
        imagePullPolicy: IfNotPresent
        name: spring-boot
        ports:
        - containerPort: 8080
          name: http
          protocol: TCP
        - containerPort: 9779
          name: prometheus
          protocol: TCP
        - containerPort: 8778
          name: jolokia
          protocol: TCP
  updateStrategy:
    type: RollingUpdate
```

##### Version
```
oc v3.9.0+191fece
kubernetes v1.9.1+a0ce1bc657
features: Basic-Auth GSSAPI Kerberos SPNEGO

Server https://192.168.42.89:8443
openshift v3.9.0+d0f9aed-12
kubernetes v1.9.1+a0ce1bc657
```

##### Steps To Reproduce
1. Start a 3.9.0 Openshift instance (e.g. Minishift)
2. Follow the instructions [here](https://github.com/jboss-fuse/spring-boot-camel-xa) (you can skip the part about dependencies, just create the pvc and run `mvn fabric8:deploy -P openshift`)

##### Current Result
The pod does not start cause "ImagePull backoff"

##### Expected Result
The pod starts as in 3.7.1.

##### Additional Information
N/A

**Comment by jwforres** [comment]
@openshift/sig-developer-experience

**Comment by bparees** [comment]
image lookup behavior is controlled by the master-config settings:
https://docs.openshift.org/latest/admin_guide/image_policy.html#image-policy-configuring-the-image-policy-admission-plug-in

to get the default behavior, the imagepolicyconfig must at least be present (even if only w/ an empty config).

So you'll need to check what the master-config looks like.

**Comment by bparees** [comment]
Also I would advise you to open this issue against the minishift repo where the minishift team can address any changes they've made in default configuration settings: https://github.com/minishift/minishift

**Comment by bparees** [comment]
i've checked the default config for a minishift v3.9 instance and indeed the admissionconfig section has not enabled the imagepolicyconfig admission controller:
```
admissionConfig:
  pluginConfig:
    GenericAdmissionWebhook:
      configuration:
        apiVersion: v1
        disable: false
        kind: DefaultAdmissionConfig
      location: ""
aggregatorConfig:
```

the config would need to contain:
```
admissionConfig:
  pluginConfig:
    openshift.io/ImagePolicy: {}
```

at a minimum to enable the plugin.

i'm going to close this but you can open the issue against minishift to change how they are defining their config to enable it properly.
