### ISSUE TITLE
Support mapping configMaps and secrets in BuildConfigs

### ISSUE THREAD

**Issue by sparty02** [openshift/origin#19745]
OpenShift BuildConfigs should support buildArgs being sourced from secrets (or config maps for that matter).

Here is an example of what using this feature would look like:

```yaml
apiVersion: build.openshift.io/v1
kind: BuildConfig
metadata:
  name: foo-build
spec:
  runPolicy: Serial
  source:
    type: Binary
  strategy:
    type: Docker
    dockerStrategy:
      dockerfilePath: Dockerfile
      buildArgs:
        - name: http_proxy
          valueFrom:
            configMapKeyRef:
              name: proxy-config
              key: proxy-url
        - name: no_proxy
          value: foo.dev.local
        - name: USERNAME
          valueFrom:
            secretKeyRef:
              name: auth-basic
              key: username
```

Note that the example above is showing a mixture of a buildArg literal, a buildArg mapped from a configMap and a buildArg mapped from a secret.  Also note that this particular example is for mapping buildArgs in a dockerStrategy, but the ability to map configMaps and secrets should be available in all BuildConfig strategies for other similar items like environment variable (env) blocks.

##### Version
OpenShift Master:
v3.7.44
Kubernetes Master:
v1.7.6+a08f5eeb62
