### ISSUE TITLE
field allowedFlexVolumes for v1.SecurityContextConstraints is required

### ISSUE THREAD

**Issue by DanyC97** [openshift/origin#19767]
Given the Origin version below
```
oc version
oc v3.7.0+7ed6862
kubernetes v1.7.6+a08f5eeb62
features: Basic-Auth GSSAPI Kerberos SPNEGO

Server https://10.84.67.201:8443
openshift v3.7.0+7ed6862
kubernetes v1.7.6+a08f5eeb62
[root@deployer ~]# kubectl version
Client Version: version.Info{Major:"1", Minor:"7", GitVersion:"v1.7.6+a08f5eeb62", GitCommit:"c84beff", GitTreeState:"clean", BuildDate:"2017-12-06T20:03:39Z", GoVersion:"go1.8.3", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"7", GitVersion:"v1.7.6+a08f5eeb62", GitCommit:"c84beff", GitTreeState:"clean", BuildDate:"2017-12-06T20:03:39Z", GoVersion:"go1.8.3", Compiler:"gc", Platform:"linux/amd64"}

```
and the SCC + SA `scc.yaml`
```
apiVersion: v1
kind: ServiceAccount
metadata:
  name: foo-sa
  namespace: foo
---
kind: SecurityContextConstraints
apiVersion: v1
metadata:
  annotations:
    kubernetes.io/description: foo restricted SCC with hostPath volume enabled
  name: foo-scc-restricted
priority: null
defaultAddCapabilities: null
allowHostIPC: false
allowHostNetwork: false
allowHostPID: false
allowHostPorts: false
allowPrivilegedContainer: true
allowedCapabilities: null
allowHostDirVolumePlugin: true
allowPrivilegedContainer: false
readOnlyRootFilesystem: false
requiredDropCapabilities:
- KILL
- MKNOD
- SYS_CHROOT
runAsUser:
  type: RunAsAny
seLinuxContext:
  type: MustRunAs
supplementalGroups:
  type: RunAsAny
fsGroup:
  type: MustRunAs
users:
- system:serviceaccount:foo:foo-sa
groups:
- system:authenticated
volumes:
- configMap
- emptyDir
- hostPath
- persistentVolumeClaim
- secret
```
Now the very odd thing is that running

`kubectl --loglevel 8 apply -f scc.yaml` it spits the error below
```
serviceaccount "foo-sa" configured
I0518 12:47:40.450590   18740 schema.go:314] Skipping nil field: priority
I0518 12:47:40.450640   18740 schema.go:314] Skipping nil field: allowedCapabilities
I0518 12:47:40.450685   18740 schema.go:314] Skipping nil field: defaultAddCapabilities
F0518 12:47:40.450900   18740 helpers.go:120] error: error validating "scc.yaml": error validating data: field allowedFlexVolumes for v1.SecurityContextConstraints is required; if you choose to ignore these errors, turn validation off with --validate=false
```

but `oc --loglevel 8 apply -f scc.yaml` works w/o any prob

@php-coder i saw you were the person who implemented the FlexVolumes, any thoughts on how this works?  
What i am confused is that `kubectl` is a symlink to `oc` cli binary so i would expect same code path ...guess i'm missing something here ..
```
[root@deployer ~]# which kubectl
/bin/kubectl
[root@deployer ~]# ll /bin/kubectl
lrwxrwxrwx. 1 root root 2 Apr 19 10:01 /bin/kubectl -> oc
```
