### ISSUE TITLE
Allow to add a new component defined externally with `oc cluster add` 

### ISSUE THREAD

**Issue by cmoulliard** [openshift/origin#19848]
The new `oc cluster add` command allows to add a component, part of [a defined list](https://goo.gl/QoyiCj). Unfortunately, the list is static and can't be extended excepted if we commit new components within the origin openshift project.

Could it be possible to extend the existing code to provide a generic component that we could use to add a new component ? This component could be designed as an Ansible playbook executed within a docker container using a k8s job

`oc cluster add new-component name_of_component --url ...` 
where `--url` is the location of the project containing the component

E.g.
`oc cluster add new-component jenkins --url https://github.com/openshift/origin/tree/master/examples/jenkins`

Of course, it will be required to define in a `METADATA.yml` file the parameters to be used to execute the k8s job as ASB does [1], to pass an OpenShift template (if needed) ...

E.g of METADATA.yml

```
name: Jenkins Ephemeral 
description: This component allows to install an ephemeral Jenkins instance
namespace: 
Template:
  url: path of the OpenShift Template to be installed
  rbac : path of the OpenShift RBAC file
Job:
  name: name of the job
  docker-image: name of the job docker image containing the playbook to be executed [1]
  playbook_params:
       - name: PLAYBOOK_FILE
          value: post_installation.yml
        - name: INVENTORY_FILE
          value: cloud_host
        - name: ANSIBLE_PRIVATE_KEY_FILE
          value: /opt/app-root/src/.ssh/id_rsa/ssh-privatekey
        - name: ANSIBLE_HOST_KEY_CHECKING
          value: "False"
        - name: OPTS
          value: "-v --tags nexus"
```

[1] : https://github.com/openshift/origin/blob/master/pkg/oc/clusteradd/components/automation-service-broker/automation_service_broker.go#L52
[2] : https://github.com/cmoulliard/playbooks/blob/master/job.yaml#L16
