### ISSUE TITLE
buildconfig deletion leftover issue

### ISSUE THREAD

**Issue by odra** [openshift/origin#19862]
Deleting all buildconfigs from a project (`oc delete bc -n myproject --all`) doesn't delete all of them leaving one "leftover" buildconfig.

The leftover buildconfig removes all existing labels and contains the following annotations:

```
jenkins.openshift.io/generated-by: jenkins
jenkins.openshift.io/job-path: myproject/myproject-helloworld-android-pipeline-2
```

##### Version
oc v3.7.2+282e43f
kubernetes v1.7.6+a08f5eeb62
features: Basic-Auth GSSAPI Kerberos SPNEGO

openshift v3.9.0+4814d4a-3
kubernetes v1.9.1+a0ce1bc657

##### Steps To Reproduce

BuildConfig file:

```
kind: BuildConfig
apiVersion: v1
metadata:
  name: helloworld-android-pipeline-2
spec:
  source:
    git:
      uri: https://github.com/odra/helloworld-android-gradle.git
      ref: jenkins-apk-path
  strategy:
    jenkinsPipelineStrategy:
      env:
        -
          name: FH_CONFIG_CONTENT
          value: empty_content
        -
          name: BUILD_CONFIG
          value: debug
      jenkinsfilePath: Jenkinsfile
```

1. Create more than one buildconfig by running `oc create -f  build.yml -n myproject`
2. Delete all buildconfigs `oc delete bc -n myproject --all`

##### Current Result

One buildconfig was not deleted.

##### Expected Result

All buildconfigs should be deleted.
