### ISSUE TITLE
Jolokia port not named when using oc new-app which results in the Jolokia link not appearing in the OCP UI.

### ISSUE THREAD

**Issue by sammarland-rh** [openshift/origin#19881]
The DC created via the UI

```
        ports:
        - containerPort: 8778
          name: jolokia
          protocol: TCP
        - containerPort: 8080
          name: http
          protocol: TCP
        - containerPort: 8443
          name: https
          protocol: TCP
```

The DC created via the oc new-app command

```
        ports:
        - containerPort: 8080
          protocol: TCP
        - containerPort: 8443
          protocol: TCP
        - containerPort: 8778
          protocol: TCP
```

##### Version
./oc version
oc v3.9.27
kubernetes v1.9.1+a0ce1bc657
features: Basic-Auth

Server https://192.168.99.100:8443
openshift v3.9.0+46ff3a0-18
kubernetes v1.9.1+a0ce1bc657

##### Steps To Reproduce
Using the OpenJDK xPaas image to create with the defaults correctly names the Jolokia port in the deployment config.

Running this command which is equivalent to following the UI does not correctly annotate the port which results in the Jolokia link doesn't appear in the UI.

`./oc new-app --name=ocp-quickstart registry.access.redhat.com/redhat-openjdk-18/openjdk18-openshift:latest~https://github.com/jboss-openshift/openshift-quickstarts.git --context-dir=undertow-servlet`

##### Current Result
Using the new-app CLI on a Java application doesn't correctly annotate the Jolokia port in the DC.

##### Expected Result
The new-app CLI will annotate the DC in the same way that using the template through the UI does.
