### ISSUE TITLE
osc new-app is not using the right image stream for the build from

### ISSUE THREAD

**Issue by smarterclayton** [openshift/origin#1996]
Scenario:

1. Create an image stream in namespace openshift called "ruby", set dockerImageRepository to "openshift/ruby-20-centos7"
2. Run `osc new-app openshift/ruby~<url>`

Build config has:
```
    strategy:
      stiStrategy:
        builderImage: openshift/ruby-20-centos7
        clean: true
        image: openshift/ruby-20-centos7
```

which is wrong, it should be "from" -> "openshift/ruby:latest".
