### ISSUE TITLE
ImageChange trigger disabled but triggered on apply

### ISSUE THREAD

**Issue by victorvoronin** [openshift/origin#20172]
I have DeplymentConfig with ImageChange trigger configured with automatic=false. When I change form.image.name with apply command and deployment triggers with ImageChange clause.

##### Version
oc v3.7.0+7ed6862
kubernetes v1.7.6+a08f5eeb62

##### Steps To Reproduce
1. Create DC with the following trigger:
```
    triggers:
      - type: ConfigChange
      - imageChangeParams:
          automatic: false
          containerNames:
            - "helloworld"
          from:
            kind: ImageStreamTag
            name: "helloworld:v1"
            namespace: "test"
        type: ImageChange
```
2. Apply DC from file with the following section:
```
    triggers:
      - type: ConfigChange
      - imageChangeParams:
          automatic: false
          containerNames:
            - "helloworld"
          from:
            kind: ImageStreamTag
            name: "helloworld:v2"
            namespace: "test"
        type: ImageChange
```
##### Current Result
Deployment triggered with new image and clause "Image change"

##### Expected Result
DC updated but not triggered

##### Additional info
oc set triggers for this DC shows image trigger auto=false before and after apply
