### ISSUE TITLE
Failed to retrieve CRD resource of kind Project

### ISSUE THREAD

**Issue by adnanyaqoobvirk** [openshift/origin#20251]
Hi,

I have been trying to install Nuclio 0.5.4 in Openshift v3.9.0 and have been facing an issue related to custom resource creation and retrieval. Nuclio has `projects.nuclio.io` crd and creation of it works fine, listing it using `oc get projects.nuclio.io -n nuclio` works as well but when I try to get or describe specific resource like `oc get projects.nuclio.io/example-project -n nuclio`, It throws an error that resource not found.

![image](https://user-images.githubusercontent.com/7362694/42426508-12644b5c-835b-11e8-8c66-50d15f0df90c.png)

For more information: https://github.com/nuclio/nuclio/issues/874

##### Version
oc v3.9.0+ba7faec-1
kubernetes v1.9.1+a0ce1bc657
features: Basic-Auth GSSAPI Kerberos SPNEGO

openshift v3.9.0+ba7faec-1
kubernetes v1.9.1+a0ce1bc657

##### Steps To Reproduce
Here is simplified version of test scenairo:

1. Create a CRD with kind Project
```
apiVersion: "apiextensions.k8s.io/v1beta1"
kind: "CustomResourceDefinition"
metadata:
  name: "projects.example.io"
spec:
  group: "example.io"
  version: "v1beta1"
  scope: "Namespaced"
  names:
    plural: "projects"
    singular: "project"
    kind: "Project"
```
2. Create custom resource with kind Project
```
apiVersion: "example.io/v1beta1"
kind: "Project"
metadata:
  name: "example-project"
  namespace: "example"
```
3. Try to retrieve the newly created project using following command:

```
oc get projects.example.io/exmaple-project

OR

curl -k -H "Authorization: Bearer $(oc whoami -t)" https://$(OPENSHIFT_URL)/apis/example.io/v1beta1/namespaces/example/projects/example-project
```
##### Current Result
`Error from server (NotFound): projects.example.io "example-project" not found`

OR

```
{
  "kind": "Status",
  "apiVersion": "v1",
  "metadata": {},
  "status": "Failure",
  "message": "projects.example.io \"example-project\" not found",
  "reason": "NotFound",
  "details": {
    "name": "example-project",
    "group": "example.io",
    "kind": "projects"
  },
  "code": 404
}
```
##### Expected Result
Details of custom resource

##### Additional Information
`oc get all -o json -n example` output:

```
{
    "apiVersion": "v1",
    "items": [],
    "kind": "List",
    "metadata": {
        "resourceVersion": "",
        "selfLink": ""
    }
}

```
