### ISSUE TITLE
Projected volumes do not work with DeploymentConfig

### ISSUE THREAD

**Issue by megakoresh** [openshift/origin#20329]
If you attempt to define a projected volume 

##### Version
```
oc v3.9.0+191fece
kubernetes v1.9.1+a0ce1bc657
features: Basic-Auth

Server https://192.168.64.3:8443
openshift v3.9.0+71543b2-33
kubernetes v1.9.1+a0ce1bc657
```
##### Steps To Reproduce
Run the following template:
```yaml
apiVersion: v1
kind: Template
metadata:
  name: at-auth-api
parameters:
- description: Memes
  value: 'https://image-cdn.neatoshop.com/styleimg/68210/none/black/default/374184-19;1515809702i.jpg'
  name: MEMES
  required: true
- description: Nodejs version
  value: '10'
  name: VERSION_TAG
  required: true
- description: Swag
  name: SWAG
  value: '(⌐■_■)'
  required: true
objects:
- apiVersion: v1
  data:
    config.json: |-
      {
        "swag": "${SWAG}",
      }
  kind: ConfigMap
  metadata:
    name: my-config

- apiVersion: v1
  stringData:
    secrets.json: |-
      {
        "dank_memes": "${DANK_MEMES}"
      }
  kind: Secret
  metadata:
    name: my-secret
  type: Opaque

- apiVersion: v1
  kind: DeploymentConfig
  metadata:
    name: node-sample
  spec:
    replicas: 1
    selector:
      deploymentconfig: node-sample
    strategy:
      type: Rolling
    template:
      metadata:
        labels:
          deploymentconfig: node-sample
      spec:
        containers:
        - name: at-auth-api
          image: node:${VERSION_TAG}
          imagePullPolicy: Always
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          volumeMounts:
          - name: all-configs
            mountPath: /etc/at-auth-api
            readOnly: true
        dnsPolicy: ClusterFirst
        restartPolicy: Always
        schedulerName: default-scheduler
        terminationGracePeriodSeconds: 30
        volumes:
        - name: all-configs
          projected:
            defaultMode: 420
            sources:
            - secret:            
                secretName: my-secret
              items:
              - key: secrets.json
                path: secrets.json
            - configMap: 
              name: my-config
              items:
                - key: config.json
                  path: config.json
                  mode: 0664
    test: false
    triggers:
    - type: ConfigChange
    - imageChangeParams:
        automatic: true
        containerNames:
          - nodejs
        from:
          kind: ImageStreamTag
          name: node:${VERSION_TAG}
      type: ImageChange
```

##### Current Result
```json
Cannot create deployment config "at-auth-api". DeploymentConfig "at-auth-api" is invalid: 
[spec.template.spec.volumes[0].projected.name: Required value, spec.template.spec.containers[0].volumeMounts[0].name: Not found: "at-auth-api-configs"]
```
##### Expected Result
The deployment config runs pods with projected volumes.

##### Additional Information
Running this on latest minishift release.
