### ISSUE TITLE
Can't provision volumes with Ceph RBD StorageClass

### ISSUE THREAD

**Issue by madddi** [openshift/origin#20363]
Hi,

I'm unable to provision Ceph RBD volumes with OpenShift 3.9. This configuration worked with OpenShift 3.6 and 3.7 and broke with 3.9. When creating a PVC, the master logs this error:

```
Jul 19 16:09:25 my.hostname origin-master-controllers[18831]: W0719 16:09:25.856179   18831 rbd_util.go:404] failed to create rbd image, output 2018-07-19 16:09:25.826539 7f85843c47c0 -1 did not load config file, using default settings.
Jul 19 16:09:25 my.hostname origin-master-controllers[18831]: rbd: extraneous parameter --image-feature
```

The issue sounds a lot like kubernetes/kubernetes#63648, but I can't simply change our storage backend... The StorageClass looks like this:

```yaml
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: ceph
  annotations:
    storageclass.kubernetes.io/is-default-class: "true"
parameters:
  adminId: ceph-admin
  adminSecretName: ceph-admin
  adminSecretNamespace: ceph-infra
  monitors: 10.100.16.1:6789,10.100.16.2:6789,10.100.16.3:6789
  pool: ceph-pool
  userId: ceph-user
  userSecretName: ceph-user
provisioner: kubernetes.io/rbd
reclaimPolicy: Delete
```

##### Version
```
# rbd --version
ceph version 0.94.5 (9764da52395923e0b32908d83a9f7304401fee43)
# ceph --version
ceph version 0.94.5 (9764da52395923e0b32908d83a9f7304401fee43)
# oc version
oc v3.9.0+ba7faec-1
kubernetes v1.9.1+a0ce1bc657
features: Basic-Auth GSSAPI Kerberos SPNEGO

Server https://my.hostname:443
openshift v3.9.0+ba7faec-1
kubernetes v1.9.1+a0ce1bc657
# lsb_release -a
LSB Version:	:core-4.1-amd64:core-4.1-noarch
Distributor ID:	CentOS
Description:	CentOS Linux release 7.5.1804 (Core) 
Release:	7.5.1804
Codename:	Core
```

##### Steps To Reproduce
1. Create a `kubernetes.io/rbd` `StorageClass`
2. Create a PVC
3. See errors
