### ISSUE TITLE
oc cluster up fails to come up with existing base directory

### ISSUE THREAD

**Issue by mfojtik** [openshift/origin#20462]
Reproduced on HEAD and images build from the HEAD.

After running:
```
$ oc cluster up --base-dir=/tmp/cluster-up-01 --loglevel=5 --server-loglevel=5 --tag=latest
```

The cluster will come up, healthy, without any problem. Then when you run `oc cluster down` and run the same command as above, it fails to back up with:

```
Error: failed to install "openshift-service-cert-signer-operator": Docker run error rc=1; caused by: Docker run error rc=1
```

The only error I can see is:

`+ oc apply --namespace=openshift-core-operators --config=/kubeconfig.kubeconfig -f -
Error from server (UnsupportedMediaType): the body of the request was in an unknown format - accepted media types include: application/json-patch+json, application/merge-patch+json`

**Comment by mfojtik** [comment]
This turned out to a possible bug in `oc apply` logic where we have cluster scoped CRD resource in template and `apply` is trying to enforce an empty namespace to it which will result in corrupted PATCH.

We should not try to patch namespace or name fields (?).

**Comment by soltysh** [comment]
@liggitt per our conversation yesterday, here's the smallest possible reproducer of the problem:
```bash
oc apply --namespace=openshift-core-operators -f ~/patch.yaml
```
```yaml
apiVersion: v1
items:
- apiVersion: servicecertsigner.config.openshift.io/v1alpha1
  kind: ServiceCertSignerOperatorConfig
  metadata:
    name: instance
  spec:
    imagePullSpec: openshift/origin-service-serving-cert-signer:v3.11
    logging:
      level: 4
    managementState: Managed
    replicas: 1
    version: 3.10.0
kind: List
metadata: {}
```

This results in patch which looks like this: `{"metadata":{"namespace":""}}` with content type set to `application/strategic-merge-patch+json`, and the response from the server is then: `the body of the request was in an unknown format - accepted media types include: application/json-patch+json, application/merge-patch+json`. That's why my initial approach in #20468 was to go with changing the content type.
