### ISSUE TITLE
Do templates support parameter arrays; if so how do you use them?

### ISSUE THREAD

**Issue by spicysomtam** [openshift/origin#20561]
Do templates support parameter arrays; if so how do you use them?

##### Version
oc v3.6.0+c4dd4cf
kubernetes v1.6.1+5115d708d7
features: Basic-Auth GSSAPI Kerberos SPNEGO

Server https://oshift-api.jfk3.qa.bamtech.co:8443
openshift v3.6.173.0.83
kubernetes v1.6.1+5115d708d7

##### Steps To Reproduce
We want to populate multiple values to say supplementalGroups:
      securityContext:
        supplementalGroups:
        - 14051
        - 14052
        - 48
        - 65533
        - 9050
OR
      securityContext:
        supplementalGroups: [14051,14052,48,65533,9050]

##### Additional Information

I tried loads of different ways to try and populate this in a template, and could not find any example of doing it, other than a parameter for each element, but then that limits you to a set number of elements.

**Comment by spicysomtam** [comment]
We found a way round it:
```
      spec:
        securityContext:
         supplementalGroups: "${{SUPPLEMENTAL_GROUPS}}"

parameters:
- description: Supplemental linux groups
  name: SUPPLEMENTAL_GROUPS
  value: "[14051, 14052, 48, 65533, 9050]"
```
