### ISSUE TITLE
How to confiure HTPasswdPasswordIdentityProvider in V3.10

### ISSUE THREAD

**Issue by Mikedu1988** [openshift/origin#20704]
[provide a description of the issue]
I recently upgraded my openshift cluster to 3.10, I set my master config file like below:

```yaml
identityProviders:
  - challenge: true
    login: true
    mappingMethod: claim
    name: my-provider
    provider:
      apiVersion: v1
      kind: HTPasswdPasswordIdentityProvider
      file: /root/user.htpasswd
```

Then I ran master-restart api controllers, I get return value 255.
And the master service is not started.
Then I ran master-restart api  and master-restart controllers separately, I sometimes get 2 sometime get 255.
Cloud anyone please tell me what does the return value mean and how to configure HTPasswdPasswordIdentityProvider in 3.10. 

BTW, I have rolled back to allow all provider and works fine by now.
##### Version
[provide output of the `openshift version` or `oc version` command]
openshift v3.10.0+20c7bd1-8
kubernetes v1.10.0+b81c8f8
##### Steps To Reproduce
1. configure master.yaml as below:

```yaml
name: my-provider
provider:
      apiVersion: v1
      kind: HTPasswdPasswordIdentityProvider
      file: /root/user.htpasswd
```

2. master-restart api controllers

##### Current Result
master service not started. 
##### Expected Result
1. need to understand the return value of master-restart
2. please help me configure HTPasswdPasswordIdentityProvider
##### Additional Information
[try to run `$ oc adm diagnostics` (or `oadm diagnostics`) command if possible]
[if you are reporting issue related to builds, provide build logs with `BUILD_LOGLEVEL=5`]
[consider attaching output of the `$ oc get all -o json -n <namespace>` command to the issue]
[visit https://docs.openshift.org/latest/welcome/index.html]
