### ISSUE TITLE
When user create, can't input uid as parameter?

### ISSUE THREAD

**Issue by fisache** [openshift/origin#20754]
when user create, can't input uid as parameter?

##### Version
v3.9

##### Steps To Reproduce
user.yaml
```
apiVersion: user.openshift.io/v1
groups: null
kind: User
metadata:
  name: xxx
  uid: xxxx-xxxx-xxxx
```
```
oc create -f user.yaml
```

##### Current Result
create user with other uid

##### Expected Result
create user with my uid in metadata
