### ISSUE TITLE
OKD 3.9 Ansible Service Broker ETCD certificate problem

### ISSUE THREAD

**Issue by uocxp** [openshift/origin#20845]
i have a problem with the Ansible Service Broker. When i view the events in the default project, i get 
```
"Error getting catalog payload for broker "ansible-service-broker"; received zero services; at least one 
service is required". 
```
I am suspecting that this issue is due to an error in the ASB-ETCD. The logs of the ASB-ETCD pod show the following error 
```

  | 2018-09-03 15:41:10.840386 I |embed: ClientTLS: cert = /etc/tls/private/tls.crt, key = /etc/tls/private/tls.key, ca = , trusted-ca = /var/run/etcd-auth-secret/ca.crt, client-cert-auth = true, crl-file =
  | 2018-09-03 15:41:10.840984 I \| etcdserver/membership: added member 8e9e05c52164694d [http://localhost:2380 ] to cluster cdf818194e3a8c32
  | 2018-09-03 15:41:10.843804 N \| etcdserver/membership: set the initial cluster version to 3.3
  | 2018-09-03 15:41:10.843851 I \| etcdserver/api: enabled capabilities for version 3.3
  | 2018-09-03 15:41:12.271738 I \| raft: 8e9e05c52164694d is starting a new election at term 2
  | 2018-09-03 15:41:12.271760 I \| raft: 8e9e05c52164694d became candidate at term 3
  | 2018-09-03 15:41:12.271779 I \| raft: 8e9e05c52164694d received MsgVoteResp from 8e9e05c52164694d at term 3
  | 2018-09-03 15:41:12.271792 I \| raft: 8e9e05c52164694d became leader at term 3
  | 2018-09-03 15:41:12.271800 I \| raft: raft.node: 8e9e05c52164694d elected leader 8e9e05c52164694d at term 3
  | 2018-09-03 15:41:12.277938 I \| embed: ready to serve client requests
  | 2018-09-03 15:41:12.278333 I \| etcdserver: published {Name:default ClientURLs:[https://asb-etcd.openshift-ansible-service-broker.svc:2379 ]} to cluster cdf818194e3a8c32
  | 2018-09-03 15:41:12.283689 I \| embed: serving client requests on [::]:2379
  | 2018-09-03 15:41:12.293754 I \| embed: rejected connection from "127.0.0.1:53690" (error "tls: failed to verify client's certificate: x509: certificate signed by unknown authority", ServerName "")
  | WARNING: 2018/09/03 15:41:12 Failed to dial 0.0.0.0:2379: connection error: desc = "transport: authentication handshake failed: remote error: tls: bad certificate"; please retry.
```
##### ASB configmaps
```
registry:
  - type: dockerhub
    name: dh
    url:  https://registry.hub.docker.com
    org:  ansibleplaybookbundle
    tag:  latest
    white_list: [".*-apb$"]
    user: "xxxx"
    pass: "xxxxxxxx"
  - type: local_openshift
    name: localregistry
    namespaces: ['openshift']
    white_list: [.*-apb$]
dao:
  etcd_host: asb-etcd.openshift-ansible-service-broker.svc
  etcd_port: 2379
  etcd_ca_file: /var/run/secrets/kubernetes.io/serviceaccount/service-ca.crt
  etcd_client_cert: /var/run/asb-etcd-auth/client.crt
  etcd_client_key: /var/run/asb-etcd-auth/client.key
log:
  stdout: true
  level: info
  color: true
openshift:
  host: ""
  ca_file: ""
  bearer_token_file: ""
  namespace: openshift-ansible-service-broker
  sandbox_role: edit
  image_pull_policy: Always
  keep_namespace: false
  keep_namespace_on_error: true
broker:
  dev_broker: false
  bootstrap_on_startup: true
  refresh_interval: 600s
  launch_apb_on_bind: false
  output_request: false
  recovery: true
  ssl_cert_key: /etc/tls/private/tls.key
  ssl_cert: /etc/tls/private/tls.crt
  auto_escalate: False
  auth:
    - type: basic
      enabled: false
```

##### Version
openshift v3.9.0+ba7faec-1
kubernetes v1.9.1+a0ce1bc657

##### Expected Result
ASB works without problem

##### Additional Information
[ansible inventory](https://gist.github.com/uocxp/f554446fc3004dd513c3ef0206afe597)
