### ISSUE TITLE
Router supporting different paths on same domain

### ISSUE THREAD

**Issue by devops-42** [openshift/origin#20986]
Hi,

I need to use the OpenShift router as a gateway for several services behind. Each service will be reached by a sub-path within a domain:

www.example.com/foo -> Service "foo"
www.example.com/bar -> Service "bar"

##### Version
oc v3.9.0+191fece
kubernetes v1.9.1+a0ce1bc657
features: Basic-Auth

Server https://172.19.3.100:8443
openshift v3.10.0+e3465d0-44
kubernetes v1.10.0+b81c8f8

##### Steps To Reproduce
- Deploy "foo" and "bar" service
- Create a route for "foo":

```
apiVersion: v1
kind: Route
metadata:
  name: route-foo
spec:
  host: www.example.com
  path: "/foo"
  to:
    kind: Service
    name: foo
```

- Create a route for "bar"

```
apiVersion: v1
kind: Route
metadata:
  name: route-bar
spec:
  host: www.example.com
  path: "/bar"
  to:
    kind: Service
    name: bar
```

##### Current Result

OpenShift throws an error message:

> Requested host www.example.com was rejected by the router. Reason: route route-foo already exposes www.example.com and is older. 

##### Expected Result

Both services can be reached by its sub-paths.

Suggestion: Extension/Modification of the Route template syntax like:

```
apiVersion: v1
kind: Route
metadata:
  name: route-services
spec:
  host: www.example.com
  - path: "/foo"
    to:
      kind: Service
      name: foo
  - path: "/bar"
    to:
      kind: Service
      name: bar
```
