### ISSUE TITLE
openshift build failed : spec.source.git: Invalid value: "":

### ISSUE THREAD

**Issue by irfanjs** [openshift/origin#20990]
Hello,
i am using jenkins and openshift to create the build and trigger the deployment. 
following is the yaml file : 

```
apiVersion: v1
kind: List
metadata: {}
items:
- apiVersion: v1
  kind: BuildConfig
  metadata:
    name: petclinic-pipeline
  spec:
    source:
      git:
       uri: <<git url>>
      type: Git
    strategy:
      type: JenkinsPipeline
      jenkinsPipelineStrategy:
        jenkinsfilePath: Jenkinsfile
    triggers:
    - generic:
        secret: FiArdDBH
      type: Generic
```
and the jenkins file is as follows : 

```
node {
  stage('Source Checkout') {
    git url: "git url"
  }
  
   stage('Build') {
      git url: "git url"
      sh "/var/lib/jenkins/apache-maven-3.5.4/bin/mvn clean package -Dorg.jenkinsci.plugins.durabletask.BourneShellScript.HEARTBEAT_CHECK_INTERVAL=300 -DskipTests=true"
      stash name:"jar", includes:"target/a.jar"
    }
    
  stage('Build Image') {
    unstash name:"jar"
    sh "oc start-build petclinic-pipeline --from-file=target/a.jar --follow"
  }
 } 
```
and getting following error : 

> + oc start-build petclinic-pipeline --from-file=target/a.jar --follow
> Uploading file "target/a.jar" as binary input for the build ...
> The Build "petclinic-pipeline-20" is invalid: spec.source.git: Invalid value: "": must be set when using Jenkins Pipeline strategy with Jenkinsfile from a git repo

not able to understand where the issue is , is it something like , spec source git should not be used in yaml file when using jenkins strategy ??
please suggest 
Regards,
