### ISSUE TITLE
`oc new-app` fails when webhook for buildConfig is given by `secretReference` param

### ISSUE THREAD

**Issue by JaniszM** [openshift/origin#21237]
I have an yml template for couple of object. One of the objects is `buildConfig` which have configured generic webhook as trigger according to instructions given here: https://docs.openshift.com/container-platform/3.10/dev_guide/builds/triggering_builds.html#generic-webhooks. I have also added correct secret to the namespace (defined in another yml template). When I am trying to create objects I am getting error.

The very weird thing is when I am adding these templates by OpenShift console `Add to project -> Import YAML/JSON` and check all boxes then all is fine, buildConfig is created and webhook is working.

##### Version
oc v3.7.1+ab0f056
kubernetes v1.7.6+a08f5eeb62
features: Basic-Auth GSSAPI Kerberos SPNEGO

OpenShift Master:
    v3.10.14 
Kubernetes Master:
    v1.10.0+b81c8f8 
OpenShift Web Console:
    v3.10.14 

##### Steps To Reproduce
1. Add test template to project: `oc create -f build-problem.yml`
2. Create resources: `oc new-app --template="build-problem"`

##### Current Result
buildConfig not created with error:
```
W1012 14:42:33.013918    9656 newapp.go:1048] Unable to check for circular build output: Unable to check for circular build input/outputs: imagestreams.image.openshift.io "test-config" not found
--> Creating resources ...
    secret "my.webhook" created
    error: BuildConfig "test-config" is invalid: spec.triggers[2].generic: Invalid value: build.WebHookTrigger{Secret:"", AllowEnv:true, SecretReference:(*build.SecretLocalReference)(nil)}: must provide a value for at least one of secret or secretReference
--> Failed
```

##### Expected Result
buildConfig should be created.

##### Additional Information
Sample template to recreate problem:
```yml
apiVersion: v1
kind: Template
metadata:
  name: build-problem
  annotations:
    iconClass: "icon-redis"
    tags: "secret,bug"
  
objects:
- apiVersion: v1
  kind: Secret
  type: Opaque
  metadata:
    name: my.webhook
    annotations:
      description: "Web Hook Secret Key."
  data:
    WebHookSecretKey: dGVzdA==
- apiVersion: v1
  kind: BuildConfig
  metadata:
    name: test-config
    labels:
      application: test-config
  spec:
    source:
      type: Git
      git:
        uri: http://some.url.com
        ref: 'master'
      contextDir: ''
    runPolicy: Serial
    strategy:
      type: Source
      sourceStrategy:
        from:
          kind: ImageStreamTag
          namespace: openshift
          name: java:8
        forcePull: true
    output:
      to:
        kind: ImageStreamTag
        name: test-config:latest
    triggers:
      - type: ConfigChange
      - type: ImageChange
        imageChange: {}
      - type: Generic
        generic:
          allowEnv: true
          secretReference:
            name: my.webhook
```
