### ISSUE TITLE
Add Generic trigger option to pass entire request as single env variable 

### ISSUE THREAD

**Issue by matihost** [openshift/origin#21240]
Generic trigger is useful to mitigate other triggers limitations - but it limits only to particular format request. It would true generic if it support any kind of paylod request and delegate that to BC.
It make sense for BuildConfigs  with  source: type: None and  strategy:   jenkinsPipelineStrategy.

Feature proposal:
- a flag to Generic trigger to so that it passes entire content of the hook request to BuildConfig environment variable.

It would be very useful for no-source type, Jenkins file based pipelines like this:
(added `passRequestAsEnv: true` as name proposal for this flag)

```
apiVersion: build.openshift.io/v1
kind: BuildConfig
metadata:
name: "some-name"
spec:
runPolicy: Parallel
strategy:
  jenkinsPipelineStrategy:
	env:
	- name: REQUEST
	jenkinsfile: |
	  #!groovy

	  def parsedRq = env.REQUEST ? readJSON(text:  env.REQUEST) : null
	  
	  //....
successfulBuildsHistoryLimit: 1
failedBuildsHistoryLimit: 2
triggers:
- type: "Generic"
  generic:
	allowEnv: true
	secret: 'some-name'
        passRequestAsEnv: true
```
