### ISSUE TITLE
Update example to show custom pod metrics

### ISSUE THREAD

**Issue by suppandi** [openshift/origin#21245]
The example at https://github.com/openshift/origin/blob/master/examples/prometheus/prometheus.yaml should show how to scrape custom metrics from pods. I tried taking the example and adding 
```
      - job_name: 'kubernetes-pods'

        tls_config:
          ca_file: /var/run/secrets/kubernetes.io/serviceaccount/ca.crt
          # TODO: this should be per target
          insecure_skip_verify: true
        scheme: https

        kubernetes_sd_configs:
        - role: node

        relabel_configs:
        - source_labels: [__meta_kubernetes_pod_label_app]
          regex: myapp
          action: keep
```

But it is not doing anything. I donot see any logs referencing pods. Could the example be updated to show how to do custom metrics from pods.

##### Version
```
oc v3.9.0+191fece
kubernetes v1.9.1+a0ce1bc657
features: Basic-Auth GSSAPI Kerberos SPNEGO

Server https://10.4.0.163:8443
openshift v3.9.0+71543b2-33
kubernetes v1.9.1+a0ce1bc657
```
