### ISSUE TITLE
oc set volume unable to create volume for subpath and existing volumeMount for enclosing directory

### ISSUE THREAD

**Issue by akram** [openshift/origin#21336]
```
oc version
oc v3.11.0+0cbc58b
kubernetes v1.11.0+d4cacc0
features: Basic-Auth

Server https://my-server:8443
openshift v3.11.0+84fe0ad-23
kubernetes v1.11.0+d4cacc0
```

oc set volume cannot add a volume with sub-path specified when an enclosing mount-path already exist.
```
oc set volume --add dc/jenkins -t configmap --mount-path=/var/lib/jenkins \
                         --sub-path=scriptApproval.xml --configmap-name=jenkins-approval-scripts \
                         --name=script-approval
```
it fails with error:
```
error: deploymentconfigs/jenkins volume mount '/var/lib/jenkins' already exists for container 'jenkins'
```
If I use --overwrite, it forcibely creates the volume, but overrides the enclosing mount.

If I change the mount-path to /var/lib/jenkins2, then it works:
```
oc set volume --add dc/jenkins -t configmap --mount-path=/var/lib/jenkins2 \
                         --sub-path=scriptApproval.xml --configmap-name=jenkins-approval-scripts \
                         --name=script-approval
```

and it creates:
```
        volumeMounts:
        - mountPath: /var/lib/jenkins
          name: jenkins-data
        - mountPath: /var/lib/jenkins2
          name: jenkins-data
          subPath: scriptApproval.xml
```

If run oc edit dc jenkins and change the mountPath /var/lib/jenkins2 to /var/lib/jenkins then, it saves correctly and produces the required result
