### ISSUE TITLE
service definition not accepting valid YAML

### ISSUE THREAD

**Issue by nstrug** [openshift/origin#21342]
Defining a service does not accept valid YAML for targetPort. Specifically, this string cannot be quoted. This is problematic when using the k8s ansible module and variable substitution, which results in the value being quoted. This doesn't seem to be a problem with any other value in the definition (such as port), just targetPort.
##### Version
3.10.45

##### Steps To Reproduce
1. Attempt to create a service with the following definition:
```
apiVersion: "v1"
kind: "Service"
metadata:
  name: "myfooservice"
  namespace: "mynewproject"
spec:
  clusterIP: "172.30.232.245"
  ports:
  - name: "mynewservice"
    port: "133"
    protocol: "TCP"
    targetPort: "1555"
  sessionAffinity: "None"
  type: "ClusterIP"
status:
  loadBalancer: {}
```
This results in the error:
```The Service "myfooservice" is invalid: spec.ports[0].targetPort: Invalid value: "1555": must contain at least one letter or number (a-z, 0-9)```

2. Now edit the definition and remove the quotes from 1555 and the service will be created.

##### Additional Information
[try to run `$ oc adm diagnostics` (or `oadm diagnostics`) command if possible]
[if you are reporting issue related to builds, provide build logs with `BUILD_LOGLEVEL=5`]
[consider attaching output of the `$ oc get all -o json -n <namespace>` command to the issue]
[visit https://docs.openshift.org/latest/welcome/index.html]
