### ISSUE TITLE
LDAPPasswordIdentityProvider provider "ldap": LDAP Result Code 200 "Network Error": EOF

### ISSUE THREAD

**Issue by xiaoxi1989** [openshift/origin#21374]
##### Version
oc version
```
oc v3.11.0+57f8760-31
kubernetes v1.11.0+d4cacc0
features: Basic-Auth GSSAPI Kerberos SPNEGO
Server https://cxx:8443
openshift v3.11.0+57f8760-31
kubernetes v1.11.0+d4cacc0
```

##### Steps To Reproduce
1. [step 1]
master-config.yaml
```
identityProviders:
  - challenge: true
    login: true
    mappingMethod: claim
    name: ldap
    provider:
      apiVersion: v1
      kind: LDAPPasswordIdentityProvider
      attributes:
        id:
        - dn
        email:
        - mail
        name:
        - cn
        preferredUsername:
        - cn
      bindDN: "cn=admin,dc=cxx,dc=com"
      bindPassword: "admin"
      ca: "ldap-ca-bundle.crt"
      insecure: false
      url: "ldaps://xxxx:636/ou=Users,dc=cxx,dc=com"
```
2. [step 2]

login by ldap user.

##### Current Result

`E1029 05:39:20.860370   26588 login.go:174] Error authenticating "chenxiaoxi" with provider "ldap": LDAP Result Code 200 "Network Error": EOF`

##### Expected Result

login success.

##### Additional Information
**use ldap:389 works fine.**
