### ISSUE TITLE
[Feature] ClusterRole/Role "resourceNames" support regex or wildcard?

### ISSUE THREAD

**Issue by penglongli** [openshift/origin#21423]
## Intro
I have a DeploymentConfig `test-nginx`, with a pod `test-nginx-33-vtpmq`.
I want to create an user `test`, and create Role with `pods/exec` resource for this account.

As follows is `role.yml`
```
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  annotations:
    openshift.io/description: role example
  name: pod-executer
rules:
- apiGroups:
  - ""
  resources:
  - pods/attach
  - pods/exec
  - pods/portforward
  - pods/proxy
  resourceNames:
  - test-nginx-33-vtpmq
  verbs:
  - create
  - delete
  - deletecollection
  - get
  - list
  - patch
  - update
  - watch
```

And then, i `add-role-to-user`
```
~# oc adm  policy add-role-to-user pod-executer test -n test-project
```

Now, it's okay. I can attach `test-nginx-33-vtpmq` pod, and run some commands in container.

## Question
Please attention `resourceNames` in role.yml, there can't replace `test-nginx-33-vtpmq` with `test-nginx-*`. OpenShift doesn't support this.
