### ISSUE TITLE
oc apply prune does not pruning resources not listed in the template

### ISSUE THREAD

**Issue by JaniszM** [openshift/origin#21433]
Looks like `oc apply` command with `--prune` option is not pruning objects not listed in passed config. According to `oc apply` documentation and behavior of the `kubectl apply` missing objects in the passed template should be deleted from the cluster. Of course option `--save-config` is used.

##### Version
oc v3.10.45
kubernetes v1.10.0+b81c8f8
features: Basic-Auth GSSAPI Kerberos SPNEGO

Server https://container-prod-***:8443
openshift v3.11.16
kubernetes v1.11.0+d4cacc0

##### Steps To Reproduce
1. Create template: `oc create -f prune-test.yml --save-config`
2. Process the template: `oc process prune-test --labels='project=prune-test,application=prune-app' | oc apply -l project=prune-test --prune -f -`
3. Now there are 2 objects, `service` and `route` with given labels. Update template by removin for e.g. route resource from the _prune-test.yml_ file: `oc replace -f prune-test.yml --save-config`
4. Update resources: `oc process prune-test --labels='project=prune-test,application=prune-app' | oc apply -l project=prune-test --prune -f -`

##### Current Result
Resources `Service` and `Route` are still present in the project.

##### Expected Result
Resource `Route` should be removed while it is not included in the config. Resource `Service` should be still present on cluster.

##### Additional Information
Sample _prune-test.yml_ file:

```yml
apiVersion: v1
kind: Template
metadata:
  name: prune-test
  annotations:
    iconClass: "icon-redis"
    tags: "prune"

parameters:
- name: APP_NAME
  value: "prune-test"
  
objects:
- apiVersion: v1
  kind: Service
  metadata:
    name: ${APP_NAME}
    annotations:
      description: "Test service for ${APP_NAME}."
    labels:
      application: ${APP_NAME}
  spec:
    ports:
      - port: 8080
        targetPort: 8080
    selector:
      deploymentConfig: ${APP_NAME}
- apiVersion: v1
  kind: Route
  metadata:
    name: ${APP_NAME}
    annotations:
      description: "Route for application's http service."
    labels:
      application: ${APP_NAME}
  spec:
    host: test.kokon.pl
    to:
      kind: Service
      name: ${APP_NAME}
```
