### ISSUE TITLE
Environment variable with a DOT in them from ConfigMap

### ISSUE THREAD

**Issue by jam01** [openshift/origin#21466]
Environment variables that contain dots are not applied if they come from a ConfigMap. If I add the environment variables directly, as in not through the confiMap then it all works just fine.

##### Version
oc v3.11.0+0cbc58b
kubernetes v1.11.0+d4cacc0
features: Basic-Auth GSSAPI Kerberos SPNEGO

Server https://192.168.42.139:8443
kubernetes v1.11.0+d4cacc0

##### Steps To Reproduce
1. Create a deployment config with envFrom.configMapRef with variables with dots
```
- kind: ConfigMap
  apiVersion: v1
  metadata:
    name: ${APPLICATION_NAME}-config
  data:
    http.port: "8081"
- kind: DeploymentConfig
  apiVersion: v1
  metadata:
    name: ${APPLICATION_NAME}
  spec:
    template:
      spec:
        containers:
        - name: ${APPLICATION_NAME}
          image: ${APPLICATION_NAME}-runtime
          envFrom:
          - configMapRef:
              name: ${APPLICATION_NAME}-config
```
2. Deploy

##### Current Result
Error: "Config map test-config contains keys that are not valid environment variable names. Only config map keys with valid names will be added as environment variables. "

##### Expected Result
Environment variables applied normally.

##### Additional Information
I'd guess it's a left over bug from [#8771](https://github.com/openshift/origin/issues/8771)

**Comment by ObviousDWest** [comment]
I hit a similar issue. It turned out to be the use of "sh", which seems to strip dotted environment variables from its available local variables. When I used "bash" instead, the dotted variables were available.

**Comment by thiDucTran** [comment]
> I hit a similar issue. It turned out to be the use of "sh", which seems to strip dotted environment variables from its available local variables. When I used "bash" instead, the dotted variables were available.

@ObviousDWest can you explain? you used bash vs. sh to do ...?

**Comment by thiDucTran** [comment]
@jam01 ...i was able to create configmap like this...we placed single quotes around our values.

```
apiVersion: v1
kind: ConfigMap
metadata:
  name: config-system
data:
  SERVERS: '10.0.0.0:111'
  spring.profiles.active: 'common,azure,sit'
  spring.config.location: 'classpath:/,file:/config/,file:/config-common/,file:/config-azure/'
```

**Comment by thiDucTran** [comment]
@jam01 we did it like this

`configmap.yml`

```
apiVersion: v1
kind: ConfigMap
metadata:
  name: config-system
data:
  spring.profiles.active: 'common,azure,sit'
  spring.config.location: 'classpath:/,file:/config/,file:/config-common/,file:/config-azure/'
```

`deploy.yml`
```
    spec:
      containers:
        - env:
            - name: spring.profiles.active
              valueFrom:
                configMapKeyRef:
                  name: config-system
                  key: spring.profiles.active

            - name: spring.config.location
              valueFrom:
                configMapKeyRef:
                  name: config-system
                  key: spring.config.location
```
