### ISSUE TITLE
Prometheus not able to get metrics from registry instance

### ISSUE THREAD

**Issue by prasenforu** [openshift/origin#21531]
OC Version 3.9

Prometheus not able to get metrics from registry instance.

Based on following URL we are able to enable metric in registry container.

https://docs.openshift.com/container-platform/3.9/install_config/registry/extended_registry_configuration.html#docker-registry-configuration-reference-openshift

https://docs.openshift.com/container-platform/3.9/install_config/registry/accessing_registry.html#accessing-registry-metrics

```
oc describe svc docker-registry

Name:              docker-registry
Namespace:         default
Labels:            docker-registry=default
Annotations:       prometheus.openshift.io/password=Passw0rd
                   prometheus.openshift.io/port=5000
                   prometheus.openshift.io/scrape=true
                   prometheus.openshift.io/username=prometheus
Selector:          docker-registry=default
Type:              ClusterIP
IP:                172.30.52.223
Port:              5000-tcp  5000/TCP
TargetPort:        5000/TCP
Endpoints:         10.130.0.99:5000
Session Affinity:  ClientIP
Events:            <none>
```

Curl command from docker registry container:

```
curl -k -s -u -asd:Passw0rd https://localhost:5000/extensions/v2/metrics


# HELP go_gc_duration_seconds A summary of the GC invocation durations.
# TYPE go_gc_duration_seconds summary
go_gc_duration_seconds{quantile="0"} 4.0836e-05
go_gc_duration_seconds{quantile="0.25"} 6.7201e-05
go_gc_duration_seconds{quantile="0.5"} 8.126e-05
go_gc_duration_seconds{quantile="0.75"} 0.000141178
go_gc_duration_seconds{quantile="1"} 0.002147467
go_gc_duration_seconds_sum 0.015416893
go_gc_duration_seconds_count 91
# HELP go_goroutines Number of goroutines that currently exist.
# TYPE go_goroutines gauge
go_goroutines 16

# TYPE go_memstats_other_sys_bytes gauge
go_memstats_other_sys_bytes 532748
# HELP go_memstats_stack_inuse_bytes Number of bytes in use by the stack allocator.
# TYPE go_memstats_stack_inuse_bytes gauge
go_memstats_stack_inuse_bytes 589824
# HELP go_memstats_stack_sys_bytes Number of bytes obtained from system for stack allocator.
# TYPE go_memstats_stack_sys_bytes gauge
go_memstats_stack_sys_bytes 589824
# HELP go_memstats_sys_bytes Number of bytes obtained from system.
# TYPE go_memstats_sys_bytes gauge
go_memstats_sys_bytes 1.6562424e+07
# HELP go_threads Number of OS threads created
# TYPE go_threads gauge
go_threads 8
# HELP http_request_duration_microseconds The HTTP request latencies in microseconds.
# TYPE http_request_duration_microseconds summary
http_request_duration_microseconds{handler="prometheus",quantile="0.5"} NaN
http_request_duration_microseconds{handler="prometheus",quantile="0.9"} NaN
http_request_duration_microseconds{handler="prometheus",quantile="0.99"} NaN
http_request_duration_microseconds_sum{handler="prometheus"} 1169.771
http_request_duration_microseconds_count{handler="prometheus"} 1
# HELP http_request_size_bytes The HTTP request sizes in bytes.
# TYPE http_request_size_bytes summary
http_request_size_bytes{handler="prometheus",quantile="0.5"} NaN
http_request_size_bytes{handler="prometheus",quantile="0.9"} NaN
http_request_size_bytes{handler="prometheus",quantile="0.99"} NaN
http_request_size_bytes_sum{handler="prometheus"} 112
http_request_size_bytes_count{handler="prometheus"} 1
# HELP http_requests_total Total number of HTTP requests made.
# TYPE http_requests_total counter
http_requests_total{code="200",handler="prometheus",method="get"} 1
# HELP http_response_size_bytes The HTTP response sizes in bytes.
# TYPE http_response_size_bytes summary
http_response_size_bytes{handler="prometheus",quantile="0.5"} NaN
http_response_size_bytes{handler="prometheus",quantile="0.9"} NaN
http_response_size_bytes{handler="prometheus",quantile="0.99"} NaN
http_response_size_bytes_sum{handler="prometheus"} 12526
http_response_size_bytes_count{handler="prometheus"} 1
# HELP imageregistry_build_info A metric with a constant '1' value labeled by major, minor, git commit & git version from which the image registry was built.
# TYPE imageregistry_build_info gauge
imageregistry_build_info{gitCommit="57e101f208cfc47ddadd97408c05970332fcd70e",gitVersion="v3.9.43",major="3",minor="9"} 1
# HELP openshift_registry_request_duration_seconds Request latency summary in microseconds for each operation
# TYPE openshift_registry_request_duration_seconds histogram
openshift_registry_request_duration_seconds_bucket{name="openshift/cakephp-ex",operation="manifestservice.get",le="0.005"} 0
openshift_registry_request_duration_seconds_bucket{name="openshift/cakephp-ex",operation="manifestservice.get",le="5"} 30
openshift_registry_request_duration_seconds_bucket{name="quotasample/ruby-hello-world",operation="manifestservice.get",le="2.5"} 30

openshift_registry_request_duration_seconds_count{name="quotasample/ruby-hello-world",operation="manifestservice.get"} 30
# HELP process_cpu_seconds_total Total user and system CPU time spent in seconds.
# TYPE process_cpu_seconds_total counter
process_cpu_seconds_total 13.77
# HELP process_virtual_memory_bytes Virtual memory size in bytes.
# TYPE process_virtual_memory_bytes gauge
process_virtual_memory_bytes 1.74546944e+08
```
### But when I was trying setup as Job in Prometheus, facing authentication error.

```
- job_name: openshift-registry
  scrape_interval: 1m
  scrape_timeout: 10s
  metrics_path: /extensions/v2/metrics
  scheme: https
  kubernetes_sd_configs:
  - api_server: null
    role: endpoints
    namespaces:
      names:
      - default
  bearer_token_file: /var/run/secrets/kubernetes.io/serviceaccount/token
  tls_config:
    ca_file: /var/run/secrets/kubernetes.io/serviceaccount/ca.crt
    server_name: docker-registry.default.svc
    insecure_skip_verify: true
  relabel_configs:
  - source_labels: [__meta_kubernetes_namespace, __meta_kubernetes_service_name, __meta_kubernetes_endpoint_port_name]
    separator: ;
    regex: default;docker-registry;5000-tcp
    replacement: $1
    action: keep
```

Error as follows ...

![image](https://user-images.githubusercontent.com/19322497/48882593-1fe22780-ee41-11e8-9c46-829b91e6bbc4.png)
