### ISSUE TITLE
secretKeyRef doesn't evaluate value in BuildConfig jenkins strategy

### ISSUE THREAD

**Issue by JaniszM** [openshift/origin#21631]
OS simply does not evaluate the `secretKeyRef` values as environment vars in the buildConfig with jenkins pipeline strategy.

##### Version
oc v3.10.45
kubernetes v1.10.0+b81c8f8
features: Basic-Auth GSSAPI Kerberos SPNEGO

Server ***
openshift v3.11.16
kubernetes v1.11.0+d4cacc0

##### Steps To Reproduce
1. Create secret and use this secret in any buildConfig with jenkins pipeline strategy in `env`.

##### Current Result
Environment ARQUILLIAN_USER is empty.

##### Expected Result
Environment ARQUILLIAN_USER should contain db user name value.

##### Additional Information
EDIT: Same problem I can see with ConfigMaps :/

Sameple template:
```yml
apiVersion: v1
kind: Template
metadata:
  name: test
  annotations:
    description: "Template with sample bookstore app."
    iconClass: "icon-redis"
    tags: "jboss,java,bookstore"

parameters:
- name: APP_NAME
  value: "test"
- name: APP_BUILDER_NAME
  value: "test-builder"
- name: PROJECT_NAME
  value: "bookstore"
- name: TEST_DB_SECRET
  value: "test-db"
  
objects:
- apiVersion: v1
  kind: ConfigMap
  metadata:
    name: ${TEST_DB_SECRET}
    labels:
      example: slowly
  data:
    DB_PASS: pass123
    DB_USER: user123
- apiVersion: v1
  kind: BuildConfig
  metadata:
    name: ${APP_BUILDER_NAME}
    labels:
      application: slowly
  spec:
    runPolicy: Serial
    strategy:
      jenkinsPipelineStrategy:
        jenkinsfile: |-
            pipeline {
                agent any
                stages {
                    stage ('test'){
                        steps {
                            echo "testing"
                            echo GIT_SSL_NO_VERIFY
                            echo ARQUILLIAN_USER
                        }
                    }
                }
            }
        env:
          - name: GIT_SSL_NO_VERIFY
            value: "false"
          - name: ARQUILLIAN_USER
            valueFrom:
              secretKeyRef:
                name: ${TEST_DB_SECRET}
                key: DB_USER
          - name: ARQUILLIAN_PASSWORD
            valueFrom:
              secretKeyRef:
                name: ${TEST_DB_SECRET}
                key: DB_PASS
```
