### ISSUE TITLE
 Nameserver value in /etc/resolv.conf file inside pods are inconsistent 

### ISSUE THREAD

**Issue by vishnoisuresh** [openshift/origin#21696]
[provide a description of the issue]
There is inconsistent values of nameserver in `/etc/resolv.conf` inside the **pods** on different nodes.However,  There is a correct values on the node's `/etc/resolv.conf` .  

with my limited knowledge I can not figure out or answer myself  the following things

1 who and how is the value of `--cluster-dns=` flag is evaluated for atomic-openshift-node service?
2 Why the dnsmasq is listening for all of the interface on the nodes? (result is below)
3 why is there inconsistency with kubelet's flag?  
##### Version
[provide output of the `openshift version` or `oc version` command]
```
oc v3.11.43
kubernetes v1.11.0+d4cacc0
features: Basic-Auth GSSAPI Kerberos SPNEGO

Server https://console.cluster1.example.com:8443
openshift v3.11.43
kubernetes v1.11.0+d4cacc0
```

##### Current Result
**on the node**
```
[suresh.vishnoi@dexxx12 ~]$ cat /etc/resolv.conf
# nameserver updated by /etc/NetworkManager/dispatcher.d/99-origin-dns.sh
# Generated by NetworkManager
search cluster.local 
nameserver 10.61.105.21

```

**inside the pods**
```
[suresh.vishnoi@dexxx12 ~]$ oc rsh busybox-1-njg59
/ $ cat /etc/resolv.conf
nameserver 169.254.173.116
search cp-394211.svc.cluster.local svc.cluster.local cluster.local 
options ndots:5

```

kubelet flags
```
root      72504  9.0  0.0 7890184 211196 ?      Ssl  Dec10 1435:13 /usr/bin/hyperkube kubelet --v=2 --address=0.0.0.0 --allow-privileged=true --anonymous-auth=true --authentication-token-webhook=true --authentication-token-webhook-cache-ttl=5m --authorization-mode=Webhook --authorization-webhook-cache-authorized-ttl=5m --authorization-webhook-cache-unauthorized-ttl=5m --bootstrap-kubeconfig=/etc/origin/node/bootstrap.kubeconfig --cadvisor-port=0 --cert-dir=/etc/origin/node/certificates --cgroup-driver=systemd --client-ca-file=/etc/origin/node/client-ca.crt --cluster-dns=169.254.152.157 --cluster-domain=cluster.local --container-runtime-endpoint=/var/run/dockershim.sock --containerized=false --enable-controller-attach-detach=true --experimental-dockershim-root-directory=/var/lib/dockershim --fail-swap-on=false --feature-gates=RotateKubeletClientCertificate=true,RotateKubeletServerCertificate=true --healthz-bind-address= --healthz-port=0 --host-ipc-sources=api --host-ipc-sources=file --host-network-sources=api --host-network-sources=file --host-pid-sources=api --host-pid-sources=file --hostname-override= --http-check-frequency=0s --image-service-endpoint=/var/run/dockershim.sock --iptables-masquerade-bit=0 --kubeconfig=/etc/origin/node/node.kubeconfig --max-pods=250 --network-plugin=cni --node-ip= --node-labels=node-role.kubernetes.io/compute=true --pod-infra-container-image=registry.access.redhat.com/openshift3/ose-pod:v3.11.43 --pod-manifest-path=/etc/origin/node/pods --port=10250 --read-only-port=0 --register-node=true --root-dir=/var/lib/origin/openshift.local.volumes --rotate-certificates=true --rotate-server-certificates=true --tls-cert-file= --tls-cipher-suites=TLS_ECDHE_ECDSA_WITH_CHACHA20_POLY1305 --tls-cipher-suites=TLS_ECDHE_RSA_WITH_CHACHA20_POLY1305 --tls-cipher-suites=TLS_ECDHE_ECDSA_WITH_AES_128_GCM_SHA256 --tls-cipher-suites=TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256 --tls-cipher-suites=TLS_ECDHE_ECDSA_WITH_AES_256_GCM_SHA384 --tls-cipher-suites=TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384 --tls-cipher-suites=TLS_ECDHE_ECDSA_WITH_AES_128_CBC_SHA256 --tls-cipher-suites=TLS_ECDHE_RSA_WITH_AES_128_CBC_SHA256 --tls-cipher-suites=TLS_ECDHE_ECDSA_WITH_AES_128_CBC_SHA --tls-cipher-suites=TLS_ECDHE_ECDSA_WITH_AES_256_CBC_SHA --tls-cipher-suites=TLS_ECDHE_RSA_WITH_AES_128_CBC_SHA --tls-cipher-suites=TLS_ECDHE_RSA_WITH_AES_256_CBC_SHA --tls-cipher-suites=TLS_RSA_WITH_AES_128_GCM_SHA256 --tls-cipher-suites=TLS_RSA_WITH_AES_256_GCM_SHA384 --tls-cipher-suites=TLS_RSA_WITH_AES_128_CBC_SHA --tls-cipher-suites=TLS_RSA_WITH_AES_256_CBC_SHA --tls-min-version=VersionTLS12 --tls-private-key-file=
```
`ip r a`  **list of interface** 
```
1: lo: <LOOPBACK,UP,LOWER_UP> mtu 65536 qdisc noqueue state UNKNOWN group default qlen 1000
    link/loopback 00:00:00:00:00:00 brd 00:00:00:00:00:00
    inet 127.0.0.1/8 scope host lo
       valid_lft forever preferred_lft forever
    inet6 ::1/128 scope host
       valid_lft forever preferred_lft forever
2: em1: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc mq master team0 state UP group default qlen 1000
    link/ether 58:8a:5a:de:e7:8c brd ff:ff:ff:ff:ff:ff
3: em2: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc mq master team0 state UP group default qlen 1000
    link/ether 58:8a:5a:de:e7:8c brd ff:ff:ff:ff:ff:ff
4: em3: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc mq state UP group default qlen 1000
    link/ether 58:8a:5a:de:ed:06 brd ff:ff:ff:ff:ff:ff
5: em4: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc mq state UP group default qlen 1000
    link/ether 58:8a:5a:de:ed:09 brd ff:ff:ff:ff:ff:ff
6: p3p1: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc mq master team1 state UP group default qlen 1000
    link/ether 58:8a:5a:de:e7:90 brd ff:ff:ff:ff:ff:ff
7: p3p2: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc mq master team1 state UP group default qlen 1000
    link/ether 58:8a:5a:de:e7:90 brd ff:ff:ff:ff:ff:ff
8: em5: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc mq state UP group default qlen 1000
    link/ether 58:8a:5a:de:e7:f4 brd ff:ff:ff:ff:ff:ff
9: em6: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc mq state UP group default qlen 1000
    link/ether 58:8a:5a:de:e7:f7 brd ff:ff:ff:ff:ff:ff
10: em7: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc mq state UP group default qlen 1000
    link/ether 58:8a:5a:de:f2:be brd ff:ff:ff:ff:ff:ff
11: em8: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc mq state UP group default qlen 1000
    link/ether 58:8a:5a:de:f2:c1 brd ff:ff:ff:ff:ff:ff
12: dummy0: <BROADCAST,NOARP> mtu 1500 qdisc noop state DOWN group default qlen 1000
    link/ether 6a:e4:e8:86:28:94 brd ff:ff:ff:ff:ff:ff
13: eth0: <BROADCAST,NOARP> mtu 1500 qdisc noop state DOWN group default qlen 1000
    link/ether d2:8e:c0:fd:a7:f6 brd ff:ff:ff:ff:ff:ff
14: team1: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc noqueue state UP group default qlen 1000
    link/ether 58:8a:5a:de:e7:90 brd ff:ff:ff:ff:ff:ff
    inet 169.254.152.157/16 brd 169.254.255.255 scope link noprefixroute team1
       valid_lft forever preferred_lft forever
    inet6 fe80::5a8a:5aff:fede:e790/64 scope link
       valid_lft forever preferred_lft forever
15: team1.1606@team1: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc noqueue state UP group default qlen 1000
    link/ether 58:8a:5a:de:e7:90 brd ff:ff:ff:ff:ff:ff
    inet 192.168.196.177/23 brd 192.168.197.255 scope global noprefixroute team1.1606
       valid_lft forever preferred_lft forever
    inet6 fe80::5a8a:5aff:fede:e790/64 scope link
       valid_lft forever preferred_lft forever
16: team0: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc noqueue state UP group default qlen 1000
    link/ether 58:8a:5a:de:e7:8c brd ff:ff:ff:ff:ff:ff
    inet 169.254.20.89/16 brd 169.254.255.255 scope link noprefixroute team0
       valid_lft forever preferred_lft forever
    inet6 fe80::5a8a:5aff:fede:e78c/64 scope link
       valid_lft forever preferred_lft forever
17: team0.1023@team0: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc noqueue state UP group default qlen 1000
    link/ether 58:8a:5a:de:e7:8c brd ff:ff:ff:ff:ff:ff
    inet 10.61.105.21/24 brd 10.61.105.255 scope global noprefixroute team0.1023
       valid_lft forever preferred_lft forever
    inet6 fe80::5a8a:5aff:fede:e78c/64 scope link
       valid_lft forever preferred_lft forever
18: docker0: <NO-CARRIER,BROADCAST,MULTICAST,UP> mtu 1500 qdisc noqueue state DOWN group default
    link/ether 02:42:e7:06:06:62 brd ff:ff:ff:ff:ff:ff
    inet 172.17.0.1/16 scope global docker0
       valid_lft forever preferred_lft forever
23: ovs-system: <BROADCAST,MULTICAST> mtu 1500 qdisc noop state DOWN group default qlen 1000
    link/ether b6:93:c0:e3:cd:b7 brd ff:ff:ff:ff:ff:ff
24: br0: <BROADCAST,MULTICAST> mtu 1450 qdisc noop state DOWN group default qlen 1000
    link/ether c2:f3:a5:8c:33:4e brd ff:ff:ff:ff:ff:ff
25: vxlan_sys_4789: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 65000 qdisc noqueue master ovs-system state UNKNOWN group default qlen 1000
    link/ether c2:f5:5b:37:6c:51 brd ff:ff:ff:ff:ff:ff
    inet6 fe80::c0f5:5bff:fe37:6c51/64 scope link
       valid_lft forever preferred_lft forever
26: tun0: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1450 qdisc noqueue state UNKNOWN group default qlen 1000
    link/ether ba:6d:4d:f2:b0:e5 brd ff:ff:ff:ff:ff:ff
    inet 172.18.8.1/24 brd 172.18.8.255 scope global tun0
       valid_lft forever preferred_lft forever
    inet6 fe80::b86d:4dff:fef2:b0e5/64 scope link
       valid_lft forever preferred_lft forever
27: veth0f6facca@if3: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1450 qdisc noqueue master ovs-system state UP group default
    link/ether 06:c7:72:62:54:7a brd ff:ff:ff:ff:ff:ff link-netnsid 0
    inet6 fe80::4c7:72ff:fe62:547a/64 scope link
       valid_lft forever preferred_lft forever
```
##### Expected Result
The Nameserver value in the file `/etc/resolv.conf` should be  **Node IP** rather than IP from random interface. 
##### Additional Information
[try to run `$ oc adm diagnostics` (or `oadm diagnostics`) command if possible]
[if you are reporting issue related to builds, provide build logs with `BUILD_LOGLEVEL=5`]
[consider attaching output of the `$ oc get all -o json -n <namespace>` command to the issue]
[visit https://docs.openshift.org/latest/welcome/index.html]

**Comment by ctonur** [comment]
is the server physical or virtual ?

**Comment by bysnupy** [comment]
AFAIK `cluster-dns` is assigned as `nodeIP`, refer [this code]( https://github.com/openshift/origin/blob/master/pkg/cmd/server/start/network/start_network.go#L159).
~~~
		nodeConfig.DNSIP = nodeConfig.NodeIP
~~~

But I can't find where to get the node IP address from mutiple interface IPs in source codes.

`99-origin-dns.sh` is assigned to `nameserver` as a `IP address` of `default gateway interface` in the multiple interfaces, so it seems the conditions to select the node IP might be required similar with it.

Can your node hostname be resolved as the 10.61.105.21 ?

**Comment by vishnoisuresh** [comment]
@bysnupy , Thanks for looking at issue.  Yea  **dnsIP** is assigned randomly on each nodes, there is no consistency, consequently there is a issues with name resolution,  When I am in a Pod A and try to resolve the service name of Pod B , I need to provide   **serviceB.ProjectB.svc** , If I just  use    **serviceB**  then it tries to do send the traffic outside of the cluster using $HTTP_PROXY environment variable even though there is a value (podsCIDR and ServiceCIDR) provided in $NO_PROXY   environment variable. 

pardon my ignorance , what is the purpose of making **dnsmasq** to listening on all of the interfaces of the node ? 

another question is, There is no **nodeIP** in the following node-config file  ? 

```
apiVersion: v1
authConfig:
  authenticationCacheSize: 1000
  authenticationCacheTTL: 5m
  authorizationCacheSize: 1000
  authorizationCacheTTL: 5m
dnsBindAddress: 127.0.0.1:53
dnsDomain: cluster.local
dnsIP: 0.0.0.0
dnsNameservers: null
dnsRecursiveResolvConf: /etc/origin/node/resolv.conf
dockerConfig:
  dockerShimRootDirectory: /var/lib/dockershim
  dockerShimSocket: /var/run/dockershim.sock
  execHandlerName: native
enableUnidling: true
imageConfig:
  format: registry.access.redhat.com/openshift3/ose-${component}:${version}
  latest: false
iptablesSyncPeriod: 30s
kind: NodeConfig
kubeletArguments:
  bootstrap-kubeconfig:
  - /etc/origin/node/bootstrap.kubeconfig
  cert-dir:
  - /etc/origin/node/certificates
  enable-controller-attach-detach:
  - 'true'
  feature-gates:
  - RotateKubeletClientCertificate=true,RotateKubeletServerCertificate=true
  node-labels:
  - node-role.kubernetes.io/compute=true
  pod-manifest-path:
  - /etc/origin/node/pods
  rotate-certificates:
  - 'true'
masterClientConnectionOverrides:
  acceptContentTypes: application/vnd.kubernetes.protobuf,application/json
  burst: 40
  contentType: application/vnd.kubernetes.protobuf
  qps: 20
masterKubeConfig: node.kubeconfig
networkConfig:
  mtu: 1450
  networkPluginName: redhat/openshift-ovs-multitenant
servingInfo:
  bindAddress: 0.0.0.0:10250
  bindNetwork: tcp4
  certFile: ''
  clientCA: client-ca.crt
  keyFile: ''
volumeConfig:
  localQuota:
    perFSGroup: null
volumeDirectory: /var/lib/origin/openshift.local.volumes

```
