### ISSUE TITLE
Web console when using 'docker in docker' cluster?

### ISSUE THREAD

**Issue by gustavonalle** [openshift/origin#21729]
Docker in docker cluster starts successfully, but can't access the web console

##### Version
oc v4.0.0-alpha.0+5091c55-829

##### Steps To Reproduce
1. Follow instructions from https://github.com/openshift/origin/blob/master/CONTRIBUTING.adoc#develop-and-test-using-a-docker-in-docker-cluster

##### Current Result

Cluster starts successfully, ```oc get nodes``` returns one master and two nodes. Accessing https://172.17.0.2:8443/ (the IP of the master) prompts to accept an invalid certificate but then redirect to a blank page with the message:
```
This page isn’t working 172.17.0.2 is currently unable to handle this request.
HTTP ERROR 503
```

##### Expected Result

Access to the web console works. Please let me know if the address below is the right address or if I need to config anything

**Comment by gustavonalle** [comment]
Never mind, figured out it is not installed for the dind-cluster. 
For those interested, after the dind is up, I run the following commands:
```
. dind-openshift.rc
oc login -u system:admin
oc create namespace openshift-web-console
oc process -f console-template.yaml -p "API_SERVER_CONFIG=$(cat console-config.yaml)" | oc apply -n openshift-web-console -f -
```

where ```console-config.yaml``` is:
```
apiVersion: webconsole.config.openshift.io/v1
kind: WebConsoleConfiguration
clusterInfo:
  consolePublicURL: https://172.17.0.2:8443/console/
  loggingPublicURL: ""
  logoutPublicURL: ""
  masterPublicURL: https://172.17.0.2:8443
  metricsPublicURL: ""
extensions:
  scriptURLs: []
  stylesheetURLs: []
  properties: null
features:
  inactivityTimeoutMinutes: 0
  clusterResourceOverridesEnabled: false
servingInfo:
  bindAddress: 0.0.0.0:8443
  bindNetwork: tcp4
  certFile: /var/serving-cert/tls.crt
  clientCA: ""
  keyFile: /var/serving-cert/tls.key
  maxRequestsInFlight: 0
  namedCertificates: null
  requestTimeoutSeconds: 0
```

and ```console-template.yml``` comes from [here](https://raw.githubusercontent.com/openshift/origin/release-3.11/install/origin-web-console/console-template.yaml)
