### ISSUE TITLE
oc new-build --strategy=pipeline how to specify jenkinsfile contents or path?

### ISSUE THREAD

**Issue by twhite0** [openshift/origin#21759]
Attempting to establish a new pipeline build by way of the cli.  I'm not seeing how I can specify the Jenkinsfile contents or the path.  I'd like to execute a similar workflow as a strategy=docker, where i can "from-dir" the code from my workstation in the start-build.

##### Version
```
$ oc version
oc v3.11.43
kubernetes v1.11.0+d4cacc0
features: Basic-Auth SSPI Kerberos SPNEGO

Server https://xxxxxxx:443
openshift v3.11.51
kubernetes v1.11.0+d4cacc0
```

##### Steps To Reproduce
Simply unfamiliar with how to do it?

##### Current Result
`oc new-build --name ocp-demo-pipeline --stategy=pipeline --binary=true `

results in 
> error: specifying binary builds and the pipeline strategy at the same time is not allowed.
> See 'oc new-build -h' for help and examples.

 `oc new-build . --name ocp-demo-pipeline --strategy=pipeline`

results in the BuildConfig being created off of my local git repo.

##### Expected Result
Some combination of parameters or flags which would allow me to specify an 'oc new-build' to establish the build config as follows:

```
kind: "BuildConfig"
apiVersion: "v1"
metadata:
  name: "sample-pipeline"
  source:
    binary: {}
    type: Binary
  strategy:
    jenkinsPipelineStrategy:
      jenkinsfilePath: ./Jenkinsfile
```

Ultimately enabling a similar binary start-build workflow of the --stategy=docker
`oc start-build bc/ocp-demo-pipeline --from-dir=. --follow`

Thanks in advance
