### ISSUE TITLE
Unable to create CronJob using a Template

### ISSUE THREAD

**Issue by whai2kay** [openshift/origin#21789]
Unable to deploy a CronJob using a Template. 

##### Version
oc v3.11.0+0cbc58b
kubernetes v1.11.0+d4cacc0
features: Basic-Auth GSSAPI Kerberos SPNEGO

Server ************
openshift v3.11.0+1a90c5c-83
kubernetes v1.11.0+d4cacc0

##### Steps To Reproduce
1. Create a template containing a sample CronJob and save it as cronjob-template.yaml
```yaml
apiVersion: v1
kind: Template
metadata:
  name: cronjob-test
objects:
- apiVersion: batch/v1beta1
  kind: CronJob
  metadata:
    name: hello
  spec:
    schedule: "*/1 * * * *"
    jobTemplate:
      spec:
        template:
          spec:
            containers:
            - name: hello
              image: busybox
              args:
              - /bin/sh
              - -c
              - date; echo Hello from the Kubernetes cluster
            restartPolicy: OnFailure
```
2. Deploy from template using `oc new-app -f cronjob-template.yaml`

##### Current Result
Deployment fails due to what seems to be an invalid apiVersion

```bash
--> Deploying template "default/cronjob-test" for "cronjob-template.yaml" to project default

--> Creating resources ...
    error: no kind "CronJob" is registered for version "batch/v1" in scheme "k8s.io/kubernetes/pkg/api/legacyscheme/scheme.go:29"
--> Failed
```
##### Expected Result
Expect to deploy a cronjob successfully
```bash
--> Deploying template "default/cronjob-test" for "cronjob-template.yaml" to project default

--> Creating resources ...
    cronjob "hello" created
--> Success

    Run 'oc status' to view your app.
```
##### Additional Information
Same template was tested on an Openshift 3.9.x cluster and was able to deploy successfully.
Have also tried using apiVersion 'batch/v2alpha1' to create a normal CronJob as specified in the documentation (https://docs.openshift.com/container-platform/3.11/rest_api/apis-batch/v2alpha1.CronJob.html#Post-apis-batch-v2alpha1-cronjobs), but it failed due to invalid apiVersion.

**Comment by schoellhammertim** [comment]
same here i become following error:
error: no kind "CronJob" is registered for version "batch/v1" in scheme "k8s.io/kubernetes/pkg/api/legacyscheme/scheme.go:29"

oc version
oc v3.11.0+62803d0-1
kubernetes v1.11.0+d4cacc0
features: Basic-Auth GSSAPI Kerberos SPNEGO

Server https://xyz:8443
openshift v3.11.0+cbab8ee-94
kubernetes v1.11.0+d4cacc0

**Comment by kahowell** [comment]
For anyone hitting this, a workaround is to use `oc process` and pipe the results into `oc apply -f -`, e.g.:

```bash
oc process -f $TEMPLATE_FILE -p foo=bar -o yaml | oc apply -f -
```

**Comment by pangzheng** [comment]
I have encountered a similar problem，I modified the master-config as follows
I modified master-config and want to open the admissionregistration.k8s.io/v1alpha1 and Initializers

View swaggerapi
{
Path: "/apis/admissionregistration.k8s.io/v1alpha1",
Description: "API at /apis/admissionregistration.k8s.io/v1alpha1"
},

Test setup Initializers

apiVersion: admissionregistration.k8s.io/v1alpha1
Kind: InitializerConfiguration
Metadata:
   Name: lxcfs.initializer
Initializers:
   - name: lxcfs.initializer.kubernetes.io
     Rules:
       - apiGroups:
           - "*"
         apiVersions:
           - "*"
         Resources:
           - deployments


got the answer
Error from server: error when creating "lxcfs-initializer.yaml.a": no kind "InitializerConfiguration" is registered for version "admissionregistration.k8s.io/v1beta1" in scheme "k8s.io/kubernetes/pkg/api/legacyscheme/ Scheme.go:29"

This is bug?

# oc version
oc v3.11.0+62803d0-1
kubernetes v1.11.0+d4cacc0
openshift v3.11.0+06cfa24-67
kubernetes v1.11.0+d4cacc0

**Comment by pangzheng** [comment]
# oc process -f lxcfs-initializer.yaml.a -p foo=bar -o yaml | oc apply -f -

error: unable to parse "lxcfs-initializer.yaml.a", not a valid Template but *v1alpha1.InitializerConfiguration
error: no objects passed to apply

**Comment by tocosonic** [comment]
I've also ran into this problem.
The cause seems to be the OpenShift CLI: when using version 3.10 running a cron job works as expected.

**Comment by pangzheng** [comment]
Hi, I saw the answer, went back to the test page, the same problem
<img width="443" alt="WeChat1a172f847a1d2e1730a814873214cdfb" src="https://user-images.githubusercontent.com/7556687/54575404-f3c16680-4a2e-11e9-9ded-8e112a0ca709.png">

**Comment by pangzheng** [comment]
# kubectl apply -f initializer.yaml --loglevel 6
I0319 12:06:04.095277   17039 loader.go:359] Config loaded from file /root/.kube/config
I0319 12:06:04.096779   17039 loader.go:359] Config loaded from file /root/.kube/config
I0319 12:06:04.115553   17039 round_trippers.go:405] GET https://master195.dmos.dataman:8443/openapi/v2?timeout=32s 200 OK in 18 milliseconds
I0319 12:06:04.287104   17039 loader.go:359] Config loaded from file /root/.kube/config
I0319 12:06:04.287929   17039 loader.go:359] Config loaded from file /root/.kube/config
I0319 12:06:04.288608   17039 loader.go:359] Config loaded from file /root/.kube/config
I0319 12:06:04.289318   17039 loader.go:359] Config loaded from file /root/.kube/config
I0319 12:06:04.321356   17039 decoder.go:224] decoding stream as YAML
I0319 12:06:04.322547   17039 loader.go:359] Config loaded from file /root/.kube/config
I0319 12:06:04.327043   17039 round_trippers.go:405] GET https://master195:8443/apis/metrics.k8s.io/v1beta1?timeout=32s 200 OK in 2 milliseconds
I0319 12:06:04.329142   17039 loader.go:359] Config loaded from file /root/.kube/config
I0319 12:06:04.331755   17039 round_trippers.go:405] GET https://master195.:8443/apis/admissionregistration.k8s.io/v1alpha1/initializerconfigurations/lxcfs.initializer 404 Not Found in 2 milliseconds
I0319 12:06:04.334622   17039 round_trippers.go:405] POST https://master195.:8443/apis/admissionregistration.k8s.io/v1alpha1/initializerconfigurations 500 Internal Server Error in 2 milliseconds
I0319 12:06:04.334859   17039 helpers.go:201] server response object: [{
  "kind": "Status",
  "apiVersion": "v1",
  "metadata": {},
  "status": "Failure",
  "message": "error when creating \"initializer.yaml\": no kind \"InitializerConfiguration\" is registered for version \"admissionregistration.k8s.io/v1beta1\" in scheme \"k8s.io/kubernetes/pkg/api/legacyscheme/scheme.go:29\"",
  "code": 500
}]
F0319 12:06:04.334960   17039 helpers.go:119] Error from server: error when creating "initializer.yaml": no kind "InitializerConfiguration" is registered for version "admissionregistration.k8s.io/v1beta1" in scheme "k8s.io/kubernetes/pkg/api/legacyscheme/scheme.go:29"

**Comment by pangzheng** [comment]
```
admissionConfig:
  pluginConfig:
    Initializers:
      configuration:
        kind: DefaultAdmissionConfig
        apiVersion: v1
        disable: false
kubernetesMasterConfig:
  apiServerArguments:
    runtime-config:
    - admissionregistration.k8s.io/v1alpha1=true
```
