### ISSUE TITLE
empty values on namespace nodeselectors result in replicaset errors

### ISSUE THREAD

**Issue by thoraxe** [openshift/origin#21972]
When labeling nodes, currently we use _roles_ in OpenShift 4. One example is `node-role.kubernetes.io/infra=""` and note the empty value for the key.

Configuring a namespace's nodselector for that label looks like the following:

```YAML
apiVersion: v1
kind: Namespace
metadata:
  annotations:
    openshift.io/node-selector: node-role.kubernetes.io/infra=
    openshift.io/sa.scc.mcs: s0:c21,c10
    openshift.io/sa.scc.supplemental-groups: 1000440000/10000
    openshift.io/sa.scc.uid-range: 1000440000/10000
```

Various iterations of `infra=` or `infra=''` don't make a difference. `infra=""` does not validate and causes an error. `infra=\"\"` also doesn't work but gives a slightly different error.

##### Version
```
oc v4.0.0-0.79.0
kubernetes v1.11.0+d4cacc0
features: Basic-Auth GSSAPI Kerberos SPNEGO

Server https://beta-190205-1-api.ocp4testing.openshiftdemos.com:6443
kubernetes v1.11.0+8868a98a7b
```

##### Steps To Reproduce
1. modify a namespace to have the nodeselector presented above
2. delete pods in a deployment causing an attempt to reschedule

##### Current Result
One of the following in the event list:

```
21m         24m          17        jaeger-collector-7f644df9f5.15808f7042bf15af               ReplicaSet                                                        Warning   FailedCreate           replicaset-control
ler                   Error creating: unable to parse requirement: found '', expected: identifier
```

```
20m         20m          1         jaeger-collector-7f644df9f5.15808fae441677cb               ReplicaSet                                                        Warning   FailedCreate           replicaset-control
ler                   Error creating: unable to parse requirement: found '', expected: '='
```

```
1m          11m          3         istio-pilot-59d5557c86.1580902741b32203                    ReplicaSet                                                        Warning   FailedCreate           replicaset-control
ler                   Error creating: unable to parse requirement: label value: Invalid value: "''": must match format [ DNS 1123 subdomain / ] DNS 1123 label
```

##### Expected Result
As this is a valid node label it should also be a valid nodeselector and should work.

##### Additional Information
N/A
