### ISSUE TITLE
Openshift does not support --cloud-provider = external ？

### ISSUE THREAD

**Issue by pangzheng** [openshift/origin#22337]
[provide a description of the issue]
Openshift does not support --cloud-provider = external ？

I want to use a third-party cloud provider, adding --cloud-provider=external and --provider-id=xxx to the node according to the documentation.
But does not take effect, the providerID cannot be obtained in the node information

[third-party cloud provider](https://github.com/kubernetes/cloud-provider-alibaba-cloud)

step:

1. add node config

```
cd /etc/origin/node && vi node-config.patch

kubeletArguments:
  cloud-provider:
  - "external"
  cloud-config:
  - "/etc/kubernetes/cloud-controller-manager.conf"
  provider-id:
  - "cn-zhangjiakou.i-xxxxxxxx"

oc ex config patch node-config.yaml.prepatch -p "$(cat node-config.patch)" > node-config.yaml
```
- reboot node

`systemctl restart origin-node`

- check node meta.data

`oc get nodes $nodename -o jsonpath="{.spec.providerID}"` 
  - return
  
     is null

   - expect

     providerID=xxxxx

- origin node log

` I0313 18:27:46.939811   19827 flags.go:27] FLAG: --cloud-provider="external"`
`I0313 18:27:46.940490   19827 flags.go:27] FLAG: --provider-id="cn-zhangjiakou.i-xxxx"`

[provide output of the openshift version or oc version command]
```
# oc version
oc v3.11.0+62803d0-1
kubernetes v1.11.0+d4cacc0
features: Basic-Auth GSSAPI Kerberos SPNEGO
openshift v3.11.0+06cfa24-67
kubernetes v1.11.0+d4cacc0
```
