### ISSUE TITLE
Advance audit with multiple webhook

### ISSUE THREAD

**Issue by prasenforu** [openshift/origin#22392]
Origin version : 3.11

Multinode cluster.

Not sure its supported or not.

Basically want to configure Advance audit with multiple webhook.

My cluster is perfectly working with advance audit with following webhook setup,

```
apiVersion: v1
kind: Config
clusters:
- name: webhook-1
  cluster:
    server: http://URL-1
contexts:
- context:
    cluster: webhook-1
    user: ""
  name: webhook1-context
current-context: webhook1-context
preferences: {}
users: []
```
but if add multiple webhook as follows, its NOT Working (looks like api not staring)

```
apiVersion: v1
kind: Config
clusters:
- name: webhook-1
  cluster:
    server: http://URL-1
- name: webhook-2
  cluster:
    server: http://URL-2
contexts:
- context:
    cluster: webhook-1
    user: ""
  name: webhook1-context
- context:
    cluster: webhook-2
    user: ""
  name: webhook2-context
current-context: ""
preferences: {}
users: []

```

Some observation 
if I change ```current-context: "webhook2-context"``` then its works but data is coming only ```webhook2 http://URL-2```

But I want data in both URL.
