### ISSUE TITLE
Is there a way for ImageStream to reference locally built Docker image?

### ISSUE THREAD

**Issue by kevin-tla** [openshift/origin#22525]
Is there a way for an ImageStream to reference a locally built docker image? I created a Docker Image via a Dockerfile named testing inside openshift and I want my template file to reference it so I can use it in my BuildConfig, but I can't for some reason or it'll give me a "you may not have access to the Docker image "testing:latest". Timestamp: 2019-04-10T14:58:06Z Error count: 2" from the console. If I manually push it into the internal Docker registry then I can use the image I just created and it works fine with the BuildConfig template.

Template file:
```
apiVersion: v1
kind: ImageStream
metadata:
  name: test-is
  annotations:
    description: test-is
spec:
  tags:
  - name: latest
    from:
      kind: DockerImage
      name: 'testing:latest'
```
