### ISSUE TITLE
[oc new-build] is there a way to copy mutiple directories using oc new-build with source-image-path flag

### ISSUE THREAD

**Issue by uocxp** [openshift/origin#22600]
when writing a build config in openshift, i can copy multiple
directories from one container to another like this
```yaml
source:
    images:
      - from:
          kind: ImageStreamTag
          name: 'buildervscv:latest'
        paths:
          - destinationDir: .
            sourcePath: /opt/app-root/src/dist/.
          - destinationDir: .
            sourcePath: /opt/app-root/src/openshift/conf/.
```

how can i do the same thing using oc new-build ?

I tried
```
oc new-build --source-image=builder
--source-image-path=/opt/app-root/src/dist/.:.
--source-image-path=/opt/app-root/src/openshift/conf/.:.
--image-stream=openshift/nginx
```
 
```
oc new-build  --source-image=builder --source-image-path
/opt/app-root/src/dist/.:.  /opt/app-root/src/openshift/conf/.:.
--image-stream=openshift/nginx
```
```
oc new-build  --source-image=builder
--source-image-path=[/opt/app-root/src/dist/.:. ,
/opt/app-root/src/openshift/conf/.:.] --image-stream=openshift/nginx
```

with the fist one only one directory is being copied! and the rest are
throwing an error. 
The documentation is only mentioning `--source-image-path='': Specify the file or directory to copy from the source image and its destination in the
build directory. Format: [source]:[destination-dir]`
