### ISSUE TITLE
Route objects owned by Ingress objects are not using the default certificate of the router in case no secret and host list is specified in the Ingress TLS configuration

### ISSUE THREAD

**Issue by hetesiistvan** [openshift/origin#22895]
In case if no certificate is specified for a Route object (just termination: edge) then it will fall back to use the certificate of the router itself. See [1] (chapter "Edge Termination").
E.g.:
```
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: "testRoute"
spec:
  tls:
    termination: edge
  to:
    kind: Service
    name: testService
```
This behaviour is pretty convenient if the router itself has a wildcard certificate.

The Kubernetes API reference [2] tells the following about the host list for TLS configuration:

> Hosts are a list of hosts included in the TLS certificate. The values in this list must match the name/s used in the tlsSecret. Defaults to the wildcard host setting for the loadbalancer controller fulfilling this Ingress, if left unspecified.

Therefore my assumption would be if I specify an Ingress object with an empty host list in the TLS configuration section (and without a secret) then I should get the same result like above by the route object. This is not the case unfortunately.
E.g. Ingress definition:
```
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: ingress
  annotations:
    kubernetes.io/ingress.class: "nginx"
spec:
  tls:
  - hosts:
  rules:
  - host: testHost
    http:
      paths:
      - path: /
        backend:
          serviceName: testService
          servicePort: 80
```

My questions:

- Is there a configuration option / annotation I am not aware of and can be used to achieve the same result?
- If not then do you see it feasible to implement this change?

Thanks for any kind of help in advance!

##### Version
oc v3.11.0+0cbc58b
kubernetes v1.11.0+d4cacc0
features: Basic-Auth

Server .......
openshift v3.10.101
kubernetes v1.10.0+b81c8f8

##### Steps To Reproduce
1. Deploy the Ingress object
2. Check the created Route object

##### Current Result
No TLS termination is defined for the created Route object (which was automatically created as by deploying the Ingress object)
```
TLS Termination:	<none>
```

##### Expected Result
TLS configured to "edge" and uses the certificate of the router, like in the case when I create the route object specified as above.
```
TLS Termination:	edge
```

##### Additional Information
[1] - https://docs.openshift.com/enterprise/3.1/architecture/core_concepts/routes.html#secured-routes
[2] - https://kubernetes.io/docs/reference/generated/kubernetes-api/v1.14/#ingresstls-v1beta1-networking-k8s-io
