### ISSUE TITLE
daemonset rollout creates object versions in infinite loop

### ISSUE THREAD

**Issue by franckgr** [openshift/origin#23032]
When flipping values in nodeAffinity definition daemonset rollout process enter in an infite loop
 
##### Version
```
$ kubectl version
Client Version: version.Info{Major:"1", Minor:"10+", GitVersion:"v1.10.0+b81c8f8", GitCommit:"b81c8f8", GitTreeState:"clean", BuildDate:"2019-02-07T18:49:53Z", GoVersion:"go1.9.4", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"11+", GitVersion:"v1.11.0+d4cacc0", GitCommit:"d4cacc0", GitTreeState:"clean", BuildDate:"2019-03-19T15:41:07Z", GoVersion:"go1.10.8", Compiler:"gc", Platform:"linux/amd64"}
```
```
$ oc version 
oc v3.10.111
kubernetes v1.10.0+b81c8f8
features: Basic-Auth GSSAPI Kerberos SPNEGO

Server https://master.xxx.ocp.lab:443
openshift v3.11.98
kubernetes v1.11.0+d4cacc0
```

###### 1. label nodes in cluster :
No matter how many nodes are labeled. I have 4 worker nodes in my cluster virtually split across 2 datacenters. However this lab is hosted on one single box.
```
oc label node node1 zone=dc1
oc label node node2 zone=dc1
oc label node node3 zone=dc2
oc label node node4 zone=dc2
```

###### 2. Create the daemonset
```
$ cat ds.yml 
apiVersion: extensions/v1beta1
kind: DaemonSet
metadata:
  labels:
    k8s-app: bug
  name: bug
spec:
  minReadySeconds: 3
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      k8s-app: bug
  template:
    metadata:
      labels:
        k8s-app: bug
    spec:
      nodeSelector:
        node-role.kubernetes.io/compute: 'true'
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: zone
                operator: In
                values:
                - dc1
                - dc2
      containers:
      - command:
        - /usr/bin/sleep
        - "1h"
        image: registry.redhat.io/rhel7-minimal:7.6-253
        name: bug
      restartPolicy: Always
  updateStrategy:
    rollingUpdate:
      maxUnavailable: 1
    type: RollingUpdate
```
```
$ oc create -f ds.yml 
daemonset.extensions "bug" created
```
```
$ oc get all
NAME            READY     STATUS    RESTARTS   AGE
pod/bug-6pd2t   1/1       Running   0          4m
pod/bug-bfnjd   1/1       Running   0          4m
pod/bug-qgvh2   1/1       Running   0          4m
pod/bug-t8rmb   1/1       Running   0          4m

NAME                 DESIRED   CURRENT   READY     UP-TO-DATE   AVAILABLE   NODE SELECTOR                          AGE
daemonset.apps/bug   4         4         4         4            4           node-role.kubernetes.io/compute=true   4m
```
```
$ oc describe daemonset bug 
Name:           bug
Selector:       k8s-app=bug
Node-Selector:  node-role.kubernetes.io/compute=true
Labels:         k8s-app=bug
Annotations:    <none>
Desired Number of Nodes Scheduled: 4
Current Number of Nodes Scheduled: 4
Number of Nodes Scheduled with Up-to-date Pods: 4
Number of Nodes Scheduled with Available Pods: 4
Number of Nodes Misscheduled: 0
Pods Status:  4 Running / 0 Waiting / 0 Succeeded / 0 Failed
Pod Template:
  Labels:  k8s-app=bug
  Containers:
   bug:
    Image:      registry.redhat.io/rhel7-minimal:7.6-253
    Port:       <none>
    Host Port:  <none>
    Command:
      /usr/bin/sleep
      1h
    Environment:  <none>
    Mounts:       <none>
  Volumes:        <none>
Events:
  Type    Reason            Age   From                  Message
  ----    ------            ----  ----                  -------
  Normal  SuccessfulCreate  7m    daemonset-controller  Created pod: bug-bfnjd
  Normal  SuccessfulCreate  7m    daemonset-controller  Created pod: bug-t8rmb
  Normal  SuccessfulCreate  7m    daemonset-controller  Created pod: bug-qgvh2
  Normal  SuccessfulCreate  7m    daemonset-controller  Created pod: bug-6pd2t
```
Here after the created ControllerRevision
```
$ oc get controllerrevision 
NAME            CONTROLLER           REVISION   AGE
bug-b86645646   daemonset.apps/bug   1          8m
```
```
$ oc describe controllerrevision bug-b86645646
Name:         bug-b86645646
Namespace:    test-lp-02389250
Labels:       controller-revision-hash=642201202
              k8s-app=bug
Annotations:  deprecated.daemonset.template.generation=1
API Version:  apps/v1
Data:
  Spec:
    Template:
      $ Patch:  replace
      Metadata:
        Creation Timestamp:  <nil>
        Labels:
          K 8 S - App:  bug
      Spec:
        Affinity:
          Node Affinity:
            Required During Scheduling Ignored During Execution:
              Node Selector Terms:
                Match Expressions:
                  Key:       zone
                  Operator:  In
                  Values:
                    dc1
                    dc2
        Containers:
          Command:
            /usr/bin/sleep
            1h
          Image:              registry.redhat.io/rhel7-minimal:7.6-253
          Image Pull Policy:  IfNotPresent
          Name:               bug
          Resources:
          Termination Message Path:    /dev/termination-log
          Termination Message Policy:  File
        Dns Policy:                    ClusterFirst
        Node Selector:
          Node - Role . Kubernetes . Io / Compute:  true
        Restart Policy:                             Always
        Scheduler Name:                             default-scheduler
        Security Context:
        Termination Grace Period Seconds:  30
Kind:                                      ControllerRevision
Metadata:
  Creation Timestamp:  2019-06-05T09:08:42Z
  Owner References:
    API Version:           apps/v1
    Block Owner Deletion:  true
    Controller:            true
    Kind:                  DaemonSet
    Name:                  bug
    UID:                   83c6d704-8771-11e9-86e3-525400aabb13
  Resource Version:        22944014
  Self Link:               /apis/apps/v1/namespaces/test-lp-02389250/controllerrevisions/bug-b86645646
  UID:                     83c99ba9-8771-11e9-a2d7-525400aabb12
Revision:                  1
Events:                    <none>
```

###### 3. Check rollout status
```
$ oc get controllerrevision -l k8s-app=bug
NAME            CONTROLLER           REVISION   AGE
bug-b86645646   daemonset.apps/bug   1          15m
```
```
$ oc rollout history ds bug 
daemonsets "bug"
REVISION  CHANGE-CAUSE
1         <none>
```
```
$ oc rollout status ds bug
daemon set "bug" successfully rolled out
```

###### 4. Edit the DaemonSet

Edit the spec daemonset and flip dc1/dc2 in values array

from
```
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: zone
                operator: In
                values:
                - dc1
                - dc2
```
to
```
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: zone
                operator: In
                values:
                - dc2
                - dc1
```

###### 5. Check the rollout process

A new ControllerRevision is created and version of booth of them increasing. Rollout process is in infite loop.
```
$ oc get controllerrevision -l k8s-app=bug
NAME             CONTROLLER           REVISION   AGE
bug-74db8998b6   daemonset.apps/bug   110        2m
bug-b86645646    daemonset.apps/bug   109        20m
```
```
$oc rollout history ds bug
daemonsets "bug"
REVISION  CHANGE-CAUSE
111       <none>
112       <none>
```
```
$ oc rollout status ds bug
Waiting for rollout to finish: 0 out of 4 new pods have been updated...
Waiting for rollout to finish: 3 of 4 updated pods are available...
Waiting for rollout to finish: 0 out of 4 new pods have been updated...
Waiting for rollout to finish: 3 of 4 updated pods are available...
Waiting for rollout to finish: 0 out of 4 new pods have been updated...
Waiting for rollout to finish: 3 of 4 updated pods are available...
Waiting for rollout to finish: 1 out of 4 new pods have been updated...
Waiting for rollout to finish: 3 out of 4 new pods have been updated...
Waiting for rollout to finish: 1 out of 4 new pods have been updated...
Waiting for rollout to finish: 3 of 4 updated pods are available...
Waiting for rollout to finish: 0 out of 4 new pods have been updated...
Waiting for rollout to finish: 3 of 4 updated pods are available...
Waiting for rollout to finish: 0 out of 4 new pods have been updated...
Waiting for rollout to finish: 3 of 4 updated pods are available...
Waiting for rollout to finish: 0 out of 4 new pods have been updated...
Waiting for rollout to finish: 3 of 4 updated pods are available...
Waiting for rollout to finish: 0 out of 4 new pods have been updated...
Waiting for rollout to finish: 1 out of 4 new pods have been updated...
Waiting for rollout to finish: 3 out of 4 new pods have been updated...
Waiting for rollout to finish: 0 out of 4 new pods have been updated...
Waiting for rollout to finish: 3 of 4 updated pods are available...
Waiting for rollout to finish: 0 out of 4 new pods have been updated...
Waiting for rollout to finish: 3 of 4 updated pods are available...
Waiting for rollout to finish: 0 out of 4 new pods have been updated...
Waiting for rollout to finish: 3 of 4 updated pods are available...
Waiting for rollout to finish: 0 out of 4 new pods have been updated...
Waiting for rollout to finish: 3 of 4 updated pods are available...
Waiting for rollout to finish: 1 out of 4 new pods have been updated...
Waiting for rollout to finish: 3 out of 4 new pods have been updated...
Waiting for rollout to finish: 1 out of 4 new pods have been updated...
```

Revision number in ControllerRevision is increasing
```
$oc get controllerrevision bug-74db8998b6 -o yaml --export
apiVersion: apps/v1
data:
  spec:
    template:
      $patch: replace
      metadata:
        creationTimestamp: null
        labels:
          k8s-app: bug
      spec:
        affinity:
          nodeAffinity:
            requiredDuringSchedulingIgnoredDuringExecution:
              nodeSelectorTerms:
              - matchExpressions:
                - key: zone
                  operator: In
                  values:
                  - dc2
                  - dc1
        containers:
        - command:
          - /usr/bin/sleep
          - 1h
          image: registry.redhat.io/rhel7-minimal:7.6-253
          imagePullPolicy: IfNotPresent
          name: bug
          resources: {}
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
        dnsPolicy: ClusterFirst
        nodeSelector:
          node-role.kubernetes.io/compute: "true"
        restartPolicy: Always
        schedulerName: default-scheduler
        securityContext: {}
        terminationGracePeriodSeconds: 30
kind: ControllerRevision
metadata:
  annotations:
    deprecated.daemonset.template.generation: "2"
  creationTimestamp: null
  labels:
    controller-revision-hash: "3086455462"
    k8s-app: bug
  name: bug-74db8998b6
  ownerReferences:
  - apiVersion: apps/v1
    blockOwnerDeletion: true
    controller: true
    kind: DaemonSet
    name: bug
    uid: 83c6d704-8771-11e9-86e3-525400aabb13
  selfLink: /apis/apps/v1/namespaces/test-lp-02389250/controllerrevisions/bug-74db8998b6
revision: 202   <----- increasing on booth ControllerRevision
```

Pods rollout is stuck on Terminating state on the first pod and is looping on creating/terminating this pod again and again

```
$ oc get all
NAME            READY     STATUS        RESTARTS   AGE
pod/bug-6pd2t   1/1       Running       0          28m
pod/bug-bfnjd   1/1       Running       0          28m
pod/bug-hhcwr   0/1       Terminating   0          3s
pod/bug-t8rmb   1/1       Running       0          28m

NAME                 DESIRED   CURRENT   READY     UP-TO-DATE   AVAILABLE   NODE SELECTOR                          AGE
daemonset.apps/bug   4         4         3         0            3           node-role.kubernetes.io/compute=true   28m
```

```
$ oc get all
NAME            READY     STATUS        RESTARTS   AGE
pod/bug-6pd2t   1/1       Running       0          29m
pod/bug-bfnjd   1/1       Running       0          29m
pod/bug-t8rmb   1/1       Running       0          29m
pod/bug-wqszx   1/1       Terminating   0          32s
```

##### Current Result
Rollout never terminates.
A new controllerrevision is created, there are now 2 controllerrevisions for the same daemonset.
The scheduler create new versions of controllerrevision/daemonset quickly in infinite loop.

##### Expected Result
Daemonset should rolling out successfully.

##### Additional Information

- Cloud provider or hardware configuration:
No cloud provider integration, KVM as bare metal

- OS (e.g: `cat /etc/os-release`):
```
$ cat /etc/redhat-release 
Red Hat Enterprise Linux Server release 7.6 (Maipo)
```

- Kernel (e.g. `uname -a`):
```
$ uname -a
Linux ocp3-ans311-b1.ocp.lab 3.10.0-957.5.1.el7.x86_64 #1 SMP Wed Dec 19 10:46:58 EST 2018 x86_64 x86_64 x86_64 GNU/Linux
```

- Install tools:
openshift-ansible-3.11.98-1.git.0.3cfa7c3.el7.noarch

- Network plugin and version (if this is a network-related bug):
None

- Others:
Noner
