### ISSUE TITLE
Cluster Loader should check for objects/pods running before exit

### ISSUE THREAD

**Issue by akrzos** [openshift/origin#23308]
Cluster Loader should check for all objects to be running after it completes creating all objects.  Currently it only checks if they are running from within a tuningset step.  This means if any objects created on the last step that doesn't land exactly on the boundary of a step will pass without checking if the objects are actually running.

##### Version
Client Version: version.Info{Major:"4", Minor:"1+", GitVersion:"v4.1.0", GitCommit:"1016bda6b", GitTreeState:"", BuildDate:"2019-04-09T04:48:59Z", GoVersion:"", Compiler:"", Platform:""}
Server Version: version.Info{Major:"1", Minor:"14+", GitVersion:"v1.14.0+dd9056a", GitCommit:"dd9056a", GitTreeState:"clean", BuildDate:"2019-06-22T18:07:05Z", GoVersion:"go1.12.6", Compiler:"gc", Platform:"linux/amd64"}

##### Steps To Reproduce
1. Use Cluster Loader

Example cluster loader configuration:
```
provider: local
ClusterLoader:
  cleanup: false
  projects:
    - num: 1
      basename: nodevertical
      tuning: default
      ifexists: delete
      pods:
        - num: 300
          basename: nodevert
          file: nodevert-pod-labeled.yaml
  tuningsets:
    - name: default
      pods:
        stepping:
          stepsize: 350
          pause: 0
          timeout: 60
        ratelimit:
          delay: 0
```

##### Current Result
Above example runs completely but leaves a number of pods in pending state as maxpods is exceeded.

##### Expected Result
The pods are not running thus cluster loader should exit 1.
