### ISSUE TITLE
ImageChangeTrigger creates new ReplicationControllers even when disabled.

### ISSUE THREAD

**Issue by blentz** [openshift/origin#23506]
I'm resurrecting issue #20172 , as it still persists on v3.11. I haven't tested any 4.x versions, but expect it to still be present, as it has not been fixed.

##### Version
oc v3.11.0+0cbc58b
kubernetes v1.11.0+d4cacc0
features: Basic-Auth GSSAPI Kerberos SPNEGO

Server https://192.168.42.64:8443
kubernetes v1.11.0+d4cacc0

##### Steps To Reproduce
1. Create DC with the following trigger:
```
    triggers:
      - type: ConfigChange
      - imageChangeParams:
          automatic: false
          containerNames:
            - "helloworld"
          from:
            kind: ImageStreamTag
            name: "helloworld:v1"
            namespace: "test"
        type: ImageChange
```
2. Apply DC from file with the following section:
```
    triggers:
      - type: ConfigChange
      - imageChangeParams:
          automatic: false
          containerNames:
            - "helloworld"
          from:
            kind: ImageStreamTag
            name: "helloworld:v2"
            namespace: "test"
        type: ImageChange
```

##### Current Result
Deployment triggered with new image and clause "Image change"

##### Expected Result
DC updated but not triggered

##### Additional Information
oc set triggers for this DC shows image trigger auto=false before and after apply
