### ISSUE TITLE
possibility to push images from external registry to internal straight-through

### ISSUE THREAD

**Issue by shalberd** [openshift/origin#23510]
I am using openShift 3.11 and have yet to find a way to seamlessly move images on demand from an external docker registry to the openshift-internal registry without using docker tooling.

I am aware of the  docker way, but would prefer something akin to the BuildConfig in openShift, declaratively in yaml.

This did not work, as it leads to a builder image, not to a from-to straight-through pull/push.

Pulling the image is ok, imagestreams in the internal repo can be referenced as well, but it is not the correct kind of config for starting a mere image from-to job:

```
apiVersion: v1
kind: Template
metadata:
  name: remote-to-internal-template
  namespace: openshift
parameters:
  - name: IMAGE_NAME
    description: "The name of the image"
    required: true
  - name: IMAGE_VERSION
    description: "The version of the image"
    required: true
  - name: DOCKER_REGISTRY
    description: "the repo to pull from"
    required: true
objects:
- apiVersion: v1
  kind: BuildConfig
  metadata:
    name: remote-to-internal-${IMAGE_NAME}
    namespace: openshift
    labels:
      order: myorder
  spec:
    source:
      from:
        kind: "DockerImage"
        name: "${DOCKER_REGISTRY}/${IMAGE_NAME}:${IMAGE_VERSION}"
      pullSecret:
          name: "source-repo-secret"
    output:
      to:
        kind: "ImageStreamTag"
        name: "${IMAGE_NAME}:${IMAGE_VERSION}"
    strategy:
      customStrategy:
        from:
          kind: "DockerImage"
          name: "${DOCKER_REGISTRY}/${IMAGE_NAME}:${IMAGE_VERSION}"
        pullSecret:
          name: "source-repo-secret"
```
