### ISSUE TITLE
Reapplying BuildConfig manifest triggers unnecessary build

### ISSUE THREAD

**Issue by crmarques** [openshift/origin#23696]
Reappling same BuildConfig manifest triggers unnecessary builds because it clears `lastTriggeredImageID` properties from `imageChange` trigger. This is very inconvenient when using an automation tool that ensure configuration from a config repo.

##### Version
```
oc v3.11.0+62803d0-1
kubernetes v1.11.0+d4cacc0
features: Basic-Auth GSSAPI Kerberos SPNEGO

Server https://xxxxx:443
openshift v3.11.0+2b20ad0-263
kubernetes v1.11.0+d4cacc0
```

##### Steps To Reproduce
1. Create a build config manifest, for example:

```
apiVersion: build.openshift.io/v1
kind: BuildConfig
metadata:
  name: my-builder
spec:
  source:
    type: Git
    git:
      uri: https://xxx/repo.git
  output:
    to:
      kind: ImageStreamTag
      name: my-image:latest
  strategy:
    type: Docker
    dockerStrategy:
      from:
        kind: ImageStreamTag
        name: base-image:v0.1
  triggers:
  - type: ConfigChange
  - type: ImageChange
```

2. Apply manifest:

```
oc apply -f my-builder.yaml
```

3. API processes and creates the following definition:

```
 ...
  triggers:
  - type: ConfigChange
  - imageChange:
      lastTriggeredImageID: base-image@sha256:53767dca35dc9da1266eac8eb9e5524cea4b00dd5a9a3e784bc400ea5490aff8
    type: ImageChange
```

4. Reapply manifest:

```
oc apply -f my-builder.yaml
```

##### Current Result

Get object and API clears `lastTriggeredImageID` properties:

```
  triggers:
  - type: ConfigChange
  - imageChange: {}
    type: ImageChange
```

 this triggers a new build after 10 min.

##### Expected Result

BuildConfig object keeps `lastTriggeredImageID` properties, not triggering a new build.
