### ISSUE TITLE
'from.name' declaration in source strategy always adds 'latest' as tag

### ISSUE THREAD

**Issue by svettwer** [openshift/origin#23882]
Hi! :wave: 

I've created a OpenShift template for one of our applications leveraging OpenShift S2I. The template provides the possibility to not only specify the builder image name but also the builder image tag to use during S2I. After applying the template, OpenShift  added a `:latest` to the builder image name no matter whether I've provided a tag myself or not. That results in a broken build config as the builder image name cannot be found in the image stream.

##### Version
3.11.0+0cbc58b

##### Steps To Reproduce
1. 
Create a template containing a build config using the following build strategy definition:
```yaml
      strategy:
        type: Source
        sourceStrategy:
          from:
            kind: ImageStream
            name: ${BUILDER_IMAGE}:${BUILDER_IMAGE_TAG}
```

2. process and apply the template
3. get the template from openshift
4. find
```yaml
      from:
        kind: ImageStreamTag
        name: <builder-image>:<builder-image-tag>:latest
```

##### Current Result
Currently, the tag `latest` is always added to the base image definition no matter whether a tag reference has added by the user or not. This results in a broken build as the referenced base image cannot be found.

##### Expected Result
That the provided image tag is used and no additional `latest` is added.

##### Additional information
- I've observed this behavior on minishift 3.11 during development
- The issue is not located in the `oc process` command. I've checked the output of it and there, the image reference is correct.

Thx and best regards
Sven
