### ISSUE TITLE
Could not login using OpenID Connect

### ISSUE THREAD

**Issue by 29x10** [openshift/origin#23911]
I am configuring auth0 as openid provider, but when I use oc login --token=id_token, it says 

`error: The token provided is invalid or expired.`

##### Version
[provide output of the `openshift version` or `oc version` command]
```
Client Version: version.Info{Major:"4", Minor:"1+", GitVersion:"v4.1.7-201907171753+1e3cff4-dirty", GitCommit:"1e3cff4", GitTreeState:"dirty", BuildDate:"2019-07-18T00:11:14Z", GoVersion:"go1.11.6", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"13+", GitVersion:"v1.13.4+4b86cc5", GitCommit:"4b86cc5", GitTreeState:"clean", BuildDate:"2019-07-24T19:42:25Z", GoVersion:"go1.11.6", Compiler:"gc", Platform:"linux/amd64"}
```

##### Steps To Reproduce
Here is my identity configuration for openid:

```
    - mappingMethod: claim
      name: auth0
      openID:
        claims:
          email:
            - email
          'name:':
            - email
          preferredUsername:
            - email
        clientID: my_client_id
        clientSecret:
          name: openid-client-secret-qbmwv
        extraScopes:
          - email
        issuer: 'https://xxx.auth0.com'
      type: OpenID
```

##### Current Result
`error: The token provided is invalid or expired.`

##### Expected Result
authenticate successfully

##### Additional Information
[try to run `$ oc adm diagnostics` (or `oadm diagnostics`) command if possible]
[if you are reporting issue related to builds, provide build logs with `BUILD_LOGLEVEL=5`]
[consider attaching output of the `$ oc get all -o json -n <namespace>` command to the issue]
[visit https://docs.openshift.org/latest/welcome/index.html]
