### ISSUE TITLE
Incorrect reconciliation of OpenShift Route based on K8s Ingress

### ISSUE THREAD

**Issue by mhofstetter** [openshift/origin#23937]
When OpenShift reconciles and therefore creates an OpenShift `Route` for each Kubernetes `Ingress`, the property `spec.port.targetPort` is set with the name of the port on the `Pod` instead of the name of the port on the referenced `Service`. This gets problematic when they differ in their names, as the referenced name doesn't exist on the `Service`.

Responsible controller: https://github.com/openshift/origin/blob/v3.11.0/pkg/route/controller/ingress/ingress.go#L576

##### Version
OpenShift Master: v3.11.141
Kubernetes Master: v1.11.0+d4cacc0

##### Steps To Reproduce

1. Create a k8s `Service` which targets a named targetPort `default`(on the `Pod`) which differs from the name of the port on the service `http-default`.

```
oc apply -f - << EOF
apiVersion: v1
kind: Service
metadata:
  name: app
spec:
  ports:
  - name: http-default
    port: 8080
    protocol: TCP
    targetPort: default
  selector:
    deployment: app
EOF
```

2. Create a k8s `Ingress` which targets the previously created `Service` on its named service port `http-default`.

```
oc apply -f - << EOF
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: app
spec:
  rules:
  - host: app.test.com
    http:
      paths:
      - backend:
          serviceName: app
          servicePort: http-default
        path: /
EOF
```

##### Current Result

OpenShift creates a `Route` which targets the service `app` but the targetPort is the name of the `Pod` (`default`)  instead of the one of the `Service` (`http-default`).

```
oc get route app-6dqpg -o yaml
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  ...
spec:
  host: app.test.com
  path: /
  port:
    targetPort: default
  to:
    kind: Service
    name: app
...
```

Therefore no connection is possible via the `Route`. Even the OpenShift webconsole warns about this ("Route target port is set to "default", but service "app" has no port with that name.")

##### Expected Result

The created `Route` should target the name of the port on the `Service` instead of the one of the `Pod`.

##### Additional Information

* Relevant sourcecode location: https://github.com/openshift/origin/blob/v3.11.0/pkg/route/controller/ingress/ingress.go#L576
* Error seems to be present in 4.x: https://github.com/openshift/openshift-controller-manager/blob/release-4.4/pkg/route/ingress/ingress.go#L576 
* Creating an Route with `oc expose service app` creates a correct Route with the name of the service port
* The description of the property `route.spec.port.targetPort` is quite irritating. maybe this is the source of the error. (_The target port on pods selected by the service this route points to. If
     this is a string, it will be looked up as a named port in the target
     endpoints port list._)
