### ISSUE TITLE
OpenAPI spec marking optional v1.Route fields as required

### ISSUE THREAD

**Issue by rblaine95** [openshift/origin#24060]
When using Helm v3-rc.1, which includes OpenAPI validation before executing an install or upgrade, Route objects fail if they're missing optional fields (such as `spec.host`, `status`, `spec.to.weight`).

After raising on the Helm Github (https://github.com/helm/helm/issues/6830), I was pointed to the [OKD v3.11 OpenAPI](https://raw.githubusercontent.com/openshift/origin/v3.11.0/api/swagger-spec/oapi-v1.json) spec which incorrectly lists these fields as Required when, according to the [Docs](https://docs.okd.io/3.11/dev_guide/routes.html) and [API](https://docs.okd.io/3.11/rest_api/apis-route.openshift.io/v1.Route.html), they should be optional.

##### Version
```sh
» oc version
oc v3.11.0+0cbc58b
kubernetes v1.11.0+d4cacc0
features: Basic-Auth GSSAPI Kerberos SPNEGO

Server https://okd.example.net:8443
openshift v3.11.0+fef6f83-275
kubernetes v1.11.0+d4cacc0
```

##### Steps To Reproduce
1. Have a Helm Chart that has an OKD Route in the `templates/` dir
2. Using Helm `>=v3.beta-5`, run `helm template ./my-chart-with-route --validate` (or `helm install ./my-chart-with-route`)
3. See error:
```
Error: unable to build kubernetes objects from release manifest: error validating "": error validating data: [ValidationError(Route.spec.to): missing required field "weight" in com.github.openshift.api.route.v1.RouteTargetReference, ValidationError(Route.spec): missing required field "host" in com.github.openshift.api.route.v1.RouteSpec, ValidationError(Route): missing required field "status" in com.github.openshift.api.route.v1.Route]
```
##### Current Result
OKD v3.11 OpenAPI incorrectly lists some Optional fields as Required.

##### Expected Result
OKD v3.11 OpenAPI spec should list Required fields as Required and Optional fields as Optional.

**Edit:**
```yaml
"v1.RouteSpec": {
  "id": "v1.RouteSpec",
  "description": "...",
  "required": [
    "host", # <--- ?
    "to"
  ],
```
```yaml
"v1.RouteStatus": {
  "id": "v1.RouteStatus",
  "description": "...",
  "required": [
    "ingress" # <-- ?
  ],
```
```yaml
"v1.RouteTargetReference": {
  "id": "v1.RouteTargetReference",
  "description": "...",
  "required": [
    "kind",
    "name",
    "weight" # <--- ?
  ],
```

**Comment by rblaine95** [comment]
This is causing a blocker for using any Helm version `>=v3.beta-5`, including the recent `RC` versions and any future versions of Helm v3 (at least until Helm v3.1.0 which will allow you to disable OpenAPI Validation https://github.com/helm/helm/pull/6819)

**Comment by rblaine95** [comment]
Now that Helm v3.0.0 has been tagged and [released](https://github.com/helm/helm/releases/tag/v3.0.0), this bug is preventing anyone using OKD from upgrading to Helm 3.

**Comment by CermakM** [comment]
There are IMHO more resources with fields that shouldn't be marked as required, for example:

```yaml
   "v1.BuildConfig": {
    "required": [
     "spec",
     "status"  # <--- ???
    ],
```
or
```yaml
  "v1.BuildConfigSpec": {
    "required": [
     "triggers",
     "strategy",
     "nodeSelector"  # <--- ???
    ],
```

**Comment by nccurry** [comment]
I opened a bugzilla for this:
https://bugzilla.redhat.com/show_bug.cgi?id=1773682

**Comment by Andrei-Stepanov** [comment]
Got the the similar error:

```
Error: unable to build kubernetes objects from release manifest: error validating "": error validating data: [ValidationError(BuildConfig.spec): missing required field "nodeSelector" in com.github.openshift.api.build.v1.BuildConfigSpec, ValidationError(BuildConfig.status): missing required field "lastVersion" in com.github.openshift.api.build.v1.BuildConfigStatus]
helm.go:76: [debug] error validating "": error validating data: [ValidationError(BuildConfig.spec): missing required field "nodeSelector" in com.github.openshift.api.build.v1.BuildConfigSpec, ValidationError(BuildConfig.status): missing required field "lastVersion" in com.github.openshift.api.build.v1.BuildConfigStatus]
```

**Comment by scniro** [comment]
same, any update?

**Comment by scniro** [comment]
FWIW I was able to move forward by stubbing out a junk `status` object

```yaml
status:
  ingress:
    - conditions:
      - lastTransitionTime: "2019-12-06T03:24:58Z"
        status: "True"
        type: Admitted
      host: <host>
      routerCanonicalHostname: <host>
      routerName: default
      wildcardPolicy: None
```
