### ISSUE TITLE
git clone fails with submodules when more than one source secret is involved

### ISSUE THREAD

**Issue by mcandre** [openshift/origin#24120]
BuildConfig's don't provide a clear mechanism for cloning version control repositories when multiple source secrets are required. For example, when the main repository uses one SSH deploy key and the main repo depends on a secondary git module repository with a different SSH deploy key.

I tried listing out keys:

```yaml
  source:
    type: "Git"
    git:
      uri: "git@github.com:foo/bar.git"
      ref: "master"
    secrets:
      - secret:
          name: "starlight-private-key"
      - secret:
          name: "mage-extras-private-key"
      - secret:
          name: "prql-private-key"
```

I tried explicitly linking these secrets to the builder and to the default OpenShift accounts. But builds continue to fail with authentication errors.
