### ISSUE TITLE
Infinite deployment loop on ImageChange trigger

### ISSUE THREAD

**Issue by mnowrot** [openshift/origin#24523]
##### Description
After adding an ImageChange trigger to a DeployentConfig, the deployment process is entering an infinite loop, spawning -deploy pods until the DeploymentConfig is removed. Each -deploy pod gets scheduled and then canceled. The reason for redeploy always being "image change". Basically, it is like the DeploymentConfig is thinking that the image is being updated every other second.

##### Version
Client Version: openshift-clients-4.2.2-201910250432
Server Version: 4.2.10
Kubernetes Version: v1.14.6+17b1cc6

##### What were you trying to achieve?
After an image tag is updated in an external container registry, I'd like my application to automatically redeploy, using the newly updated image.

##### Steps To Reproduce
1. Import image for tracking
```bash
oc import-image my-project/app-server:1.0.0-SNAPSHOT-latest --from=mycorp.azurecr.io/my-org-unit/my-project/app-server:1.0.0-SNAPSHOT-latest --confirm --scheduled -n my-project
```
So far everything works fine. An ImageStream and ImageStreamTag get created and the changes to the original tag are seen by the ImageStream (I can see the sha256 checksums being updated in the History tab as there are new pushes to `mycorp.azurecr.io/my-org-unit/my-project/app-server:1.0.0-SNAPSHOT-latest`).

2. Create the DeploymentConfig (I'm using an Operator to do that, hence the `{{ variables }}` in the yaml file below:
```yaml
kind: DeploymentConfig
apiVersion: apps.openshift.io/v1
metadata:
  name: "{{ meta.name }}-application"
  namespace: "{{ meta.namespace }}"
spec:
  replicas: {{ size }}
  selector:
    app: "{{ meta.name }}"
  triggers:
    - type: ConfigChange
    - type: ImageChange
      imageChangeParams:
        automatic: true
        containerNames:
          - app-server
        from:
          kind: ImageStreamTag
          name: app-server:1.0.0-SNAPSHOT-latest
          namespace: my-project
  template:
    metadata:
      labels:
        app: "{{ meta.name }}"
    spec:
      serviceAccountName: app-server-operator
      imagePullSecrets:
        - name: "{{ external_registry_image_pull_secret_name }}"
      containers:
        - image: image-registry.openshift-image-registry.svc:5000/my-project/app-server:1.0.0-SNAPSHOT-latest
          imagePullPolicy: Always
          securityContext:
            runAsUser: 998
            runAsGroup: 996
          name: app-server
          ports:
            - containerPort: 8080
              protocol: TCP
```

##### Current Result
The deployment process is entering an infinite loop, spawning -deploy pods until the DeploymentConfig is removed (or the ImageChange trigger section gets commented out). Each -deploy pod gets scheduled and then a few seconds later canceled. The reason for redeploy always being "image change".

##### Expected Result
Application gets deployed in the Openshift cluster. After a new change is pushed to the external container registry, the application will automatically redeploy. The redeployment process actually finishes.
