### ISSUE TITLE
Azure-files error on Openshift 4.3 : exit status 32 mount error(2): No such file or directory 

### ISSUE THREAD

**Issue by abudavis** [openshift/origin#24961]
We are trying to dynamically provision azure file persistent volume on Openshift cluster 4.3.18 (as per instructions in  https://docs.openshift.com/container-platform/4.3/storage/dynamic-provisioning.html#azure-file-definition_dynamic-provisioning & https://docs.microsoft.com/en-us/azure/aks/azure-files-dynamic-pv) deployed on Azure and got the below reported error (see at the bottom). Please help!
 
More info:
- Logged in Bugzilla : https://bugzilla.redhat.com/show_bug.cgi?id=1833697
- Successfully able to reproduce the issue on PRE-PROD and PROD Openshift cluster 4.3.18
- Kubernetes version : v1.16.2
- Size of cluster : 3 masters, 2 workers.
- Static provisioning also gives the same error (see at the bottom)
-*This is similar to issue reported: Using Azure Files with Kubernetes causes mount error(2): No such file or directory #46*
- NOTE: It was verified to work okay with Openshift 4.2 (k8s version v1.14) with Azure files. But not with Openshift 4.3. May be a k8s version problem? 

Storage class yaml:
```
kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: azurerwx
provisioner: kubernetes.io/azure-file
mountOptions:
  - dir_mode=0777
  - file_mode=0777
  - uid=0
  - gid=0
  - mfsymlinks
  - cache=strict
parameters:
  skuName: Standard_LRS
reclaimPolicy: Retain
volumeBindingMode: Immediate
```
 
Azurefilepod yaml:
```
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: azurefile
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: azurerwx
  resources:
    requests:
      storage: 5Gi
---
apiVersion: v1
kind: Pod
metadata:
  name: mountfilepod
spec:
  containers:
  - image: busybox
    command:
      - sleep
      - "3600"
    imagePullPolicy: IfNotPresent
    name: busybox
    volumeMounts:
    - mountPath: /mnt/azure
      name: volume
  restartPolicy: Always
  volumes:
    - name: volume
      persistentVolumeClaim:
        claimName: azurefile
```
 
---------
 
$ oc get pvc
```
NAME        STATUS   VOLUME                                     CAPACITY   ACCESS MODES   STORAGECLASS   AGE
azurefile   Bound    pvc-ff42cc57-9e7b-4ac5-8770-4cb4f919b177   5Gi        RWX            azurerwx       11h
```

$ oc get pv
```
NAME                                       CAPACITY   ACCESS MODES   RECLAIM POLICY   STATUS     CLAIM                                                STORAGECLASS   REASON   AGE
pvc-ff42cc57-9e7b-4ac5-8770-4cb4f919b177   5Gi        RWX            Retain           Bound      ace/azurefile                                        azurerwx                11h
```
 
$ oc get pods
```
NAME           READY   STATUS              RESTARTS   AGE
mountfilepod   0/1     ContainerCreating   0          2m33s
```

——
THE ERROR:

```
8m15s       Warning   FailedMount   pod/mountfilepod   (combined from similar events): MountVolume.SetUp failed for volume "pvc-ff42cc57-9e7b-4ac5-8770-4cb4f919b177" : mount failed: exit status 32
Mounting command: systemd-run
Mounting arguments: --description=Kubernetes transient mount for /var/lib/kubelet/pods/95365137-01b4-4031-9700-05189f318988/volumes/kubernetes.io~azure-file/pvc-ff42cc57-9e7b-4ac5-8770-4cb4f919b177 --scope -- mount -t cifs -o cache=strict,dir_mode=0777,file_mode=0777,gid=0,mfsymlinks,uid=0,username=f21150e7e1f014d15a77c20,password=qk4N+2z2HnUrhWo8yCWagAoFal4xexRkuE//1FXEps22IUV/1INF+uLYMX9CG/53qJprs6qu3fG7nhs+eKhtBA==,vers=3.0 //f21150e7e1f014d15a77c20.file.core.windows.net/testcluster-d68nv-dyna-pvc-ff42cc57-9e7b-4ac5-8770-4cb4f919b177 /var/lib/kubelet/pods/95365137-01b4-4031-9700-05189f318988/volumes/kubernetes.io~azure-file/pvc-ff42cc57-9e7b-4ac5-8770-4cb4f919b177
Output: Running scope as unit: run-r476d8a255fbf4cb09ee6d6b9bcb341a6.scope
mount error(2): No such file or directory
Refer to the mount.cifs(8) manual page (e.g. man mount.cifs)
2m13s       Warning   FailedMount   pod/mountfilepod   Unable to attach or mount volumes: unmounted volumes=[volume], unattached volumes=[volume default-token-gnb5t]: timed out waiting for the condition
```
