### ISSUE TITLE
Set horizontal-pod-autoscaler-downscale-delay in master-config.yaml

### ISSUE THREAD

**Issue by woland7** [openshift/origin#25907]
Openshift Origin v3.11
How am I supposed to pass these parameters in the master-config.yaml?

`kubernetesMasterConfig:`
`  apiServerArguments:`
`    cloud-config:`
`    - /etc/origin/cloudprovider/openstack.conf`
`    cloud-provider:`
`    - openstack`
`    storage-backend:`
`    - etcd3`
`    storage-media-type:`
`    - application/vnd.kubernetes.protobuf`
`  controllerArguments:`
`    horizontal-pod-autoscaler-downscale-delay=2m0s`
`    cloud-config:`
`    - /etc/origin/cloudprovider/openstack.conf`
`    cloud-provider:`
`    - openstack`
`    cluster-signing-cert-file:`
`    - /etc/origin/master/ca.crt`
`    cluster-signing-key-file:`
`    - /etc/origin/master/ca.key`
`    pv-recycler-pod-template-filepath-hostpath:`
`    - /etc/origin/master/recycler_pod.yaml`
`    pv-recycler-pod-template-filepath-nfs:`
`    - /etc/origin/master/recycler_pod.yaml`
`  masterCount: 1`
`  masterIP: 192.168.10.24`

If I put in this way, it gives me an error in the yaml syntax. And I haven't been able to find any example for it.

**Comment by woland7** [comment]
```
kubernetesMasterConfig:
  apiServerArguments:
    cloud-config:
    - /etc/origin/cloudprovider/openstack.conf
    cloud-provider:
    - openstack
    storage-backend:
    - etcd3
    storage-media-type:
    - application/vnd.kubernetes.protobuf
  controllerArguments:
    **horizontal-pod-autoscaler-downscale-delay:**
    **- 2m0s**
    cloud-config:
    - /etc/origin/cloudprovider/openstack.conf
    cloud-provider:
    - openstack
    cluster-signing-cert-file:
    - /etc/origin/master/ca.crt
    cluster-signing-key-file:
    - /etc/origin/master/ca.key
    pv-recycler-pod-template-filepath-hostpath:
    - /etc/origin/master/recycler_pod.yaml
    pv-recycler-pod-template-filepath-nfs:
    - /etc/origin/master/recycler_pod.yaml
```

I found them out, you can add them in this way.
