### ISSUE TITLE
Not able to label services

### ISSUE THREAD

**Issue by anderssv** [openshift/origin#2634]
I'm creating a service (amongst other things), and trying to add labels to it to ease cleanup. Most items support metadata->labels, but this does not seem to work on services? Running on 0.5.3.

Template:
```
items:
- apiVersion: v1beta1
  id: testservice
  kind: Service
  port: 8080
  selector:
    deployment_id: test
  metadata:
    name: test
    labels:
      deployment_id: test
```

After osc create I get:
```
NAME                       LABELS    SELECTOR                     IP(S)            PORT(S)
testservice                <none>    deployment_id=test           172.30.251.234   8080/TCP
```

So obviously no labels here, I try to delete just to be sure:
```
$ osc delete services -l deployment_id=test
No resources found
```

**Comment by derekwaynecarr** [comment]
The Kubernetes v1beta1 API did not uniformly support labeling objects across all of its object types.

You can properly use labels by using the v1beta3 syntax like the following example:

```shell
apiVersion: v1beta3
kind: Service
metadata:
  labels:
    name: redis-master
  name: redis-master
spec:
  ports:
  - nodePort: 0
    port: 6379
    protocol: TCP
    targetPort: 6379
  selector:
    name: redis-master
  sessionAffinity: None
  type: ClusterIP
```

Then the label selector on delete syntax will work fine.

**Comment by derekwaynecarr** [comment]
@danmcp - can you close this issue since the problem was lack of labeling support in v1beta1 for service objects?

**Comment by anderssv** [comment]
Thanks for the swift feedback guys. For future reference my cleaned up conversion to v1beta3 is;

```
- apiVersion: v1beta3
  kind: Service
  metadata:
    name: testservice
    labels:
      deployment_id: test
  spec:
    ports:
      - port: 8080
        protocol: TCP
    selector:
      deployment_id: test
```
