### ISSUE TITLE
osc login can create configs with back-step paths

### ISSUE THREAD

**Issue by thoraxe** [openshift/origin#2786]
```
[joe@ose3-master beta4]$ osc version
osc v0.5.2.2-22-g84b1674-dirty
kubernetes v0.17.1-804-g496be63
```

```
[alice@ose3-master ~]$ osc config view
apiVersion: v1
clusters:
- cluster:
    certificate-authority: ../../../../etc/openshift/master/ca.crt
    server: https://ose3-master.example.com:8443
  name: ose3-master-example-com:8443
contexts:
- context:
    cluster: ose3-master-example-com:8443
    namespace: demo
    user: alice/ose3-master-example-com:8443
  name: demo/ose3-master-example-com:8443/alice
current-context: demo/ose3-master-example-com:8443/alice
kind: Config
preferences: {}
users:
- name: alice/ose3-master-example-com:8443
  user:
    token: yjL5tiUhPevV9NNq60_Mb26ZY6Uq0SSzRk1asTqxaok
```
