### ISSUE TITLE
Templates parameters not showing on web console

### ISSUE THREAD

**Issue by vbehar** [openshift/origin#3839]
Hi,

I have a template which renders strangely in the web console UI (when creating a new app from a template) : the parameters are not shown. (same thing for the list of images, which are missing).

It seems related to the BuildConfig's dockerStrategy : if I changed it to sourceStrategy, I can see my parameters in the web console UI.

Here is the template that does not work : 

```
kind: Template
apiVersion: v1
metadata:
  name: not-working

parameters:

- name: APPLICATION
- name: BASE_IMAGE
- name: GIT_URI

objects:

- kind: BuildConfig
  apiVersion: v1
  metadata:
    name: ${APPLICATION}
  spec:
    strategy:
      type: Docker
      dockerStrategy:
        from:
          kind: DockerImage
          name: ${BASE_IMAGE}
    source:
      type: Git
      git:
        uri: ${GIT_URI}
    output:
      to:
        kind: ImageStreamTag
        name: ${APPLICATION}:latest

- kind: ImageStream
  apiVersion: v1
  metadata:
    name: ${APPLICATION}
  spec:
    tags:
    - name: latest
      from:
        kind: DockerImage
        name: library/${APPLICATION}:latest

- kind: DeploymentConfig
  apiVersion: v1
  metadata:
    name: ${APPLICATION}
  spec:
    replicas: 1
    selector:
      deploymentconfig: ${APPLICATION}
    template:
      metadata:
        name: ${APPLICATION}
        labels:
          deploymentconfig: ${APPLICATION}
      spec:
        containers:
        - name: ${APPLICATION}
          image: library/${APPLICATION}:latest
```

and the template that does work (the only change is line 21 : "dockerStrategy" has been renamed "sourceStrategy") : 

```
kind: Template
apiVersion: v1
metadata:
  name: working

parameters:

- name: APPLICATION
- name: BASE_IMAGE
- name: GIT_URI

objects:

- kind: BuildConfig
  apiVersion: v1
  metadata:
    name: ${APPLICATION}
  spec:
    strategy:
      type: Docker
      sourceStrategy:
        from:
          kind: DockerImage
          name: ${BASE_IMAGE}
    source:
      type: Git
      git:
        uri: ${GIT_URI}
    output:
      to:
        kind: ImageStreamTag
        name: ${APPLICATION}:latest

- kind: ImageStream
  apiVersion: v1
  metadata:
    name: ${APPLICATION}
  spec:
    tags:
    - name: latest
      from:
        kind: DockerImage
        name: library/${APPLICATION}:latest

- kind: DeploymentConfig
  apiVersion: v1
  metadata:
    name: ${APPLICATION}
  spec:
    replicas: 1
    selector:
      deploymentconfig: ${APPLICATION}
    template:
      metadata:
        name: ${APPLICATION}
        labels:
          deploymentconfig: ${APPLICATION}
      spec:
        containers:
        - name: ${APPLICATION}
          image: library/${APPLICATION}:latest
```

I don't know if it is really related to the dockerStrategy, but I have no problems with templates using the sourceStrategy.

Thanks,
Vincent
