### ISSUE TITLE
A variable to expand to the default domain in templates

### ISSUE THREAD

**Issue by chmouel** [openshift/origin#3910]
It would be nice if it was possible in template to expand to the default routingConfig.Subdomain to make it easier to share complete templates for template authors.

if we have a template like this : 

```yaml
apiVersion: v1
kind: Route
metadata:
  labels:
    name: hello-openshift
  name: hello-openshift-route
spec:
  host: hello.${defaultSubdomain}
  tls:
    termination: edge
  to:
    name: hello-openshift-service
```

the defaultSubdomain will be expanded to what is configured in routingConfig.subdomain (or the default which is currently `router.default.local`)

I am not sure if we can have a 'reserved' keyword to not have conflict if there is a variable actually named like that, or have something like openshift.RoutingConfig.subDomain for openshift reserved variables.
