### ISSUE TITLE
UI adds `generatedby` label instead of namespaced annotation

### ISSUE THREAD

**Issue by spadgett** [openshift/origin#3966]
The Web Console adds the label `generatedby: OpenShiftWebConsole` when creating from a source repository. It should use a namespaced annotation instead.

@liggitt @smarterclayton

**Comment by spadgett** [comment]
Seeing inconsistent use of prefixes in labels. Is this expected?

![openshift_web_console](https://cloud.githubusercontent.com/assets/1167259/9007592/c649baac-3760-11e5-9690-8df2ab22f05f.png)

Also it's different on the command line 

> oc get rc nodejs-ex-1 -o yaml -n project3

```
      labels:
        deployment: nodejs-ex-1
        deploymentconfig: nodejs-ex
        generatedby: OpenShiftWebConsole
        name: nodejs-ex
```

`openshift.io/deployment-config.name` is only displayed in the UI.

**Comment by spadgett** [comment]
UI adds the label `name: nodejs-ex` to services, but the CLI adds label `app: nodejs-ex`.

**Comment by spadgett** [comment]
CLI generated deployment config labels:

```
  labels:
    app: nodejs-ex
```

UI generated deployment config labels:

```
  labels:
    deploymentconfig: nodejs-ex
    generatedby: OpenShiftWebConsole
    name: nodejs-ex
```

I'm not sure why we have a `deploymentconfig` label on the dc itself.
