### ISSUE TITLE
DeploymentConfig trigger doesn't work properly

### ISSUE THREAD

**Issue by sebiwi** [openshift/origin#4284]
Hello, 

I have a DeploymentConfig that's deploying a container from an image right after the build, even if the image does not have the right tag.

Here's the DeploymenConfig:

```
- kind: DeploymentConfig
  apiVersion: v1
  metadata:
    name: chatter-dev-dc
  template:
  spec:
    strategy:
      type: Recreate
      resources: {}
    triggers:
    - type: ConfigChange
    - type: ImageChange
      imageChangeParams:
        automatic: true
        containerNames:
        - chatter-app-dev
        from:
          kind: ImageRepository
          name: chatter-app
          tag: dev
    replicas: 1
    selector: 
      deploymentconfig: chatter-dev-dc
    template:
      metadata:
        labels:
          deploymentconfig: chatter-dev-dc
      spec:
        containers:
        - name: chatter-app-dev
          image: chatter-app:dev
          env:
          - key: PORT
            name: PORT
            value: "8080"
          - key: ENV_NAME
            name: ENV_NAME
            value: dev
          ports:
          - containerPort: 8080
            protocol: TCP
```
The ImageChange trigger is set to work with the "dev" tag, and the built image has the "latest" tag.

Here's the BuildConfig I used to create the image:
```
- apiVersion: v1
  kind: BuildConfig
  metadata:
    name: chatter-bc
  spec:
    source:
      type: Git
      git:
        uri: https://gitserver/username/chatter.git
        ref: master
    strategy:
      type: Source
      sourceStrategy:
        from:
          kind: ImageStreamTag
          clean: true
          name: nodejs-010-centos7:latest
    output: 
      to:
        kind: ImageStream
        name: chatter-app
        tag: latest
    resources: {}
```
With this setup the container is deployed right after the build, which is not the desired behaviour. 

I want the deployment to be triggered after the image is tagged with the "dev" tag.

**Comment by sebiwi** [comment]
This was fixed by referencing an ImageStreamTag instead of an ImageRepository on the DeploymentConfig:

```
...
    - type: ImageChange
      imageChangeParams:
        automatic: true
        containerNames:
        - chatter-app-dev
        from:
          kind: ImageStreamTag
          name: chatter-app:dev
...

```
