### ISSUE TITLE
Permission problem when reading metadata using "Volume Plugi-In"

### ISSUE THREAD

**Issue by roldancer** [openshift/origin#4429]
Hi All,
    I have some "permission" problems reading metadata (labels, annotation),  my image is using the "java" user, but the metadata is mounted as root, I followed the Develper Guide "Chapter 21.4. Using the Volume Plug-in".
Any idea on how to resolve the problem ? is this feature only ready for root containser user ? 

[java@test2-1-526qi ]$ whoami  
java
[java@test2-1-526qi ]$ cat /etc/metadata/labels
cat: /etc/metadata/labels: Permission denied

[java@test2-1-526qi ]$ ls -l /etc/metadata/labels
lrwxrwxrwx. 1 root root 15 Aug 31 04:59 /etc/metadata/labels -> .current/labels
[java@test2-1-526qi ]$ ls -ld /etc/metadata/.current/
drwx------. 2 root root 80 Aug 31 04:59 /etc/metadata/.current/

template:

```
      volumeMounts:
        - name: podinfo
          mountPath: /etc/metadata
          readOnly: false
    volumes:
      - name: podinfo
        metadata:
          items:
            - name: "labels"
              fieldRef:
                fieldPath: metadata.labels
            - name: "annotations"
              fieldRef:
                fieldPath: metadata.annotations
```

Many thanks.
