### ISSUE TITLE
Ulimit support

### ISSUE THREAD

**Issue by nak3** [openshift/origin#4517]
It may depend on https://github.com/kubernetes/kubernetes/issues/3595 , however if  AP server like JBoss/Tomcat is used on OpenShift, I think we need it as soon as possible.

EAP/Tomacat needs ulimit turning. https://access.redhat.com/solutions/874633

**Comment by f-w** [comment]
[Elasticsearch@5](https://www.elastic.co/guide/en/elasticsearch/reference/current/system-config.html) now enforces custom ulimit settings check in prod env. Can the priority of this issue be escalated?

Given that `docker run` supports [--ulimit](https://docs.docker.com/engine/reference/commandline/run/#/set-ulimits-in-container---ulimit) option, how hard is it to relay this DeploymentConfig parameter to docker?

**Comment by therevoman** [comment]
Looking for a solution to this as well.  Need it on a high profile project which needs to run Oracle XE in a container.

**Comment by jmencak** [comment]
Doesn't `CAP_SYS_RESOURCE` help?  Can this not be done by something like:

```
apiVersion: v1
kind: Pod
metadata:
  name: sleep
spec:
  containers:
  - name: friendly-container
    image: "alpine:3.4"
    command: ["/bin/sleep", "3600"]
    securityContext:
      capabilities:
        add:
        - CAP_SYS_RESOURCE
```

And `setrlimit()` inside the container?

```
$ oc rsh sleep
/ # ulimit -l 
16384
/ # ulimit -l unlimited
/ # ulimit -l 
unlimited
/ # 
```
