### ISSUE TITLE
Template parameter and project name

### ISSUE THREAD

**Issue by roberto-gomez** [openshift/origin#4609]
Hello.

I need to use the project name in some fields of my template and I don't know if is possible to get the project name. For example:

```
parameters:
- name: PROJECT_NAME
    value: metadata.namespace
    description: Project name [required]
```

Thanks.
