### ISSUE TITLE
store the environments for a BuildConfig so we can link a build config to Dev -> Test -> Staging -> Prod environments

### ISSUE THREAD

**Issue by jstrachan** [openshift/origin#4693]
When implementing [Continuous Delivery Pipelines](http://fabric8.io/guide/cdelivery.html), a git repo tends to be used to create a stream of docker images and OpenShift templates which then get staged on different environments (Dev -> Test -> Staging -> Prod).

To provide a good developer experience its useful to view a git repository/BuildConfig and all its environments and to easily see which versions of which images/templates are in which environment to help visualise the pipeline.

Each environment could well be just a different kubernetes namespace; though sometimes they may be on completely separate kubernetes clusters (e.g. production might be created via a different OpenStack tenant).

Up to now to help visualise the CD Pipeline we've been using annotations on the BuildConfig but for environments really we could do with a slightly more complex structure than just annotations.

e.g. for each environment we might want something like this...
```yaml
environments:
  - name: Production
    namespace: myproject-prod
    cluster: something.com:8443
  - name: Dev
    namespace: myproject-dev
  - name: Test
    namespace: myproject-test
```
  
if `cluster` is blank it implies its on this cluster; then the `namespace` refers to a kubernetes namespace (OpenShift project) and `name` is the logical name developers wish to refer to it (rather than the physical namespace name which probably has a domain/user/group/build config prefix or something).
