### ISSUE TITLE
Volumes not mounted for Pre-hook container

### ISSUE THREAD

**Issue by ewolinetz** [openshift/origin#4711]
I'm trying to leverage a Recreate Pre-hook and a PV to seed configuration for a container.  I see that my seeding script fails because the mounted path for my container, as specified by my template, cannot be found.  But the application pod succeeds using the same script (and is able to write to the mounted path).  The PVC and PV have status 'bound' when I do a oc get pvc; oc get pv

```
apiVersion: "v1"
  kind: "DeploymentConfig"
  metadata:
    name: "elasticsearch"
  spec:
    strategy:
      type: Recreate
      recreateParams:
        pre:
          failurePolicy: Abort
          execNewPod:
            command: [ "./run.sh" ]
            containerName: "elasticsearch"
    replicas: 1
    selector:
      provider: "openshift"
      component: "elasticsearch"
    template:
      metadata:
        labels:
          provider: "openshift"
          component: "elasticsearch"
      spec:
        containers:
          -
            env:
            -
              name: "KUBERNETES_TRUST_CERT"
              value: "true"
            -
              name: "SERVICE_DNS"
              value: "es-logging-cluster"
            -
              name: "CLUSTER_NAME"
              value: "elasticsearch"
            image: "openshift/elasticsearch:v1"
            name: "elasticsearch"
            ports:
            -
              containerPort: 9200
              name: "http"
            -
              containerPort: 9300
              name: "transport"
            volumeMounts:
              - name: certs
                mountPath: /etc/elasticsearch/keys
                readOnly: true
              - name: pvc
                mountPath: /elasticsearch
                readOnly: false
        volumes:
          - name: certs
            secret:
              secretName: elasticsearch
          - name: pvc
            persistentVolumeClaim:
              claimName: pvc-001
```
