### ISSUE TITLE
Issue with auth not logging when it fails

### ISSUE THREAD

**Issue by ebalsumgo** [openshift/origin#4977]
There seems to be no logging in the master logs even with loglevel=5 about status 500 errors or general authentication errors when working with anything other than AllowAll/DenyAll. In our case we were trying to setup BasicAuth and continuously recieved 500 return code on the CLI end and just generic error in the UI but nothing was logged in the master.
This is happening on OSE-3.0.2.0-0.git.16.4d626fe.el7ose.x86_64
@liggitt has been looking into this with me for the last day or so.

**Comment by liggitt** [comment]
Additional info:
```
  identityProviders:
    - name: remote_auth
      challenge: true
      login: true
      provider:
        apiVersion: v1
        kind: BasicAuthPasswordIdentityProvider
        url: https://example.com/path/to/remote/auth
```

If the remote endpoint returns a 301 redirect or a 401 negotiate challenge, both the UI login and CLI login cases were getting a 500 from the OpenShift OAuth server
