### ISSUE TITLE
Cinder volumes in OpenShift fail to create PV

### ISSUE THREAD

**Issue by childsb** [openshift/origin#5120]
I finally got to testing out the Cinder integration for OpenShift based on the guide you pointed us to (https://github.com/openshift/origin/pull/4403).  However, it fails to create the PV as shown below.  I'm using the latest released OpenShift bits.  Is the Cinder integration in there or is it not yet available?  If not there, could you point me to something pre-release where I can test this?

One other question about the integration.  Do your OpenStack credentials need to always be sourced if OpenShift needs to reschedule a pod?  Or just on initial deployment?

---

[root@openshift-master ~]# oc create -f pv-openshift-registry.yaml
The PersistentVolume "pv-openshift-registry" is invalid.
: invalid value '{GCEPersistentDisk:<nil> AWSElasticBlockStore:<nil> HostPath:<nil> Glusterfs:<nil> NFS:<nil> RBD:<nil> ISCSI:<nil> CephFS:<nil>}', Details: exactly 1 volume type is required
[root@openshift-master ~]# cat pv-openshift-registry.yaml
apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-openshift-registry
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  cinder:
    fsType: xfs
    volumeID: 70452faa-4edb-47ec-ae6f-34ca3cce906e

**Comment by childsb** [comment]
@jsafrane

**Comment by deads2k** [comment]
Can you resend your failing yaml with its whitespace?  The version posted
here is invalid since yaml is whitespace sensitive:
https://en.wikipedia.org/wiki/YAML#Syntax.

**Comment by deads2k** [comment]
Yeah, looks like whitespace:

```yaml
apiVersion: v1
kind: PersistentVolume
metadata:
    name: pv-openshift-registry
spec:
    capacity:
        storage: 10Gi
    accessModes:
    - ReadWriteOnce
    cinder:
        fsType: ext3
        volumeID: 70452faa-4edb-47ec-ae6f-34ca3cce906e
```

works

**Comment by deads2k** [comment]
Also, `fsType` of `xfs` gives: `cinder.fsType required and should be of type ext3 or ext4: required value`

**Comment by FranBarrera** [comment]
I'm following the latest documentation (https://docs.openshift.org/latest/admin_guide/persistent_storage/persistent_storage_cinder.html)

I've created this json:
```json
{
  "apiVersion": "v1",
  "kind": "PersistentVolume",
  "metadata": {
    "name": "pv2"
  },
  "spec": {
    "capacity": {
        "storage": "2Gi"
    },
    "accessModes": [ "ReadWriteOnce" ],
    "cinder": {
        "fsType": "ext3",
        "volumeID": "fcf1fddb-e5cb-4e86-a029-499e5208e203"
    },
  }
}
```
```bash
[root@mastergmv ~]# oc create -f pv_cinder.json
invalid character '}' looking for beginning of object key string
```

With yaml other error:
```yaml
apiVersion: v1
kind: PersistentVolume
metadata:
    name: pv2
spec:
    capacity:
      storage: 2Gi
      accessModes:
      - ReadWriteOnce
      cinder:
        fsType: ext3
        volumeID: fcf1fddb-e5cb-4e86-a029-499e5208e203
```
```bash
[root@mastergmv ~]# oc create -f pv_cinder.yaml
error: could not read an encoded object: unable to load "pv_cinder.yaml": quantities must match the regular expression '^([+-]?[0-9.]+)([eEimkKMGTP]*[-+]?[0-9]*)$'
error: no objects passed to create
```

**Comment by deads2k** [comment]
The whitespace in your yaml is still messed up.  Compare against the example I provided.

@stevekuznetsov can you diagnose the json problem?  It's probably that last comma.

**Comment by FranBarrera** [comment]
I have tested with your example and I get this error:

```bash
The PersistentVolume "pv2" is invalid.
: invalid value '{GCEPersistentDisk:<nil> AWSElasticBlockStore:<nil> HostPath:<nil> Glusterfs:<nil> NFS:<nil> RBD:<nil> ISCSI:<nil> CephFS:<nil>}', Details: exactly 1 volume type is required
```

**Comment by stevekuznetsov** [comment]
@FranBarrera In your JSON, you had an extra comma, In your YAML, your whitespace was not correct. Here are correct versions:

```json
{
  "apiVersion": "v1",
  "kind": "PersistentVolume",
  "metadata": {
    "name": "pv2"
  },
  "spec": {
    "capacity": {
      "storage": "2Gi"
    },
    "accessModes": [
      "ReadWriteOnce"
    ],
    "cinder": {
      "fsType": "ext3",
      "volumeID": "fcf1fddb-e5cb-4e86-a029-499e5208e203"
    }
  }
}
```

```yaml
apiVersion: v1
kind: PersistentVolume
metadata:
  creationTimestamp: null
  name: pv2
spec:
  accessModes:
  - ReadWriteOnce
  capacity:
    storage: 2Gi
  cinder:
    fsType: ext3
    volumeID: fcf1fddb-e5cb-4e86-a029-499e5208e203
  persistentVolumeReclaimPolicy: Retain
status: {}
```

**Comment by jsafrane** [comment]
> Is the Cinder integration in there or is it not yet available? 

It's part of OpenShift since this merge:

```
commit 2009660eb84e1a56df68db8e1077e2b0bd136d3f
Author: kargakis <mkargaki@redhat.com>
Date:   Mon Sep 14 14:07:45 2015 +0200

    bump(k8s.io/kubernetes) 86b4e777e1947c1bc00e422306a3ca74cbd54dbe
```

I'm testing with today's origin git master and I see in kubelet logs:

```
I1015 12:55:08.973090    8208 volumes.go:100] Used volume plugin "kubernetes.io/cinder" for mysql-persistent-storage
I1015 12:55:08.973196    8208 cinder.go:166] PersistentDisk set up: /home/fedora/origin/_output/local/bin/linux/amd64/openshift.local.volumes/pods/648ed15c-725c-11e5-b6db-fa163e3b7c59/volumes/kubernetes.io~cinder/mysql-persistent-storage false stat /home/fedora/origin/_output/local/bin/linux/amd64/openshift.local.volumes/pods/648ed15c-725c-11e5-b6db-fa163e3b7c59/volumes/kubernetes.io~cinder/mysql-persistent-storage: no such file or directory
E1015 12:55:08.973271    8208 cinder_util.go:45] Cloud provider not initialized properly
```

"no such file or directory" message is perfectly OK, the plugin just checks that the target directory is not already used (and it's not -> everything is fine).

Problem is with "Cloud provider not initialized properly" message. This means that [`Init`] (https://github.com/openshift/origin/blob/master/Godeps/_workspace/src/k8s.io/kubernetes/pkg/volume/cinder/cinder.go#L47)  method in cinder.go was called with invalid `volume.VolumeHost` argument. It's called during Kubelet initialization and it **must** get a `host`, which returns initialized instance of `openstack.OpenStack` on `host.GetCloudProvider()` call. This was working couple of weeks (months?) ago...

In "vanilla" Kubernetes it works like charm, Kubelet initialization seems to be different in OpenShift and I suspect something is wrong there.

**Comment by jsafrane** [comment]
@stevekuznetsov:
> Creating it works for me:
oc create -f pv2.json

PV create works fine, problem is with creating a pod which actually uses it.

**Comment by deads2k** [comment]
> PV create works fine, problem is with creating a pod which actually uses it.

Ok, can you create different issues for different problems?  This issue was definitely about bad yaml and json for PV creation.  Having discrete issues will help us find the right people to answer them.

**Comment by jsafrane** [comment]
Done, issue #5156. Sorry for the noise here.

**Comment by stevekuznetsov** [comment]
@FranBarrera Have you been able to get the PV working with our help here?

**Comment by jhou1** [comment]
I've tested this on 
```
openshift v3.0.2.901-61-g568adb6
kubernetes v1.1.0-alpha.1-653-g86b4e77
```
The cinder plugin is now supported.

```
# oc get pv cinder -o yaml
apiVersion: v1
kind: PersistentVolume
metadata:
  creationTimestamp: 2015-10-21T06:46:20Z
  name: cinder
  resourceVersion: "6384"
  selfLink: /api/v1/persistentvolumes/cinder
  uid: 6fb4b384-77bf-11e5-ad28-fa163ed41a0d
spec:
  accessModes:
  - ReadWriteMany
  capacity:
    storage: 5Gi
  cinder:
    fsType: ext4
    volumeID: 614ac6ef-423d-490b-be4a-16fa829f20cc
  claimRef:
    apiVersion: v1
    kind: PersistentVolumeClaim
    name: cinderc
    namespace: jhou
    resourceVersion: "6381"
    uid: 7972cc3a-77bf-11e5-ad28-fa163ed41a0d
  persistentVolumeReclaimPolicy: Default
status:
  phase: Bound
```

**Comment by FranBarrera** [comment]
> @FranBarrera Have you been able to get the PV working with our help here?

@stevekuznetsov I tried with the version 1.0.6 installed via Ansible and the error seems to cinder is not one of the options available:

```bash
[root@mastergmv ~]# oc create -f pv_cinder.yaml
The PersistentVolume "pv-openshift-registry" is invalid.
: invalid value '{GCEPersistentDisk:<nil> AWSElasticBlockStore:<nil> HostPath:<nil> Glusterfs:<nil> NFS:<nil> RBD:<nil> ISCSI:<nil> CephFS:<nil>}', Details: exactly 1 volume type is required
```

**Comment by stevekuznetsov** [comment]
@FranBarrera I've tried as well, my local version is:
```
openshift v1.0.6-764-g64ce99a
kubernetes v1.2.0-alpha.1-1107-g4c8e6f4
etcd 2.1.2
```

Although not installed through Ansible. Could you paste your `pv_cinder.yaml` or confirm that it is identical to the following?

```yaml
apiVersion: v1
kind: PersistentVolume
metadata:
  creationTimestamp: null
  name: pv2
spec:
  accessModes:
  - ReadWriteOnce
  capacity:
    storage: 2Gi
  cinder:
    fsType: ext3
    volumeID: fcf1fddb-e5cb-4e86-a029-499e5208e203
  persistentVolumeReclaimPolicy: Retain
status: {}
```

**Comment by FranBarrera** [comment]
@stevekuznetsov This is my version, maybe this is the problem:
```bash
openshift v1.0.6-2-ge2a02a8
kubernetes v1.1.0-alpha.0-1605-g44c91b1
```
And the file pv_cinder.yaml:

```yaml
apiVersion: v1
kind: PersistentVolume
metadata:
    name: pv-openshift-registry
spec:
    capacity:
        storage: 2Gi
    accessModes:
    - ReadWriteOnce
    cinder:
        fsType: ext3
        volumeID: fcf1fddb-e5cb-4e86-a029-499e5208e203
```
I've tested with your yaml and the same error.
