### ISSUE TITLE
Cinder volume plugin does not get cloud provider

### ISSUE THREAD

**Issue by jsafrane** [openshift/origin#5156]
When Cinder volume plugin is initialized, it gets a `VolumeHost` instance which returns `nil` from `GetCloudProvider()` call (e.g. in [AttachDisk function](https://github.com/openshift/origin/blob/master/Godeps/_workspace/src/k8s.io/kubernetes/pkg/volume/cinder/cinder_util.go#L43))

As result, Kubelet cannot attach a Cinder volume to a pod, with following error in the log:
```
cinder_util.go:45] Cloud provider not initialized properly
```

My node config.yaml includes `--cloud-provider` and `--cloud-config` arguments:
```yaml
kubeletArguments:  
  cloud-provider:  
    - "openstack"  
  cloud-config:  
    - "/etc/cloud.conf"  
```

"Standard" Kubelet (e.g. when running outside of OpenShift) initializes cloud provider in [KubeletServer.Run()](https://github.com/openshift/origin/blob/master/Godeps/_workspace/src/k8s.io/kubernetes/cmd/kubelet/app/server.go#L406). In OpenShift, this method gets non-nil KubeletConfig, therefore it expects that the cloud provider was already initialized by the caller.
