### ISSUE TITLE
Pod should have a warning, but doesn't

### ISSUE THREAD

**Issue by spadgett** [openshift/origin#5549]
Things are likely working as intended, but we might need a new troubled pod rule. This container is in waiting and crashed the last time it ran, but the pod is not marked with a warning.

![openshift_web_console](https://cloud.githubusercontent.com/assets/1167259/10857583/47967508-7f25-11e5-8dff-14491bf3af60.png)

![openshift_web_console](https://cloud.githubusercontent.com/assets/1167259/10857544/1557ed4c-7f25-11e5-8fe4-eda24fc29d15.png)

```
status:
  conditions:
  - lastProbeTime: null
    lastTransitionTime: 2015-10-30T20:04:30Z
    message: 'containers with unready status: [lonely-pod]'
    reason: ContainersNotReady
    status: "False"
    type: Ready
  containerStatuses:
  - containerID: docker://20fbac68ba08fbb305c885e59bb8f0f8ae96b09a7f152deac214e1ad8565e495
    image: openshift/hello-openshift
    imageID: docker://30f93353d95d12198b8b9c16223ed0ac587c70a2a1521a5504a3647a765897c5
    lastState:
      terminated:
        containerID: docker://20fbac68ba08fbb305c885e59bb8f0f8ae96b09a7f152deac214e1ad8565e495
        exitCode: -1
        finishedAt: 2015-10-30T20:39:01Z
        message: '[8] System error: no such file or directory'
        reason: ContainerCannotRun
        startedAt: 2015-10-30T20:39:01Z
    name: lonely-pod
    ready: false
    restartCount: 136
    state:
      waiting:
        message: Back-off 5m0s restarting failed container=lonely-pod pod=lonely-pod_monopod
        reason: CrashLoopBackOff
  hostIP: 10.0.2.15
  phase: Running
  podIP: 172.17.0.14
  startTime: 2015-10-30T20:04:28Z
```

/cc @jwforres
