### ISSUE TITLE
Rolling updates fail when there are no pods scheduled

### ISSUE THREAD

**Issue by paralin** [openshift/origin#5787]
This is due to rollingUpdate requiring maxSurge or maxUnavailable as seen here:

https://github.com/kubernetes/kubernetes/blob/master/pkg/kubectl/rolling_updater.go#L213

Despite my dc having this:

```yaml
strategy:
  resources: {}
  rollingParams:
    intervalSeconds: 1
    maxSurge: 25%
    maxUnavailable: 25%
    timeoutSeconds: 600
    updatePeriodSeconds: 1
  type: Rolling
```

Note that my current pod count is set to zero. So rolling update doesn't make too much sense in this case anyway.

I think the solution is to just set one of the two to 1 if 25% * pod count = 0.
