### ISSUE TITLE
registry does not have write permission when use glusterfs as back storage

### ISSUE THREAD

**Issue by pstinghua** [openshift/origin#5924]

**Comment by pstinghua** [comment]
glusterfs endpoints 
```
apiVersion: v1
kind: Endpoints
metadata:
  name: glusterfs-cluster
subsets:
  - addresses:
      - ip: 193.0.10.166
    ports:
      - port: 1
  - addresses:
      - ip: 193.0.10.167
    ports:
      - port: 1
```

add registry volume
```
oc volume dc docker-registry --add --overwrite --name=registry-storage --mount-path=/registry --claim-name=docker-registry --claim-size=20Gi --claim-mode=rwm --type=persistentVolumeClaim
```
