### ISSUE TITLE
Combination of http and passthrough routes bound to the same host confuses ha-proxy

### ISSUE THREAD

**Issue by jpechane** [openshift/origin#5946]
Use route configuration

``` yaml
apiVersion: v1
items:
- apiVersion: v1
  kind: Route
  metadata:
    name: ws-test-route
  spec:
    host: ws.jpechane.cloudapps.example.com
    to:
      kind: Service
      name: ws-test-service
- apiVersion: v1
  kind: Route
  metadata:
    name: ws-test-route-secure
  spec:
    host: ws.jpechane.cloudapps.example.com
    tls:
      termination: passthrough
    to:
      kind: Service
      name: ws-test-secure-service
kind: List
metadata: {}
```

Haproxy creates record in  os_sni_passthrough.map and os_tcp_be.map instead of http and passthrough

**Comment by ramr** [comment]
@jpechane  that looks correct because both the routes have the same hostname `ws.jpechane.cloudapps.example.com`  

and the algorithm for multiple routes w/ the same name causes the oldest route to win and in this case the route for the passthrough termination wins  and really is the equivalent of this config:

```
apiVersion: v1  
items:  
- apiVersion: v1  
  kind: Route   
  metadata:  
    name: ws-test-route-secure  
  spec:  
    host: ws.jpechane.cloudapps.example.com  
    tls:  
      termination: passthrough  
    to:  
      kind: Service  
      name: ws-test-secure-service  
kind: List  
metadata: {}  
```
