### ISSUE TITLE
`oc new-build <src> --dockerfile "..."` ignores the Dockerfile

### ISSUE THREAD

**Issue by rhcarvalho** [openshift/origin#6199]
If should be possible to use the `--dockerfile` option in conjunction with a Git source repo argument, however:

```
$ oc new-build https://github.com/rhcarvalho/chained-builds-ex/ --context-dir=app -D $'FROM rhcarvalho/httphostname\nENV ok=1' -o yaml
```

Gives:

```yaml
....
  spec:
    output:
      to:
        kind: ImageStreamTag
        name: chained-builds-ex:latest
    resources: {}
    source:
      contextDir: app
      git:
        uri: https://github.com/rhcarvalho/chained-builds-ex/
      type: Git
    strategy:
      dockerStrategy:
        from:
          kind: DockerImage
          name: rhcarvalho/httphostname:latest
      type: Docker
....
```

Only one source, the Git repository.
