### ISSUE TITLE
S2I builds should try annotate the RC / DC with the git commit sha and the build id / pod when the build completes

### ISSUE THREAD

**Issue by jstrachan** [openshift/origin#6241]
which would make it easier from a console to link to the source code version and build log that makes an RC / DC.

We've been doing this by default in our fabric8 Jenkins Workflows which means for each environment of interest, its easy to link to the version, git commit and build log for each RC / DC / pod.

e.g. like this UI - you can see the git commit and build log for each RC in each environment (and see the code differences for the rolling upgrade in the Staging env)...
![environments-rollingupgrade](https://cloud.githubusercontent.com/assets/30140/11684356/017cc14a-9e69-11e5-8c95-9eca5be24708.png)

Right now S2I annotates the deployer pod; but that dies so there's no easy way to get the build log. Nor is there any annotation for the git commit SHA so we can't easily view the source version for the RC.

here's the main annotations right now that get added to the RC:
```
apiVersion: v1
kind: ReplicationController
metadata:
  annotations:
    openshift.io/deployer-pod.name: james-1-deploy
    openshift.io/deployment-config.latest-version: "1"
    openshift.io/deployment-config.name: james
    openshift.io/deployment.phase: Complete
```
which is cool and about deployment; but there's nothing about build logs or git commit sha etc.

FWIW here's the annotations we use for fabric8 + jenkins:
https://github.com/fabric8io/fabric8/blob/master/docs/annotations.md
