### ISSUE TITLE
htaccess, cannot login 'admin' user using HTPasswd Auth

### ISSUE THREAD

**Issue by terrywong2** [openshift/origin#6286]
the *admin* user is created by following command:
```htpasswd /etc/origin/htpasswd admin```

```origin-master: E1213 23:25:06.249589    2434 login.go:141] Unable to authenticate password: Error creating or updating mapping for: &api.DefaultUserIdentityInfo{ProviderName:"htpasswd_auth", ProviderUserName:"admin", Extra:map[string]string{}} due to user "admin" cannot be claimed by identity "htpasswd_auth:admin" because it is already mapped to [allow_all:admin]```

any solutions?

**Comment by liggitt** [comment]
Set the mapping method on the new identity provider to "add"

See https://docs.openshift.org/latest/install_config/configuring_authentication.html#mapping-identities-to-users

**Comment by terrywong2** [comment]
still no luck after change the identity provider to "add" and restart the VM, keeps showing the same error message and cannot login
```
Unable to authenticate password: Error creating or updating mapping for: &api.DefaultUserIdentityInfo{ProviderName:"htpasswd_auth", ProviderUserName:"admin", Extra:map[string]string{}} due to user "admin" cannot be claimed by identity "htpasswd_auth:admin" because it is already mapped to [allow_all:admin]
```

config:
```
oauthConfig:
  assetPublicURL: https://172.16.51.20:8443/console/
  grantConfig:
    method: auto
  identityProviders:
  - challenge: true
    login: true
    name: htpasswd_auth
    provider:
      apiVersion: v1
      file: /etc/origin/htpasswd
      kind: HTPasswdPasswordIdentityProvider
      mappingMethod: "add"
  masterCA: ca.crt
  masterPublicURL: https://172.16.51.20:8443
  masterURL: https://172.16.51.20:8443
  sessionConfig:
    sessionMaxAgeSeconds: 3600
    sessionName: ssn
    sessionSecretsFile: /etc/origin/master/session-secrets.yaml
  tokenConfig:
    accessTokenMaxAgeSeconds: 86400
    authorizeTokenMaxAgeSeconds: 500
```

```
[root@openshift-01-master master]# kubectl get users
NAME      UID                                    FULL NAME   IDENTITIES
admin     811a04d4-a197-11e5-b3d7-000c29234ec3               allow_all:admin
user      03974631-a1ab-11e5-a640-000c29234ec3               htpasswd_auth:user
```
