### ISSUE TITLE
oc new-app <repo> --strategy=docker constructs bad app 

### ISSUE THREAD

**Issue by rhcarvalho** [openshift/origin#6347]
tl;dr: `new-app` should not come up with a builder image for the app and reference it in the build config strategy when strategy=docker.
---

Use case: I have a Dockerfile in my source repository and want to setup a build that will simply build that Dockerfile.

"Go-to" solution:

``` console
$ oc new-app https://github.com/openshift/ruby-hello-world --strategy=docker
```

Problem: `new-app` sets up a BuildConfig that will replace the FROM line in my Dockerfile with a builder image (the image `openshift/ruby-22-centos7` in the example above).

YAML output of `new-app`:

``` yaml
# ...
- apiVersion: v1
  kind: BuildConfig
  metadata:
    annotations:
      openshift.io/generated-by: OpenShiftNewApp
    labels:
      app: ruby-hello-world
    name: ruby-hello-world
  spec:
    output:
      to:
        kind: ImageStreamTag
        name: ruby-hello-world:latest
    source:
      git:
        uri: https://github.com/openshift/ruby-hello-world
      type: Git
    strategy:
      dockerStrategy:
        from: # <-- this will replace the FROM line of the Dockerfile in the source repository
          kind: ImageStreamTag
          name: ruby-22-centos7:latest
      type: Docker
# ...
```

`new-app` should not come up with a builder image for the app and reference it in the build config strategy when strategy=docker.

The strategy should be:

``` yaml
   strategy:
      dockerStrategy: {}
```
