### ISSUE TITLE
Cannot find anyway to create cluster-admin without system:user

### ISSUE THREAD

**Issue by terrywong2** [openshift/origin#6408]
I installed openshift in the VM via ansible playbook and just create the account call "user" and login this account, it cannot do any administration and i didn't create cluster-admin account before, so is there anyway can create the cluster-admin account or manage the openshift in this situation? thanks.

**Comment by deads2k** [comment]
Ansible should leave you with a file local to the master called `admin.kubeconfig`.  That file contains credentials for "system:admin" (a cluster-admin).  You can use that file to add more roles to various users by running

`oadm policy add-cluster-role-to-user cluster-admin <your username>`

@sdodson do you know the exact location right off?

**Comment by terrywong2** [comment]
cool.

`admin.kubeconfig` is local in `/etc/origin/master/` by default.

```
apiVersion: v1
clusters:
- cluster:
    certificate-authority-data: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUM1akNDQWRDZ0F3SUJBZ0lCQVRBTEJna3...
    server: https://172.16.51.20:8443
  name: 172-16-51-20:8443
contexts:
- context:
    cluster: 172-16-51-20:8443
    namespace: default
    user: system:admin/172-16-51-20:8443
  name: default/172-16-51-20:8443/system:admin
current-context: default/172-16-51-20:8443/system:admin
kind: Config
preferences: {}
users:
- name: system:admin/172-16-51-20:8443
  user:
    client-certificate-data: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSURDVENDQWZPZ0F3SUJBZ0lCQnpBTEJna3...
    client-key-data: LS0tLS1CRUdJTiBSU0EgUFJJVkFURSBLRVktLS0tLQpNSUlFcEFJQkFBS0NBUUVBNHNENzF4bkh...
```

so, how can i log into system:admin/172-16-51-20:8443 account?  i tried to copy the certificate in `client-certificate-data`  field to a single file call `cert` and run the following command.

```oc login --certificate-authority=./cert```

it shows an error message.
```error: The server uses a certificate signed by unknown authority. You may need to use the --certificate-authority flag to provide the path to a certificate file for the certificate authority, or --insecure-skip-tls-verify to bypass the certificate check and use insecure connections.
```

finally, i was execute the following command, it works.
```oadm policy --config=/etc/origin/master/admin.kubeconfig add-cluster-role-to-user cluster-admin user```
