### ISSUE TITLE
`oc rsh` should do a transitive authority check

### ISSUE THREAD

**Issue by deads2k** [openshift/origin#6504]
We prevent exec into privileged pods because a given user lacks the authority to create a given pod.  However, the SA being used usually has those rights and I have the power to view the SAs secret.  This gives me the power to impersonate the SA and make the connection.  I'd like to find a way have that check be transitive in nature.

@liggitt Any reasonable ideas?  This is more than the power to use the SA.

**Comment by deads2k** [comment]
This might the be the use-case to describe for Eric Tune's act-as.

**Comment by deads2k** [comment]
hmmm...  On further consideration, "act-as" wouldn't work either, since most SAs can't create pods, so the check would still fail.

There is a slightly more power if you're allowed to exec into a privileged pod because the SA has the SCC power to create it, but I think it only breaks down if you're doing a lot of work to restrict exactly which images can run.

@csrwng comments or advice?

**Comment by csrwng** [comment]
Just to clarify the build use case... the SA that creates the build pod is not accessible by regular users. (The build controller SA) The SA that the build pod 'runs as' is part of the project and regular users can see its secret. Because the pod is created in the current project, any admin, editor, etc can exec into it...  you don't need the secret of the SA running it.

**Comment by csrwng** [comment]
Once the pod is running there's nothing linking it back to the SA that created it. So not sure how a transitive check would work.

**Comment by deads2k** [comment]
1.  Create an SA called sa-01 and grant it the power to use host ports.
1.  Create an RC with a PodSpec that specifies using sa-01
1.  RC manager creates a new pod that uses sa-01 and is admitted because sa-01 can use host ports.
1.  `oc rsh` is rejected, because my user doesn't have SCC permissions to use host ports.

The check wouldn't only need to look at the SA of the pod.  The question is whether the additional power (arbitrary command) would be too great.

**Comment by liggitt** [comment]
aren't we already considering the SA of the pod itself? That seems like enough.

**Comment by deads2k** [comment]
> aren't we already considering the SA of the pod itself? That seems like enough.

Code looks like it should, but it doesn't:

```
oc create sa privileged
KUBECONFIG=openshift.local.config/master/admin.kubeconfig oadm policy add-scc-to-user privileged system:serviceaccount:foo:privileged
oc create -f ../host-port-pod.yaml
 oc rsh my-pod
Error from server: pods "my-pod" is forbidden: unable to validate against any security context constraint: [securityContext.runAsUser: Invalid value: 0: UID on container busybox does not match required range.  Found 0, required min: 1000030000 max: 1000039999 spec.containers[0].securityContext.privileged: Invalid value: true: Privileged containers are not allowed]
```

```yaml
apiVersion: v1
kind: Pod
metadata:
  name: my-pod
spec:
  containers:
  - image: busybox
    name: busybox
    command: 
    - /bin/sleep
    args:
    - "60"
    securityContext:
      capabilities: {}
      privileged: true
      runAsUser: 0
  serviceAccount: privileged
  serviceAccountName: privileged
  terminationGracePeriodSeconds: 30

```

Since I've been reminded, I'll go ahead and look.
