### ISSUE TITLE
Web console pod status not as specific as CLI

### ISSUE THREAD

**Issue by spadgett** [openshift/origin#6584]
In the CLI, you can see a "DeadlineExceeded" status for some pods.

```
$ oc get pods
NAME                         READY     STATUS             RESTARTS   AGE
database-15-deploy           0/1       DeadlineExceeded   0          16d
database-15-posthook         0/1       DeadlineExceeded   0          16d
...
```

In the UI (browse pods), we just show "Failed."

![openshift_web_console](https://cloud.githubusercontent.com/assets/1167259/12199704/4583ee72-b5e8-11e5-87bb-4f2e9bd16d43.png)

We only show "Failed" on the inidividual pod page as well.

We also sort differently and order the table columns differently. The age value is different as well, but that might just be due to different rounding strategies, see https://bugzilla.redhat.com/show_bug.cgi?id=1232251

/cc @jwforres @fabianofranz

**Comment by spadgett** [comment]
Looks like the CLI is showing `reason`:

```
status:
  phase: Failed
  message: 'Pod was active on the node longer than specified deadline'
  reason: DeadlineExceeded
  startTime: '2015-12-22T19:19:06Z'
```
