### ISSUE TITLE
Should the DeploymentConfig's selector be mandatory?

### ISSUE THREAD

**Issue by vbehar** [openshift/origin#6719]
Hi,

I just noticed that the ReplicationController's selector is optional, and default to the labels defined in the pod template - https://docs.openshift.org/latest/rest_api/kubernetes_v1.html#v1-replicationcontrollerspec

So the following is valid:
``` yaml
kind: ReplicationController
apiVersion: v1
metadata:
  name: hello-openshift
spec:
  replicas: 1
  template:
    metadata:
      labels:
        pod: hello-openshift
    spec:
      containers:
      - name: hello-openshift
        image: openshift/hello-openshift:latest
```

But the DeploymentConfig's selector is mandatory - https://docs.openshift.org/latest/rest_api/openshift_v1.html#v1-deploymentconfigspec

Is there a real reason to have a different policy? Could the DC selector changed to an optional field to have the same behaviour as the RC? (and be easier to write for simple cases)
