### ISSUE TITLE
About the ssh support in router

### ISSUE THREAD

**Issue by thincal** [openshift/origin#6755]
After deployed the gerrit following below definitions in openshift, I want to do the ```git clone``` like this:
```
git clone ssh://admin@gerrit.example.com:29418/hello-gerrit
```
it reports error:
```
Cloning into 'hello-gerrit'...
ssh: connect to host gerrit.example.com port 29418: No route to host
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
```
might be I should change to use the route about 29418 like this:
```
git clone ssh://admin@gerrit-ssh.example.com/hello-gerrit
```
it will report to need the password:
```
Cloning into 'hello-gerrit'...
admin@gerrit-ssh.example.com's password: 

```

What do you think about that ? are there any suggestions or thoughts ? many thanks.

P.S.
The gerrit pod is exposing the container ports as bellow:
```
ports:
  - containerPort: 8080
    protocol: TCP
  - containerPort: 29418
    protocol: TCP
```
The service definition as here
```
apiVersion: v1
kind: Service
metadata:
  name: gerrit
  labels:
    app: gerrit
spec:
  ports:
  - name: web-tcp
    port: 8080
    protocol: TCP
    targetPort: 8080
  - name: ssh-tcp
    port: 29418
    protocol: TCP
    targetPort: 29418
  selector:
    name: gerrit-server
  sessionAffinity: None
  type: ClusterIP
```
The gerrit route definition as here
```
apiVersion: v1
kind: Route
metadata:
  name: gerrit
spec:
  host: gerrit.example.com
  port:
    targetPort: web-tcp
  to:
    kind: Service
    name: gerrit
```
The gerrit-ssh route definition as here
```
apiVersion: v1
kind: Route
metadata:
  name: gerrit-ssh
spec:
  host: gerrit-ssh.example.com
  port:
    targetPort: ssh-tcp
  to:
    kind: Service
    name: gerrit
```
