### ISSUE TITLE
Run unit tests as part of build flow

### ISSUE THREAD

**Issue by rhcarvalho** [openshift/origin#6758]
We want to support developers and teams using OpenShift to implement CI/CD workflows.

We want to close gaps and offer seamless transitions from simply running unit tests to more complex scenarios including integration with Jenkins.

This issue is meant to discuss how we add support for running unit tests as part of the build flow.

Requirements:
- Should require a minimum amount of user input, no boilerplate (think `rake test`);
- Should require no changes to source repositories (solutions like `.travis.yml` files are discarded);
- Should work the same for Source and Docker builds;
- If the test execution returns a non-zero exit code, the build will be marked as failed;
- Logs shall be streamed to the build logs, just like S2I streams logs from the assemble script;
- It should be possible to install test-only dependencies as part of the test script, and these dependencies will not be committed to the final image.

---------------------------------------

Related Trello cards:
- https://trello.com/c/BzV509ca/795-8-run-unit-tests-before-pushing-built-images-r-d
- https://trello.com/c/I1v1YeOf/844-8-implement-post-build-command

---------------------------------------

## Assumptions

- The unit tests will be executed on a fresh container running the Docker image that has been built, right after the last commit and prior to pushing to a registry (think `docker run image@sha test command`);
- The working directory is not changed, so the tests will be executed in the default working directory of the image;
- For this test command to work, assume that source code or whatever other fundamental artifacts are present in the image.
- Test execution time is not limited, nor is the scope of what the test script can do. In fact it could be abused to do anything a bash script can do. Timeouts, and other resource quota related concerns are taken care by the platform, and the user uses her quota the way she wants.

### Drone.io
![droneio-cmd](https://cloud.githubusercontent.com/assets/88819/12482017/7172974e-c04d-11e5-8fd0-3b1173f8f9be.png)

- User enter one or more lines in a text area :+1: 
  - In drone.io, you need to include all the steps required before the command that run tests (install systems packages, dependencies, etc) :-1: 
  - In OpenShift, we don't need those extra steps, `npm test` would be enough :+1: 
- It is possible to pass in extra environment variables (but, instead of this, perhaps users could add lines `export FOO=bar` in their list of commands to run?)
- The working directory where the command is run is clearly shown in the UI :+1: 
- Choosing a language automatically fill in the "build command" with some default value for the given language :+1: 
- Commands are run in Bash (mentioned in their intro video, but a written specification could not be found in their official docs)

### Circle CI
![circleci-cmd-test](https://cloud.githubusercontent.com/assets/88819/12482249/e4d17344-c04e-11e5-8342-047bc6bf78f7.png)

- User enter one or more lines in a text area :+1: 
- It is clearly specified that tests will be run with Bash on Ubuntu 12.04 (make it a predictable experience) :+1: 
- If user don't provide their own script, Circle CI tries to infer the commands based on the software stack

### Travis

https://docs.travis-ci.com/user/customizing-the-build/#Customizing-the-Build-Step
```
script:
  - bundle exec rake build
  - bundle exec rake builddoc
```

- Requires writing a `.travis.yml` file :-1: 
- Allows specifying, in a concise way, multiple scripts that are sequentially executed even if a previous command returns non-zero exit code :+1: 
- "Each command in `script` is processed by a special bash function." (predictable experience) :+1:

**Comment by rhcarvalho** [comment]
@bparees @mfojtik @PI-Victor @smarterclayton @liggitt @deads2k 

I'd like to take the API discussion from #6715 to this issue, and also include the @openshift/ui-review team, since to effectively achieve our objective of making it easy to include unit tests as part of a build, UI work will have to be done, as that's what end users will mostly interact with.

**Comment by deads2k** [comment]
I don't see unit tests as part of a build.  I see the build completing, pushing to its image stream, then having that trigger a series of `jobs` that are created to represent the various tests.  Upon successful completion of the tests, the imagestreamtag is annotated with various pass indicators and maybe promoted by re-tagging.

That flow fits with most systems I've worked with.  The build and its output is considered successful regardless of test passes.  Then a series of different tests are used to vet the build, adding information until various boundaries are passed that allow promotion to addition test activity.

You could even use `jobs` to do the work we have in our test queue, where we have multiple test attempts and all of them have to pass.

**Comment by bparees** [comment]
@deads2k that ship has sailed (during extensive discussions about what this feature/card is for) so please don't derail this discussion.  The feature is:
image has been built and committed but not pushed, I want to run a command against the image to perform some basic unit test/validation.  I do not want to have to push the image to a repository and deploy it somewhere and do complicated things.

**Comment by jwforres** [comment]
It should be clear from _something_ in the API response for the build that the reason for the build failure was the unit tests step, and not that the build itself failed, preferably not just a block of status details text, I'm thinking a "reason" field?  You may want to visually flag these failures differently in the UI.

**Comment by rhcarvalho** [comment]
@jwforres :+1: I'd love to see builds that failed unit tests "colored" differently -- there are a few "new" cases to consider:
- failed to run unit tests (because of configuration errors, typos, etc)
- unit tests passed
- unit tests failed
- unit tests were not run (with a link to setup unit tests for the build config :smile: )

**Comment by mfojtik** [comment]
@rhcarvalho are you going to update the build annotation to deliver the message to UI?

**Comment by bparees** [comment]
@rhcarvalho now who's feature bloating.....

**Comment by jwforres** [comment]
So we won't limit their execution time, but should we allow them to set a "kill my build unit tests if they take longer than X amount of time".  Only reason would be that quota-ed users may not want to block their whole build queue with one borked test run.  Obviously they could do this themselves in their test commands, but having a guarantee from the system that they will get killed can be comforting :smile:

**Comment by rhcarvalho** [comment]
> I'm thinking a "reason" field

Fortunately it already exists, we'd just need to add more possible values:
https://github.com/openshift/origin/blob/2670ca01a09977a13e0b3583ede3cd855ad705dc/pkg/build/api/v1/types.go#L61

**Comment by rhcarvalho** [comment]
@bparees Web Console work are ideas for @jwforres to make we recognized by excellent UX.
Of couse it doesn't affect the scope of my PR that will introduce the feature.

**Comment by bparees** [comment]
@rhcarvalho i'm not really clear on the point of this issue.  If you want to drive the discussion about what the api for defining the test-cmd should be, let's do that in a specific discussion, not one that revisits the entire feature.  (The UX discussion is a fine one to have, but that doesn't seem like your most pressing concern for getting the card done, right?)

**Comment by rhcarvalho** [comment]
> "kill my build unit tests if they take longer than X amount of time"

@jwforres there's already `oc cancel-build` today, so adding a button to the UI to cancel an in-flight build is certainly possible. We're not aiming to add automatic cancel after a timeout.

**Comment by jwforres** [comment]
yeah @rhcarvalho we already have cancel build in the UI, this was from the perspective of my build queue is running overnight with no one watching it so nothing was able to finish.  But yep that's fine, was just a suggestion.

**Comment by mfojtik** [comment]
@bparees +1

**Comment by rhcarvalho** [comment]
> what the api for defining the test-cmd should be

So, when we started to talk about container API, and modelling this after ExecNewPodHook (Deployment Config lifecycle hooks), I think things started to look more complex then they need to be, based on the scope originally discussed.

We have previously aborted [Build lifecycle hooks #3674](https://github.com/openshift/origin/pull/3674), which were modeled after DC hooks. The implementation was exactly in that direction -- generic fields that let you run any image with any argument, entrypoint, volumes, env, etc, etc.
It was super powerful, could be used to cover many use cases, but still solved no clear use case in a very easy to use way.

Our next step was to target something more focused -- [Start builds after a build completes #6311](https://github.com/openshift/origin/pull/6311). It have clearly a much more focused scope and all the API suggestions targeted solving a single problem. We put there the elements that we needed, nothing more, and still kept in mind we might add more things in the future. And eventually we aborted it.

This is the third try at solving a very particular use case. I wouldn't be surprised that at this time our implementation is even less generic, but made to solve one problem very well and leaving room for additive changes.

All CI tools we looked at give you a single free-form string field that is run as a bash script.
That is sufficient to all unit testing use cases we've discussed. That makes users happy, they know what they get. Advanced users can do arbitrary things, combine commands with `&&`, get rid of bash by using `exec`, and so on.

I've also seen people messing up with passing string arrays to cmd and entrypoint. Sure we could do that, but why complicate?

**Comment by rhcarvalho** [comment]
```yaml
apiVersion: v1
kind: BuildConfig
metadata:
  name: example
  namespace: demo
spec:
  output:
    to:
      kind: ImageStreamTag
      name: example:latest
  resources: {}
  source:
    git:
      uri: https://github.com/openshift/example
    type: Git
  strategy:
    dockerStrategy: {}
    type: Docker
  # postCommit: specify commands to be run in the output Docker image after its
  # last layer is committed and before the image is pushed to a registry. Use
  # this to run unit tests.
  postCommit:
    # runBash: most people will be fine with running their unit tests within a
    # Bash script, as that's what they are used to in tools they use today. Bash
    # scripts are flexible, and can be simple and powerful. While it is easy to
    # call 'rake test', you're not limited in any way to perform more advanced
    # actions if need be.
    runBash: rake test
    # run: if there really are interesting user-driven use cases where the image
    # entrypoint needs to be preserved, or that the user needs to explicitly
    # specify a custom entrypoint, then she uses "run" and not "runBash".
    run:
      # entrypoint: if omitted, the image's entrypoint will be preserved. Maps
      # directly to the entrypoint option when starting a Docker container.
      entrypoint: ["custom", "value"]
      # cmd: maps directly to the cmd option when starting a Docker container.
      cmd: ["custom", "value"]
      # if need be, this can grow to match the Docker Container spec, including
      # 'env', 'volumes', etc.
```

What I am proposing is `postCommit.runBash` for today, because that is simple, direct, and predictable and is what we have use cases for, while having the possibility to have `postCommit.run` in the future if need be.
Unless anyone can present a use case today that would not the addressed by the proposed solution.
