### ISSUE TITLE
rebase changed serialization of empty yaml arrays

### ISSUE THREAD

**Issue by stevekuznetsov** [openshift/origin#6936]
Previously, empty list of users on a group in the LDAP group sync extended test would be reported as :
```yaml
apiVersion: v1
kind: Group
metadata:
  name: group1
users: []
```

Now it is serialized to:
```yaml
apiVersion: v1
kind: Group
metadata:
  name: group1
users: null
```

@liggitt @deads2k
