### ISSUE TITLE
Create Docker image with just "oc" binary inside

### ISSUE THREAD

**Issue by mfojtik** [openshift/origin#6961]
It would be cool to have minimal Docker image that has just the "oc" binary inside and the entrypoint is pre-configured to pickup the `/var/run/secrets/..` token. Then we can run this image in PostDeploymentHooks or in Job to do things like image tagging or having more complex workflows.

**Comment by mfojtik** [comment]
@soltysh

**Comment by mfojtik** [comment]
@smarterclayton just something we were discussing with Maciej today. I think having something like that will be very helpful and allow us to create more complex flows.

**Comment by mfojtik** [comment]
```yaml
apiVersion: extensions/v1beta1
kind: Job
metadata:
  name: tag-to-stage
spec:
  selector:
    matchLabels:
      app: tag-to-stage
  template:
    metadata:
      name: tag-to-stage
    spec:
      containers:
      - name: tagger
        image: openshift/oc
        args: ["tag",  "dev/image:latest", "stage/image:latest"]
      restartPolicy: Never
```
