### ISSUE TITLE
Details: multiple ImageChange triggers refer to the same image stream tag

### ISSUE THREAD

**Issue by YannMoisan** [openshift/origin#7136]
I encounter the following error when I create the application from the template : `Details: multiple ImageChange triggers refer to the same image stream tag`.

It seems because I have 2 differents ImageChange on a BuildConfig.
Is it possible ? This need seems legit.

```
    - type: ImageChange
      from:
        kind: DockerImage
        name: abc/def:latest
    - type: ImageChange
      from:
        kind: ImageStreamTag
        name: myapp:latest
```
