### ISSUE TITLE
ImageChange trigger is not taken into account with a custom strategy

### ISSUE THREAD

**Issue by YannMoisan** [openshift/origin#7143]
I have a BuildConfig using a custom strategy.

Here is the interesting part 
```
- kind: BuildConfig
  spec:
    strategy:
      type: Custom
      customStrategy:
        from:
          kind: DockerImage
          name: company/builder:latest
        pullSecret:
          name: dockercfg
        forcePull: true
    triggers:
    - type: ImageChange
      from:
        kind: ImageStreamTag
        name: myapp:latest
```

When I look at the resource created with `oc get bc` :

```
        "triggers": [
            {
                "type": "ImageChange",
                "imageChange": {
                    "lastTriggeredImageID": "company/builder:latest"
                }
            }
        ],
```

It seems that my image change is silently overriden with an image change generated automatically by openshift from the docker image of my custom strategy.

I would appreciate to have two ImageChange trigger for a single BuildConfig.
