### ISSUE TITLE
Update one element of an array with oc patch

### ISSUE THREAD

**Issue by YannMoisan** [openshift/origin#7182]
Here is what I want to achieve : I want to deploy a new image : from tag v1 to tag v2

Here is an extract of my DC :
```
    triggers:
    - type: ConfigChange
    - type: ImageChange
      imageChangeParams:
        automatic: true
        from:
          kind: ImageStreamTag
          name: foobar:v1
        containerNames:
        - ${APPLICATION_NAME}
```

My idea is to use `oc patch` to modify an ImageChange trigger.

Is it possible to update one element of an array ?

I've tried without success : 
```
oc patch dc mydc -p '{"spec":{"triggers[1]":{"imageChangeParams":{"from":{"name":"foobar:v2"}}}}}'
```
