### ISSUE TITLE
error with an ImageChange on another namespace

### ISSUE THREAD

**Issue by YannMoisan** [openshift/origin#7192]
I have defined an Image Change trigger on my DC
```
    - type: ImageChange
      imageChangeParams:
        automatic: true
        from:
          kind: ImageStreamTag
          name: ${APPLICATION_NAME}:${DOCKER_IMAGE_TAG}
          namespace: foobar-int
        containerNames:
        - ${APPLICATION_NAME}
```
I don't have an ImageStream because the image comes from another namespace.

And I get this error :
```
The image trigger for dc/foobar will have no effect because is/foobar-integration does not exist.
```

Is it a false negative ?
