### ISSUE TITLE
Still need to add secrets to service account

### ISSUE THREAD

**Issue by YannMoisan** [openshift/origin#7213]
I have a BC with a custom strategy and the docker image is located on an external registry.

Since security change in [v1.0.5](https://github.com/openshift/origin/releases/tag/v1.0.5), I don't need anymore to add secrets to service account.

But the build fails with a credential error until I add the secret with this command : 

```
oc secrets add sa/builder secrets/dockercfg --for=pull,mount
```

**Comment by liggitt** [comment]
You need to add them to the service account for the build to automatically pick them up. It will only search the secrets on the builder service account automatically. You can manually set the pullSecret in your custom strategy if you want without needing to add it to the service account

**Comment by YannMoisan** [comment]
pullSecret is configured but not mounted automatically

```
    strategy:
      type: Custom
      customStrategy:
        from:
          # this is the builder image
          kind: DockerImage
          name: foo/bar:latest
        pullSecret:
          name: dockercfg
        forcePull: true
```
