### ISSUE TITLE
router probes is killing the router

### ISSUE THREAD

**Issue by jorgemoralespou** [openshift/origin#7308]
I just provisioned a VM with latest origin, and the router is configured to use liveness and readiness probes. But the container is killed.
This is the router image in my env:
````
docker.io/openshift/origin-haproxy-router             v1.1.2              96eb1ffb05c9        8 days ago          405.8 MB
````

These were the probes generated in the DC:
````
          livenessProbe:
            httpGet:
              path: /healthz
              port: 1936
              host: localhost
              scheme: HTTP
            initialDelaySeconds: 10
            timeoutSeconds: 1
            periodSeconds: 10
            successThreshold: 1
            failureThreshold: 3
          readinessProbe:
            httpGet:
              path: /healthz
              port: 1936
              host: localhost
              scheme: HTTP
            initialDelaySeconds: 10
            timeoutSeconds: 1
            periodSeconds: 10
            successThreshold: 1
            failureThreshold: 3
````

And this is the log I got for the deployment:
````
I0215 17:04:21.098887       1 deployer.go:199] Deploying default/router-1 for the first time (replicas: 1)
2  I0215 17:04:21.101072       1 recreate.go:126] Scaling default/router-1 to 1 before performing acceptance check
3  I0215 17:04:23.436042       1 recreate.go:131] Performing acceptance check of default/router-1
4  I0215 17:04:23.436161       1 lifecycle.go:445] Waiting 600 seconds for pods owned by deployment "default/router-1" to become ready (checking every 1 seconds; 0 pods previously accepted)
5  F0215 17:14:23.444817       1 deployer.go:69] update acceptor rejected default/router-1: pods for deployment "default/router-1" took longer than 600 seconds to become ready
````

Once, I removed the probes, this is the log I get, and the container is working fine.
````
I0215 17:20:17.283666       1 router.go:161] Router is including routes in all namespaces
```` 

I then connected to the running router and verified that using localhost on the probes is not working.

````
[root@origin conf]# curl http://127.0.0.1:1936/healthz
<html><body><h1>200 OK</h1>
Service ready.
</body></html>
[root@origin conf]# curl http://localhost:1936/healthz
curl: (7) Failed connect to localhost:1936; Connection refused
````

Not sure if this is related: https://github.com/openshift/origin/issues/6797

**Comment by jorgemoralespou** [comment]
More info:

````
[root@origin conf]#  getent ahostsv4 localhost
127.0.0.1       STREAM localhost
127.0.0.1       DGRAM  
127.0.0.1       RAW    
````

**Comment by jorgemoralespou** [comment]
Using 127.0.0.1 and not localhost works for me:

````
          livenessProbe:
            httpGet:
              path: /healthz
              port: 1936
              host: 127.0.0.1
              scheme: HTTP
            initialDelaySeconds: 10
            timeoutSeconds: 1
            periodSeconds: 10
            successThreshold: 1
            failureThreshold: 3
          readinessProbe:
            httpGet:
              path: /healthz
              port: 1936
              host: 127.0.0.1
              scheme: HTTP
            initialDelaySeconds: 10
            timeoutSeconds: 1
            periodSeconds: 10
            successThreshold: 1
            failureThreshold: 3
````

And the output
````
I0215 18:07:56.247600       1 router.go:161] Router is including routes in all namespaces
````
