### ISSUE TITLE
Adding mid hook for Recreate deployment strategy fails through oc edit.

### ISSUE THREAD

**Issue by GrahamDumpleton** [openshift/origin#7366]
Create a new application. Edit the deployment configuration using ``oc edit`` and change:

```
  strategy:
    resources: {}
    rollingParams:
      intervalSeconds: 1
      maxSurge: 25%
      maxUnavailable: 25%
      timeoutSeconds: 600
      updatePeriodSeconds: 1
    type: Rolling
```

to:

```
  strategy:
    resources: {}
    recreateParams:
      mid:
        failurePolicy: Abort
        execNewPod:
          command:
            - /bin/sh
          containerName: myapp
    type: Recreate
```

Run ``oc edit`` again and see what was saved and you find:

```
  strategy:
    recreateParams: {}
    resources: {}
    type: Recreate
```

It has not saved the details of the ``mid`` deployment hook.

Now edit the deployment configuration through the UI and once again add the ``mid`` deployment hook. Save change and then edit through the UI once again. The change is still present.

Actually trigger a deployment and the recreate strategy is applied and the ``mid`` deployment hook is run.

Go back and do an ``oc edit`` on the deployment configuration, the ``mid`` deployment hook still isn't shown.

Just for fun, add it back in again via ``oc edit`` and save.

Now go back to the UI again and edit the deployment configuration there, the ``mid`` deployment hook has gone missing from there again.

In summary, adding a ``mid`` deployment hook for ``Recreate`` deployment strategy is not saved when done through ``oc edit``. Further, if change attempted through ``oc edit``, it will wipe any ``mid`` deployment hook that had been able to be setup from the UI.

I have not tried any other types of deployment hooks for ``Recreate`` or ``Rolling``. Is possible affects others, or could be an oversight with ``mid`` deployment hook being new in 1.1.2.
