### ISSUE TITLE
_flexbox.less doesn't properly handle all -ms prefixes

### ISSUE THREAD

**Issue by benjaminapetersen** [openshift/origin#7559]
Per convesation with @sg00dwin yesterday~
Example:

```less
align-items: flex-start; 
-webkit-align-items: flex-start; 
-ms-align-items: start;   // bah, deviant!
```
But our mixin assumes `-ms-` is sufficient:
```less
.align-items(@align: stretch) {
  -webkit-align-items: @align;
     -moz-align-items: @align;
      -ms-align-items: @align;
          align-items: @align;
}
```
Grunt autoprefixer should handle this, though deprecated.  [PostCSS](https://github.com/postcss/autoprefixer) seems to be taking its place as the supported plugin.
