### ISSUE TITLE
Web console: logs show pod start time, not container start time

### ISSUE THREAD

**Issue by spadgett** [openshift/origin#7646]
The start time for pod logs shouldn't be the pod start time. It should be the container start time since we're showing logs for one container. These are often close, but not always.

<img width="567" alt="openshift_web_console" src="https://cloud.githubusercontent.com/assets/1167259/13340376/ce08dd8a-dbfd-11e5-9630-15935843f397.png">

We're setting the start time based on `pod.status.startTime`.

```html
                    <log-viewer
                        ng-if="selectedTab.logs"
                        follow-affix-top="390"
                        follow-affix-bottom="90"
                        resource="pods/log"
                        name="pod.metadata.name"
                        context="projectContext"
                        options="logOptions"
                        time-start="pod.status.startTime | date : 'short'"
                        run="logCanRun">
                    </log-viewer>
```

But `containerStatuses` has a start time for the container:

```yaml
  containerStatuses:
    -
      name: ruby-helloworld-database
      state:
        running:
          startedAt: '2016-02-26T00:32:07Z'
```

I'd prefer the log-viewer directive to do the date formatting as well so it's always consistent.

Related to #7414

/cc @jwforres @benjaminapetersen
