### ISSUE TITLE
"one of maxSurge or maxUnavailable must be specified" after upgrading to master

### ISSUE THREAD

**Issue by brenton** [openshift/origin#7700]
I previously had a 1.1 deployment.  When I updated my environment to master and updated the deployment config for my router to point to the latest image the deployment fails as follows:

"one of maxSurge or maxUnavailable must be specified"

It seems related to https://github.com/openshift/origin/pull/7626 since I wasn't hitting this earlier last week.  In both cases the 1.1 and master deployment config for my router have:

```
  strategy:
    resources: {}
    rollingParams:
      intervalSeconds: 1
      maxSurge: 0
      maxUnavailable: 25%
      timeoutSeconds: 600
      updatePercent: -25
      updatePeriodSeconds: 1
    type: Rolling
```
