### ISSUE TITLE
spec.source.type == "Binary" not used for creating default

### ISSUE THREAD

**Issue by rhuss** [openshift/origin#7976]
## Version

1.1.3

## Description

When using binary source validation fails when only a `type: "Binary"` is given but no `binary: {}`. This behaviour is different for the build strategy where a `type: "Docker"` is sufficient without providing a `dockerStrategy:`

This behaviour is inconsistent and either providing only the `type` is allowed, too for both parts of forbidden for both (but not allowed for strategy but not for source)

## Steps To Reproduce

For example thus definition is valid:

```yaml
kind: "BuildConfig"
apiVersion: "v1"
metadata:
  name: "cdi-camel-binary-build"
spec:
  source:
    binary: {}
  strategy:
    dockerStrategy: {}
```

but this not:

```yaml
kind: "BuildConfig"
apiVersion: "v1"
metadata:
  name: "cdi-camel-binary-build"
spec:
  source:
    type: "Binary"
  strategy:
    type: "Docker"
```

The mixed form also works:

```yaml
kind: "BuildConfig"
apiVersion: "v1"
metadata:
  name: "cdi-camel-binary-build"
spec:
  source:
    binary: {}
  strategy:
    type: "Docker"
```

## Additional Information

The validation code for the source can be found [here](https://github.com/openshift/origin/blob/master/pkg/build/api/validation/validation.go#L106-L108) and clearly doesn't take into account any given type. For a `binary` source no extra information is needed most of the time so that this config is usually empty. It would be better to allow a type specification here, too.

Interestingly, the client [adds an empty `dockerStrategy`](https://github.com/openshift/origin/blob/482a64f46f0d8f51d332958b50729f9a47d628c9/pkg/build/api/v1/conversion.go#L215-L222) when a `Strategy.Type == "Docker"` is present.

My suggestion is to do the same for the source, especially the [documentation](https://github.com/openshift/openshift-docs/blob/master/dev_guide/builds.adoc#binary-source) suggests this as a valid use case. (Alternatively, the documentation should be updated to remove 'type:' and mention 'binary:' as mandatory).

If we could agree on the correct behaviour I can prepare a PR for this.
