### ISSUE TITLE
`oc process` fails incoherently when bad values are given for a template

### ISSUE THREAD

**Issue by stevekuznetsov** [openshift/origin#8044]
Given a template YAML like:
```yml
kind: Template
apiVersion: v1
metadata:
  name: template
objects:
- kind: Pod 
  apiVersion: v1 
  metadata: 
    name: no-pull-pod
  spec: 
    containers: 
    - name: no-pull-pod
      image: ${DOCKER_REGISTRY}/image-ns/busybox
      command:
      - ls
parameters:
- name: DOCKER_REGISTRY
```

With an invocation of `oc process` without any values works (but shouldn't?):
```
$ oc process -f $ORIGIN/test/extended/fixtures/image-pull-secrets/pod-with-no-pull-secret.yaml | oc create -f -
pod "no-pull-pod" created
```

With an invocation of `oc process` with an incorrect value, an incoherent error message is given:
```
$ oc process -f $ORIGIN/test/extended/fixtures/image-pull-secrets/pod-with-no-pull-secret.yaml --value=docker_registry=172.30.120.153:5000 | oc create -f -
yaml: line 2: mapping values are not allowed in this context
```

With an invocation of `oc process` with a correct value, things work as expected:
```
$ oc process -f $ORIGIN/test/extended/fixtures/image-pull-secrets/pod-with-no-pull-secret.yaml --value=DOCKER_REGISTRY=172.30.120.153:5000 | oc create -f -
pod "no-pull-pod" created
```

Issues:
 - Should there be an error message when a template parameter is not given a value inside `process`?
 - `process` should give better errors when incorrect values are given

/cc @deads2k
