### ISSUE TITLE
gitlab-ce image cannot be executed from inside OpenShift

### ISSUE THREAD

**Issue by jpechane** [openshift/origin#8083]
Follow the procedure described here - https://blog.openshift.com/getting-any-docker-image-running-in-your-own-openshift-cluster/

The net result is that GitLab will start but then the pod crashes with a message in the log
```
================================================================================
Error executing action `restart` on resource 'service[gitlab-workhorse]'
================================================================================

Mixlib::ShellOut::ShellCommandFailed
------------------------------------
Expected process to exit with [0], but received '1'
---- Begin output of /opt/gitlab/embedded/bin/chpst -u root /opt/gitlab/embedded/bin/sv restart /opt/gitlab/service/gitlab-workhorse ----
STDOUT: timeout: run: /opt/gitlab/service/gitlab-workhorse: (pid 275) 35s, got TERM
STDERR: 
---- End output of /opt/gitlab/embedded/bin/chpst -u root /opt/gitlab/embedded/bin/sv restart /opt/gitlab/service/gitlab-workhorse ----
Ran /opt/gitlab/embedded/bin/chpst -u root /opt/gitlab/embedded/bin/sv restart /opt/gitlab/service/gitlab-workhorse returned 1
```

I even tried to give it *privileged* scc but the issue persists.
If I run the image via docker run then it starts correctly.

The same image runs in OSE 3.1 or in CDK flawlessly.

```
oc version
oc v3.2.0.3
kubernetes v1.2.0-origin-41-g91d3e75

docker version
Client:
 Version:         1.9.1
 API version:     1.21
 Package version: docker-1.9.1-19.el7.x86_64
 Go version:      go1.4.2
 Git commit:      185277d/1.9.1
 Built:           
 OS/Arch:         linux/amd64

Server:
 Version:         1.9.1
 API version:     1.21
 Package version: docker-1.9.1-19.el7.x86_64
 Go version:      go1.4.2
 Git commit:      185277d/1.9.1
 Built:           
 OS/Arch:         linux/amd64
```

**Comment by bparees** [comment]
you ran this command `oadm policy add-scc-to-user anyuid -z default` to grant anyuid permissions?  I'm able to run the image with no problem on the latest origin master code.

**Comment by jpechane** [comment]
yes I did - just different project name
```
oc get scc anyuid -o yaml
users:
- system:serviceaccount:gitlab:default
```
And the error is different to one that happens when you do not run as a root

**Comment by bparees** [comment]
@jpechane can you make sure your node pulled the latest version of the image?

**Comment by jpechane** [comment]
pod
```
     from:
        kind: ImageStreamTag
        name: gitlab-ce:8.5.7-ce.0
```
imagestream
```
spec:
  dockerImageRepository: gitlab/gitlab-ce
  tags:
  - from:
      kind: DockerImage
      name: gitlab/gitlab-ce:8.5.5-ce.0
    name: 8.5.5-ce.0
  - from:
      kind: DockerImage
      name: gitlab/gitlab-ce:8.5.5-rc1.ce.0
    name: 8.5.5-rc1.ce.0
  - from:
      kind: DockerImage
      name: gitlab/gitlab-ce:8.5.6-ce.0
    name: 8.5.6-ce.0
  - from:
      kind: DockerImage
      name: gitlab/gitlab-ce:8.5.7-ce.0
    name: 8.5.7-ce.0
  - from:
      kind: DockerImage
      name: gitlab/gitlab-ce:latest
    name: latest
```
