### ISSUE TITLE
autoscaling/v1 HPA validation, editing, export broken

### ISSUE THREAD

**Issue by stevekuznetsov** [openshift/origin#8213]
Attempting to create the following HPA:
```yml
apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: test-autoscaler 
spec:
  scaleRef:
    kind: DeploymentConfig 
    name: frontend 
    apiVersion: v1
  minReplicas: 1 
  maxReplicas: 10  
```

We get the following error:
```sh
$ oc create -f hpa.yaml
The HorizontalPodAutoscaler "test-autoscaler" is invalid.

* spec.scaleRef.kind: Required value
* spec.scaleRef.name: Required value
```

This doesn't make sense as the values that seem to be missing in fact are in the YAML -- the issue is that `scaleRef` is the name of the reference in the `extensions/v1beta1` groupversion, whereas `scaleTargetRef` is the name in `autoscaling/v1` as seen [here](https://github.com/openshift/origin/blob/master/Godeps/_workspace/src/k8s.io/kubernetes/pkg/apis/autoscaling/v1/types.go#L38).

/cc @liggitt
