### ISSUE TITLE
Router creation doesn't configure hostPort

### ISSUE THREAD

**Issue by simon3z** [openshift/origin#8252]
When running:

```
oadm router management-metrics \
  -n default \
  --credentials=/etc/origin/master/openshift-router.kubeconfig \
  --service-account=router \
  --ports='443:5000' \
  --selector='kubernetes.io/hostname=vm-oshift01.vn1.bytenix.com' \
  --stats-port=1937 \
  --host-network=false
```

The resulting dc is not configured with the `hostPort` (5000):

```
# oc get dc management-metrics -o yaml
 ....
        name: router
        ports:
        - containerPort: 443
          protocol: TCP
```

##### Version
origin-1.1.4-0.git.0.9d8230b.el7.centos.x86_64
oc v1.1.4
kubernetes v1.2.0-origin-41-g91d3e75

##### Steps To Reproduce
Provided above.

##### Current Result
The `hostPort` is not configured (it was in the past).

##### Expected Result
The `hostPort` should be configured:

```
        name: router
        ports:
        - containerPort: 443
          hostPort: 5000
          protocol: TCP
```

cc @deads2k
