### ISSUE TITLE
Using nodeallocatable allocatable memory

### ISSUE THREAD

**Issue by jeremyeder** [openshift/origin#8547]
Before:
```
root@bkr-hv01: ~ # oc get node/`hostname` -o yaml|grep -A8 allocatable                           
  allocatable:
    cpu: "0"
    memory: "66271389184"
    pods: "100"
  capacity:
    cpu: "32"
    memory: 65694716Ki
    pods: "100"
  conditions:
```

Set a system-reserve and restart the node service:
```
root@bkr-hv01: ~ # grep -A1 system-reserve /etc/origin/node/node-config.yaml
  system-reserved:
  - 'cpu=200m,memory=1G'
root@bkr-hv01: ~ # systemctl restart atomic-openshift-node.service                                                                                                                            
```

Check if it was set properly:
```
root@bkr-hv01: ~ # oc get node/`hostname` -o yaml|grep -A8 allocatable                                                                                                                        
  allocatable:
    cpu: 31800m
    memory: "66271389184"
    pods: "100"
  capacity:
    cpu: "32"
    memory: 65694716Ki
    pods: "100"
  conditions:
```

The allocatable CPU makes sense.  The allocatable memory does not.  I was expecting capacity:memory minus 1024^2 Ki (it's close, but not exact).

Now...if I change it to Gi instead of just G (the example in the docs is just 'G', it keeps the Ki unit suffix and the number is lower than the capacity.
```
root@bkr-hv01: ~ # grep -A1 system-reserve /etc/origin/node/node-config.yaml
  system-reserved:
  - 'cpu=200m,memory=1Gi'
root@bkr-hv01: ~ # systemctl restart atomic-openshift-node.service
root@bkr-hv01: ~ # oc get node/`hostname` -o yaml|grep -A8 allocatable
  allocatable:
    cpu: 31800m
    memory: 64646140Ki
    pods: "100"
  capacity:
    cpu: "32"
    memory: 65694716Ki
    pods: "100"
  conditions:
```

@ingvagabund @derekwaynecarr
