### ISSUE TITLE
How to use the persistence when I build?

### ISSUE THREAD

**Issue by wenskys** [openshift/origin#8671]
Hi,
   I want to use the .m2 as a persistence  for maven when i build java application.it's make the fast build when i use the local maven repository(we have a nexus repository).
   So i use volumeMounts and nfs to mount a persistence volumes,but to come into force only when running the pod,such as
```
          volumeMounts:
          - name: registry-storage
            mountPath: /home/www/.m2
        volumes:
        - name: registry-storage
          nfs:
            server: zop1.goshift.cn
            path: /data/.m2
```
  How to use the persistence when I build?
  Looking forward to your help，Thank you.
