### ISSUE TITLE
Pushing a docker image generated in a Build to an external registry

### ISSUE THREAD

**Issue by AlbertoPeon** [openshift/origin#8790]
Our use case is using the OpenShift build system as a Docker image build service.

I've tried to create a buildconfig that generates the image as usual but instead of pushing the generated docker image to the internal registry, it does so to an external one.

I've tried to define an ImageStream with a 'spec.DockerImageRepository' pointing to the right registry, but it hasn't work so far (for pushing but it does work for pulling)

```yaml
apiVersion: v1
kind: ImageStream
metadata:
  name: min-dockerfile
spec:
  dockerImageRepository: {external-repository}/minimal-dockerfile
```
In the build config, the output part is defined as:

```yaml
...
spec:
  output:
    to:
      kind: ImageStreamTag
      name: min-dockerfile:latest
  strategy:
    dockerStrategy:
      from:
        kind: ImageStreamTag
        name: centos:latest
    type: Docker
...
```
Despite this, the build ends up pushing to the internal registry:

In the build logs
```
docker.go:118] Pushing image {internal-registry-ip}/test-docker-build/min-dockerfile:latest ...
docker.go:122] Push successful
```

Is it possible to do this? Any ideas on how to proceed?

**Comment by mfojtik** [comment]
I think the build output should be something like this:

```yaml
output:
  to:
    kind: "DockerImage"
    name: "my-registry.mycompany.com:5000/myimages/myimage:tag"
```
