### ISSUE TITLE
How to use docker-registry to save a common images but not sti images

### ISSUE THREAD

**Issue by wenskys** [openshift/origin#8833]
Hi,
I create a  ImageStream for nginx,and it is use as a sti images:
```
kind: ImageStream
apiVersion: v1
metadata:
  name: nginx
  namespace: openshift
spec:
  dockerImageRepository: nginx
status:
  dockerImageRepository: 172.30.2.26:5000/openshift/nginx
  tags:
  - tag: latest
```
Is that docker-registry can be use as a private-registry，not only as a sti-images,but also a common images(a common images needn't git in web console)?
May be create a harbor is good for openshift to save the common images?
Thanks.
