### ISSUE TITLE
oauthConfig.identityProvider[0].provider.ca: Invalid value --> could not read file

### ISSUE THREAD

**Issue by cmoulliard** [openshift/origin#8917]
This error is reported when Openshift starts : 

`
error: Invalid MasterConfig /var/lib/origin/openshift.local.config/master/master-config.yaml
  oauthConfig.identityProvider[0].provider.ca: Invalid value: "/var/lib/origin/keycloak-ca.cert": could not read file
`

##### Version
Latest docker openshift image published : 18 May 2016

##### Steps To Reproduce

- Command used to start OpenShift with Docker

`
docker run -d --name "origin" --privileged --pid=host --net=host -v /:/rootfs:ro -v /var/run:/var/run:rw -v /sys:/sys -v /var/lib/docker:/var/lib/docker:rw -v /var/lib/origin/openshift.local.volumes:/var/lib/origin/openshift.local.volumes -v /var/lib/origin/openshift.local.config:/var/lib/origin/openshift.local.config openshift/origin start --master-config=/var/lib/origin/openshift.local.config/master/master-config.yaml  --node-config=/var/lib/origin/openshift.local.config/node-openshift/node-config.yaml --loglevel=5
`

- Config file used  

```
admissionConfig:
  pluginConfig: null
apiLevels:
- v1
apiVersion: v1
assetConfig:
  extensionDevelopment: false
  extensionScripts: null
  extensionStylesheets: null
  extensions: null
  loggingPublicURL: ""
  logoutURL: "https://192.168.1.80:8443/auth/realms/openshift/protocol/openid-connect/logout?redirect_uri=https://192.168.99.100:8443/console"
  masterPublicURL: https://192.168.99.100:8443
  metricsPublicURL: ""
  publicURL: https://192.168.99.100:8443/console/
  servingInfo:
    bindAddress: 0.0.0.0:8443
    bindNetwork: tcp4
    certFile: master.server.crt
    clientCA: ""
    keyFile: master.server.key
    maxRequestsInFlight: 0
    namedCertificates: null
    requestTimeoutSeconds: 0
auditConfig:
  enabled: false
controllerConfig:
  serviceServingCert:
    signer:
      certFile: service-signer.crt
      keyFile: service-signer.key
controllerLeaseTTL: 0
controllers: '*'
corsAllowedOrigins:
- 192.168.99.100:8443
- 127.0.0.1
- localhost
disabledFeatures: null
dnsConfig:
  allowRecursiveQueries: true
  bindAddress: 0.0.0.0:8053
  bindNetwork: tcp4
etcdClientInfo:
  ca: ca.crt
  certFile: master.etcd-client.crt
  keyFile: master.etcd-client.key
  urls:
  - https://192.168.99.100:4001
etcdConfig:
  address: 192.168.99.100:4001
  peerAddress: 10.0.2.15:7001
  peerServingInfo:
    bindAddress: 0.0.0.0:7001
    bindNetwork: tcp4
    certFile: etcd.server.crt
    clientCA: ca.crt
    keyFile: etcd.server.key
    namedCertificates: null
  servingInfo:
    bindAddress: 0.0.0.0:4001
    bindNetwork: tcp4
    certFile: etcd.server.crt
    clientCA: ca.crt
    keyFile: etcd.server.key
    namedCertificates: null
  storageDirectory: /var/lib/origin/openshift.local.etcd
etcdStorageConfig:
  kubernetesStoragePrefix: kubernetes.io
  kubernetesStorageVersion: v1
  openShiftStoragePrefix: openshift.io
  openShiftStorageVersion: v1
imageConfig:
  format: openshift/origin-${component}:${version}
  latest: false
imagePolicyConfig:
  disableScheduledImport: false
  maxImagesBulkImportedPerRepository: 5
  maxScheduledImageImportsPerMinute: 60
  scheduledImageImportMinimumIntervalSeconds: 900
jenkinsPipelineConfig:
  enabled: true
  parameters: null
  serviceName: jenkins
  templateName: jenkins
  templateNamespace: openshift
kind: MasterConfig
kubeletClientInfo:
  ca: ca.crt
  certFile: master.kubelet-client.crt
  keyFile: master.kubelet-client.key
  port: 10250
kubernetesMasterConfig:
  admissionConfig:
    pluginConfig: null
  apiLevels: null
  apiServerArguments: null
  controllerArguments: null
  disabledAPIGroupVersions: {}
  masterCount: 1
  masterIP: 10.0.2.15
  podEvictionTimeout: 5m
  proxyClientInfo:
    certFile: master.proxy-client.crt
    keyFile: master.proxy-client.key
  schedulerConfigFile: ""
  servicesNodePortRange: 30000-32767
  servicesSubnet: 172.30.0.0/16
  staticNodeNames: null
masterClients:
  externalKubernetesKubeConfig: ""
  openshiftLoopbackKubeConfig: openshift-master.kubeconfig
masterPublicURL: https://192.168.99.100:8443
networkConfig:
  clusterNetworkCIDR: 10.128.0.0/14
  externalIPNetworkCIDRs: null
  hostSubnetLength: 9
  networkPluginName: ""
  serviceNetworkCIDR: 172.30.0.0/16
oauthConfig:
  alwaysShowProviderSelection: false
  assetPublicURL: https://192.168.99.100:8443/console/
  grantConfig:
    method: auto
  identityProviders:
  - challenge: true
    login: true
    name: keycloak
    provider:
      apiVersion: v1
      kind: OpenIDIdentityProvider
      ca: /var/lib/origin/keycloak-ca.cert
      clientID: admin
      clientSecret: admin
      claims:
        id:
        - sub
        preferredUsername:
        - preferred_username
        name:
        - name
        email:
        - email
      urls:
        authorize: https://192.168.1.80:8080/auth/realms/fabric8/tokens/login
        token: https://192.168.1.80:8080/auth/realms/fabric8/tokens/access/codes
  masterCA: ca-bundle.crt
  masterPublicURL: https://192.168.99.100:8443
  masterURL: https://192.168.99.100:8443
  sessionConfig:
    sessionMaxAgeSeconds: 300
    sessionName: ssn
    sessionSecretsFile: ""
  templates: null
  tokenConfig:
    accessTokenMaxAgeSeconds: 86400
    authorizeTokenMaxAgeSeconds: 300
pauseControllers: false
policyConfig:
  bootstrapPolicyFile: policy.json
  openshiftInfrastructureNamespace: openshift-infra
  openshiftSharedResourcesNamespace: openshift
  userAgentMatchingConfig:
    defaultRejectionMessage: ""
    deniedClients: null
    requiredClients: null
projectConfig:
  defaultNodeSelector: ""
  projectRequestMessage: ""
  projectRequestTemplate: ""
  securityAllocator:
    mcsAllocatorRange: s0:/2
    mcsLabelsPerProject: 5
    uidAllocatorRange: 1000000000-1999999999/10000
routingConfig:
  subdomain: router.default.svc.cluster.local
serviceAccountConfig:
  limitSecretReferences: false
  managedNames:
  - default
  - builder
  - deployer
  masterCA: ca-bundle.crt
  privateKeyFile: serviceaccounts.private.key
  publicKeyFiles:
  - serviceaccounts.public.key
servingInfo:
  bindAddress: 0.0.0.0:8443
  bindNetwork: tcp4
  certFile: master.server.crt
  clientCA: ca.crt
  keyFile: master.server.key
  maxRequestsInFlight: 500
  namedCertificates: null
  requestTimeoutSeconds: 3600
volumeConfig:
  dynamicProvisioningEnabled: true
```

- keycloak ca.cert is available : 

`
ll /var/lib/origin/keycloak-ca.cert
-rw-------    1 root     root          1489 May 18 10:42 /var/lib/origin/keycloak-ca.cert
` 

- keycloak-ca.cert

```
-----BEGIN CERTIFICATE-----
MIIEHjCCAwagAwIBAgIBAjANBgkqhkiG9w0BAQsFADAmMSQwIgYDVQQDDBtvcGVu
c2hpZnQtc2lnbmVyQDE0NjM1NjU2MDMwHhcNMTYwNTE4MTAwMDAyWhcNMTgwNTE4
MTAwMDAzWjAUMRIwEAYDVQQDEwkxMC4wLjIuMTUwggEiMA0GCSqGSIb3DQEBAQUA
A4IBDwAwggEKAoIBAQC0qoq7zsCkPGKKQtCrsPGYEEoFSNAxNDImX4UftHlLN9jG
uXSyMQ95cRyMTnzeGJZezVHKOfmZnp+OBTL8EQXDWd7eDaoLA7aDwlfOFczdXMS6
6IKYiAi2nk8p/2YWeHo5TQk8x2gZbjOIibLlmZiFdAPEGDKXoG0BZWCFFxElaMOv
PWH3fl60D7CoMPEvEiYVIPxOW3wwkKmvJNaE1vvnCqga1K9zA2GoeD7B9C5EyTc0
RZg5677ihB2/ZfixoGbx/oMjfhBXtz/C/4EZFj8fDqVrJH6LFTqxXHZxKARA+9SM
j5glTwI4mS0vQXzUBW3hoiJ7As6JQI0W6FvcqpcnAgMBAAGjggFnMIIBYzAOBgNV
HQ8BAf8EBAMCBaAwEwYDVR0lBAwwCgYIKwYBBQUHAwEwDAYDVR0TAQH/BAIwADCC
ASwGA1UdEQSCASMwggEfggprdWJlcm5ldGVzghJrdWJlcm5ldGVzLmRlZmF1bHSC
Fmt1YmVybmV0ZXMuZGVmYXVsdC5zdmOCJGt1YmVybmV0ZXMuZGVmYXVsdC5zdmMu
Y2x1c3Rlci5sb2NhbIIJbG9jYWxob3N0gglvcGVuc2hpZnSCEW9wZW5zaGlmdC5k
ZWZhdWx0ghVvcGVuc2hpZnQuZGVmYXVsdC5zdmOCI29wZW5zaGlmdC5kZWZhdWx0
LnN2Yy5jbHVzdGVyLmxvY2FsggkxMC4wLjIuMTWCCTEyNy4wLjAuMYIKMTcyLjE3
LjAuMYIKMTcyLjMwLjAuMYIOMTkyLjE2OC45OS4xMDCHBAoAAg+HBH8AAAGHBKwR
AAGHBKweAAGHBMCoY2QwDQYJKoZIhvcNAQELBQADggEBADVJhbBsrxlZUWcLAMIv
DoUTFnywuPOHlkAeU4ROSqsqa413VmeFX1ojwrMFrSjqFs+YTLWwWOdYncHSbLUz
wxhAPLsUMwI0UxVA9LQTdMlqoLB55SJFRPp8nqqbysvZqzH8FUN8FiYDgVE70CXw
WFVnkg7umfxVs66uPXZwM4DnNmETouJC/t86b4bp2kISRQs6OLfQYr4mWAkg7/vg
ZuICdVUkciLNED3Y6qjZl0S7MCWQAdiGZUfB8xfU3jqYvEXLGzYYdt5hL5KiXKOa
qBiYir/IAFU04hs2CvjOzq8P21sAllSkVmcIxl8Na8/Ko1hJ0PMioaG2+RWBV9o1
pdI=
-----END CERTIFICATE-----

```
