### ISSUE TITLE
oc start-build --from-repo does not clone submodules

### ISSUE THREAD

**Issue by sosiouxme** [openshift/origin#8922]
Similar to https://github.com/openshift/origin/issues/5910 which got fixed - builds from a URL will clone submodules, but builds from a local git repo won't (even though the submodule code is remote).
##### Steps To Reproduce

Create the following build:

```
apiVersion: v1
kind: BuildConfig
metadata:
  labels:
    build: logging-auth-proxy
  name: logging-auth-proxy
spec:
  output:
    to:
      kind: ImageStreamTag
      name: logging-auth-proxy:latest
  resources: {}
  source:
    git:
      uri: https://github.com/sosiouxme/origin-aggregated-logging
      ref: issue-example-build-from-repo-submodule
    contextDir: deployer/common/openshift-auth-proxy
    type: Git
  strategy:
    dockerStrategy:
      from:
        kind: DockerImage
        name: library/node:0.10.36
    type: Docker
```
1. oc start-build --follow
2. git clone --recursive https://github.com/sosiouxme/origin-aggregated-logging -b issue-example-build-from-repo-submodule /tmp/foo
3. oc start-build --follow --from-dir=/tmp/foo
4. oc start-build --follow --from-repo=/tmp/foo
##### Current Result

1 and 3 work, 4 fails because of missing submodule
##### Expected Result

All work - when given a local git repo in 4, should at least attempt to clone submodules. If the submodule isn't accessible, it's obviously fine for the clone to fail and just continue the build without it (as in current behavior).
