### ISSUE TITLE
E0518 AuthenticationError: Post  x509: certificate signed by unknown authority

### ISSUE THREAD

**Issue by cmoulliard** [openshift/origin#8933]
Can you provide some guidance to resolve this error when we setup Keycloak as Identity Provider with Openshift ?

`E0518 19:22:45.911642   10471 errorpage.go:30] AuthenticationError: Post https://192.168.1.80:8443/auth/realms/openshift/protocol/openid-connect/token: x509: certificate signed by unknown authority`

##### Version
Openshift Docker Image : 15 of May 2016

**Comment by liggitt** [comment]
Are you providing the CA that signed the keycloak serving cert to OpenShift? You can do so with the `ca` attribute on the identity provider in the master-config.yaml (see https://docs.openshift.org/latest/install_config/configuring_authentication.html#OpenID)

**Comment by cmoulliard** [comment]
Yes. I have included the ca cert file coming from the Keycloak SSL Server

Config used

```
oauthConfig:
  alwaysShowProviderSelection: false
  assetPublicURL: https://192.168.99.100:8443/console/
  grantConfig:
    method: auto
  identityProviders:
  - challenge: false
    login: true
    name: keycloak
    provider:
      apiVersion: v1
      kind: OpenIDIdentityProvider
      ca: keycloak-ca.cert
      clientID: openshift
      clientSecret: fbde8b27-3342-4494-b3a3-7db645e9dfe5
      claims:
        id:
        - sub
        preferredUsername:
        - preferred_username
        name:
        - name
        email:
        - email
      urls:
        #authorize: https://192.168.1.80:8443/auth/realms/openshift/tokens/login
        #token: https://192.168.1.80:8443/auth/realms/openshift/tokens/access/codes
        #userInfo: https://192.168.1.80:8443
        # authorize: https://192.168.1.80:8443/auth/realms/openshift/protocol/openid-connect/auth
        # token: https://192.168.1.80:8443/auth/realms/openshift/protocol/openid-connect/token
        authorize: https://192.168.1.80:8443/auth/realms/openshift/protocol/openid-connect/auth
        token: https://192.168.1.80:8443/auth/realms/openshift/protocol/openid-connect/token
        userInfo: https://192.168.1.80:8443/auth/realms/openshift/protocol/openid-connect/userinfo
```

Certificate info

```
openssl x509  -text -noout -in /var/lib/origin/openshift.local.config/master/keycloak-ca.cert
Certificate:
    Data:
        Version: 3 (0x2)
        Serial Number: 1371713250 (0x51c2aee2)
    Signature Algorithm: sha256WithRSAEncryption
        Issuer: C=BE, ST=Heaven, L=Eden, O=ACME, OU=IT, CN=192.168.1.80
        Validity
            Not Before: May 19 04:44:39 2016 GMT
            Not After : May 14 04:44:39 2017 GMT
        Subject: C=BE, ST=Heaven, L=Eden, O=ACME, OU=IT, CN=192.168.1.80
        Subject Public Key Info:
            Public Key Algorithm: rsaEncryption
                Public-Key: (2048 bit)
                Modulus:
                    00:82:13:f6:d2:d2:1f:19:a8:ab:bf:80:0e:0f:ff:
                    ed:d2:41:0a:ce:6d:84:32:9c:63:23:2d:3d:6a:f5:
                    98:ef:91:ed:85:45:ce:3b:b9:b3:b1:2a:2d:be:6a:
                    51:3c:a2:0e:21:b4:cf:c9:f1:c5:99:db:4d:59:ad:
                    46:db:94:1b:56:01:c9:82:22:ce:54:37:27:7a:39:
                    f7:ec:6f:eb:7e:f2:b4:29:d1:65:f1:3d:13:58:7d:
                    20:3b:33:94:ee:a7:32:54:7c:90:71:51:07:86:f9:
                    31:cb:09:c7:bc:35:ff:65:37:fe:10:11:40:74:8f:
                    34:5e:5c:8d:7c:de:a1:3d:e7:d2:46:df:72:75:3d:
                    30:e0:86:a7:1d:5e:54:bd:9f:d9:14:e5:3a:01:03:
                    fd:ba:e5:22:65:26:6d:ee:32:ac:02:5e:62:b8:33:
                    23:cf:92:ff:2b:fb:c8:60:7d:0d:ba:15:21:4c:ae:
                    69:6a:63:3d:a4:d5:ec:b3:d2:85:39:fb:e7:c0:04:
                    0c:61:63:cb:75:f0:55:c5:6a:77:9b:31:09:48:48:
                    97:78:24:00:da:83:28:4c:c4:83:03:be:06:0f:14:
                    29:96:9d:a2:64:21:85:44:d0:e2:3a:fb:68:f8:d0:
                    ae:ad:0d:da:19:fe:7a:3c:a2:fb:79:84:c8:cd:09:
                    19:17
                Exponent: 65537 (0x10001)
        X509v3 extensions:
            X509v3 Subject Alternative Name:
                IP Address:192.168.1.80
            X509v3 Subject Key Identifier:
                96:9E:52:EB:D0:7A:DE:99:98:44:3A:87:AE:79:AB:8C:A9:48:FE:31
    Signature Algorithm: sha256WithRSAEncryption
         3c:50:60:b6:d2:7c:26:d0:c9:13:d0:52:15:52:d0:bc:6f:12:
         bb:d0:29:38:b6:e5:44:c1:0b:3a:56:40:0b:c9:b6:6c:ff:d4:
         92:a8:ab:1d:17:6f:60:be:57:14:5c:c9:67:b7:e6:8e:06:74:
         f8:b4:18:98:37:7d:e2:37:93:00:51:bc:fe:fb:75:57:c6:a7:
         44:ab:24:de:54:e3:52:fe:c7:a5:5d:24:ba:2a:ef:e4:fe:78:
         68:40:cd:21:37:e0:ef:cc:04:2f:be:16:0a:3c:72:23:d1:cb:
         48:72:d2:43:29:0b:43:05:c2:31:60:15:20:49:d7:1c:0b:23:
         40:60:fe:cd:5c:44:ce:c6:30:1a:0f:b1:de:27:f3:5d:44:40:
         b3:99:ff:30:20:9c:aa:bd:75:5a:e8:a1:24:0b:e6:9c:1d:16:
         e8:8a:41:71:18:1c:ef:9b:0f:21:92:73:10:39:ff:98:24:90:
         f8:b3:7b:6f:ed:03:a4:77:8f:ac:82:67:0d:d3:68:81:c3:f0:
         90:a5:cf:6a:ed:67:df:8b:2e:b5:23:20:89:0a:40:8d:53:d3:
         3d:28:25:00:2a:83:2f:f7:c5:b3:0c:45:40:f3:ff:a8:59:07:
         2c:6e:17:c4:09:03:06:a9:c1:2b:00:46:b8:85:cc:8f:e2:66:
         20:d2:39:31
```

With my latest certficate generated using this command

````
keytool -genkey -keyalg RSA -alias localhost -ext san=ip:192.168.1.80 -storetype JKS -keystore keycloak.jks -storepass secret -keypass secret -validity 360  -dname "CN=192.168.1.80, OU=IT, O=ACME, L=Eden, ST=Heaven, C=BE" -keyalg RSA -keysize 2048
````

I get this error now

````
E0519 04:50:57.435532    2733 errorpage.go:30] AuthenticationError: Post https://192.168.1.80:8443/auth/realms/openshift/protocol/openid-connect/token: x509: certificate signed by unknown authority (possibly because of "x509: invalid signature: parent certificate cannot sign this kind of certificate" while trying to verify candidate authority certificate "192.168.1.80")
````

**Comment by liggitt** [comment]
It doesn't seem like the referenced CA is actually a valid CA. I would expect to see this in the x509 info:
```
        X509v3 extensions:
            X509v3 Key Usage: critical
                Digital Signature, Key Encipherment, Certificate Sign
            X509v3 Basic Constraints: critical
                CA:TRUE
```

**Comment by cmoulliard** [comment]
Here are the commands that I'm using to generate a root CA, keys of the localhost, generate a cert req, sign the certificate request with the CA root

```
keytool -genkeypair -alias ca -dname "CN=Keycloak-signer" -ext bc=ca:true -ext KU=digitalSignature,keyEncipherment,dataEncipherment,keyCertSign -validity 3600 -keyalg RSA -keysize 2048 -storetype JKS -keystore keycloak.jks -storepass secret -keypass secret

keytool -genkey -alias localhost -ext SAN=ip:192.168.1.80 -ext bc=ca:false -ext KU=digitalSignature,keyEncipherment,dataEncipherment -validity 900 -dname "CN=192.168.1.80" -keyalg RSA -keysize 2048 -storetype JKS -keystore keycloak.jks -storepass secret -keypass secret

keytool -certreq -alias localhost -file keycloak-leaf.csr -keystore keycloak.jks -storepass secret

keytool -gencert -alias ca -infile keycloak-leaf.csr -outfile keycloak-leaf.cer -ext SAN=ip:192.168.1.80 -ext bc=ca:false -ext KU=digitalSignature,keyEncipherment,dataEncipherment -validity 900 -keystore keycloak.jks -storepass secret

keytool -importcert -keystore keycloak.jks -storepass secret -file keycloak-leaf.cer -alias localhost
```

And we can verify that it contains the correct extensions

```
keytool -v -list -keystore keycloak.jks -storepass secret

Owner: CN=192.168.1.80
Issuer: CN=Keycloak-signer
Serial number: 257d812c
Valid from: Fri May 20 09:10:51 CEST 2016 until: Tue Nov 06 08:10:51 CET 2018

...


#2: ObjectId: 2.5.29.19 Criticality=false
BasicConstraints:[
  CA:false
  PathLen: undefined
]

#3: ObjectId: 2.5.29.15 Criticality=false
KeyUsage [
  DigitalSignature
  Key_Encipherment
  Data_Encipherment
]

#4: ObjectId: 2.5.29.17 Criticality=false
SubjectAlternativeName [
  IPAddress: 192.168.1.80
]
```

but I'm getting now a `x509: certificate signed by unknown authority` 

```
E0520 07:12:04.157072    1816 errorpage.go:30] AuthenticationError: Post https://192.168.1.80:8443/auth/realms/openshift/protocol/openid-connect/token: x509: certificate signed by unknown authority
```

**Comment by cmoulliard** [comment]
Here is another approach that I have tested using the CA Certificate created by Openshift

The problem is still there : 

E0520 08:50:14.952748    1816 errorpage.go:30] AuthenticationError: Post https://192.168.1.80:8443/auth/realms/openshift/protocol/openid-connect/token: x509: certificate signed by unknown authority

Cmds used :

1) Linux Machine running Openshift as Docker container

```
export CA=/var/lib/origin/openshift.local.config/master
./oc adm ca create-server-cert --signer-cert=$CA/ca.crt --signer-key=$CA/ca.key --signer-serial=$CA/ca.serial.txt --hostnames='192.168.1.80' --cert=client/keycloak.crt --key=client/keycloak.key
cd client
cat keycloak.crt keycloak.key $CA/ca.crt > keycloak.pem
sudo chmod 666 keycloak.key
```
2) SCP file from the Linux machine to my local MacOSX

Linux Host

```
mkdir /home/docker/keys
cp keycloak.* /home/docker/keys/
```
From MacOSX

```
docker-machine scp openshift:/home/docker/keys/* 
```
3) Import key & certificate within keycloak.jks store

```
openssl pkcs12 -export -inkey keycloak.key -in keycloak.pem -name localhost -out keycloak.p12
keytool -importkeystore -srckeystore keycloak.p12 -srcstoretype pkcs12 -destkeystore keycloak.jks
```

4) Copy the keystore with the certificate to the Keycloak Server

```
cp keycloak.jks /Users/chmoulli/Temp/_apiman/apiman-all-1.2.5.Final/wildfly-10.0.0.Final/standalone/configuration/keycloak.jks
```

**Comment by cmoulliard** [comment]
Problem resolved after changing the ca file to be used within the master-config file

```
oauthConfig:
  alwaysShowProviderSelection: false
  assetPublicURL: https://192.168.99.100:8443/console/
  grantConfig:
    method: auto
  identityProviders:
  - challenge: false
    login: true
    name: keycloak
    provider:
      apiVersion: v1
      kind: OpenIDIdentityProvider
      ca: ca.crt
```
