### ISSUE TITLE
LDAP Sync With Augmented AD Schema Creates Groups That Do Not Match Group Filter

### ISSUE THREAD

**Issue by cpitman** [openshift/origin#8987]
In 3.2, it looks like group sync with augmented AD will create a group if (it matches the filter expression) _or_ (any of the users matching the user filter belong to the group _and_ the group belongs to the baseDN specified for groups). This is confusing and surprising. I expected only groups that match the group filter to be created and populated. In a large company users may belong to many groups that do not matter to OSE administration.

``` yaml
kind: LDAPSyncConfig
apiVersion: v1
augmentedActiveDirectory:
    groupsQuery:
        baseDN: "OU=Application Groups,OU=Groups,OU=Administrators,DC=example,DC=org"
        scope: sub
        derefAliases: never
        filter: (&(objectClass=group)(CN=*openshift))
        pageSize: 0
    groupUIDAttribute: dn 
    groupNameAttributes: [ cn ] 
    usersQuery:
        baseDN: "DC=example,DC=org"
        scope: sub
        derefAliases: never
        filter: (&(objectclass=user)(memberof=CN=openshift-access,OU=Application Groups,OU=Groups,OU=Administrators,DC=example,DC=org))
        pageSize: 0
    userNameAttributes: [ sAMAccountName ] 
    groupMembershipAttributes: [ memberOf ]  
```
##### Version

OSE 3.2
##### Steps To Reproduce
1. Create an AD user, and three AD groups (openshift-access, admin-openshift, dummy) and assign the user to all three groups
2. Use an LDAP sync config similar to the above
##### Current Result

Group Sync creates all three groups, even though dummy and openshift-access do not match the filter
##### Expected Result

Group sync only creates admin-openshift

**Comment by deads2k** [comment]
@stevekuznetsov

**Comment by liggitt** [comment]
I think I would expect to use the whitelist for that, rather than a group filter. I'm sort of surprised that didn't result in errors about the other groups not being able to be found

**Comment by stevekuznetsov** [comment]
I believe the reason this occurs is that, in the Augmented AD scenario, actual group records are only used to determine group metadata - the groups that are synced are based either on the membership of the people that you select with your query, or on the blacklist and whitelist provided. I believe what should occur in this case is a log message or error message should occur when the OpenShift client can't find the group record for groups that it is creating. Could you run the following and post it here?

```
$ oadm sync-groups --sync-config=<your file> --loglevel=5
```

**Comment by cpitman** [comment]
There is an error message for any group that has a DN that doesn't match `groupsQuery.baseDN`, once the client gets back I'll get you output.

I understand now that the behavior of `groupsQuery.filter` is not  what I expected. I expected it to filter groups that would be synchronized. Instead, it sounds like it filters groups that OSE will fetch metadata for. Honestly, that is still extremely confusing from the user's perspective. There is no way for the user to know (either from the configuration or documentation) that `groupsQuery` has nothing to do with selecting which groups will be synchronized.

**Comment by stevekuznetsov** [comment]
> still extremely confusing from the user's perspective

I agree. Unfortunately, some of the difficulty with this is due to the disparate ways in which organizations use LDAP, and we do assume that the users will be the LDAP adminstrators to alleviate some of the issues.

> There is no way for the user to know (either from the configuration or documentation) that `groupsQuery` has nothing to do with selecting which groups will be synchronized. 

I will attempt to clarify our documentation to clarify this point. I will look into the issue that all groups are made, as if your sync configuration specifies that an attribute from the metadata is to be used in creating the group, I'm not exactly sure how the command could sync and *not* fail for groups that it cannot retrieve metadata for.

**Comment by cpitman** [comment]
Here's some representative output from our run:

First, the output and errors we get for a group that does not match the `groupsQuery.baseDN`:

    Error building OpenShift group for LDAP group "CN=ar-gg-msfc-mce-sysadmin,OU=ARGroups,OU=AR,DC=example,DC=org": search for entry with dn="CN=ar-gg-msfc-mce-sysadmin,OU=ARGroups,OU=AR,DC=example,DC=org" would search outside of the base dn specified (dn="OU=Application Groups,OU=Groups,OU=Administrators,DC=example,DC=org").
    search for entry with dn="CN=ar-gg-msfc-mce-sysadmin,OU=ARGroups,OU=AR,DC=example,DC=org" would search outside of the base dn specified (dn="OU=Application Groups,OU=Groups,OU=Administrators,DC=example,DC=org")

Second, here is a group being synchronized that matches the baseDN but not the filter:

```

 apiVersion: v1
  kind: Group
  metadata:
    annotations:
      openshift.io/ldap.sync-time: 2016-05-23T13:19:02-0500
      openshift.io/ldap.uid: CN=ND-DLG-13708-NEACC TAG IDMAX Dev,OU=Application Groups,OU=Groups,OU=Administrators,DC=example,DC=org
      openshift.io/ldap.url: [redacted]
    creationTimestamp: null
    labels:
      openshift.io/ldap.host: [redacted]
    name: ND-DLG-13708-NEACC TAG IDMAX Dev
  users:
  - user01
```
