### ISSUE TITLE
`build:` does not work as expected with `oc import docker-compose ...`

### ISSUE THREAD

**Issue by containscafeine** [openshift/origin#9081]
Hi,

I am using this [docker-compose.yaml](https://gist.github.com/containscafeine/6040436aed9215865da774f1b5ceddb9) file, which has services defined such as this:

``` yaml
version: "2"
services:
  hello:
    build: ./hello/.
    ports:
    - "13371:8080"
    labels:
     - "app=hello"
     - "hystrix.enabled=true"
```

The directory `./hello/` is a cloned git repository.

When I run `oc import docker-compose -f docker-compose.yaml`, all of the build pods error out.
##### Version

``` bash
oc v1.3.0-alpha.1-20-g30f598e-dirty
kubernetes v1.3.0-alpha.1-331-g0522e63
```
##### Current Result

``` bash
[root@localhost frontend]# oc logs hello-1-build
warning: OpenShift server version "v1.3.0-alpha.1-20-g30f598e-dirty" differs from this image "v1.3.0-alpha.1"
Downloading "https://github.com/redhat-helloworld-msa/hello" ...
Cloning source from https://github.com/redhat-helloworld-msa/hello
error: build error: open /tmp/docker-build254714191/hello/Dockerfile: no such file or directory
```
- Why is OpenShift cloning the repository when I have specified the build directory from where the image is supposed to be built?
- Even if it clones the remote git repository, it does have a Dockerfile present. I am at a loss as to why the pods error out in such fashion.
##### Expected Result

The images should be build from the directories specified and not from the git remotes.
##### Steps To Reproduce
- `git clone https://github.com/redhat-helloworld-msa/hello`
- `cd hello`
- `mvn package -Popenshift`
- `cd ..`
- Put the following in a `docker-compose.yaml` file:

``` yaml
version: "2"
services:
  hello:
    build: ./hello/.
    ports:
    - "13371:8080"
    labels:
     - "app=hello"
     - "hystrix.enabled=true"
```
- `oc new-project hello-test`
- Change hello/Dockerfile's `FROM` directive to point to `registry.access.redhat.com/jboss-eap-7-beta/eap70-openshift`
- `oc import docker-compose -f docker-compose.yaml`
- `oc logs hello-1-build`
