### ISSUE TITLE
port bindings in docker-compose.yaml not honored by `oc import docker-compose ...`

### ISSUE THREAD

**Issue by containscafeine** [openshift/origin#9083]
Hi,

I am using this [docker-compose.yaml](https://gist.github.com/containscafeine/37bc4388d0a08fefd39774cbdef56f41) file which has the port bindings for services described like this:

``` yaml
version: "2"
services:
  hello:
    image: containscafeine/hello
    ports:
    - "13371:8080"
    labels:
     - "app=hello"
     - "hystrix.enabled=true"
```

`oc import docker-compose -f docker-compose.yaml` works just fine, but the services are not exposed to the specified port in the `docker-compose.yaml`, but instead to the port mentioned in the `EXPOSE` directive in the respective Dockerfiles of the services.
##### Version

``` bash
oc v1.3.0-alpha.1-20-g30f598e-dirty
kubernetes v1.3.0-alpha.1-331-g0522e63
```
##### Steps To Reproduce
- `wget https://gist.githubusercontent.com/containscafeine/37bc4388d0a08fefd39774cbdef56f41/raw/53482698f99a8033117901aa26c045f55c9c16f5/docker-compose-port-fail-oc.yaml`
- `oc import docker-compose -f docker-compose-port-fail-oc.yaml`
##### Current Result

``` bash
# oc get svc
NAME                 CLUSTER-IP       EXTERNAL-IP   PORT(S)             AGE
aloha                172.30.133.98    <none>        8080/TCP            15m
api-gateway          172.30.69.132    <none>        8080/TCP            15m
bonjour              172.30.28.251    <none>        8080/TCP            15m
frontend             172.30.27.8      <none>        8080/TCP            15m
hello                172.30.106.233   <none>        8080/TCP            15m
hola                 172.30.33.74     <none>        8080/TCP            15m
...
...
```
##### Expected Result

The services should get exposed to the ports specified in the `docker-compose.yaml` file, instead to the exposed ports (that should be the default behavior, but overridden by the values set in the `docker-compose.yaml`.)

**Comment by surajssd** [comment]
Maybe this can be done by creating a route, for every service that is exposed for the outside world.

**Comment by smarterclayton** [comment]
In this case the mapping affects how other services connect, so we do need to set the mapping

**Comment by surajssd** [comment]
@smarterclayton so these mappings go into docker-compose.yml?

**Comment by containscafeine** [comment]
@smarterclayton where and how do you propose these mappings are done?

Should this not work out of the box like it does work with Docker Compose,
if not, then this breaks the application which worked with Compose but
fails to run with OpenShift out of the box!

**Comment by smarterclayton** [comment]
We should be setting the service mapping from the "external" to the internal address when we generate.  Although this behavior in a sense is an antipattern (having to map ports is a docker issue, but not a Kube issue where every container has an IP).  It's just usually not necessary in Kube.

**Comment by containscafeine** [comment]
@smarterclayton yep, agree, it does not make much sense in k8s/oc!

But then, it's a blocker in making Docker Compose applications run on
OpenShift out of the box. Does that not defeat the purpose of `oc import
docker-compose ...`?

**Comment by kadel** [comment]
Maybe little unrelated question, but why not map hostPort from docker-compose definition to ServicePort?

For example with docker compose like this:
```yaml
services:
  hello:
    image: containscafeine/hello
    ports:
    - "13371:8080"
```

Generate this service:
``` yaml
  apiVersion: v1
  kind: Service
  metadata:
    name: hello
  spec:
    ports:
    - port: 13371
      targetPort: 8080
    selector:
      deploymentconfig: hello
```

It is not going to solve @containscafeine  problem with his application, but at least services will be listening on same ports as defined in docker-compose.yml
