### ISSUE TITLE
Image limits to tags not applies

### ISSUE THREAD

**Issue by soltysh** [openshift/origin#9376]
Similarly to #9375.

##### Version
```
oc v1.3.0-alpha.1-379-g662753c
kubernetes v1.3.0-alpha.3-599-g2746284
```

##### Steps To Reproduce
Create following limits, purposefully low, but this time just `openshift.io/image-tags`:
```
apiVersion: "v1"
kind: "LimitRange"
metadata:
  name: "images"
spec:
  limits:
    - type: openshift.io/Image
      max:
        storage: 100Mi 
    - type: openshift.io/ImageStream
      max:
        openshift.io/image-tags: 1
```

Push image to integrated registry, I've used `openshift/origin-pod`.
Currently I have one image, having single tag and within the storage size.

oc edit is/origin-pod and add 2nd tag, like so:
```
  tags:
  - name: "3.5"
    from:
      kind: DockerImage
      name: openshift/python-34-centos7:latest
```

oc describe that is gives me:
```
...
latest	<pushed>				22 minutes ago	172.30.252.121:5000/test/origin-pod@sha256:f5d7c2975de6fb...	<same>
3.5	openshift/python-34-centos7:latest	6 minutes ago	openshift/python-34-centos7@sha256:ca0cabc43b8b98...		<same>
```

Why was I able to add 2nd tag to that image stream? Shouldn't `openshift.io/image-tag` stop me from doing that?
