### ISSUE TITLE
External Registry ImageStream source trying to pull over HTTP

### ISSUE THREAD

**Issue by yoshiwaan** [openshift/origin#9395]
I'm trying to configure a BuildConfig to use an imagestream source. I specify the imagestream and the buildconfig and run a build, but the build fails, stating the image pull failed. The URL that the pull attempt is from states HTTP instead of HTTS

##### Version
```
[vagrant@localhost ~]$ openshift version
openshift v1.2.0
kubernetes v1.2.0-36-g4a3f9c5
etcd 2.2.5
```

##### Steps To Reproduce
1. This is our imagestream:
```
apiVersion: v1
kind: ImageStream
metadata:
  annotations:
    description: gateway registry image pointer
  creationTimestamp: null
  generation: 1
  labels:
    app: gateway
    poc: gateway
  name: gateway
spec:
  tags:
  - annotations: null
    from:
      kind: DockerImage
      name: isl-dsdc.ca.com:5000/apim-gateway/gateway:latest
    generation: null
    importPolicy: {}
    name: latest
  dockerImageRepository: isl-dsdc.ca.com:5000/apim-gateway/gateway
```

This is our buildconfig:
```
apiVersion: v1
kind: BuildConfig
metadata:
  annotations: {}
  creationTimestamp: null
  labels:
    app: pssg
  name: pssg
spec:
  postCommit: {}
  resources: {}
  source:
    git:
      uri: ssh://git@our.github/our-org/pssg.git
    secrets: []
    sourceSecret:
      name: pssg
    type: Git
  output:
    to:
      kind: ImageStreamTag
      name: pssg:latest
  strategy:
    type: Docker
    dockerStrategy:
      from:
        kind: ImageStreamTag
        name: gateway:latest
  triggers:
  - type: ConfigChange
  - imageChange: {}
    type: ImageChange
status:
  lastVersion: 0
```

Triggering a build with those two configs results in this error (running `oc start-build pssg --build-loglevel=5` produces no further information relevant to the error):
```
[root@45b86b9e75de pssg]# oc logs -f build/pssg-3
I0617 05:25:54.402300       1 source.go:197] Downloading "ssh://git@our.github/our-org/pssg.git" ...
Step 1 : FROM isl-dsdc.ca.com:5000/apim-gateway/gateway@sha256:91b6f83a5d139bd86c7a1c744ad5a69833f5a75a0b31f98acf05345585f9f83e
Trying to pull repository isl-dsdc.ca.com:5000/apim-gateway/gateway ... failed
F0617 05:26:24.632353       1 builder.go:204] Error: build error: Get http://isl-dsdc.ca.com:5000/v2/: EOF
```
If I curl that URL over http I get a null reponse too (but over https it works).

If I remove the imagestream and use the following buildconfig instead, which uses a dockerimage instead of an imagestream and the same image source in the FROM line of the Dockerfile in this repo, it works fine:
```
apiVersion: v1
kind: BuildConfig
metadata:
  annotations: {}
  creationTimestamp: null
  labels:
    app: pssg
  name: pssg
spec:
  postCommit: {}
  resources: {}
  source:
    git:
      uri: ssh://git@our.github/our-org/pssg.git
    secrets: []
    sourceSecret:
      name: pssg
    type: Git
  output:
    to:
      kind: ImageStreamTag
      name: pssg:latest
  strategy:
    type: Docker
  triggers:
    type: GitHub
  - type: ConfigChange
status:
  lastVersion: 0
```

##### Current Result
The Openshift build fails as it is unable to pull the base image

##### Expected Result
Successful build
