### ISSUE TITLE
oc apply does not work correctly with host: ""

### ISSUE THREAD

**Issue by tnozicka** [openshift/origin#9417]
`oc apply` will fail if you use it twice in a row with the same file which has `host: ""`

[Docs](https://docs.openshift.org/latest/architecture/core_concepts/routes.html#route-hostnames) clearly states that if you leave route empty, if will generate one for you in format `<route-name>[-<namespace>].<suffix>`. 

##### Version
$ oc version
oc v1.3.0-alpha.1-430-g7f154be
kubernetes v1.3.0-alpha.3-599-g2746284

##### Steps To Reproduce
Let's assume we have a file called `route.yaml`:
```yaml
apiVersion: v1
kind: Route
metadata:
  name: no-route-hostname
spec:
  to:
    kind: Service
    name: service-name
```
This is a valid route spec, taken directly from docs.
1. $ oc apply -f route.yaml
2. $ oc apply -f route.yaml

##### Current Result
```
The Route "no-route-hostname" is invalid.
spec.host: Invalid value: "": field is immutable
```

##### Expected Result
Works and leaves the hostname as is.
