### ISSUE TITLE
Deployment Config describer doesn't show mount path for volume

### ISSUE THREAD

**Issue by smarterclayton** [openshift/origin#9576]
```
    spec:
      containers:
      - args:
        - python
        - app.py
        image: 172.30.71.66:5000/example/vote@sha256:f830f3227a09d1160d1a1a0f03b1f2d1cb2404b9cd418e4276d628ba7ff25885
        imagePullPolicy: Always
        name: vote
        ports:
        - containerPort: 80
          protocol: TCP
        resources: {}
        terminationMessagePath: /dev/termination-log
        volumeMounts:
        - mountPath: /app
          name: dir-1
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      securityContext: {}
      terminationGracePeriodSeconds: 30
      volumes:
      - emptyDir: {}
        name: dir-1
```

Shows

```
Template:
  Labels:	deploymentconfig=vote
  Containers:
   vote:
    Image:	172.30.71.66:5000/example/vote@sha256:f830f3227a09d1160d1a1a0f03b1f2d1cb2404b9cd418e4276d628ba7ff25885
    Port:	80/TCP
    Args:
      python
      app.py
    QoS Tier:
      memory:			BestEffort
      cpu:			BestEffort
    Environment Variables:	<none>
  Volumes:
   dir-1:
    Type:	EmptyDir (a temporary directory that shares a pod's lifetime)
    Medium:
```

which is missing the mount path.
