### ISSUE TITLE
Binary source build timeout after 5 minutes in case of an error

### ISSUE THREAD

**Issue by rhuss** [openshift/origin#9923]
When starting a Docker build with a binary source with `oc start-build` and the build has an error like an invalid imagestream name, then `oc start-build` blocks forever without ever returning.

##### Version

```
$ oc version
oc v1.3.0-alpha.2
kubernetes v1.3.0-alpha.1-331-g0522e63

$ openshift version
openshift v1.3.0-alpha.2
kubernetes v1.3.0-alpha.1-331-g0522e63
etcd 2.3.0
```
##### Steps To Reproduce

* Create a `BuildConfig` and an `ImageStream`:

```yaml
---
apiVersion: "v1"
items:
- apiVersion: "v1"
  kind: "ImageStream"
  metadata:
    name: "spring-boot-web"
- apiVersion: "v1"
  kind: "BuildConfig"
  metadata:
    name: "spring-boot-web-build"
  spec:
    output:
      to:
        kind: "ImageStreamTag"
        name: "fabric8/spring-boot-web:1.0.1"
    source:
      binary: {}
    strategy:
      dockerStrategy: {}
kind: "List"
```

Note that the output image stream name is invalid because of the contained `/`

* Start a build with a binary source

```
cat docker.tar | oc start-build --from-dir=- spring-boot-web-build
```

* In an other terminal verify that the build has an error:

```
$ oc describe build

Name:		spring-boot-web-build-1
Created:	7 minutes ago
Labels:		buildconfig=spring-boot-web-build,openshift.io/build-config.name=spring-boot-web-build,openshift.io/build.start-policy=Serial
Annotations:	openshift.io/build-config.name=spring-boot-web-build
		openshift.io/build.number=1
Build Config:	spring-boot-web-build
Duration:	waiting for 7m10s
Build Pod:	spring-boot-web-build-1-build
Strategy:	Docker
Binary:		provided on build
Output to:	ImageStreamTag fabric8/spring-boot-web:snapshot-160719-084528-0494
Status:		New (The referenced output image stream default/fabric8/spring-boot-web could not be found by build default/spring-boot-web-build-1: invalid resource name "fabric8/spring-boot-web": name may not contain "/".)
Events:
  FirstSeen	LastSeen	Count	From			SubobjectPath	Type		Reason		Message
  ---------	--------	-----	----			-------------	--------	------		-------
  7m		7m		1	{build-controller }			Warning		HandleBuildError	Build has error: the referenced output image stream default/fabric8/spring-boot-web could not be found by build default/spring-boot-web-build-1: invalid resource name "fabric8/spring-boot-web": name may not contain "/"
```
##### Current Result

The original `oc start-build` times out after 5 minutes

```
cat docker.tar | oc start-build --from-dir=- spring-boot-web-build
Uploading archive file from STDIN as binary input for the build ...
Error from server: Timeout: timed out waiting for build spring-boot-web-build-1 to start after 5m0s
```

If there is is no error in the build config and the build succeeds, then this command returns within seconds.

##### Expected Result

An error should be printed immediately and the command should be aborted. I suspect that the HTTP connection over which the tar is sent is not closed properly after an error ocured on the server side.
